### ISSUE TITLE
[Input] Странная подсветка значения в инпуте с маской

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#1003]
retail-ui 0.32.1
Windows 10 Chrome 71
Странное поведение подсветки маски
Введённые символы постепенно становятся цвета маски. Сравни последние 4 единицы при фокусе

![2018-12-17_13-35-59](https://user-images.githubusercontent.com/19679857/50075405-b5829400-0200-11e9-8034-63244ac47811.gif)

**Comment by zhzz** [comment]
У меня не получается воспроизвести. Остался пример кода?
Пробовал так:
```
<Input mask={"9999 9999 9999 9999 9999"} />;
```

**Comment by zhzz** [comment]
Воспроизвести не получилось. Пока закрываем.
