### ISSUE TITLE
[ComboBox] Визуальное отображение не соответствует гайдам

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#1005]
Выпадашка чуть уже чем инпут + рамка
![image](https://user-images.githubusercontent.com/19679857/50080793-bb7f7180-020e-11e9-9548-8f75cdbaa1fb.png)

В гайдах вроде выравнено с рамкой
https://guides.kontur.ru/components/combobox/

**Comment by wKich** [comment]
Кажется это происходит из-за того что у выпадашки отсутствует бордер в 1 пиксель. Но если выпадашку выровнять по краю рамки, то при отсутствии рамки она будет казаться визуально шире инпута (хотя такой сценарий маловероятен и не описан в гайдах)

Так же в гайдах у выпадашки отсутствуют верхних и нижний паддинги.

Заметил ещё такой момент только в https://guides.kontur.ru/controls/combobox/#71 выпадашка стоит не вплотную к инпуту, похоже это косяк в гайда. @dzekh

**Comment by dzekh** [comment]
Да, это нужно поправить в библиотеке.
Обводка выпадающего меню должна совпадать с краем рамки фокуса.
![image](https://user-images.githubusercontent.com/26383080/51674299-17999a80-1ff2-11e9-99ea-6d924d14f892.png)

Для примера —  выпадашка дэйтпикера позиционируется правильно.

Еще, лучше когда выпадающее меню по ширине чуть шире инпута. Это не нужно зашивать в компонент, но это можно сделать в примерах, указав какую-то фиксированную ширину меню, большую чем ширина инпута. В примерах в Гайдах оно шире на 40px. 

> Заметил ещё такой момент только в https://guides.kontur.ru/controls/combobox/#71 выпадашка стоит не вплотную к инпуту, похоже это косяк в гайда. @dzekh

да, тут косяк гайда, поправил.
