### ISSUE TITLE
[Sticky] и [Tooltip] В браузере Samsung Internet все всплывашки съезжают

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#1006]
Это дефолтный браузер на самсунгах

![image](https://user-images.githubusercontent.com/19679857/50082807-b07b1000-0213-11e9-80f2-aa6e3e2defd1.png)

![image](https://user-images.githubusercontent.com/19679857/50082820-b5d85a80-0213-11e9-8d21-eeb8eeec8bef.png)

**Comment by MozgalinaDaria** [comment]
Больше не воспроизводится

**Comment by MozgalinaDaria** [comment]
можно закрывать
