### ISSUE TITLE
[ComboBox] Лоадер показывается на мгновение при загрузке

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#1007]
Можно как-то уметь показывать его через, например, две секунды после начала аякса?

**Comment by wKich** [comment]
В гайдах кстати этот момент зафиксирован 
https://guides.kontur.ru/controls/combobox/#17

> Если обработка запроса для построения списка занимает дольше 0,5 секунды, показываем лоадер минимум 1 секунду. Если список уже открыт, и при получении ответа возникла задержка — показываем лоадер, список до обновления остается в прежнем состоянии.
