### ISSUE TITLE
[ComboBox] Потеря фокуса после выбора элемента

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#1008]
Привет! Опиши, пожалуйста, проблему, которая возникла:
- Библиотека retail-ui 0.32 и выше
- Браузер last Chrome, ОС Win 10

До версии 0.32 у комбобокса после выбора элемента мышью терялся фокус у комбобокса, и если снова кликнуть по комбобоксу, то выпадает весь список вариантов:
![как было](http://g.recordit.co/IYyqIJOtfC.gif)

Начиная с версии 0.32, после выбора элемента мышью, фокус остается на комбобоксе и если на него кликнуть снова, то выпадет единственный, уже выбранный элемент:
![как стало](http://g.recordit.co/qevENx9RIj.gif)

И чтобы выбрать другой вариант приходится бэкспэйсом стереть введенное название, перед тем как покажется список вариантов. Причем при выборе с клавиатуры, фокус теряется и сценарий перевыбора сразу же после выбора работает.

**Comment by zhzz** [comment]
В принципе, так и задумывалось. Но, возможно, стоит открывать весь список на клик в фокусе. @dzekh

**Comment by dzekh** [comment]
Кажется странным, что что-то меняется при клике. Если фокус остался — то клик не должен ничего менять, ведь фокус уже стоит. Но это не главное. 

Комбобокс со стрелкой при фокусе должен показывать все варианты. Именно по этому тут есть стрелка — аналогия с селектом. Есть стрелка при фокусе показываем список. А когда выбираем элемент из списка это значит, что мы закончили работать с этим полем и оставлять открытым список не нужно и при выборе элемента мышью фокус должен сниматься с поля. При выборе с клавиатуры — переходить на следующее.

**Comment by dzekh** [comment]
Да, кажется ты прав. 
У меня в голове просто было фокус в поле == показываем список. 

Но если это не связанные действия, то можно оставлять фокус и при клике запускать поиск с пустым запросом. 

Получается поиск == показать выпадающее меню. 

Поиск запускается в момент когда поле получает фокус, изменяется значение поля (ввод или стирание символа), и при клике в поле, если выпадающее меню скрыто — так?
Условие про «скрыто» я добавил потому, что я могу кликнуть в поле чтобы просто переставить курсор в новую позицию, при уже открытом меню.
Есть еще ситуации когда меню скрыто, кроме случая, когда пользователь в него кликнул чтобы выбрать значение?

**Comment by zhzz** [comment]
> Да, кажется ты прав.
> У меня в голове просто было фокус в поле == показываем список.
> 
> Но если это не связанные действия, то можно оставлять фокус и при клике запускать поиск с пустым запросом.
> 
> Получается поиск == показать выпадающее меню.
> 
> Поиск запускается в момент когда поле получает фокус, изменяется значение поля (ввод или стирание символа), и при клике в поле, если выпадающее меню скрыто — так?
> Условие про «скрыто» я добавил потому, что я могу кликнуть в поле чтобы просто переставить курсор в новую позицию, при уже открытом меню.
> Есть еще ситуации когда меню скрыто, кроме случая, когда пользователь в него кликнул чтобы выбрать значение?

После нажатия "Esc".

**Comment by wKich** [comment]
> У меня в голове просто было фокус в поле == показываем список.

Да, такое впечатление могло сложится из-за того что ранее только фокус триггерил открытие списка, но в коде за рисование списка отвечает отдельный флаг, независящий от фокуса :)

> Получается поиск == показать выпадающее меню.

Не совсем. Внутри реализации для показа выпадашки используется отдельный флаг. Который может быть переключен различными способами.

> Поиск запускается в момент когда поле получает фокус, изменяется значение поля (ввод или стирание символа), и при клике в поле, если выпадающее меню скрыто — так?

Или при явном вызове метода `search`

> После нажатия "Esc" в фокусе.

И при явном вызове метода `close`
