### ISSUE TITLE
[Button] Проблемы с фокусом

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1013]
Проверено в Chrome@71 и Firefox@64 на MacOS@10.14

- В хроме при клике на кнопку в некоторых случаях рисуется рамка
![screen recording 2018-12-19 at 09 56 44_44](https://user-images.githubusercontent.com/6397708/50204380-71b99700-0386-11e9-8219-141d46e7f27e.gif)

- Переход фокуса в Chrome и Firefox работают по разному (Может быть это баг браузеров)
![screen recording 2018-12-19 at 11 41 29_29](https://user-images.githubusercontent.com/6397708/50204711-919d8a80-0387-11e9-821f-f96c9c74352c.gif)

**Comment by dzekh** [comment]
А то что в сафаре кнопки вообще фокус игнорят это норм?

**Comment by zhzz** [comment]
С Кебабом такая же история.
