### ISSUE TITLE
[Button] Некорректный цвет бордера

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1014]
В Firefox@64 из-за округления ширины правая граница иногда рисуется другим цветом
![screen recording 2018-12-19 at 11 16 44_44](https://user-images.githubusercontent.com/6397708/50205115-e8f02a80-0388-11e9-9019-69dc3b9ab8c7.gif)

Кажется что это связано с #728

**Comment by 21alexander21** [comment]
Можно решить, используя для границ border вместо box-shadow

**Comment by wKich** [comment]
Давай @mortifer призову

**Comment by qwerty2323** [comment]
Закрываю, т.к. на chrome 78, ff 70, IE11 для разных кнопок (размер, тип, цвет границы) не воспроизводится :)
