### ISSUE TITLE
[Retail-ui] и совместимость с @types/react^15

### ISSUE THREAD

**Issue by StarLordJ** [skbkontur/retail-ui#1016]
Со времён https://github.com/skbkontur/retail-ui/pull/719 те пропсы, у которых есть дефолтное значение, стали обязательными.
Сказано, что с TypeScript версии 3 всё будет работать нормально.
Но это происходит только если реакт 16-й версии. При 15-й компилятор ругается на то, что эти обязательные пропсы не были прописаны

**Comment by wKich** [comment]
Обнови пока пакет `@types/react` до 16-й версии.

Мы подумаем, можно ли порешать эту проблему для типов 15-й версии

**Comment by wKich** [comment]
Есть предположение, что в рамках библиотеки эту проблему не решить. Скорее всего придется править тайпинги для 15-го реакта в [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

Я попробую создать там ишью.

**Comment by wKich** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32662

**Comment by wKich** [comment]
Будет проще обновить тайпинги или сам react до 16-й версии
