### ISSUE TITLE
[Checkbox] Добавить поле use

### ISSUE THREAD

**Issue by bdskrur** [skbkontur/retail-ui#1017]
- retail-ui@last;

Нужна возможность выбора варианта использования checkbox'a в нескольких цветах одновременно. На данный момент требуется еще хотя-бы один вариант. На подобии как в Button'e

![image](https://user-images.githubusercontent.com/16319410/50220063-0e922980-03b3-11e9-9df3-137553d4cdf6.png)

**Comment by wKich** [comment]
Цветом checkbox/radio можно управлять через ThemeProvider. Кастомизация доступна в библиотеке с версии 1.0

**Comment by dzekh** [comment]
Кажется это не совсем тот случай когда удобно будет использовать темы. Тут нужен какой-то легкий способ переопределить цвет чекбокса. С тем же успехом можно было и про кнопки так же сказать и иметь только одну кнопку серую, а переопределять цвет через темы. В общем я бы еще пообсуждал и дождался обратной связи от @bdskrur — способ предложенный Димой подходит? Понятно как это сделать?
