### ISSUE TITLE
[Input] Одновременное использование разных цветов focus'a

### ISSUE THREAD

**Issue by bdskrur** [skbkontur/retail-ui#1018]
retail-ui@last;

Нужна возможность одновременного использования, как минимум, двух разных цветов состояния focus у Input'a.

![image](https://user-images.githubusercontent.com/16319410/50220202-7d6f8280-03b3-11e9-9e49-6030d9747d20.png)

**Comment by dzekh** [comment]
Если это критичное действие — удаление, после которого не будет возможности восстановить — можно применять красный в кнопках и ссылках. Но если в этом поле будет ошибка, как вы покажете ее?

**Comment by bdskrur** [comment]
Тоже думал над этим моментом, как вариант решения именно в этой ситуации: есть четкое понимание что в этом поле будет число, поэтому можно ограничить возможность ввода некорректных данных. Но если ситуация такова что нужно показать ошибку, то не знаю, у меня пока идей нету.

**Comment by wKich** [comment]
А действительно ли оправдана необходимость выделять чекбокс и инпут красным? В гитхабе кнопки с опасными действиями выделены красным, но инпуты в модалке вполне обычные. Можно наверно навесить плашку с сообщением об опасном действии, но оставить стандартные инпуты.

**Comment by wKich** [comment]
Цветом можно управлять через ThemeProvider. Кастомизация доступна в библиотеке с версии 1.0
