### ISSUE TITLE
[retail-ui] Заапрувить скриншотные тесты на плоскую тему контролов

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1023]
В задаче #985 будут добавлены скриншотные тесты на контролы с плоской темой. Необходимо проверить что отображение соответствует гайдам, если нет, завести задачу по исправлению.

**Comment by wKich** [comment]
Случайно коммит месаджем закрыл. Переоткрываю

**Comment by dzekh** [comment]
Предлагаю во все кнопки flat версии поставить border-radius: 2px; и в маленькие и в большие. 
А то брауеры так рендерят скругление в один пиксель что совсем не видно отличий от полей ввода. 

**Правки в стили во Flat версию** 
Кнопка при наведении
background: rgba(0, 0, 0, 0.05);
border: 1px solid rgba(0, 0, 0, 0.15);

Кнопка нажатая
background: rgba(0, 0, 0, 0.10);
border: 1px solid rgba(0, 0, 0, 0.15);

Поле ввода и текстэрия обычные
border: 1px solid rgba(0, 0, 0, 0.15);

Поле ввода и текстэрия заблокированные 
background: rgba(0, 0, 0, 0.05);
border: 1px solid rgba(0, 0, 0, 0.05);

Еще не достаточно подробно отсмотрел радиокнопки и чекбоксы но кажется что там все ок. 
Вообще они должны наследовать стили фона и границ от кнопок. Так же как и toggle

Во флет версии кнопки стрелки отображаются как обычные, без стрелок — это нужно исправить. Кажется, что во флет версии должно быть проще с этими кнопками. 

Хочется еще увидеть скриншоты:
- полей с иконками + текстами, в том числе плейсхолдером, выровненными по разным краям, 
- + к обычным полям — переполненные, когда значение длиннее поля
- Switcher во флет версии
- toggle и button в состоянии disabled
