### ISSUE TITLE
[ComboBox] [Fias] Пропадает фокус после нажатия enter в поле search

### ISSUE THREAD

**Issue by Ubitso** [skbkontur/retail-ui#1026]
Привет! 
Проблема с поведение инпута поиска в компоненте Fias.
С поля ввода пропадает фокус после нажатия tab или enter.

- Библиотека и её версия (retail-ui, react-ui-validations или другие);
retail-ui 0.33.0
- Браузер, его версию, ОС;
chrome 70.0
- Сценарий или произведенные действия;
1) Зайти http://tech.skbkontur.ru/react-ui/#/Components/Fias
2) Открыть пример с Fias search={true}
3) Написать "Новосиби"
4) Нажать enter
#### Ожидаемый результат:
Фокус остался на поле поиска.
#### Фактический результат: 
Фокус пропал

**Comment by dzekh** [comment]
> С поля ввода пропадает фокус после нажатия tab или enter.

А в чем проблема с `tab`? вроде таб для того и нужен чтоб перевести фокус на другое поле =)
А с `enter` — так [договорились дизайнеры](https://guides.kontur.ru/controls/combobox/#Fokus_i_rabota_s_klaviaturoi) — при работе с клавиатурой `enter` переводит фокус на следующее поле. Можно конечно пересмотреть это правило, уточнить или сделать исключение, но пока я тут не вижу ошибки. 

@zhzz предлагаю перенести как фичу в #905 и закрыть

**Comment by zhzz** [comment]
Перенесено в #905
