### ISSUE TITLE
[Гайды] На странице Сайдпейджа нет блока с компонентом из библиотеки

### ISSUE THREAD

**Issue by igorlukanin** [skbkontur/retail-ui#1027]
На странице [Сайдпейджа](https://guides.kontur.ru/components/sidepage/) нет блока со встроенным компонентом из библиотеки и ссылкой на задачи. А вот на соседней странице [Лайтбокса](https://guides.kontur.ru/components/lightbox/) всё есть :|

**Comment by dzekh** [comment]
Да, давно нет. Было бы круто если мне кто-то помогал с технической поддержкой Гайдов, там многих примеров не хватает. Лйтбокс там тоже пока не родной =)

Авторизацию никак не можем допилить уже который год. =// 

Я не справляюсь...

**Comment by dzekh** [comment]
Перенес в проект гайдов

**Comment by dzekh** [comment]
Добавили, теперь есть
