### ISSUE TITLE
[retail-ui] в all.ts описаны не все компоненты

### ISSUE THREAD

**Issue by slogger** [skbkontur/retail-ui#1028]
Версия: 0.33.0

Не хватает `Toggle`, возможно еще каких-то

**Comment by wKich** [comment]
Надо учитывать, что импорт компонентов из `all.ts` будет тянуть в бандл всю библиотеку контролов.

Какую задачу хочется решить с помощью `all.ts`?

**Comment by slogger** [comment]
Еще RenderLayer нету

В нашем случае не будет, ибо есть вебпак плагин для замены (components-import)

**Comment by dzekh** [comment]
@slogger Какую задачу хочется решить с помощью all.ts? Для вас критично чтобы мы добавили туда все компоненты? Актуальна еще задача?

@wKich а какая у нас логика, по какому принципу мы добовляем компоненты в all.ts ? В чем проблема если он будет тянуть все?

**Comment by slogger** [comment]
Для самописных попап-подобных компонент

**Comment by wKich** [comment]
А `DropdownContainer` или `TooltipMenu` не подходят? Если не подходят, то почему, есть ли уже ишью на это?

В `index.ts` хочется ограничится только публичными компонентами, которые представлены на витрине. Если вытаскивать наружу всё, то это усложнит поддержку.
