### ISSUE TITLE
Toast. Дизейблить кнопку 

### ISSUE THREAD

**Issue by govorukhin-do** [skbkontur/retail-ui#1031]
Часто в параметр label тоста нужно передать кнопку, которая вызывает какое-либо асинхронное действие. Например: "Повторить отправку письма".

После первого нажатия на кнопку не происходит никакой реакции в интерфейсе тоста. А отобразить реакцию на странице не всегда  возможно, так как пользователь мог уйти со страницы, на которой совершал действие.

Пользователь кликает повторно. Письмо снова отправляется (при дефолтном поведении, если не сделать специально зашиту от повторных кликов) 

Поэтому нужно как -то дефолтно защитится от повторных кликов и дать пользователю понимание что действие выполняется. 

Да, можно закрыть тост, но не всегда хочется так делать. Также при закрытии тоста есть анимация, так что повторные клики могут прилетать 

Для этого можно дать возможность тосту дизейблить кнопку и показывать mini спиннер. Но такого поведения нет в гайдах. возможно нужно согласовать.

**Comment by dzekh** [comment]
Такое поведение вполне логично. Можно дизэйблить кнопку или сылку в тосте, и как только выполнится действие скрывать старый тост, и, возможно, показывать новый. Спиннер будет лишним в тосте, его не нужно показывать. В гайд добавим. 

@wKich есть возможность у продуктов самим менять содержимое тоста после клика в ссылку в нем?

**Comment by wKich** [comment]
К сожалению нет такой возможности, в `ToastView` захардкожена ссылка

**Comment by dzekh** [comment]
> К сожалению нет такой возможности, в `ToastView` захардкожена ссылка

С одной стороны кажется что это плохо, и нужно как-то дать возможность дизэйблить ссылку, как минимум. Но с другой стороны есть вопрос:

> Часто в параметр label тоста нужно передать кнопку, которая вызывает какое-либо асинхронное действие. Например: "Повторить отправку письма".

@dimaname, а можно полностью сценарий? Как так получилось что ссылка «Повторить отправку» попала в тост? Там точно для нее хорошее место? 

Когда придумывали тост и ссылку в нем был один вариант сценария — отменить действие о выполнении которого сообщает тост. В контексте этого отмену можно только один раз сделать, и дизэйблить кнопку особо нет смысла. Пример в гайдах: https://guides.kontur.ru/components/toast/

**Comment by dimaname** [comment]
Ну вот есть в тосте кнопка "Отмена". После того как на нее нажать, тост начинает закрываться. Закрывается он с анимацией. И довольно легко можно успеть кликнуть по кнопке несколько раз.

**Comment by dimaname** [comment]
И второй вариант. После нажатия на кнопку в тосте, тост продолжает висеть сколько ему отведено по таймеру. Кнопку можно снова спокойно нажать. Я привел пример с "Повторить отправку" письма. На счет хорошее это место, так было нарисовано https://www.figma.com/file/LDEsTJl8QovDxguNShCkPXpA/%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B?node-id=708%3A15589

**Comment by dzekh** [comment]
по ссылке
<img width="616" alt="image" src="https://user-images.githubusercontent.com/26383080/66118654-60c5d380-e5f0-11e9-91b5-4fd7d04f2dfd.png">
