### ISSUE TITLE
[DropdownMenu] Лишний скроллбар

### ISSUE THREAD

**Issue by pravosud** [skbkontur/retail-ui#1044]
Система: Mac OS,
Браузер: Chrome 71.0.3578.98 

![ezgif-2-d073b0cd58cc](https://user-images.githubusercontent.com/5364762/50433894-d16eef80-08fc-11e9-83d1-d7baaf2c6873.gif)

**Comment by wKich** [comment]
Не понятно как воспроизвести. Возможно есть какие-то нюансы в настройках или окружении.

**Comment by dzekh** [comment]
Я тоже замечал такое в сафари

**Comment by wKich** [comment]
Воспроизводится при открытии браузера на экране ноутбука. На подключенном внешнем мониторе баг не проявляется. Первая гифки записана на внешнем мониторе, вторая на родном экране MacBook с ретиной
![screen recording 2019-02-01 at 10 53 23_23](https://user-images.githubusercontent.com/6397708/52105344-33172d80-2610-11e9-9302-c7c69839a8d7.gif)
![screen recording 2019-02-01 at 10 53 37_37](https://user-images.githubusercontent.com/6397708/52105345-33172d80-2610-11e9-8ff6-7940413bc886.gif)
