### ISSUE TITLE
[Input] - тормоза в Хроме и Опере при большом количестве контролов на странице

### ISSUE THREAD

**Issue by StarLordJ** [skbkontur/retail-ui#1046]
Много полей используется в книге покупок/продаж.

Опытным путём было выяснено, что проблема появилась после приведения Input'a к стилю по гайдам в версии 0.21.2. (https://github.com/skbkontur/retail-ui/issues/627).

Если не использовать определение цвета через формат rgba, проблема исчезает

**Comment by dzekh** [comment]
Видимо придется отказаться от rgba и прозрачности.

**Comment by wKich** [comment]
Воспроизводится, когда бордер имеет цвет в rgba и одна из сторон бордера имеет цвет отличный от остальных сторон, например:
```css
{
  border: 1px solid rgba(255, 0, 0, 0.5);
  border-top: 1px solid rgba(0, 0, 255, 0.5);
}
```
Отрисовка в iframe усугубляет ситуацию
![screen recording 2018-12-27 at 14 23 28_28](https://user-images.githubusercontent.com/6397708/50477035-6ac8ff00-09ec-11e9-99ab-71f77f159252.gif)
![screen recording 2018-12-27 at 14 35 56_56](https://user-images.githubusercontent.com/6397708/50477031-66044b00-09ec-11e9-8a05-291383aec9f8.gif)

**Comment by wKich** [comment]
Померил загрузку cpu/gpu
```
two colors:
iframe: 50 CPU, 70 GPU
no-iframe: 30 CPU, 5-7 GPU

one color:
iframe: 110 CPU, 15 GPU
no-iframe: 30 CPU, 5-7 GPU
```

**Comment by wKich** [comment]
Проблема решается указанием цвета без прозрачности для переменных `@border-color-gray-light` и `@border-color-gray-dark`.

Решение, использующее прозрачность и слегка улучшающее ситуацию, может привести к изменению цвета бордера в продуктах использующих другую цветовую схему и необходимости обновить значение для новой переменной.

Поэтому считаю, что задачу можно закрыть.
