### ISSUE TITLE
[Input] - нельзя задать собственный словарь formatChars

### ISSUE THREAD

**Issue by StarLordJ** [skbkontur/retail-ui#1047]
На версии 0.30.0 ещё работает 
![oldworkingmask](https://user-images.githubusercontent.com/14982003/50480831-26dff500-0a00-11e9-8877-910ae29f3311.gif)

Начиная с версии 0.31.0 словарь не прокидывается в ReactInputMask в MaskedInput.tsx, поэтому работает только дефолтное значение. Символы, которых нет в словаре, автоматически прописываются в поле.

![dontworkmaskinput](https://user-images.githubusercontent.com/14982003/50480869-66a6dc80-0a00-11e9-9918-9f39f76b2f7d.gif)

Если прокинуть:
![workmaskinput](https://user-images.githubusercontent.com/14982003/50480875-6dcdea80-0a00-11e9-9919-95d0ccd01584.gif)

**Comment by 21alexander21** [comment]
Пофикшено #1068
