### ISSUE TITLE
Проблемы с комбобоксом

### ISSUE THREAD

**Issue by fedorfo** [skbkontur/retail-ui#106]
Хочется, чтобы комбобокс умел делать следующие штуки:
1. Показывал плашку "загрузка", пока не получил resolve для промиса из source
2. Показывал каким-нибудь образом ошибку, если получил reject для промиса из source
3. Не реагировал на нажатие клавиши enter, пока source не resolved
4. Умел в промис source после фокусировки, когда значение уже выбрано и valueToText проставляется, передавать этот самый текст.
5. После появления MenuItem'ов сразу фокусировался на первом активном.

**Comment by nanot1m** [comment]
Разбил на части, будем решать одну проблему за раз
