### ISSUE TITLE
Select и Dropdown: disablePortal

### ISSUE THREAD

**Issue by fedorfo** [skbkontur/retail-ui#107]
Хочется для Select и Dropdown получить свойство disablePortal по аналогии с ComboBox. Мотивация: не можем легко обновиться но новый retail-ui, т.к. тестируем select и dropdown без Lookup и adapter, кажется, что это приемлемое временное решение

**Comment by nanot1m** [comment]
Поправлено в 2393ea3bfc3d9b543b88d1fb51f5a103de7f202d
