### ISSUE TITLE
[Select] Порефакторить и удалить неиспользуемый код

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1070]
При беглом взгляде у `Select` есть несколько проблем, возможно что их больше, если поразбираться.

В описании интерфейса пропов есть несколько заигноренных свойств: `_icon`, `_renderButton`, `diadocLinkIcon`. Надо уточнить у диадока используют ли они ещё их. Если используют, предложить вариант использования без этих свойств, например `<Button use="link" /> + <DropdownMenu />`

Свойство `search` добавляет в выпадашку поле ввода для поиска, которое в данный момент не работает из-за ошибки `TypeError: t.toLowerCase is not a function`. По отсутствию ишью и описанию в гайдах такого поведения, есть предположение, что данный функционал можно удалить.

**Comment by dzekh** [comment]
Учитывая последние обсуждения нужно бы вернуть поле и запустить поиск: https://staff.skbkontur.ru/post/50091c238021433486836ecd92c644ee

**Comment by dzekh** [comment]
Если это единственное не закрытое из этого таска, хорошобы вынести в отдельный а этот закрыть.

**Comment by zhzz** [comment]
Про поиск завел отдельно #1996. А про `_icon` и `_renderButton` еще актуально.
