### ISSUE TITLE
[Textarea] Управление высотой

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1072]
Хотелось уметь задавать минимальную высоту поля. Иначе получается не красиво, как на скриншоте.
![image](https://user-images.githubusercontent.com/9654622/51100078-287a2d00-17f6-11e9-8f31-7f50d8b55dac.png)

**Comment by dzekh** [comment]
можно зашить минимальный размер в компонент. по гайдам должно быть не меньше трех строк — https://guides.kontur.ru/controls/textarea/#07

**Comment by nextgennexia** [comment]
да, было бы замечательно

**Comment by 21alexander21** [comment]
Какая система, версия библиотеки, браузер?

**Comment by nextgennexia** [comment]
Проверял http://tech.skbkontur.ru/react-ui/#/Components/Textarea 
Хром 71.0.3578.98.
win10

По дефолту 3 строки, но можно уменьшить. Хотелось бы зашить min-height

**Comment by nextgennexia** [comment]
```javascript
<Textarea
  value={state.value}
  onChange={(_, value) => setState({ value })}
  resize="vertical"
  placeholder="Through faith we can reign in every area of life"
/>;
```

**Comment by dzekh** [comment]
Если я правильно понимаю такая проблема возникает только если пользователь сам уменьшил поле до такого размера. Если это так, то кажется что это не баг, и пользователь сможет вернуть все до нужных размеров и в будущем не уменьшать. Я закрываю баг. Если не согласны, или я не правильно понял — переоткройте с более подробным описанием.

**Comment by dzekh** [comment]
Ну если не сложно, давайте сделаем =)
