### ISSUE TITLE
[docs(react-icons)] Добавить поиск имени иконки в примере компонента Icons

### ISSUE THREAD

**Issue by sashasushko** [skbkontur/retail-ui#1079]
Бывает так, что из макетов дизайнера не узнать `name` иконки, по которому можно импортировать нужный компонент из `@skbkontur/react-icons`.

Сейчас иконки разложены по мелкой сетке, сами они тоже мелкие, что затрудняет поиск глазами.

Хочется поля поиска сразу в примере в документации, и чтобы с алиасами помимо `name`. Как поиск эмодзи в Твиттере или Вацапе:

![s90115-11375927](https://user-images.githubusercontent.com/4469056/51163060-4dd06f00-18ba-11e9-87bd-efd6f63f1097.jpg)

**Comment by sashasushko** [comment]
@nanot1m подсказал, что такой поиск есть в [Гайдах](https://guides.kontur.ru/resources/icons).

Если набор иконок между библиотекой и Гайдами синхронизирован, то можно обойтись бюджетным вариантом:
- заменить пример "Все иконки" в документации ссылкой на Гайды;
- в Гайдах добавить копирование обычного имени вместо C# варианта

**Comment by dzekh** [comment]
> Если набор иконок между библиотекой и Гайдами синхронизирован
да, синхронизирован, можно ссылку поставить

**Comment by wKich** [comment]
Надо уточнить, что синхронизация в ручном режиме :)

**Comment by dzekh** [comment]
Ну да, в ручном. но там очень не часто что-то меняется.
Обычного имени вместо C# варианта — это какого?

**Comment by dzekh** [comment]
Перенес в репу иконок в парковку
