### ISSUE TITLE
Combobox: debounce

### ISSUE THREAD

**Issue by fedorfo** [skbkontur/retail-ui#108]
Хочется иметь выставлять в Combobox debounce для source. Сейчас если вводить длинную строчку по одному символу, то сгенерируется куча запросов на сервер и все они будут обрабатываться последовательно

**Comment by Frumcheg** [comment]
Как видно из документации: http://tech.skbkontur.ru/react-ui/#/components/ComboBox, функция `search` возвращает промис. При создании промиса, можно самостоятельно определить, когда ему резолвиться, ибо:
```
new Promise((resolve, reject) => {
  if(true) {
    resolve();
  } else {
    reject();
  }
}):
```
Таки создадим промис с дебаунсом:
```
const debouncedPromise = new Promise(
  _.debounce((resolve, reject) => {
    resolve();
  }, 300)
);
````
Теперь можно из функции search возвращать промисы, которые будут резолвиться не чаще, чем через каждые 300мс.

**Comment by fedorfo** [comment]
Мы это уже сделали и засунули в нашу обертку для комбобокса. Но есть проблема.

Во-первых, сейчас в апи никак не зафиксировано как комбобокс работает с промисами: параллельно или последовательно. Нигде не сказано могу ли я возвращать reject с предыдущих, если уже есть новый промис. Нигде не сказано какой промис победит.

Во-вторых, я не понимаю почему я должен писать этот код на своей стороне. Это общая логика контрола. Кстати, в гайдах сегодня появится выпадашка "загружается". И debounceInterval на стороне retail-ui внесет ясности в апи.

**Comment by nanot1m** [comment]
Добавлен пропс `debounceInterval` в 040ea5685de6d2a4475a784fe51726799569901a
