### ISSUE TITLE
[Tooltip] Не позиционируется по гайдам

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1087]
В ситуации когда внутри Checkbox есть текст, Tooltip позиционируется не над чекбоксом
Версия: 0.36.0
Браузер: хром, последняя версия

![image](https://user-images.githubusercontent.com/9654622/51514206-947d1680-1e30-11e9-8d00-2c2c78d48748.png)

**Comment by 21alexander21** [comment]
Обойти проблему можно заворачиванием чекбокса с тултипом в `label`:

```javascript
<label>
  <Tooltip render={render} pos="right top">
    <Checkbox checked={state.checked} onChange={(_, v) => setState({ checked: v })} />
  </Tooltip>
  {' '}
  Checkbox
</label>
```
