### ISSUE TITLE
[DatePicker] Вызов onChange не только при Blur

### ISSUE THREAD

**Issue by michaeluskov** [skbkontur/retail-ui#109]
Допустим, есть такая модалка:

```
var TestModal = React.createClass({

    getInitialState() {
        return {value: new Date(), modal: true}
    },

    onChange(date) {
        console.log(date.target.value.toString());
        this.setState({value: date.target.value});
    },

    onClose() {
        alert(this.state.value.toString());
        this.setState({modal: false});
    },

    render() {
        if (!this.state.modal)
            return <div />;
        return <Modal onClose={this.onClose}>
            <Modal.Body>
                <DatePicker onChange={this.onChange} value={this.state.value}/>
            </Modal.Body>
            <Modal.Footer>
                <Button onClick={this.onClose}>Process date and do something</Button>
            </Modal.Footer>
        </Modal>
    }

});
```

По клику на кнопку модалка убирается и что-то происходит дальше с введенной датой. Но если дату ввести с клавиатуры и нажать на кнопку, то новое значение не подхватить:

![animation](https://cloud.githubusercontent.com/assets/4506837/23303930/ce6b14b6-fab8-11e6-9fe2-c65380d5af44.gif)

Так происходит, потому что Button не дает себя зафокусировать, а поэтому не дает заблюрить DatePicker, а событие onChange генерируется при блюре элемента.

**Comment by nanot1m** [comment]
Думаю, что при клике на кнопку все же стоит ей принимать фокус.

**Comment by michaeluskov** [comment]
@nanot1m А если сделать пропс focus: boolean? чтоб не поломать поведение, на которое команды могли завязаться.

**Comment by nanot1m** [comment]
`onFocus`, `onBlur` – не являются публичным апи и, более того, они не пробрасываются в кнопку.
