### ISSUE TITLE
[Input] размер шрифта medium

### ISSUE THREAD

**Issue by 21alexander21** [skbkontur/retail-ui#1094]
По-дефолту, размер **medium** равен `14px` и переключается на `16px` флагом `Upgrade.enableSizeMedium16px`. Но во flat-версии он по-дефолту `16px`. Нужно привести обе версии к одному поведениею

**Comment by dzekh** [comment]
Внутри команды договорились что синхронизируем дефолтное значение флага Upgrade.enableSizeMedium16px для плоской и обычной версии библиотеки, чтобы механизм был прозрачней и нам было проще поддерживать. 

По-дефолту, размер текста в полях medium будет равен 14px и переключается на 16px флагом Upgrade.enableSizeMedium16px и в плоской и в дефолтной версии библиотеки.

Перед тем как переключим нужно оповестить пользователей. Те кто использует плоскую тему должны будут включить у себя этот флаг, чтобы у них все осталось по старому.

**Comment by dzekh** [comment]
Судя по опросу в чатике скорее всего никто не использует переключатель Upgrade.enableSizeMedium16px — по этому есть смысл просто отказаться от этого переключателя. В плоской теме будут свои значения, в дефолтной свои.

Возвращаем значения для полей size=medium к состоянию которое было до этих правок
