### ISSUE TITLE
[react-ui-validations] [Input] [CurrencyInput] У инпута с маской сбрасывается выделение текста

### ISSUE THREAD

**Issue by halfee** [skbkontur/retail-ui#1102]
- retail-ui@0.36.0, react-ui-validations@0.3.0
- Любой браузер

1. Есть инпут с маской обернутый валидацией из react-ui-validations
2. Выделить текст в поле 
3. Навести курсор мыши на поле или убрать с поля курсор

Как есть: Сбрасывается выделение текста
Как должно быть: Выделение текста не должно сбрасываться

```
<ValidationContainer>
  <ValidationWrapperV1 validationInfo={validationInfo}>
    <Input value={value}
                mask={"999999999"}
                maskChar={""}/>
  </ValidationWrapperV1>
</ValidationContainer>
```

![20190129105535221](https://user-images.githubusercontent.com/1036441/51887156-8c832080-23b4-11e9-949b-d55d5c8c7ac2.gif)

**Comment by slawwan** [comment]
Похожий баг у CurrencyInput, сценарий:
1. В поле CurrencyInput введено число
2. Начинаем выделение текста в поле мышкой - зажимаем левую клавишу мыши и расширяем выделение
3. Не отпуская кнопку мыши выходим за границы CurrencyInput
4. Выделение в CurrencyInput сбрасывается

Причины:

CurrencyInput сам управляет выделением значения. Внутри метода `componentDidUpdate` устанавливает выделение в нативном инпуте с помощью метода `input.setSelectionRange(start, end)`. позиции курсорсару берутся из state компонента `CurrencyInput`. В процессе выделения вышкой state компонента `CurrencyInput` не обновляется и там лежит старая позиция курсора/выделения, она обновится только на `mouseUp`. Получается что при любой перерисовке компонента `CurrencyInput` во время выделения значения, выделение сбросится в методе `componentDidUpdate`.

Компонент `ValidationWrapper` для отображения валидации в тултипе оборачивает вложенный контрол в компонент `ValidationTooltip`, который в свою очередь следит за событиями мыши `onMouseEnter` и `onMouseLeave`. В обработчике события обновляется state компонента `ValidationTooltip` - устанавливается значение флага, находится ли курсор над оборачиваемым полем. То есть чередующиеся события `onMouseEnter` и `onMouseLeave` приводят к перерисовке оборачиваемого компонента.

Поэтому теряется выделение в `CurrencyInput`. Предполагаю что в компоненте `Input` с маской подобный сценарий.

Кажется проблему нужно решать с двух сторон.
1. Сделать механизм работы с позиционированием курсора и выделением значения более стойким к внешним факторам
2. Добавить в Tooltip из react-ui дополнительный `trigger`, который бы реализовывал поведение, требуемое в ValidationTooltip, то есть показывать тултип код поле в фокусе или когда по ховером, то есть объединение триггеров `focus` & `hover`

**Comment by Ant-VAV** [comment]
Столкнулись с такой же порблемой
