### ISSUE TITLE
[Input] Поведение с маской из разных групп допустимых символов

### ISSUE THREAD

**Issue by halex2005** [skbkontur/retail-ui#1103]
Библиотека: retail-ui v0.33.1
Браузер: любой

Сценарий:
Необходимо дать пользователю возможность вводить номер автомобиля по маске `a999aa 999` (подходит дефолтное значение `formatChar`).

Проблема:
При удалении символов в середине введенной строки, символы, не подходящие под маску, неожиданным образом стираются (см. гифку). Предлагается обсудить в гайдах как должен вести себя Input в случае маски с разным набором символов?

Как воспроизвести:
На https://tech.skbkontur.ru/react-ui/#/Components/Input задать поле ввода так:

```jsx
<Input mask="a999aa 999" />
```

![input-mask-behavior](https://user-images.githubusercontent.com/1401048/51900860-28725380-23d8-11e9-9f97-977e1b489f8e.gif)

**Comment by dzekh** [comment]
Одно из возможных решений этой проблемы — научиться объединять отдельные позиции в группы по принципу «если у них одинаковая маска» и сдвигать при удалении символы только в рамках этих групп. Внутри группы символы должны сдвигаются когда удаляются, а снаружи группы - введенные символы остаются на месте.

**Пример**
Например у маски "a999aa 999" 4 группы. Если стирать первые символы внутри групп, должно быть так:
Ввели значение: A123BC 456 
Стерли первый символ — _123BC 456 
Стерли второй символ — _23_BC 456
Стерли пятый символ — _23_C_ 456

**Нужно не забыть про курсор**
Если потом стереть всю левую часть: _ _ _ _ _ _ 456, и пытаться поставить курсор в середину маски (_ _ _ _ |_ _ 456) — курсор должен вставать в крайнюю левую позицию игнорируя пустые группы(|_ _ _ _ _ _ 456)&

**Прибитые символы**
«Прибитые» символы типа «_», « », «-» или «.» не должны разбивать группы. Хороший пример — маска кредитной карты. Сквозь разделитель групп пробел должны перемещаются символы. В случае если я ввел лишнюю цифру в начале номера карты и потом решил ее стереть, все символы справа должно сдвинуться.

**Comment by halex2005** [comment]
@zhzz, в значении input вместо удаленного символа можно подставлять, например, пробел.

Кажется, сам input не должен пытаться валидировать значение инпута.
Валидация формы, которая содержит input с маской, сам отловит невалидные значения.

Задача input - помочь ввести значение по маске предсказуемым образом, и так чтобы это не вызывало раздражения пользователя.

**Comment by zhzz** [comment]
Задача маски в том числе и фильтровать невалидные символы. Если потом придется делать это еще раз в форме, то будет странно.

Можно, конечно, вообще ничего не отдавать пользователю, пока маска не будет заполнена полностью. Но все равно, предлагаемое поведение кажется очень не естественным для текстового поля. Пока не понятно, реализуемо оно или нет.

**Comment by dzekh** [comment]
Подвожу резюме и закрываю баг. Фича довольно однозначное, решение на уровне библиотеки сложное. В ближайшем обозримом будущем поведение отличное от текущего реализовывать не будем. Если будут подобные запросы — поднимем эту тему снова.

Решение на уровне продукта — не использовать маску в таких случаях, оставлять обычный инпут, валидировать поле и подсказывать что не так при валидации.

Для таких сложных масок, тем более когда для них есть проверка на сервере лучше использовать обычное поле, так будет удобней для пользователя, либо разбивать поле по группам на отдельные инпуты, что тоже не очень удобно для пользователя. Либо очищать поле всегда целиком.
