### ISSUE TITLE
Помощь с переездом @skbkontur/react-ui => retail-ui

### ISSUE THREAD

**Issue by vkosovskikh** [skbkontur/retail-ui#1104]
Используем в проекте **@skbkontur/react-ui**. Появилась необходимость поменять цвета некоторых контролов. Подскажите, пожалуйста:

1) Будет ли безопасно полностью заменить все компоненты на аналоги из **retail-ui**, или стоит ввести эту библиотеку отдельно?

2) Наш текущий прод-конфиг для стилей:
```
{
  test: /\.less$/,
  loader: ExtractTextPlugin.extract(
    Object.assign(
      {
        use: [
          {
            loader: 'css-loader',
            options: {
              modules: true,
              minimize: true,
              sourceMap: shouldUseSourceMap,
            },
          },
          {
            loader: 'postcss-loader',
            options: postCSSOptions
          },
          'less-loader'
        ]
      },
      extractTextPluginOptions
    )
  )
}
```
То есть, используем локальные **css-модули**. Будет ли правильным, в таком случае, отдельно для **retail-ui** добавить:

```
{
  test: /\.less$/,
  include: /retail-ui/,      // Эта строка
  use: [
    'style-loader',
    {
      loader: 'css-loader',
      options: { modules: 'global' } // и эта строка
    },
    'less-loader'
  ],
}
```

3) В ReadMe так же есть конфиг для файлов **.jsx**:

```
{
  test: /\.jsx?$/,
  use: [
    {
      loader: 'babel-loader',
      options: {
        presets: ['env', 'react'],
        plugins: [
          'proposal-object-rest-spread',
          'proposal-class-properties'
        ]
      }
    }
  ],
  include: /retail-ui/
}
```
Все ли здесь в порядке? Некоторые компоненты написаны на **.js** или **.tsx** (если делать импорт из папки **/components**). Или же нужно сделать какой-то prebuild и делать импорт по-другому?

**Comment by zhzz** [comment]
Привет!

1. Безопасно. Два пакета библиотеки точно держать не нужно.
2. Ваш текущий конфиг подходит, отдельное правило не требуется. Мы в своих стилях везде проставляем `:local` и `:global`, поэтому они должны работать в любом режиме css-modules.
3. Это необходимое правило для обоих пакетов, т.к. компоненты всегда поставляются скомпилированными в `.js`. Отличаются лишь файлы стилей: `.less` в "retail-ui" и `.css` в "@skbkontur/react-ui".

Будут еще вопросы - пиши.

**Comment by zhzz** [comment]
Пока прикроем issue. Еще у нас есть специальный [чатик](https://t.me/joinchat/CdESHkfq-QczDV0WxaPdKg) по контролам.
