### ISSUE TITLE
[ScrollContainer] не работает preventWindowScroll в ИЕ11

### ISSUE THREAD

**Issue by original001** [skbkontur/retail-ui#1105]
Привет! Опиши, пожалуйста, проблему, которая возникла:
- Библиотека retail-ui
- Браузер ИЕ
- скролю до конца список в контейнере с пропсом `preventWindowScroll`

**Comment by step-off** [comment]
@original001 Баг еще актуален? Если да, приведи, пожалуйста, пример воспроизведения. По тому, как ты описал, не воспроизводится ни на https://tech.skbkontur.ru/react-ui, ни локально.

**Comment by original001** [comment]
воспроизводится на маке под виртуалкой

**Comment by step-off** [comment]
@original001 
Это баг движка:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7134034/
При скролле 2-мя пальцами на PTP тачпадах не происходит событие onwheel. Если скролить мышкой, баг не воспроизводится.
Хотя у бага стоит статус fixed, он по-прежнему воспроизводится и в Edge 17, и в IE11 на новых сборках Windows 10. Нормального обхода этого бага нет. Предлагаю закрыть issue.
