### ISSUE TITLE
[react-ui-screenshot-tests] Не детерминированный переход фокуса по табу в Firefox

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1109]
Для скриншотных тестов на кнопку в которых происходит нажатие кнопки `Tab` и проверяется корректность перехода фокуса на трестируемую кнопку. Прохождение зависит от предыдущих состояния. В результате тест проходит только после `Retry`.

**Comment by lossir** [comment]
Как выяснилось, основная проблема была в реализации либы `TabListener`.
Исправлено здесь https://github.com/skbkontur/retail-ui/pull/1400.

Однако, это не снимает вопрос о не детерминированности некоторых тестов)

**Comment by dzekh** [comment]
Дежурному выявить такие тесты и переписать.

**Comment by dzekh** [comment]
#1941 возможно и это за одно
