### ISSUE TITLE
[DateInput] Курсор мыши в состоянии disabled отличается от Input

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1118]
В `<DateInput disabled />` курсор мыши принимает форму стрелки. В то время как у `<Input disabled />` курсор не изменяется по сравнению с не задизейбленым.

Нужно понять какой из вариантов правильный и сделать однообразно везде.

**Comment by dzekh** [comment]
Текстовый курсор появляется над любым текстом, и показывает, что текст можно выделить и скопировать.  Должна быть возможность выделить и скопировать значение из заблокированного поля, следовательно курсор должен быть текстовый. И текст должен выделяться.

**Comment by wKich** [comment]
Тогда поведение реализованное в #1117 верное.
