### ISSUE TITLE
[retail-ui] Описать гайдлайны для контрибьюторов

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1132]
- [x] Ссылка на работу с гитхабом (PR, fork, upstream). Процесс принятия PR.
- [x] Что нужно установить, чтобы начать разработку (xcode-select, windows-build-tools).
- [x] Как запустить тесты, линтеры, сторибук
- [ ] Как включить плоскую тему.
- [x] Код стайл, настройки IDE.
- [x] `yarn commit` и ссылка на conventional-changelog.

Частично обновил гайд в #1144

**Comment by dzekh** [comment]
Cсылки в помощь: [material-ui](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md), [arui-feather](https://github.com/alfa-laboratory/arui-feather/blob/master/.github/CONTRIBUTING.md)
