### ISSUE TITLE
[MenuItem] Перекрывает скроллинг

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#114]
Когда в выпадашке, например, комбобокса есть скроллинг, MenuItem при ховере перекрывает скроллбар, и его нельзя схватить мышкой
![image](https://cloud.githubusercontent.com/assets/9248122/23461744/ef352b26-feac-11e6-8d91-2b6c67633475.png)

**Comment by nanot1m** [comment]
Поправлено в #125
