### ISSUE TITLE
[Modal] Анимация

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#115]
Хочется иметь возможность задавать анимацию появления и исчезновения.
С исчезновением будет посложенее, похоже, надо допиливать RenderContainer.

**Comment by nanot1m** [comment]
@molokovev про задачу не забыли, ждем гайдов по анимациям
@dzekh есть сроки по релизам гайда?

**Comment by 21alexander21** [comment]
займемся после появления гайда
