### ISSUE TITLE
[ComboBox] Исправить в гайдах значение времени перед показом спиннера

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1152]
0,5 секунды достаточно большой интервал и пользователь может подумать, что интерфейс тупит. В #1096 было установлено значение в 0,3 секунды.

https://guides.kontur.ru/controls/combobox/#17

**Comment by dzekh** [comment]
Исправил на облаке, скоро уедет на боевую, закрываю.
https://guides.dev.kontur/components/combobox/#Spinner
