### ISSUE TITLE
[Token] Отличается положение текста в разных браузерах

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1158]
![screenshot 2019-02-15 at 17 05 11](https://user-images.githubusercontent.com/6397708/52855946-cb4eff80-3144-11e9-84f0-f7829c895676.png)

В Chrome и Firefox текст располагается ниже чем в IE

**Comment by dzekh** [comment]
Крестик в Хроме и ФФ более менее ровно стоит. Есть какое-то субпиксельное смещение, если получится лучше от него избавиться. 

Текст в Хроме и ФФ нужно поднять 1px.
Крестик в ИЕ нужно опустить на 2px а текст на 1px.

Все то же самое но по другому если сформулировать: 
Крестик относительно текста везде стоит на пиксель выше. Если сместить везде текст на пиксель выше, то в ИЕ придется весь блок крестика с текстом опустить на 2px.

**Comment by dzekh** [comment]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/26383080/52859440-892abb80-314e-11e9-9378-610a6f509172.png">
