### ISSUE TITLE
[Modal] Адаптация под мобилки

### ISSUE THREAD

**Issue by pravosud** [skbkontur/retail-ui#1164]
В ряде случаев модалкой сложно пользоваться в мобильных интерфейсах.

Пример:
![telegram-cloud-file-2-257125866-17262-4202850686772591285](https://user-images.githubusercontent.com/5364762/52948548-82dd4f00-339b-11e9-90fe-eef6ce346a04.jpg)

Хотел бы подкинуть пищу для размышлений, как никак мобильные интерфейсы с каждым годом все больше и больше набирают обороты. Если заглянуть в Material-ui, можно увидеть хорошую возможность открывать модалку во весь экран или выбирать возможность скроллить целиком или только контент (https://material-ui.com/api/dialog/) 

p.s прикрепленный скришот — отзыв реального пользователя, который пожаловался на неудобство использования формы внутри модалки

**Comment by wKich** [comment]
Адаптация под мобилки кажется достаточно объемной задачей, учитывая отсутствия гайдов под это дело. Я предлагаю, если есть возможность, сделать пробный подход для модалки и прислать PR, мы с @dzekh посмотрим. Во всяком случае это сдвинет дело с мертвой точки.

**Comment by dzekh** [comment]
а вроде у модалки должны убираться отступы на мобилках или узких экранах. 
что-то делали для этого: https://github.com/skbkontur/retail-ui/pull/598

**Comment by wKich** [comment]
Так в ишью не идет речь про отступы.

**Comment by dzekh** [comment]
В моем представлении «открывать модалку во весь экран» равно «убрать лишние отступы между модалкой и страницей». «Выбирать возможность скроллить целиком или только контент» вроде как примерно равно «убрать залипающие панели», что тоже вроде есть в настройках. 

Или я что-то не понимаю? Или в #598 про другие отступы речь?

**Comment by wKich** [comment]
Кажется в данном случае, даже если убрать отступы сильно лучше не станет.

Но в принципе можно попробовать. Судя по той правке надо для мобилок переключать рубильник `Upgrades.setAdaptiveStyles(true)`. А по скрину это не было сделано. Возможно наш косяк, что ничего про него нет в доках. @pravosud попробуй с включить

**Comment by dzekh** [comment]
Мне кажется этот рубильник можно по умолчанию включить, всем только лучше от этого станет.

**Comment by wKich** [comment]
Интересно почему его изначально не включили? Или зачем вообще это рубильник был сделан @mshatikhin?

**Comment by mshatikhin** [comment]
![2019-02-20 10_26_36-gcloud staff](https://user-images.githubusercontent.com/1788385/53068373-0f9e1f00-34fa-11e9-9273-bd6fa678269b.png)

нам в стафе (который на продажу) нужна адаптивность, поэтому втащили этот флаг, флаг - для обратной совместимости, конечно лучше сделать по дефолту нормальное поведение (адаптивное)

у меня для "адаптивности" модалки втащен костыль из медиа запросов, который уменьшает боди модалки, а модалки стоит width auto,

это хреново.

я не против поучаствовать в обсуждении адаптивности, могу привести примеры из стафа, где мне пришлось либо писать свои компоненты, либо как то костылить retail-ui

**Comment by dzekh** [comment]
Давайте уберем флаг и может добавим это уменьшение боди про которое ты говоришь, чтобы ты убрал костыль.

Такие штуки, которые включаются только на узких экранах, кажется можно не прятать под флагами, а сразу делать нормально для всех. Всем только лучше будет. 

Чтобы начать работу над отображением на мобильных нужно, наверное первым делом договориться о брекпоинтах для медиазапросов, какие ставим, какие нужны. [Типа как тут](https://material-ui.com/layout/breakpoints/). Потом уже для них правила добавлять. м?
