### ISSUE TITLE
[Input, ComboBoxOld, ComboBox] разный цвет placeholder

### ISSUE THREAD

**Issue by Lelchik** [skbkontur/retail-ui#1166]
Привет!
- retail-ui, версия последняя (сейчас 0.39.0)
- Firefox Quantum 65.0.1
- ```
  <div>
    <ComboBoxOld placeholder="ComboBoxOld"/>{" "}
    <Input placeholder="Input" />{" "}
    <ComboBox placeholder="ComboBox"/>
  </div>
![image 3](https://user-images.githubusercontent.com/11275614/52952517-96da7e00-33a6-11e9-89f4-0d62418e5069.png)

**Comment by dzekh** [comment]
[Цвет текста](https://guides.kontur.ru/principles/color/#Tekst) плейсхолдера во всех компонентах должен быть #A0A0A0 в дефолтном состоянии и #CDCDCD в момент фокуса. 

В сафари теперь тоже баг с цветом плейсхолдера в инпутах — он стал черный. 

У префикса, кстати тоже должен быть #A0A0A0, но при фокусе он не меняется. Вроде сейчас так и есть, нужно просто проверить.
