### ISSUE TITLE
[ComboBox] Не отображает значение после выбора при кастомном renderValue 

### ISSUE THREAD

**Issue by kmal1363** [skbkontur/retail-ui#1170]
Библиотека retail-ui, версия 0.40.0
Браузер хром, версия 72.0.3626.109

Шаги воспроизведения
1. Массив значений в формате {value: 1, text: 'Some text'}
2. Переопределяем renderValue и renderItem вот так:
renderValue={item => item.text}
renderItem={item => item.text}
3. Выбираем значение из списка
Ожидание: после выбора значения список схлапывается, поле инпута в фокусе, в нем появляется текст выбранного значения
Реальность: после выбора значения список схлапывается, поле инпута в фокусе, но в нем нем значение. Значение видно только после потери фокуса

Воспроизводится в том числе на страничке https://tech.skbkontur.ru/react-ui/. Сразу в первом примере

В 29 версии еще все работало нормально

Гифка - http://recordit.co/XiFMnqSqva

**Comment by wKich** [comment]
Тебе необходимо переопределить проп `valueToString`
<img width="778" alt="screenshot 2019-02-19 at 12 29 58" src="https://user-images.githubusercontent.com/6397708/52997360-2c771b80-3442-11e9-9f2b-f05792dd177b.png">
