### ISSUE TITLE
[retail-ui] Выпилить tslint

### ISSUE THREAD

**Issue by k-g-a** [skbkontur/retail-ui#1179]
Сейчас eslint нужен для проверки компонентов не переписанных на ts. Но по факту он линтит js'ки получившиеся после yarn build. Так как компонентов на js осталось мало, можно отказаться от eslint.
После [переезда на babel@7](https://github.com/skbkontur/retail-ui/issues/1129) можно будет поступить правильно: выкинуть tslint и вернуть eslint в полном объеме.

**Comment by wKich** [comment]
Пожалуй переименую, так как tslint задеприкейтился в пользу eslint
