### ISSUE TITLE
[Input] Проблема выделения значения с префиксом

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1196]
На момент версии 0.41. Нельзя выделить часть префикса или значение вместе с префиксом.
![screen recording 2019-02-26 at 12 42 41_41](https://user-images.githubusercontent.com/6397708/53396274-dec05d00-39c5-11e9-8081-e366fcc82b2c.gif)

**Comment by dzekh** [comment]
Кажется что сценарий очень редкий и не стоит усилий чтоб исправлять. Если для какого-то продукта частый — можно сделать отдельную кнопку «копировать адрес» или типа того. пока закрою.
