### ISSUE TITLE
[DatePicker] Error: Не удалось завершить действие. Ошибка 800a025e.

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1205]
Версия библиотеки: 0.41.1
Браузер: ie 11.967.16299.0

Тестировал на http://tech.skbkontur.ru/react-ui/#/Components/DatePicker
Необходимо добавить Input:
```javascript
<Tooltip
  trigger={state.tooltip ? 'opened' : 'closed'}
  render={() => 'Такой даты не существует'}
  onCloseClick={removeTooltip}
>
  <Input />
  <br/>
  <DatePicker
    error={state.error}
    value={state.value}
    onChange={handleChange}
    onFocus={unvalidate}
    onBlur={validate}
    enableTodayLink
  />
</Tooltip>
```

Далее поставить фокус в датапикер и не выбирая даты/не закрывая поставить фокус в инпут.
С первого раза может не сработать. Бывает и с первого раза упадет ошибка, а бывает тыкаешь туда сюда и ничего. 

![image](https://user-images.githubusercontent.com/9654622/53716881-2f2d3400-3e78-11e9-8933-2cb2efdfdc84.png)

Может по видео станет чуть более понятны действия: http://recordit.co/xiiByJnPTR

**Comment by nextgennexia** [comment]
Тоже самое происходит при переключении между двумя датапикерами 

![image](https://user-images.githubusercontent.com/9654622/53720721-41609f80-3e83-11e9-8cb6-f1820f7050c3.png)

Ругается на здесь:
![image](https://user-images.githubusercontent.com/9654622/53720762-56d5c980-3e83-11e9-8662-441f2e058ab4.png)

**Comment by wKich** [comment]
Пишут что это какая-то дичь в ИЕ https://stackoverflow.com/questions/22914075/javascript-error-800a025e-using-range-selector/37580789#37580789

Но так же есть фикс, который можно попробовать и проверить, что проблема в ИЕ больше не проявляется. @nextgennexia, есть возможность проверить?

**Comment by nextgennexia** [comment]
Впринципе работатет (по крайней мере ошибка не падает). При клике на соседний датапикер не происходит выделения, приходится кликать повторно. Ну я думаю это меньшее из зол

http://recordit.co/dmYvIh4jSb

**Comment by wKich** [comment]
Хорошо, тогда сегодня постараемся катнуть.
