### ISSUE TITLE
Реализовать локализацию контролов

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#1209]
Возникла необходимость в локализации контролов.
Пришли в выводу, что контролы должны иметь локализацию "из коробки", чтобы типовые случаи каждый команде не приходилось реализовывать самостоятельно.
Но для уникальных случаев, таки должна быть возможность кастомизации.

Часть "простых" контролов можно локализовать в рамках задачи.

- [x] TokenInput
- [x] ComboBox
- [x] Spinner
- [x] TopBar
- [x] Select
- [x] Paging
- [x] Logotype

**Comment by wKich** [comment]
Опиши более подробное, особенно про дейтпикер
