### ISSUE TITLE
[Password] Поле для пароля с прогресс-баром

### ISSUE THREAD

**Issue by pikhnova** [skbkontur/retail-ui#1229]
Привет!
Планируется ли, и если да, то когда, создать контрол с прогресс-баром? Хотим заиспользовать его в:
- странице регистрации auth.kontur.ru/registration
- странице восстановления пароля
- личном кабинете пользователя.
Апишка из auth.api

Описание работы `PasswordInput` в гайдах https://guides.kontur.ru/components/password/

**Comment by wKich** [comment]
@dzekh, нужно посмотреть требуются ли какие-нибудь доработки или актуализация гайдов.

**Comment by dzekh** [comment]
Посмотрел, возможно совсем незначительные пара правок, в целом все ок. 
В гайдах даже стоит правильный PasswordInput, только ссылку на доку нельзя поставить, так как компонент приватный. Давайте его хотябы откроем. Заодно, кажется эту задачку можно порешать: https://github.com/skbkontur/retail-ui/issues/1028 
Ну и само собой эту: https://github.com/skbkontur/retail-ui/issues/1181

**Comment by dzekh** [comment]
Даша, ребята [сделали это](https://ui.gitlab-pages.kontur.host/docs/#/new-password/NewPassword)! =)

**Comment by pikhnova** [comment]
Ураааааааааааааа! Спасибо!
