### ISSUE TITLE
[FxInput] Prop width не работает в ie

### ISSUE THREAD

**Issue by Sergey-Ubogov** [skbkontur/retail-ui#1234]
retail-ui 0.43.0
ie 11.523.17134.0

добавил к FxInput width={130}
вот так выглядит в ie:
![image](https://user-images.githubusercontent.com/19286511/54195036-7d2ce200-44df-11e9-97ab-b2463dabb5d6.png)
а так в chrome:
![image](https://user-images.githubusercontent.com/19286511/54195047-84ec8680-44df-11e9-985a-74c7a88e4d50.png)

https://github.com/skbkontur/retail-ui/blob/5dc94431148860b2888c5369c18e10e07d628bb2/packages/retail-ui/components/Group/Group.tsx#L81
если здесь сделать `<div className={wrapCss} style={style}>` то сработает в ie

**Comment by dzekh** [comment]
Кажется что-то похожее: https://github.com/skbkontur/retail-ui/issues/1199
