### ISSUE TITLE
[react-ui-validations] Не показывается тултип при валидации RadioGroup

### ISSUE THREAD

**Issue by dpeshkin** [skbkontur/retail-ui#1249]
Не срабатывает тулип при валидации радио кнопок. Сообщение появляется только по ховеру.
![validation](https://user-images.githubusercontent.com/13113273/44333686-fb189580-a488-11e8-909a-231b93f44861.gif)

**Comment by wKich** [comment]
Сейчас при валидации фокус устанавливается в первый RadioButton и перекрывает подсветку ошибки
![Screenshot 2019-03-15 at 17 55 30](https://user-images.githubusercontent.com/6397708/54432628-8cb06300-474b-11e9-9439-3a6f8dc6ba1b.png)

**Comment by dzekh** [comment]
Нужно сделать чтоб не перекрывал 🤷‍♂️
https://guides.kontur.ru/principles/validation/#13 — Красная подсветка снимается с поля, как только пользователь начал исправлять ошибочное значение.

Этот же принцип должен работать в остальных контролах, пока не редактировали — красный, как только поменяли значение — синий фокуса.
