### ISSUE TITLE
[retail-ui] Выпилить полифил add-event-listener

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#1256]
Полифил [add-event-listener](https://www.npmjs.com/package/add-event-listener) требовался для IE8- и больше не актуален.

- [x] Button
- [x] IgnoreLayerClick
- [x] Kebab
- [x] Link
- [x] Logotype
- [x] Modal
- [x] Paging
- [x] RenderLayer (done in 7ff23357)
- [x] Select
- [x] SidePage
- [x] LayoutEvents
- [x] listenFocusOutside

**Comment by wKich** [comment]
Будет пофикшено в #1322
