### ISSUE TITLE
[Modal] Съезжают отступы, т.к. не работает сравнение по type вместе с react-hot-loader

### ISSUE THREAD

**Issue by sergeyshmakov** [skbkontur/retail-ui#1267]
- react-ui последняя версия
- Chrome последняя версия
- При использовании `react-hot-loader` в dev-режиме все компоненты приобретают hot-обертку, из-за этого сравнение элементов по `type` не работают. Так в режиме разработки с `react-hot-loader` у нас ломались отступы в лайтбоксе.

Пример кода в `ModalHeader.tsx` который всегда возвращал `false` - `child.type === Header`.
Абсолютно то же самое в `ModalFooter.tsx` - `child.type === Footer`

Все это относится к особенности работы `react-hot-loader`, которую нельзя изменить.
https://github.com/gaearon/react-hot-loader/issues/304

**Comment by wKich** [comment]
А почему у тебя компоненты библиотеки оборачиваются в обертку?

**Comment by theKashey** [comment]
Да, настало время это починить.

**Comment by zhzz** [comment]
Мы починили в [0.46.0](https://github.com/skbkontur/retail-ui/releases/tag/retail-ui%400.46.0).

**Comment by theKashey** [comment]
Вы то да, а React-Hot-Loader пока еще нет. В понедельнику авось и [починится](https://github.com/gaearon/react-hot-loader/pull/1261).
