### ISSUE TITLE
[FxInput] FxInput спредом прокидывает свойство refInput до Input-а

### ISSUE THREAD

**Issue by tihonove** [skbkontur/retail-ui#1270]
А Input прокидывает его до input-а, в итоге вылатет warning в консоли

Проверено на retail-ui@0.33.3

**Comment by tihonove** [comment]
Также в FxInput-е используется `Group`, которые к добавляет к `Input` свойство corners, которое летит в `input`

**Comment by wKich** [comment]
corners поникшего в #1247
