### ISSUE TITLE
[Input] неправильно работает с маской

### ISSUE THREAD

**Issue by Sergey-Ubogov** [skbkontur/retail-ui#1282]
retail-ui@0.44.1
chrome  72.0.3626.121

сделал такой инпут с маской: 
```
<Input width={252}
       mask="999 99 999 9 99999999999"
       placeholder="___ __ ___ _ ___________"
  />;
```

при длинном вводе текст сдвигается влево + нельзя начать выделение текста с пустой области инпута
![thebuginput](https://user-images.githubusercontent.com/19286511/54922845-d73f9580-4f2a-11e9-8a43-ce0202929c5e.gif)

**Comment by zhzz** [comment]
Пофиксилось в 0.44.3
