### ISSUE TITLE
[retail-ui] Отказаться от поддержки адаптеров к компонентам и Lookup.js

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1286]
В библиотеке компонентов написаны хелперы для тестирования [`Lookup.js`](https://github.com/skbkontur/retail-ui/blob/master/packages/retail-ui/testing/Lookup.js), которые не развиваются и их работоспособность никак не проверяется.

Нужно убедится что никто этими хелперами не пользуется и удалить. На конец 2018 года точно известно что Формы и Диадок пользовались этими хелперами в своих тестах.

**Comment by zhzz** [comment]
После выпиливания можно будет удалить пакет `object-assign` из retail-ui.

**Comment by wKich** [comment]
Диадок и формы предупреждены, что адаптеры будут удалены в 2.0.
