### ISSUE TITLE
[react-ui-testing] Вынести js в отдельный npm пакет

### ISSUE THREAD

**Issue by Frumcheg** [skbkontur/retail-ui#1288]
Привет. Мы пишем selenium тесты на js и используем [react-selenium-testing](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui-testing/react-selenium-testing.js) из репозитория react-ui-testing. Хочется устанавливать этот модуль в проект, как и все остальные зависимости - через `npm ci`. Есть ли у вас в планах вынесение этого файла в отдельный пакет?

**Comment by slawwan** [comment]
сейчас в скрипте, который пробрасывает пропы в верстку есть нюанс. в 16 реакте data-tid у Button и Radio ставится не у рутового тэга компонента а у вложенного, потмоу что в него спредятся все пропы компонента вместе с data-tid. на 15 реакте все было нормально.

возможно стоит рассмотреть альтернативу в виде https://github.com/DevExpress/testcafe-react-selectors/ - @tihonove раобтал с подобным

**Comment by zhzz** [comment]
В отдельный пакет вынесли: [react-props2attrs](https://github.com/skbkontur/react-props2attrs). Проблема с Button и Radio была решена в #1872. Закрываю.
