### ISSUE TITLE
[Tooltip] если в popup передается content=null то пишет ошибку в консоль

### ISSUE THREAD

**Issue by Sergey-Ubogov** [skbkontur/retail-ui#1292]
retail-ui@0.44.2

![image](https://user-images.githubusercontent.com/19286511/55003319-02dd8100-4ffa-11e9-80c3-2dd1158b398f.png)

тут написано что content может быть null
https://github.com/skbkontur/retail-ui/blob/d545f4cffa4092eb7850b2c85d0a2f5ca08eab98/packages/retail-ui/components/Tooltip/Tooltip.tsx#L222-L226
затем этот content передается в Popup, а в нем написано что children не может быть null
https://github.com/skbkontur/retail-ui/blob/d545f4cffa4092eb7850b2c85d0a2f5ca08eab98/packages/retail-ui/components/Popup/Popup.tsx#L111

если убрать .isRequired то ошибки нету. ошибки так же не было в версии 0.44.0

**Comment by wKich** [comment]
Есть такая проблема https://github.com/facebook/react/issues/3163. Суть в том что тип `React.ReactNode` может быть `null`, в то время как рантайм валидация `PropTypes.node` не предполагает, что нода может быть `null`
