### ISSUE TITLE
[Tooltip] Не открывается при смене trigger с 'closed' на 'click'

### ISSUE THREAD

**Issue by Lelchik** [skbkontur/retail-ui#1297]
retail-ui@0.44.2
Браузер любой

После обновления библиотеки контролов с версии 0.29.0 перестал открываться тултип при смене trigger с 'closed' на 'click'

Воспроизводится на витрине компонентов

```
const initialState = {
  disabled: true,
};

<div style={{ fontFamily: 'Segoe UI' }}>
   <Tooltip render={() => <div>213</div>} trigger={state.disabled ? 'closed' : 'click'}>
      <Button disabled={state.disabled}>Open tooltip</Button>
   </Tooltip>
   <div>
      <Checkbox checked={state.disabled} onChange={(e, v) => setState({disabled: v})}>Disabled</Checkbox>
   </div>
</div>;
```

**Comment by zhzz** [comment]
В пылу оптимизации подписок на события в попапе не учли, что сами коллбэки тоже могут обновляться (появляться/исчезать) по ходу выполнения:

https://github.com/skbkontur/retail-ui/blob/eb3048173333e1c54d81cefed4841da823576f44/packages/retail-ui/components/Popup/Popup.tsx#L277
