### ISSUE TITLE
[Link] Сделать возможность создавать серую ссылку, которая при наведении становится красной

### ISSUE THREAD

**Issue by sergey-soloviev** [skbkontur/retail-ui#130]
Это нужно для критичных действий, которые не хочется делать по умолчанию красными.

![screen shot 2017-03-14 at 16 16 35](https://cloud.githubusercontent.com/assets/11822529/23898118/a2ff45e6-08d1-11e7-8ff6-e30c35f52f11.png)

**Comment by wKich** [comment]
Можно решить кастомным компонентом, внутри которого использовать обычную ссылку
```jsx
<Link use={this.state.hovered ? 'danger' : 'grayed'}>
  Удалить
</Link>
```
