### ISSUE TITLE
[Button] Проверить и поправить стили

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#1309]
1. Остаточный бордер у стрелок при флаге `borderless`:
<img width="169" alt="Screen Shot 2019-03-26 at 18 49 37" src="https://user-images.githubusercontent.com/4607770/55002161-f0624800-4ff7-11e9-97de-0a62ded8283b.png">

2. Добавить фон у button use="link" warning такой-же как у error, только цветом #FFF0BC 

3. ~~Стрелка перекрывает содержимое кнопки при width: 0~~ fixed
(background: #fff, а не transparent)
<img width="80" alt="Screen Shot 2019-03-26 at 18 54 53" src="https://user-images.githubusercontent.com/4607770/55002619-c1000b00-4ff8-11e9-80e2-7da1934bb779.png">

4. ~~Ссылка нулевой длинны занимает две строки~~ fixed
<img width="396" alt="Screen Shot 2019-03-26 at 18 56 05" src="https://user-images.githubusercontent.com/4607770/55002704-e5f47e00-4ff8-11e9-991a-444485219d85.png">

5. ~~Обводкам ворнинга и ошибки для кнопок добавить внутреннюю белую однопиксельную обводку, как у фокуса~~ fixed

6. ~~Добавить состояние checked disabled фон #A0A0A0, обводка 0,37 alpha от #000., текст 0,7 alpha от #FFF.~~ fixed

**Comment by lenoraart** [comment]
Часть кнопки-стрелки перекрыла текст при width: 0
(background: #fff, а не transparent)
![image](https://user-images.githubusercontent.com/37067213/55396315-0c686b00-555d-11e9-8dbb-4865ecdb1eed.png)

**Comment by lenoraart** [comment]
В IE 11 белые полосы на arrow button в состоянии checked и при размерах medium и large.
![image](https://user-images.githubusercontent.com/37067213/55385257-20ed3900-5546-11e9-8842-48f67ecd6a7f.png)

**Comment by lenoraart** [comment]
borderless кнопки с бордером
![image](https://user-images.githubusercontent.com/37067213/55399546-d3cc8f80-5564-11e9-91b9-5fdca34b5e1c.png)
![image](https://user-images.githubusercontent.com/37067213/55400671-f1e7bf00-5567-11e9-91ff-4c9f944f486d.png)

**Comment by lenoraart** [comment]
Большой горизонтальный паддинг у кнопки narrow medium
![image](https://user-images.githubusercontent.com/37067213/55401604-b5699280-556a-11e9-8d7b-3048a219d23f.png)

**Comment by lenoraart** [comment]
В IE 11 и Edge ширина borderless button размеров medium и large не соответствует размеру текста. При нажатии кнопка увеличивается вправо.

![image](https://user-images.githubusercontent.com/37067213/55457051-2d36cc00-5602-11e9-9ad7-329d2b3cf7a8.png)
![ezgif-2-3194a7a1efaf](https://user-images.githubusercontent.com/37067213/55457962-fe6e2500-5604-11e9-95be-9dc0b7384b63.gif)

**Comment by lenoraart** [comment]
Сужается синяя обводка у borderless visuallyFocused кнопки при наведении на нее мышкой
![image](https://user-images.githubusercontent.com/37067213/55458999-de8c3080-5607-11e9-8e50-01e1f5e91a8e.png)

**Comment by lenoraart** [comment]
В IE 11 и Edge синие границы кнопок medium и large толше сверху и справа,
![image](https://user-images.githubusercontent.com/37067213/55459610-6e7eaa00-5609-11e9-9064-2dc262a241c0.png)

у small - снизу и слева,
![image](https://user-images.githubusercontent.com/37067213/55459742-aa197400-5609-11e9-82f9-cbc3e52ac568.png)

**Comment by lenoraart** [comment]
Неровная стрелочка у кнопки при табировании 
![image](https://user-images.githubusercontent.com/37067213/55454737-5fdcc680-55fa-11e9-868a-1421df64370f.png)

И без табирования, когда нет заливки
![image](https://user-images.githubusercontent.com/37067213/55456480-93baea80-5600-11e9-87be-1cc07f88d104.png)

В состоянии checked
![image](https://user-images.githubusercontent.com/37067213/55458897-a8e74780-5607-11e9-905d-ef191b4d7860.png)

**Comment by lenoraart** [comment]
Добавить белую внутреннюю тень в ворнинги и ошибки
![image](https://user-images.githubusercontent.com/37067213/55623681-328c4600-57bd-11e9-8611-36f339f407c4.png)

**Comment by lenoraart** [comment]
В IE 11 не работает выравнивание start и end.
![image](https://user-images.githubusercontent.com/37067213/56290864-85f78000-613d-11e9-9c21-f045b844ad47.png)

**Comment by mshatikhin** [comment]
![image](https://user-images.githubusercontent.com/1788385/68008667-7be43b80-fca1-11e9-829e-bcea202275f3.png)

@skbkontur/react-ui - 1.6.1

flat тема, стрелка назад - кривенькая( верхний бордер переходит в стрелку неровно.

**Comment by dzekh** [comment]
Кажется что тут большинство проблем полечилось уже, вот бы проверить их все

**Comment by zhzz** [comment]
Обновил посты. Еще осталось 4 пункта. В первом сообщении, про borderless, и стрелка с обводкой.
