### ISSUE TITLE
[react-ui-validations] Добавить в доку пример использования валидаций с кастомными компонентами

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1313]
Валидации используют публичные пропы и методы компонентов. Чтобы кастомный компонент работал с валидациями правильно нужно чтобы он понимал пропы `error`, `warning`, `onFocus`, `onBlur`, `onMouseEnter`, `onMouseLeave`, `onInput`, `onChange`. И имел публичный метод `focus`

**Comment by rustho** [comment]
#1753  дубль
