### ISSUE TITLE
[Tooltip] позиционирование

### ISSUE THREAD

**Issue by kokovin** [skbkontur/retail-ui#132]
При изменении ширины контента тултип не позиционируется. Из за этого возможна ситуация, когда клюв оторван от контента:
![tooltip](https://cloud.githubusercontent.com/assets/7185310/23903290/d7f412b8-08e5-11e7-8f67-c045880e6cb1.png)

**Comment by nanot1m** [comment]
У нас нет возможности перерисовывать тултип при изменении ширины контента, так как тултип ничего не знает об изменениях дочерних элементов.

Можно зафорсить тултип пересчитать позицию вызвав `LayoutEvents.emit()`
```js
import LayoutEvents from "@skbkontur/react-ui/lib/LayoutEvents";
LayoutEvents.emit();
```

**Comment by wKich** [comment]
А если MutationObserver?

**Comment by nanot1m** [comment]
@wKich у него ограниченная поддержка браузерами и нужно изучать как он влияет на производительность. Когда сможем добиться примерно одинакового поведения во всех поддерживаемых браузеров, тогда сможем начать его использование

**Comment by wKich** [comment]
То есть уже изучался вопрос его использования в разных браузерах?

**Comment by nanot1m** [comment]
@wKich, написал же, что нужно изучать (:

Если есть такая возможность, то буду рад помощи

**Comment by nanot1m** [comment]
Было бы круто получить, что то такое:
```jsx
<SizeChangeObserver onChange={this._reflow}>
  {children}
</SizeChangeObserver>
```
