### ISSUE TITLE
[retail-ui] Не закрываются выпадашки по событию `popstate`

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1321]
Только в компоненте `Select` есть подписка на `popstate` и закрытие выпадашки при переходе по истории. В остальных компонентах при переходе по истории, если не происходит полной перерисовки приложения выпадашки не закрываются.

Сценарий для воспроизведения
Для Windows:
- В консоли выполнить `history.pushState({}, '')`
- Открыть выпадашку
- Нажать кнопку "Назад"

Для Mac OS
- В консоли выполнить `history.pushState({}, '')`
- Открыть выпадашку
- Перейти назад с помощью хоткея `Cmd+Left`

**Comment by dzekh** [comment]
@wKich, а почему у этой задачки лэйбл wait design? Какое тут дизайнерское решение нужно? Кажется очевидно, что выпадахи всегда должны закрываться при переходах по истории, нет?

**Comment by wKich** [comment]
Ты же сам добавил 19-го мая, судя по истории :)

**Comment by dzekh** [comment]
А я чот не помню почему. Наверно, чтоб спросить у тебя просто подробности по задачке. Ты считаешь что они должны закрываться? Тогда их открытие закрытие будут писаться в историю? И почему ты сам ставил  wait design 4 апреля?

**Comment by wKich** [comment]
4-го апреля прошлого года, я уж забыл что там было, вполне возможно случайно проставил, потому что сразу же удалил. 

Сложно сказать когда они должны закрываться, в большинстве случае да, должны. Но есть нюансы например, если выпадахе тултипу или хинту явно задали состояние открыто или же это валидация сработала и в инпуте стоит фокус. То при переходе назад тултип закроется, хотя фокус в поле остался.

В историю открытие/закрытие попадать не будет.

**Comment by dzekh** [comment]
Да, примерно такого правила будет достаточно, думаю: 
При переходам по истории выпадающие не модальные меню и тултипы открытые пользователем должны закрываться, но не создавать при этом в истории отдельных шагов. Если они были открыты автоматически я думаю что они так же откроются при переходе по истории. Если нет — то наверное об этом пусть уже заботится приложение.

**Comment by wKich** [comment]
Открытие/закрытие выпадах не влияет на историю, никак, никакие дополнительные шаги самими выпадахами при этом не создаются.

Автоматически открытые выпадахи не откроются при переходе по истории и приложение не может на это повлиять, потому что логика открытия, например для валидации, находится внутри `ValidationWrapper`. Если выпадаха решит закрыться она закроется, а приложение не может повлиять на неожиданно закрывшийся тултип валидации.
