### ISSUE TITLE
[ScrollContainer] [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1326]
Версия: 0.45.0
Браузер: chrome

Скроллить вверх, когда список максимально вверху / скроллить вниз, когда список максимально внизу
![image](https://user-images.githubusercontent.com/9654622/55550926-f55b8180-56f2-11e9-8a62-b4783b418ebf.png)

**Comment by wKich** [comment]
Похоже прилетело с новой версией хрома. Воспроизводится даже на старых версиях библиотеки

**Comment by wKich** [comment]
Вот тут выкатилось https://www.chromestatus.com/features/6662647093133312

И react не поддерживает пока листнеров с `passive: true` https://github.com/facebook/react/issues/6436

Тут вот ещё обсуждают https://github.com/facebook/react/issues/14856
