### ISSUE TITLE
[TokenInput] Поддержать API и поведение ComboBox

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1335]
По гайдам `TokenInput` https://guides.kontur.ru/components/tokens/#01 должен вести себя и иметь схожий функционал что и `ComboBox`. В данный момент в (версии 0.46) в API `TokenInput` отсутствуют пропы `onInputChange` и `onUnexpectedInput`, которые не позволяют реализовать сценарии:
> 1) пользователь что-то ввел в TokenInput, ничеге не выбрал, снял фокус. Хотим показать ошибку
> 2) Далее пользователь снова установил фокус в поле с ошибкой и все удалил. Хотим очистить ошибку

**Comment by rustho** [comment]
#1521

**Comment by zhzz** [comment]
Снова возник подобный сценарий. Предлагаю в рамках этого issue добавить проп `onUnexpectedInput`. `onInputChange` (точнее `onInputValueChange`) уже добавили ранее.

Полный перевод TokenInput на CustomComboBox (из 1521) сделаем позже.

**Comment by dzekh** [comment]
Заметил что уже добавлены `onInputValueChange` и `onUnexpectedInput` в [#1980](https://github.com/skbkontur/retail-ui/pull/1980). В контексте этого еще актуальна задача? Что подразумевалось под «Поддержать API и поведение ComboBox» кроме этих пропов?

**Comment by zhzz** [comment]
Думаю этот можно закрыть, реализовано.
