### ISSUE TITLE
[DatePicker] Не работает переход на следующую часть даты по пробелу

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1338]
Версия: 0.46.0
Браузер: хром

После ввода одной цифры можно нажать пробел — фокус должен перейти на следующую часть даты.

https://guides.kontur.ru/components/calendar/#20

**Comment by wKich** [comment]
Кажется в гайде не хватает слеша и тире. Они тоже могут использоваться в качестве разделителя и по ним должен происходить переход

**Comment by nextgennexia** [comment]
Я думаю можно закрывать после выпуска 0.52.0
