### ISSUE TITLE
[Input] Увеличить область клика под правую иконку

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1339]
Версия: 0.46.0

По гайдам https://guides.kontur.ru/components/input/#21 область клика должна равняться полю ввода по высоте, но сейчас она выглядит как на скрине ниже

![image](https://user-images.githubusercontent.com/9654622/55852276-b3f52700-5b75-11e9-946a-8b08e3bd2c54.png)
```javascript
<Input
  rightIcon={
    <div
      onClick={props.onResetQuery}
      onMouseEnter={props.onMouseEnter}
      onMouseLeave={props.onMouseLeave}
    >
      <ClearIcon color={props.isHovered ? "#808080" : "#a0a0a0"} size={14} />
    </div>
  }
>
```

**Comment by dzekh** [comment]
Описал [области кликов полей тут](https://www.figma.com/file/HXJFs6glLNxfoTburQbgP3/React-UI-Theming?node-id=163%3A545)
Вся область поля где стоит иконка вплоть до текста должна быть её кликабельной областью:

![image](https://user-images.githubusercontent.com/26383080/84359389-fedb5600-abe1-11ea-9709-90f8268ff86b.png)
