### ISSUE TITLE
[Spinner] React бросает warning из-за не валидных пропсов

### ISSUE THREAD

**Issue by vansosnin** [skbkontur/retail-ui#134]
Ошибки появляются не всегда, но как именно воспроизвести - не понятно. Кажется, воспроизводится только для `Type = mini`.

![default](https://cloud.githubusercontent.com/assets/8207551/23936062/aaacb35a-0971-11e7-8bb0-94a194f828cc.PNG)
![2](https://cloud.githubusercontent.com/assets/8207551/23936063/ac3eb52e-0971-11e7-9549-1026fc526a1d.PNG)

**Comment by mortifer** [comment]
всегда они появляются в дев версии. в любом размере спиннера или лоадера.
причем все советы со стековерфлоу как это зачинить у меня на заехали :(

**Comment by vansosnin** [comment]
Мы у себя в node_modules подхачили, нам помогло просто поменять [stroke-dashoffset](https://github.com/skbkontur/retail-ui/blob/83350ffedc7f51188a3356a3a59105cd358316ed/components/Spinner/Spinner.js#L84) на strokeDashoffset. Ну и со [stroke-miterlimit](https://github.com/skbkontur/retail-ui/blob/83350ffedc7f51188a3356a3a59105cd358316ed/components/Spinner/Spinner.js#L83) аналогично.

**Comment by nanot1m** [comment]
Проблема возникла в 15 версии реакта, т.к. он научился понимать все svg атрибуты. 14 реакт просто игнорил непонятные ему атрибуты.
