### ISSUE TITLE
[DatePicker] Поправить стили

### ISSUE THREAD

**Issue by lenoraart** [skbkontur/retail-ui#1342]
1. ~~В **DateInput** нельзя мышкой сразу выбрать ту часть даты, которая нужна.~~
Например, мне нужно только год поменять, но по клику всегда выделяется день.
---
2. ~~На 1 шаг отстает отображение даты в *DateInput* от выбранной в календаре при навигации стрелками.~~ 
<details>
 <summary><b>STR</b></summary>
<ol>
   <li>Открыть стори <b>DatePickerWithError</b> (<code style="background: gray;">value: null</code>);</li>
   <li>Кликнуть в <em>DateInput</em>;</li>
   <li>Перейти на число стрелкой <em>вправо</em>;</li>
   <li>Выбрать число стрелками <em>вверх-вниз</em>.</li>
</ol>
<b>Результат:</b> отображение даты в инпуте отстает на 1 шаг.<br/>
<b>Ожидание:</b> отображание даты в инпуте соответвует выбранной в календаре.<br/>
<image src="https://user-images.githubusercontent.com/37067213/55859578-cb3f0f00-5b8b-11e9-8d2e-39801a372f7b.png" alt="" width="200px"><br/>
<b>Дополнительно:</b> также "отстает" номер месяца.
</details>
 
---
3. ~~Добавить в дата инпут предустановленное значение, чтобы пользователю было понятно, в каком формате вводить дату.~~ 
> 3 — не нужно, если поле не заполнено пусть будет пустое, маска появляется только при фокусе - этого достаточно.

---
4. Добавить установку даты с помощью ```Enter```. Если пользователь вводит данные с клавиатуры, то ему будет удобнее нажать enter для установки даты, а не кликать мышкой по календарю.
---
5. ~~Добавить возможность удалять дату. Сейчас если выделить дату в инпуте и нажать *delete*/*backspace* и кликнуть вне компонента, установленная дата сохраняется.~~
---
6.  ~~Меняется значение *Today* после клика.~~
<details>
<summary><b>STR</b></summary>
<ol>
   <li>Открыть стори <b>DatePickerWithError</b> (<code style="background: gray;">value: null</code>);</li>
   <li>Кликнуть в инпут;</li>
   <li>Кликнуть по <em>Today dd.mm.yyyy</em>;</li>
   <li>Повторить предыдущий шаг.</li>
</ol>
   <b>Результат:</b> значение <em>Today</em> увеличивается (было: 10.04.2019, стало: 10.05.2019).<br/>
<b>Ожидание:</b> значение <em>Today</em> не меняется.<br/>
<b>Дополнительно:</b> при большом количестве кликов по <em>Today dd.mm.yyyy</em> ломается верстка.
<image src="https://user-images.githubusercontent.com/37067213/55859599-d4c87700-5b8b-11e9-8c72-5522a2832bfd.png" alt="" width="200px"><br/>
</details>
 
---
7. ~~Добавить автоматический переход между частями даты при заполнении пустого инпута (сейчас такой переход работает только если в инпуте уже установлено значение).~~
---
8. ~~При вводе даты с клавиатуры на календаре не отображается указанный год.~~
<image src="https://user-images.githubusercontent.com/37067213/55859709-0b05f680-5b8c-11e9-837e-49baa453ebf3.png" alt="" width="200px"><br/>
 
---
9. ~~Добавить возможность вставки даты с помощью ```ctrl+v``` в пустой инпут.~~
---
10. ~~Несвоевременная валидация неверной даты.~~
<details>
<summary><b>STR</b></summary>
<ol>
   <li>Открыть стори <b>DatePickerWithError</b> (<code style="background: gray;">value: null</code>);</li>
   <li>Кликнуть в инпут;</li>
   <li>Выбрать в календаре валидную дату;</li>
   <li>Кликнуть по <em>"Set '99.99.9999'"</em>;</li>
   <li>С помощью календаря установить валидную дату.</li>
</ol>
<b>Результат:</b> тултип "Такой даты не существует".<br/>
<image src="https://user-images.githubusercontent.com/37067213/55859764-296bf200-5b8c-11e9-8b18-81f4bc725587.png" alt="" width="200px"><br/>
<b>Ожидание:</b> тултип появляется после клика в инпут со значением <em>'99.99.9999'</em> и затем вне инпута.
</details>
 
> все варианты «показать валидацию» (что означает покрасить поле красной рамкой и выдать сообщение об ошибке), нужно отдать на откуп продуктам.
---
11. ~~Нет тултипа с ошибкой при вводе даты, выходящей за границы установленного интервала.~~

<details>
<summary><b>STR</b></summary>
<ol>
   <li>Установить <code style="background: gray;">minDate="02.07.2017"</code>;</li>
   <li>Открыть стори <b>DatePickerWithError</b> (<code style="background: gray;">value: null</code>);</li>
  <li>Кликнуть в инпут;</li>
  <li>Ввести с клавиатуры дату 02.07.2016;</li>
  <li>Кликнуть за пределами дейтпикера.</li>
</ol>
<b>Результат:</b> инпут очистился, дата не установлена.<br/>
<b>Ожидание:</b> тултип с ошибкой "Дата за пределами интервала".
</details>
  
> все варианты «показать валидацию» (что означает покрасить поле красной рамкой и выдать сообщение об ошибке), нужно отдать на откуп продуктам.
---
12. ~~При вводе даты в пустой инпут календарь не отображает изменения.~~

**Comment by lenoraart** [comment]
13. Если установлен ```order: DateCustomOrder.YMD``` при вводе даты с клавиатуры не устанавливается год.

**STR**
* Установить ```locale={{ DatePicker: { order: DateCustomOrder.YMD } }}```;
* Открыть стори **DatePickerWithError**;
* Кликнуть в инпут;
* Ввести с клавиатуры дату 2016.02.25.
**Результат:** год не ввелся. Тултип с ошибкой "Такой даты не существует".
**Ожидание:** дата введена полностью.
**Дополнительно:** воспроизводится при пустом и заполненном инпуте.

**Comment by lenoraart** [comment]
14. В пустом дейт инпуте нет валидации по количеству дней в месяце.

**STR**
* Открыть стори **DatePickerWithError** (```value: null```);
* Кликнуть в инпут;
* Ввести с клавиатуры дату 31.02.2019;
* Кликнуть за пределами дейтпикера.
**Результат:** установлена невалидная дата.
**Ожидание:** тултип с ошибкой "Такой даты не существует" | автоматическое исправление даты в инпуте.
![image](https://user-images.githubusercontent.com/37067213/55863913-e5c9b600-5b94-11e9-8fa7-84a81d28b839.png)

**Comment by lenoraart** [comment]
15. При вводе в заполненный инпут в календаре подсвечивается неверная дата.

**STR**
* Открыть стори **DatePickerWithError**;
* Кликнуть в инпут;
* Ввести с клавиатуры дату 12.13.2019.
**Результат:** на календаре подсветилось число *1*.
![image](https://user-images.githubusercontent.com/37067213/55866297-815d2580-5b99-11e9-9581-5253ecf1a422.png)
**Ожидание:** на каледнаре подсвятилось число *13*.

**Comment by lenoraart** [comment]
16. Не исчезает тултип с ошибкой после установки валидной даты.

**STR**
* Открыть стори **DatePickerWithError**;
* Кликнуть по *"Set '99.99.9999'"*;
* Кликнуть в инпут -> кликнуть за переделами дейт пикера;
* С помощью календаря установить валидную дату.
**Результат:** тултип "Такой даты не существует".
![image](https://user-images.githubusercontent.com/37067213/55866479-e3b62600-5b99-11e9-8d5a-2d1db8d6ddca.png)
**Ожидание:** тултип с ошибкой исчез.

**Comment by dzekh** [comment]
Хочу уточнить по пунктам 3 и 4
3. Добавить в дата инпут предустановленное значение, чтобы пользователю было понятно, в каком формате вводить дату.
4. Добавить установку даты с помощью enter. Если пользователь вводит данные с клавиатуры, то ему будет удобнее нажать enter для установки даты, а не кликать мышкой по календарю.

3 — не нужно, если поле не заполнено пусть будет пустое, маска появляется только при фокусе - этого достаточно. 

4 — хочется уточнить, что значит «установка даты»? И куда потом перейдет фокус? Пока отдельного гайда по фокусу и работе с клавиатурой нет. В гайде по полю фокус должен перейти на следующее поле, но не везде это реализовано. Если можно — по Enter в поле, если оно заполнено до конца — переводить фокус на следующее и устанавливать дату

**Comment by dzekh** [comment]
Отдельно по валидации. [Обсудили с дизайнерами](https://staff.skbkontur.ru/group/5361?action=discussions&id=45362865655e42eaa054d3ec8d4d9b4d), решили что:
17. Даем вводить с клавиатуры любое значение (день 1-31, месяц 1-12, год вообще любой)
18. По мере ввода никак не показываем не валидность даты, только после окончания ввода - когда пользователь убрал фокус с поля или нажал Enter. 
19. При вводе стрелками ограничиваем ввод даты и не даем переключить дату вне диапазона. [Как описано в гайде](https://guides.kontur.ru/components/calendar/#25).
20. Не меняем никак веденную с клавиатуры невалидную дату. Не сбрасываем ни год, ни месяц ни число, просто показываем сообщение об ошибке, когда пользователь убрал фокус. 
21. Сообщения об ошибке:
Если дата не по фомату сообщение об ошибке как сейчас: «Такой даты не существует»
Если дата вне диапазона — [сообщение как в гайде](https://guides.kontur.ru/components/calendar/#29)

**Comment by lenoraart** [comment]
> 4 — хочется уточнить, что значит «установка даты»? И куда потом перейдет фокус? Пока отдельного гайда по фокусу и работе с клавиатурой нет. В гайде по полю фокус должен перейти на следующее поле, но не везде это реализовано. Если можно — по Enter в поле, если оно заполнено до конца — переводить фокус на следующее и устанавливать дату

Имеется в виду подтверждение выбора даты пользователем (как в сценарии с мышкой клик по дате в календаре).

**Comment by lenoraart** [comment]
22. Если месяц "занимает" 6 недель название следующего месяца "прилипает" к предыдущему блоку
![image](https://user-images.githubusercontent.com/37067213/56024806-3888a680-5d2a-11e9-9907-67835fb21342.png)

**Comment by lenoraart** [comment]
При удалении даты с помощью Del части даты сдвигаются, при этом последние два числа игнорируются.
![ezgif-4-35bd909ab43f](https://user-images.githubusercontent.com/37067213/56031267-61b03380-5d38-11e9-9958-5846f68588fd.gif)

**Comment by lenoraart** [comment]
24. Не блокируется скролл основной страницы при скролле календаря

**Comment by lenoraart** [comment]
[Чек-лист проверки DatePicker ](https://docs.google.com/spreadsheets/d/1fU8653d-jbggCzXQO_SuB_arP0NxXHSnfM6a2w--Hsg/edit?usp=sharing)(приветствуется дополнение и корректировка)

**Comment by lenoraart** [comment]
25. Текст не соответствует ошибке.

**STR**
* Установить ```minDate="02.07.2018"```;
* Открыть стори **DatePickerWithError** (```value: null```);
* Кликнуть по *Today dd.mm.yyyy*;
* Кликнуть за пределами дейтпикера (если не появился тултип, то обновить страницу).
**Результат:** тултип с ошибкой "Такой даты не существует".
**Ожидание:** тултип с ошибкой "Укажите дату в промежутке ... в формате ...".

**Comment by lenoraart** [comment]
26. Нельзя перемещаться по частям даты с помощью запятой

**STR**
* Добавить в ```render()``` к ```<LocaleProvider>``` атрибуты ```langCode={LangCodes.en_EN}
            locale={{ DatePicker: { 
order: DateCustomOrder.DMY, 
separator: DateCustomSeparator.Dot, 
firstDayWeek: DateCustomFirstDayWeek.Saturday } }}```
* Открыть стори **DatePickerWithError**;
* Кликнуть в инпут;
* Ввести с клавиатуры "*2*";
* Нажать "*,*".
**Результат:** выделение не переходит на следующую часть даты.
**Ожидание:** после ввода одной цифры можно перейти на следующую часть даты с помощью запятой.

**Comment by lenoraart** [comment]
27. При изменении года стрелками ```↑``` ```↓``` выставляется значение "*0000*"

**STR**
* Добавить в ```render()``` к ```<LocaleProvider>``` атрибуты ```langCode={LangCodes.en_EN} locale={{ DatePicker: { order: DateCustomOrder.DMY, separator: DateCustomSeparator.Dot, firstDayWeek: DateCustomFirstDayWeek.Saturday } }}```;
* Открыть стори **DatePickerWithError**;
* Кликнуть в инпут;
* Выбрать в календаре дату;
* Кликнуть в инпут;
* Перейти клавишей ```→``` на год;
* Нажать клавишу ```↑``` или ```↓```.
**Результат:** год сменился на "*0000*".
**Ожидание:** год увеличивается/уменьшается на 1.

**Comment by lenoraart** [comment]
28. Если вставить дату из буфера обмена, при последующем выборе даты на календаре значение месяца = "*00*"

**STR**
* Добавить в ```render()``` к ```<LocaleProvider>``` атрибуты ```langCode={LangCodes.en_EN} locale={{ DatePicker: { order: DateCustomOrder.DMY, separator: DateCustomSeparator.Dot, firstDayWeek: DateCustomFirstDayWeek.Saturday } }}```;
* Открыть стори *DatePickerWithError*;
* Вставить в поле "*30/01/2019*";
* В календаре выбрать дату "*15/01/2019*".
* Убрать фокус с календаря.
**Результат:** месяц равен "*00*".
![image](https://user-images.githubusercontent.com/37067213/56116852-46376980-5f80-11e9-93ec-6a7801359f0f.png)
**Ожидание:** в поле отобразилась выбранная дата.

**Comment by lenoraart** [comment]
Невозможно вставить дату в формате "*30,01,2019*"

**Comment by lenoraart** [comment]
```Del``` не удаляет слева направо.
(Пользователи, работающие за компьютером (особенно в MS Office Word) привыкли, что ```Backspace``` удаляет символы справа налево, а ```Del``` слева направо).

**Comment by lenoraart** [comment]
31. Меняется неверное число
> 20. Не меняем никак веденную с клавиатуры невалидную дату. Не сбрасываем ни год, ни месяц ни число, просто показываем сообщение об ошибке, когда пользователь убрал фокус.

**Comment by lenoraart** [comment]
31. Дописать в текст ошибки при вводе даты в неверном формате  " укажите дату в формате..."

**Comment by lenoraart** [comment]
32. Праздничные дни не подсвечиваются красным
![image](https://user-images.githubusercontent.com/37067213/56121417-86e7b080-5f89-11e9-81f1-44bfe78c359f.png)

**Comment by lenoraart** [comment]
32. Добавить стори с пропсом ```isHoliday```

**Comment by lenoraart** [comment]
33. Значение из списка не подставляется в поле ввода

**STR**
* Открыть стори **DatePickerWithError**;
* Кликнуть в инпут;
* Кликнуть по месяцу или году в заголовке календаря;
* Выбрать год/месяц из списка.
**Результат:** выбранное значение не подставилось в поле ввода.
**Ожидание:** значение подставляется в поле ввода, календарь прокручивается к соответствующей дате.

**Comment by dzekh** [comment]
в 25
>   **Дополнительно:** при незаполненном поле такая же ошибка "Такой даты не существует", а должна быть "Заполните поле".

Так, уточнение — показ шибки на незаполненность должен быть в руках продукта, не должен быть зашит в компонент, [по гайдам мы не ругаемся](https://guides.kontur.ru/principles/validation/#08) на незаполненность полей при потере фокуса.

**Comment by dzekh** [comment]
Мне кажется что вообще все варианты «показать валидацию» (что означает покрасить поле красной рамкой и выдать сообщение об ошибке), нужно отдать на откуп продуктам. Нам возможно достаточно уметь через апи сообщать об обнаруженных ошибках. А как и в какой момент показывать сообщение об ошибке — об этом пусть думают продукты, или библиотека валидаций. 

Или у нас все так и устроено? Что думаете по этому поводу?

**Comment by lossir** [comment]
> Или у нас все так и устроено? Что думаете по этому поводу?

Да, сейчас именно так и реализовано.

**Comment by lenoraart** [comment]
Если задан диапазон выбора дат, при скроле вниз у границы диапазона "выталкивается" вверх и исчезает заголовок календаря
![image](https://user-images.githubusercontent.com/37067213/56209897-19fa1680-606e-11e9-9fc9-ae8fde9f9334.png)

**Comment by lenoraart** [comment]
35. Не добавляются текущий месяц и год при вводе числа из одной или двух цифр 

**STR**
* Открыть стори **DatePickerWithError**;
* При необходимости очистить инпут;
* Кликнуть в инпут;
* Ввести "*1*" или "*21*";
* Убрать фокус с дэйт пикера.
**Результат:** месяц и год остались пустыми.
**Ожидание:** в соответствующие части даты вставились текущий месяц и год.
![image](https://user-images.githubusercontent.com/37067213/56212599-c8548a80-6073-11e9-8f0b-654f739252df.png)

**Comment by lenoraart** [comment]
Добавить стори с разделителями

**Comment by lenoraart** [comment]
38. Не двигается дата внутри дэйт инпута с маленькой шириной при вводе числа или переходе стрелками по частям даты

**Comment by lenoraart** [comment]
В FF год "прилипает" к стрелкам справа
![image](https://user-images.githubusercontent.com/37067213/56497768-5dde9700-6518-11e9-807e-6d7b73ddea22.png)

**Comment by lenoraart** [comment]
Порядок частей даты на кнопке "Сегодня" соответствует порядку частей даты в поле ввода
<details>
<summary><b>STR</b></summary>
<ol>
<li>К <code style="background: gray;">LocaleProvider</code> добавить атрибут <code style="background: gray;">locale={{ DatePicker: { order: DateCustomOrder.MDY } }}</code>;</li>
<li>К <code style="background: gray;">DatePicker</code> добавить пропс <code style="background: gray;">enableTodayLink</code>;</li>
<li>Открыть стори <b>DatePickerWithError</b>;</li>
<li>Открыть календарь.</li>
</ol>
<b>Результат:</b> порядок частей даты на кнопке "Сегодня" - DMY.<br/>
<image src="https://user-images.githubusercontent.com/37067213/56499470-f88ea400-651f-11e9-97ce-b8b2937c31c3.png" alt="" width=200px>

<b>Ожидание:</b> порядок частей даты на кнопке "Сегодня" - MDY.<br/>
</details>

**Comment by lenoraart** [comment]
Ошибка в консоли при перелистывании месяцев стрелками
![image](https://user-images.githubusercontent.com/37067213/56500138-18739700-6523-11e9-9b79-e331ed56392d.png)

**Comment by lenoraart** [comment]
Зависает календарь при перелистывании даты зажатием стрелки

**Comment by lenoraart** [comment]
Если сначала выбрать год из списка, то список с месяцами открывается только по второму клику
<details>
<summary><b>STR</b></summary>
<ol>
<li>Открыть стори <b>DatePickerWithError</b>;</li>
<li>Открыть календарь;</li>
<li>Нажать на год в заголовке календаря;</li>
<li>Выбрать год из списка;</li>
<li>Кликнуть по месяцу в заголовке.</li>
</ol>
<b>Результат:</b> ничего не происходит.<br/>
<b>Ожидание:</b> открылся список месяцев.
</details>

**Comment by lenoraart** [comment]
Из буфера обмена можно вставить дату с отличным от поля ввода ордером
<details>
<summary><b>STR</b></summary>
<ol>
<li>К <code style="background: gray;">LocaleProvider</code> добавить атрибут <code style="background: gray;">locale={{ DatePicker: { order: DateCustomOrder.MDY } }}</code>;</li>
<li> Открыть стори <b>DatePickerWithError</b>;</li>
<li>Выделить значение в инпуте;</li>
<li>Вставить из буфера обмена дату <em>30/04/2019</em>.</li>
</ol>
<b>Результат:</b> вставилась дата с отличным от инпута ордером.<br/>
<b>Ожидание:</b>дата с отличным от инпута ордером не вставилась. <br/>
 
> Даем вводить с клавиатуры любое значение (день 1-31, месяц 1-12, год вообще любой)
</details>

**Comment by dzekh** [comment]
не получилось ввести дату 30.03.2009 если указана 28.02.2009 после ввода 30 курсор переходит на месяц и веденный день сбрасывается до 28 =(

**Comment by dzekh** [comment]
Это нормально что в стори formatting 2 дата, которая стоит по умолчанию, невалидная, а инпут переключает, и при этом не замечает совсем этого?

**Comment by dzekh** [comment]
В каких-то случаяй бэкспейсом стирается дата по одному символу, в каких-то стирается блок целиком. Пока я не понял логику. =)

**Comment by lenoraart** [comment]
> не получилось ввести дату 30.03.2009 если указана 28.02.2009 после ввода 30 курсор переходит на месяц и веденный день сбрасывается до 28 =(
> Так же с другими месяцами — 31.05.2009 если указано 30.04.2009
> При чем если поле изначально пустое сброс не срабатывает. Я могу ввести 31.04.2009

 Все правильно, при вводе с клавиатуры не дает ввести числа вне диапазона, а вот если вставить с помощью ```Ctrl+V```, то дает.

**Comment by lossir** [comment]
> не получилось ввести дату 30.03.2009 если указана 28.02.2009 после ввода 30 курсор переходит на месяц и веденный день сбрасывается до 28 =(
> Так же с другими месяцами — 31.05.2009 если указано 30.04.2009

Если это неправильное поведение, то как должно быть?

> При чем если поле изначально пустое сброс не срабатывает. Я могу ввести 31.04.2009

Да, при потере фокуса забыл добавить "обрезание" по лимитам. Но теперь и не знаю, а как надо сделать)

> Это нормально что в стори formatting 2 дата, которая стоит по умолчанию, невалидная, а инпут переключает, и при этом не замечает совсем этого?

Это баг.

> А в стори formatting при управлении годом с клавиатуры стрелками вверх-вниз сбрасывается до 0000 ?

Не смог воспроизвести.

> В каких-то случаяй бэкспейсом стирается дата по одному символу, в каких-то стирается блок целиком. 

Логика такая - если реальное значение состоит из одной цифры(1-9), то значение очищается при первом нажатии `backspace`. Типа `UX`, но, похоже, неудачный)

**Comment by dzekh** [comment]
> Если это неправильное поведение, то как должно быть?

> Да, при потере фокуса забыл добавить "обрезание" по лимитам. Но теперь и не знаю, а как надо сделать)

Можно сделать такую проверку при переходе на год, но если последовательность другая и год первый, тогда нужно отслеживать момент «когда заполнена последняя цифра последнего поля»

Как вариант можно вообще не сбрасывать, просто считать что заполнено не по формату. 

> Логика такая - если реальное значение состоит из одной цифры(1-9), то значение очищается при первом нажатии `backspace`. Типа `UX`, но, похоже, неудачный)

хм 🤔

**Comment by lenoraart** [comment]
> не получилось ввести дату 30.03.2009 если указана 28.02.2009 после ввода 30 курсор переходит на месяц и веденный день сбрасывается до 28 =(
> Так же с другими месяцами — 31.05.2009 если указано 30.04.2009
> При чем если поле изначально пустое сброс не срабатывает. Я могу ввести 31.04.2009

Решение: валидация по потере фокуса. Дата автоматически не меняется

**Comment by lenoraart** [comment]
В IE 11 год обрезается до ближайшего лимита по потере фокуса
> Даем вводить с клавиатуры любое значение (день 1-31, месяц 1-12, год вообще любой)

В Хроме год обрезается, если перейти на другой блок даты

**Comment by lenoraart** [comment]
Если ввести в поле с порядком YMD год вне лимита, то выделение не переходит на следующую часть автоматически
![image](https://user-images.githubusercontent.com/37067213/56808040-ff802400-6849-11e9-8f5e-21e112dc1bfb.png)

**Comment by lenoraart** [comment]
Список не закрывается, если скроллить страницу
![image](https://user-images.githubusercontent.com/37067213/56809713-f8f3ab80-684d-11e9-85d3-a17c95167123.png)

**Comment by lenoraart** [comment]
`minDate` и `maxDate` должны передаваться в формате `DMY`
