### ISSUE TITLE
[Tabs] Некорректное поведение при отсутствии активного таба

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1348]
В 0.46 версии компонент `Tabs` не подсвечивает ни один из табов и никак не сообщает о том что в данный активный таб отсутствует. При этом поле `value` для обозначения активного таба является обязательным.

Есть несколько вариантов решения:
- Кидать вменяемую ошибку, что в качестве активного таба был передан идентификатор отсутствующий среди отрисованых табов
- Сбрасывать активный таб, генерируя например `onChange` и выставлять активным (первый?)
- Оставить текущее поведение и считать состояние табов, где ни один из табов не является активным корректным

В последнем случае нужна аргументация в каких сценариях это допустимо, описание в гайдах и пометить поле `value` в `Tabs` как необязательное.

**Comment by dzekh** [comment]
Обсудили, решили ничего не делать. Именно в Гайды не нужно тащить описание.
