### ISSUE TITLE
[Paging] IE11 Блокируется переключение страниц после четвертого нажатия с клавиатуры

### ISSUE THREAD

**Issue by kmn75** [skbkontur/retail-ui#1358]
retail-ui@0.46.0.
internet explorer 11, windows 10.

Сценарий:
1. На витрине открыть компонент Paging: https://tech.skbkontur.ru/react-ui/#/Components/Paging
2. Нажать левой кнопкой мыши по любой цифре (например, цифре 5), кроме первой (1-ой) и последней (12-ой) и "дальше".
3. Нажать ctrl+-> четыре раза подряд.

Баг: после четвёртого нажатия ничего не происходит.
![ie11 paging](https://user-images.githubusercontent.com/22619528/56118069-f7d79a00-5f82-11e9-9c2c-30db8bd27a80.gif)

Ожидаемый результат: после нажатия происходит переход на следующую страницу пейджинга.

*Примечание. В обратную сторону также воспроизводится.

**Comment by dzekh** [comment]
а если другую страницу выбрать в начале, количество доступных переходов тоже только 4 будет?

**Comment by kmn75** [comment]
> а если другую страницу выбрать в начале, количество доступных переходов тоже только 4 будет?

Воспроизводится, если выбрать сначала нажать любую страницу (кроме первой (1-ой) и последней (12-ой). Обновил описание.
