### ISSUE TITLE
[Input] Добавить возможность переключаться между полями с помощью ```Enter```

### ISSUE THREAD

**Issue by lenoraart** [skbkontur/retail-ui#1362]
При нажатии на ```Enter``` фокус должен переходить на следующее поле. Если больше полей нет, то ничего не должно происходить.

**Comment by wKich** [comment]
Обсуждали этот сценарий с командой форм, на тот момент @dzekh делал табличку в которой было описано как тот или иной элемент должен вести себя по нажатию на Enter. Возможно стоит переиспользовать решение из `ComboBox` для всех полей и сделать переход настраиваемым через глобальный флаг (?) или каким-то образом ограничивать работу в контексте формы

**Comment by dzekh** [comment]
Решили, что не будем реализовывать это в компонентах библиотеки. Управлять тем куда и как перейдет фокус продукт решает сам. Формулировки в гайдах исправим, когда нибудь напишем гайд по этому поводу, но поддерживать компоненты это не будут.
