### ISSUE TITLE
[TopBar] Виджет с сервисами

### ISSUE THREAD

**Issue by pravosud** [skbkontur/retail-ui#1368]
При использовании TopBar в старом варианте (в последней версии контролов) не отображается выпадающий список с сервисами контура: https://tech.skbkontur.ru/react-ui/#/Components/TopBar

**Comment by zhzz** [comment]
Со старым TopBar'ом все в порядке. Можно видеть, что на отдельной странице пример работает: 
[https://tech.skbkontur.ru/react-ui/#!/TopBar/3](https://tech.skbkontur.ru/react-ui/#!/TopBar/3).

Просто детали текущей реализации не позволяют работать более чем одному виджету на странице. Возвращается только первый `#spwDropdown`:
```
var $dropdown = $("#spwDropdown");
```

Вероятно пофикстится в новом виджете, который будет без jQuery.
