### ISSUE TITLE
Проблема с совместимостью со вторым Webpack'ом

### ISSUE THREAD

**Issue by BooleT37** [skbkontur/retail-ui#137]
Во втором вебпаке больше не резолвятся модули, находящиеся в папке "web_modules". Из-за этого ломается файл [variables.less](https://github.com/skbkontur/retail-ui/blob/master/components/variables.less#LC178), т.к. он содержит строку 
`@import '~react-ui-theme/variables.less';` (самый конец) и все компоненты, которые от него зависят. Проблема лечится добавлением "web_modules" в resolve.modules в webpack.config.js. Но кажется, что это всё равно надо исправить.

**Comment by nanot1m** [comment]
Отказались от web_modules
