### ISSUE TITLE
[Switcher] добавить свойство disabled

### ISSUE THREAD

**Issue by Soheevich** [skbkontur/retail-ui#1370]
Не хватает задизейбленного состояния контрола

**Comment by denexapp** [comment]
+1. Хочется на время сетевого запроса дизаблить контрол

**Comment by dzekh** [comment]
Стиль для заблокированной выбранной кнопки совпадает во флет теме и в дефолтной:
Текст color: #FFFFFF; opacity: 0.7;
Обводка border: 1px solid rgba(0, 0, 0, 0.37);
Заливка background: #A0A0A0;

Стиль для заблокированной не выбранной тоже одинаковый во флет теме и в дефолтной:
Текст — color: #A0A0A0;
Обводка — border: 1px solid rgba(0, 0, 0, 0.15);
Заливка — background: #F2F2F2;

Нужно бы его заодно проверить. 

![Switch Disabled Selected](https://user-images.githubusercontent.com/26383080/76396372-dfdae700-639a-11ea-93f8-0368a353a1cb.png)

**Comment by wKich** [comment]
@dzekh, такое состояние будет отражено в фигме?

**Comment by dzekh** [comment]
Да, оно там уже есть для свитчеров

**Comment by wKich** [comment]
А это нормально, что между кнопок есть расстояние и всех кнопок, кроме первой отсутствует левый бордер?
![Screenshot 2020-03-17 at 10 36 27](https://user-images.githubusercontent.com/6397708/76825239-36cd3a00-683b-11ea-9920-29e62a38be24.png)

**Comment by dzekh** [comment]
Да, это просто компоненты немного отдельно лежат. В таком виде, отдельно они не используются. Не знаю зачем их так положили 🤷‍♂️

**Comment by zhzz** [comment]
@dzekh А у заблокированной нажатой кнопки текст не должен быть смещен вниз на 1px, как у просто нажатой?

**Comment by dzekh** [comment]
> @dzekh А у заблокированной нажатой кнопки текст не должен быть смещен вниз на 1px, как у просто нажатой?

Да, поправлю в библиотеке для дизайнеров
