### ISSUE TITLE
[ComboBox] С включенным флагом searchOnFocus в getItems приходит пустой query

### ISSUE THREAD

**Issue by GM2mars** [skbkontur/retail-ui#1374]
Версия retail-ui@0.44.3
Браузер Хром 73.0
Если в компоненте ComboBox включить флаг `searchOnFocus` то при фокусе в `getItems` приходит пустой `query`, хотя заполнено значение. Из-за этого выпадающий список автокомплита показывает что ничего не найдено.
Если попробовать стереть один символ, то автокомплит сработает корректно и отобразить нужное значение.
```javascript
<ComboBox
  getItems={this.autocompleteGetItems}
  itemToValue={this.itemToValue}
  renderValue={this.renderValue}
  renderItem={renderItem}
  valueToString={this.valueToString}
  renderNotFound={renderNotFound}
  onUnexpectedInput={this.onUnexpectedInput}
  onInputChange={this.onInputChange}
  searchOnFocus={true}
  drawArrow={false}
  value={value}
  onChange={this.onChange}
/>
```

**Comment by wKich** [comment]
Логику `getItems` ты можешь реализовать любую. Ты вполне можешь на вернуть массив из имеющегося значения

**Comment by GM2mars** [comment]
Да, я так и сделал, но выглядит как костыль. Раньше автокомплит работал нормально.

**Comment by wKich** [comment]
Раньше это когда? И «нормально» это как? Возможно ты имеешь в виду поведение ComboBox с флагом autocomplete?

**Comment by GM2mars** [comment]
Да. В проекте Диадок мы используем `retail-ui`. Там на нем сделаны все многочисленные формы. Судя по ченджлогу в 0.44 версии в компонент `ComboBox` добавили свойство `searchOnFocus` и убрали `autocomplete` (по сути автокомплит разложили на два свойства).
Свойства `searchOnFocus` и старый `autocomplete` по заявлениям должны работать одинаково, то есть при фокусе на компонент, должен появляться автокомплит с выбором значений.
Баг в том, что если у нас уже стоит значение в `ComboBox` и мы делаем на него фокус, то вызывается `getItems` с уже введенным значением, но значние приходит в виде пустой строки. С `autocomplete` раньше в `getItems` при фокусе приходило корректное значение строки.
Ну и выглядит это так, что у тебя комбобокс со значением, ты ставишь на него фокус, выпадает автокомплит и пишет что ничего не найдено )).

**Comment by wKich** [comment]
`autocomplete` было заменено двумя свойствами `searchOnFocus` и `drawArrow`. И `searchOnFocus={false} drawArrow={false}` соответствуют `autocomplete={true}`. Факт в том что `autocomplete={true}` раньше не вызывал `getItems` при фокусе. При этом флаг `drawArrow` никак не влияет на логику работу и отвечает только за отрисовку стрелки. Вызов `getItems` со значением или без определяется внутренним флагом состояния `editing`, cудя по истории эта логика не менялась. Этот флаг устанавливается в `true` когда пользователь начинает редактировать поле ввода и сбрасывается, когда пользователь выбирает значение из выпадающего списка. В состоянии `editing` при фокусе будет вызван `getItems` со значением введенным пользователем. Если флаг сброшен то вызов `getItems` произойдет с пустой строкой. Но ещё раз повторюсь, раньше в состоянии `autocomplete={true}` при фокусе вызова `getItems` не происходило. Поэтому я не понимаю как раньше у тебя при фокусе срабатывал поиск в автокомплите

**Comment by zhzz** [comment]
Кажется тут возникло некоторое недопонимание. 

Дело в том, что раньше мы действительно делали поиск со значением по фокусу в режиме автокомплита. Но в [0.31.0](https://github.com/skbkontur/retail-ui/blob/master/packages/retail-ui/CHANGELOG.md#0310-2018-12-04) мы убрали такое поведение, мотивируя тем, что автокомплит должен искать только при редактировании значения.

Соответственно, сейчас автокомплиту времен 0.31.0 - 0.44.0 соответсвует комбинация  пропов `drawArrow={false} searchOnFocus={false}`. Поведение версии <0.31.0 вернуть нельзя, поскольку оно неверное и не соответсвует [гайдам](https://guides.kontur.ru/components/combobox/#35). `searchOnFocus={true}` же всегда делает пустой поиск, поскольку это считается [правильным](https://guides.kontur.ru/components/combobox/#20).

@GM2mars, ваша проблема с "ничего не найдено" решается через `searchOnFocus={false}`, если хотите правильный автокомплит, или возвратом всего списка вариантов из `getItems` при пустом query.

**Comment by GM2mars** [comment]
Я решил эту проблему проверкой на введеное значение и его подстановкой.
```javascript
    autocompleteGetItems = query => {
      if (!query) {
        if (this.props.value && this.props.value.name) {
          query = this.props.value.name;
        } else {
          return [];
        }
      }
      return getItems(query)
      .then(items => items.map(item => ({name: getName(item), item})));
    };
```
