### ISSUE TITLE
[Select] в плоской тему цвет placeholder отличается от цвета placeholder в поле ввода

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1375]
Для `placeholder` в полях ввода используются цвета:
```less
@placeholder-color: #a0a0a0; // состояние disabled
@placeholder-color-light: #cdcdcd; // обычное состояние
```
Тогда как для `Select` всегда используется цвет: `@slt-placeholder-color: #888;`

**Comment by dzekh** [comment]
Для плейсхолдера селекта в обоих состояниях нужно использовать `@placeholder-color: #a0a0a0;` этот цвет так же используется и в кнопках и полях и для плейсхолдера и для заблокированного состояния. 

@placeholder-color-light: #cdcdcd; — это цвет плейсхолдера в поле по фокусу: https://guides.kontur.ru/components/input/#10
