### ISSUE TITLE
[Tooltip] Неверно позиционируется с большим контентом

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1392]
С позицией `top left`, в случае если контент тултипа не влезает во вьюпорт и начинает переносится на следующую строку, сам тултип не перепозиционируется и начинает налезать на элемент к которому прицеплен.
![Screenshot 2019-04-29 at 11 15 03](https://user-images.githubusercontent.com/6397708/56878968-1011e380-6a70-11e9-89a6-f566674a6934.png)

**Comment by dzekh** [comment]
Мы ограничены технологиями нашего времени 🤷‍♂️

**Comment by dzekh** [comment]
А точно что всё еще воспроизводится в текущей LTS ? 
Я закрою, если я не прав и воспроизводится — поправьте меня.

**Comment by JackUait** [comment]
> А точно что всё еще воспроизводится в текущей LTS ?

Плюсик, у меня тоже не получается воспроизвести на последней `LTS`
