### ISSUE TITLE
[Button] [UI Flat] Серый вариант

### ISSUE THREAD

**Issue by nulladdict** [skbkontur/retail-ui#1407]
В библиотеке флетовых контролов для дизайнеров (`Kontur UI Flat`) существует вариант серой не-задизейбленной кнопки (`Default gray`), для которого нет соответствующей пропсы `use` в библиотеке контролов

**Comment by dzekh** [comment]
Все идет к тому, что мы откажемся от использования такой серой кнопки во флет теме. Из библиотеки для дизайнеров удалим, соответственно тут не появится. =/
