### ISSUE TITLE
[Input] не работают вместе пропы autoFocus и selectAllOnFocus

### ISSUE THREAD

**Issue by evifox** [skbkontur/retail-ui#1413]
Параметры:
- retail-ui 0.49.0;
- Google Chrome Version 69.0.3497.100 (Official Build) (64-bit), Win10;
- При появлении инпута срабатывает автофокус, но не срабатывает выделение. Но если переключить вкладку и вернуться обратно, то текст будет выделен. Также выделение срабатывает, если фокуситься вручную;
- `<Input autoFocus selectAllOnFocus value="value" />`;

**Comment by zhzz** [comment]
[Вот](https://github.com/facebook/react/issues/7769) в чем дело.
