### ISSUE TITLE
[Sticky] Реализовать компонент Sticky.Container

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#1417]
Имеет смысл добавить новый контрол (`Sticky.Container`), который будет контролировать несколько `Sticky` с "зависимым" контентом.

Предпосылки: https://github.com/skbkontur/retail-ui/issues/972
Временное решение: https://github.com/skbkontur/retail-ui/pull/1399

**Comment by JackUait** [comment]
Закрываем до лучших времён, так как пользователи в последнее время [не обращались](https://github.com/skbkontur/retail-ui/issues/972#issuecomment-1178839018) к нам с этой проблемой. Вероятно баг был пофикшен в ходе решение какой-то другой задачи
