### ISSUE TITLE
[react-ui-validations] Мгновенное исчезание тултипа при вводе валидного значения при типе валидации 'lostfocus'

### ISSUE THREAD

**Issue by iftruereturn** [skbkontur/retail-ui#1428]
Суть:
Валидация 'lostfocus'. Если в контроле ввода введеное невалидное значение менять на валидное, то тултип пропадет, а по гайдам тултип должен исчезать только в случае потерянного фокуса в инпуте.

- Версии библиотек: "react-ui-validations": "^0.8.1", "@skbkontur/react-ui": "^0.45.0", "react": "15.6.2";
- Браузер и ОС: Chrome 74.0.3729.169, Win 10;

http://tech.skbkontur.ru/react-ui-validations/#/on-blur-validations - воспроизводится прямо в документации
http://recordit.co/LADCuC1hNE

**Comment by dzekh** [comment]
[Обсудили с дизайнерами](https://staff.skbkontur.ru/group/5361?action=discussions&id=837edf79c3664b818a13a589f7b9daa2), договорились: 

Добавляем после §21:
«Если значение в поле с ошибкой было изменено, потеряло фокус, а потом заново оказалось в фокусе — тултип с текстом старой ошибки уже не возникает. Это правило одинаково работает для всех типов валидаций — и по потере фокуса и при отправке».

Изменяем §25:
«Красный текст ошибки появляется сразу, как только произошла валидация и ошибочное поле подсветилось. Как только пользователь начал исправлять значение, подсветка красным снимается, и цвет текста ошибки меняется на черный.

Текст ошибки пропадает при потере фокуса и больше не появляется, если поле заново получает фокус».
