### ISSUE TITLE
[Input] В плоской теме синяя рамка фокуса перебивает красную рамку error=true

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#1431]
@skbkontur/react-ui: "0.49.1"

**Что делаем**
1) Выставляем error=true
2) Видим красную рамку
3) Фокусим инпут

**Что получаем**
Видим синюю рамку

**Что должно быть**
Видим красную рамку

Так выглядят стили в хроме в момент error=true и фокуса
![image](https://user-images.githubusercontent.com/19679857/58408153-e9969680-8075-11e9-82ac-3f61017a4a44.png)

**Comment by lossir** [comment]
На ветке с кастомизацией (#1333) этот дефект исправлен.

| ![image](https://user-images.githubusercontent.com/2708211/58953660-937dcd80-87b0-11e9-95de-8ceb6fabe0a9.png) |
| --- |
