### ISSUE TITLE
[Tokeninput] Визуальное отображение disabled

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1435]
Версия: 0.51.0
Браузер: любой

Если в TokenInput передать disabled = true, то инпут не меняет цвет, и визуально кажется, что он доступен

**Comment by laion220995** [comment]
https://github.com/skbkontur/retail-ui/pull/1442 сделал пр

**Comment by lossir** [comment]
@dzekh Допустимо ли повторить задизейбленый вид как у `Input`?
