### ISSUE TITLE
[retail-up] Не работает закрытие попапов на айос

### ISSUE THREAD

**Issue by slogger** [skbkontur/retail-ui#1439]
На видео не понятно, но я старательно тапаю за пределы попапа

Последний сафари. Воспроизводил как на айпаде, так и на айфоне

https://share.icloud.com/photos/0AVQSJryDdVUkrZ_kgq6iDu9A

**Comment by nulladdict** [comment]
Вообще все элементы, которые используют библиотековский ClickOutside перестали работаь
