### ISSUE TITLE
[DatePicker] нужен метод focus()

### ISSUE THREAD

**Issue by sulasevich** [skbkontur/retail-ui#144]
Сделайте, пожалуйста, метод focus() в DatePicker

**Comment by molokovev** [comment]
@nanot1m я нашёл, [в какой момент](https://github.com/skbkontur/retail-ui/commit/03e84cb4b712af125b56080f6f431cdfa82f61a3#diff-7202f35d8831a342610a9b212c9e02bfL254) потерялся метод:

**Comment by molokovev** [comment]
Вернул в #147
