### ISSUE TITLE
[Input] IE11. Два инпута с маской. При выделении текста прыгает фокус между инпутами

### ISSUE THREAD

**Issue by knevostruev** [skbkontur/retail-ui#1443]
Браузер IE11, версия: 11.756.17134.0

Два инпута на странице:
```
<span>
  <Input mask="99:99" />
  <Input mask="99:99" />
</span>
```
Если оба инпута заполнены не до конца, например: `12:__`, то при попытке выделить текст в одном инпуте начинается перепрыгивание фокуса между инпутами. Это выжирает ядро процессора и не дает сфокусироваться на других контролах или выделить текст в этих инпутах. Если в одном из инпутов заполнить текст до конца, то происходит фокус на другой инпут и перепрыгивание прекращается.

Удалось воспроизвести на https://tech.skbkontur.ru/react-ui/#/Components/Input Фокусируемся за пределы браузера, затем быстро кликаем по одному из инпутов. Не всегда срабатывает с первого раза. Гифка:
![iebug2](https://user-images.githubusercontent.com/32193945/58805132-1b7e9e80-861c-11e9-9faf-7c1373ecf3fc.gif)

**Comment by dzekh** [comment]
Дежурному, проверить, сохранилось ли такое поведение

**Comment by zhzz** [comment]
Не удалось воспроизвести в IE11 (11.508.19041.0). Пробовал в последней на момент создания ишью версии 0.51.1 и в 2.6.0. 

Если все же еще актуально, то откроем снова.
