### ISSUE TITLE
[Dropdown] Выпадает вниз, когда внутри модального окна.

### ISSUE THREAD

**Issue by Frumcheg** [skbkontur/retail-ui#145]
Когда дропдаун внутри модального окна и не влезает в экран, он выпадает вниз, хотя должен выпасть вверх.
![- google chrome-e1jwn](https://cloud.githubusercontent.com/assets/2862206/24390645/ac1845c4-13a3-11e7-82b0-8d2e4d47bbb6.png)

**Comment by nanot1m** [comment]
![out](https://cloud.githubusercontent.com/assets/9278185/24390840/bf98f674-13a4-11e7-9799-28b81e5bfccb.gif)

**Comment by nanot1m** [comment]
А в каком браузере воспроизводится данная проблема?

**Comment by Frumcheg** [comment]
Нашёл корень проблемы.
https://github.com/skbkontur/retail-ui/blob/master/components/DropdownContainer/DropdownContainer.js#L85
Не определяем позицию, если `disablePortal: true`, без портала это трудно посчитать, я правильно понимаю?

**Comment by nanot1m** [comment]
Какова ситуация с этой проблемой?

**Comment by nanot1m** [comment]
ping
