### ISSUE TITLE
[Icon] Написать в документации о существовании иконок Kontur-Iconic20px

### ISSUE THREAD

**Issue by pravosud** [skbkontur/retail-ui#146]
В данный момент в документации компоненты Icon описаны все иконки из пака 14px,
но не сказано о компоненте './Icon/20px' , в которой реализованы все иконки из пака Kontur-Iconic20px

https://guides.kontur.ru/resources/icons/

**Comment by nanot1m** [comment]
Склоняюсь к тому, что об этом не стоит писать. Иконки планируем вынести в отдельную библиотеку
