### ISSUE TITLE
[retail-ui] Новый компонент «Увеличение картинок»

### ISSUE THREAD

**Issue by ahmadinurova** [skbkontur/retail-ui#1467]
Разработать компонент для увеличения картинок:

— Картинка масштабируется плавно (см. анимацию увеличения картинок на Медиуме https://medium.com/designkontur/скетч-библиотека-для-работы-19a692ea959f)

— Цвет фона, на котором открывается картинка и возможность листания настраиваются опционально.

Прототип:
https://www.figma.com/file/c2OXaYQoHJWlawehYq5285Te/%D0%A3%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BE%D0%BA?node-id=93%3A77&viewport=-2869%2C541%2C0.3340594470500946

**Comment by dzekh** [comment]
@ahmadinurova, а у вас не реализовали еще?

**Comment by ahmadinurova** [comment]
Нет еще. У нас задачка только в планах и то не в полном виде, а только на открытие картинок без зума, скачивания и листания.
@dzekh, а у вас какие планы? Может мы дождемся компонента, если это быстрее получится.

**Comment by dzekh** [comment]
В ближайших планах нет. Возможно в конце 2020. Когда начнёте делать — маякните.
