### ISSUE TITLE
[react-icons] Проблемы с рендеренгом в IE

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#1473]
> @dzekh 
Почему-то на скриншотах не могу найти иконку Mail3. И нужно разбираться с рендеренгом иконок в IE. Они все немного съехавшие и замыленные, как будто иконка рисуется с дробными значениями координат. Особенно хорошо это видно у иконок которые стоят в середине или в конце слова. Возможно там не круглое значение высоты строки, и он координаты для текста округляет, а для иконок нет. <img width="852" alt="image" src="https://user-images.githubusercontent.com/26383080/56365683-e0124700-620a-11e9-993c-0ed1e385f2c1.png">
Возможно поэтому квадрат съехал больше чем нужно. 
Но квадрат в IE на пиксель выше чем в остальных браузерах.

© https://github.com/skbkontur/retail-ui/pull/1353#pullrequestreview-228303546

**Comment by dzekh** [comment]
Перенесли задачу в гитлаб
