### ISSUE TITLE
[retail-ui] Адаптировать работу стилей библиотеки в формате css-modules с CRA

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1477]
CRA c версии 2.0 начал поддерживать css-modules. Для этого необходимо, чтобы файл со стилями имел расширение `.module.css` https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet

Нужно все `less` файлы компонентов переименовать в `.module.less`

**Comment by lossir** [comment]
Можно так, но не знаю, на сколько это правильно.

[/scripts/babel/imports-less-to-css.js#L2](https://github.com/skbkontur/retail-ui/blob/master/packages/retail-ui/scripts/babel/imports-less-to-css.js#L2)
![image](https://user-images.githubusercontent.com/2708211/59920067-b95ad180-9442-11e9-9a4c-c9e0f7644e2c.png)

**Comment by wKich** [comment]
Так только импорты в js файлах заменятся. Переименовывать less в любом случае нужно будет. По идее ничего в существующих проектах не должно сломаться, зато чинится в CRA. Можно проверить заведутся ли контролы после этого на codesandbox, так на всякий случай.

**Comment by zhzz** [comment]
CRA с версии 3 переехал на css-loader 2.x, в котором по умолчанию выключены css-модули. Без доп конфигурации все стили слетают. Переход на `.module.css` должен помочь.
