### ISSUE TITLE
[retail-ui] Собрать прототип для SmokeTests

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1482]
Мотивация:
Необходимо проверять что собранная версия библиотеки содержит корректные пути импортов/экспортов контролов, все нужные файлы попадающие в пакет не потерялись, тайпинги не сломаны.

Скрипт примерно следующий:
- Разворачивается CRA
- Устанавливается собраный пакет контролов
- Закидываются заранее подготовленный набор файлов с тестовыми страницами
- Запускается сборка, проверка типов, сборки
- Рендеринг и проверка что страница нарисовалась без ошибок

Можно взять табличку с компонентами из кастомизации #1333

**Comment by rustho** [comment]
#1885 Сделано
