### ISSUE TITLE
[Tabs] Дублируется подсветка фокуса при быстром переключении стрелками

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1483]
<img width="174" alt="Screenshot 2019-06-26 at 11 00 42" src="https://user-images.githubusercontent.com/6397708/60154737-ac9efa80-9801-11e9-8f8b-7abc74a9460b.png">

Проблема вероятнее всего из-за того что для каждого компонента Tab навешивается свой хендлер на нажатие клавиш-стрелок. Возможно, что причиной проблемы является асинхронная установка флага `focusedByKeyboard` в обработчике `handleFocus`.

Правильнее будет вынести обработку нажатий клавиш и переключение фокуса на уровень вверх в компонент `Tabs`.

#1429

**Comment by zhzz** [comment]
В последней 4.11.0 версии не воспроизводится
