### ISSUE TITLE
[Modal] Уменьшать внутренние отступы модалки при отображении на мобильных

### ISSUE THREAD

**Issue by IrinaSkb** [skbkontur/retail-ui#1491]
Привет! Опиши, пожалуйста, проблему, которая возникла:

- react-ui 1.0.0;
- Google Chrome 75.0.3770.100, Windows;
- В мобилках не адаптивно;
![image](https://user-images.githubusercontent.com/41990507/60569277-64935100-9d88-11e9-94e8-3c0821b39ff0.png)

Есть предложение, но нужно одобрение)
Уменьшить отступы самой модалки и зону крестика
![photo_2019-07-03_11-49-16](https://user-images.githubusercontent.com/41990507/60569396-b9cf6280-9d88-11e9-88ff-10c8ef538b79.jpg)

**Comment by dzekh** [comment]
Реализовано в 3.0
