### ISSUE TITLE
[ComboBox] Неккоректное поведение при рендеринге combobox на hover

### ISSUE THREAD

**Issue by ando771** [skbkontur/retail-ui#15]
Пример ошибки по [ссылке](https://ando771.github.io/combobox-hover-example/).  
Проблема заключается в том, что меню combobox рендерится не внутри самого компонента, а в body, используя паттерн [Portal](https://habrahabr.ru/company/smartprogress/blog/306096/). Поэтому при наведении на меню, событие hover у основого контейнера пропадает и combobox теряется.

**Comment by ando771** [comment]
Один из вариантов решения этой проблемы: добавить в ComboBox параметр, отвечающий за то, каким образом будет рендерится меню: используя концепцию portal или же как обычный блок с абсолютным позиционированием внутри компонента. По-умолчанию будет использоваться реализация с порталом.  
Я займусь такой доработкой и выложу соответствующий pull request.

**Comment by ando771** [comment]
Соответствующий pull request https://github.com/skbkontur/retail-ui/pull/18, решающий проблему, был смержен, поэтому закрываю issue.

**Comment by mortifer** [comment]
мне че-т кажется это решение кривым. 
это не поможет точно так же если этот комбобокс по ховеру будет спрятан в контейнер с overflow: hidden

@nanot1m я же вроде бы на словах тебе рассказывал как надо побороть - не стали так делать что ли?

**Comment by nanot1m** [comment]
@mortifer мы понимаем что такой подход не подходит для всех случаев. Поэтому сделали это решение опциональным. По сути мы переложили ответственность на пользователя контрола.

Твою идею об обертке я не забросил, потихоньку развиваю.
Пока я себе это представляю так:
```javascript
<Hover>
{hover => renderComponent(hover)}
</Hover>
```

**Comment by ando771** [comment]
@mortifer я в принципе считаю использование портала для рендеринга меню не верным, поэтому предложил такое решение. Основной аргумент за использование портала, который я услышал - это сценарий, когда комбобокс находится в overflow:hidden и в position:relative. Но мне кажется, что эта ситуация довольно специфичная. Использование overflow: hidden, в моем понимании, вообще говорит о том, что с версткой что-то не то. Обычно же его ставят, когда у блока появляются полосы прокрутки и их нужно убрать или контент немного вылазит за границы? Возможно, есть еще какие-то случаи, но я их не знаю.
Кстати, посмотрел реализации в других реактовских ui-библиотечках, интересно, что в material-ui тоже используют portal в autocomplete (http://www.material-ui.com/#/components/auto-complete). Правда, проблема та же: в моем сценарии их компонент тоже не работает, проверил.
