### ISSUE TITLE
[Fias] неверное значение fiasId

### ISSUE THREAD

**Issue by mortifer** [skbkontur/retail-ui#1505]
retail-ui 0.53.0 и 1.0.0

Заполняем адрес ручками по полям
"Екатеринбург, ул. Свердлова, дом 7"
Получаю в поле home.fiasId = "84501943-9da6-4cc8-9b59-a0f222dd2759"

При этом человекочитаемое название верное 
"Свердловская область, город Екатеринбург, улица Свердлова, дом 7"

Стоит мне загрузить в контрол 
fiasId = "84501943-9da6-4cc8-9b59-a0f222dd2759"
я получают другое название 
"Свердловская область, город Екатеринбург, село Горный Щит, улица Свердлова, дом 7"

Итого - на самом деле мы получаем в поле home неверное значение

**Comment by zhzz** [comment]
Привет. Могу воспроизвести только в 0.47.0 и ниже. Далее, с 0.48.0 адрес не валидировался, а в [0.51.1](https://tech.skbkontur.ru/react-ui/0.51.1/#/Fias) проблему пофиксили.

**Comment by mortifer** [comment]
че-то я по ходу дела выставил версию 0.46.0 и полез проверять, а потом на последнюю не вернул, мой косяк!
