### ISSUE TITLE
[Token] Проблема с типами

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#1519]
У конечных пользователей ругается typescript.

![image](https://user-images.githubusercontent.com/4607770/61542701-8c0e3d00-aa5b-11e9-91a0-1f6c9123219f.png)

**Comment by lossir** [comment]
Не помешал бы сценарий воспроизведения.

**Comment by coolassassin** [comment]
> Не помешал бы сценарий воспроизведения.

В CRA проблему не удалось воспроизвести. Но в нашем проекте, при добавлении флага `esModuleInterop` проблема пропадает.
