### ISSUE TITLE
[Modal] Лайтбокс не блокирует скролинг родительской страницы

### ISSUE THREAD

**Issue by sergey-soloviev** [skbkontur/retail-ui#152]
По крайней мере так себя ведет лайтбокс, который можно открыть на странице примера — http://tech.skbkontur.ru/react-ui/#/components/Modal

Лайтбокс должен блокировать скрол родительской страницы, чтобы она не прокрачивалась при использовании колесика мыши или стрелок на клавиатуре.

**Comment by pravosud** [comment]
@sergey-soloviev Подскажи пожалуйста, в каком браузере воспроизводится этот баг и при каком сценарии (при использовании стрелок на клавиатуре?)

**Comment by sergey-soloviev** [comment]
стрелками не прокручивается, но мышкой легко.

Mac OS 10.3
Safari 10.1

**Comment by pravosud** [comment]
Спасибо. 
В FF поймал такой же баг, только при использовании стрелок.

**Comment by nanot1m** [comment]
Исправлено
