### ISSUE TITLE
[CurrencyInput] Баг с удалением значения на андроиде

### ISSUE THREAD

**Issue by Na1ve** [skbkontur/retail-ui#1523]
retail-ui v 0.52.0, андроид;
При нажатии на "бэкспейс" на вирт. клавиатуре, курсор смещается влево и ничего не стирает.

**Comment by rustho** [comment]
В 2.6.0 повторяется

**Comment by zhzz** [comment]
Починили в 2.16.0 установкой  `inputMode` в `decimal` по умолчанию. Если нужно в более ранних версиях - пиши.
