### ISSUE TITLE
[MenuItem] Не применяется фон при hover/selected

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#1530]
Привет! 

Версия `"@skbkontur/react-ui": "1.1.0"`.
Браузер последний Chrome.

Когда наводишь на элемент в выпадающем меню не применяется фон:
![image](https://user-images.githubusercontent.com/22623111/61841618-cc801780-aeae-11e9-962c-35b9681b486b.png)
_(пропавший пункт, это как раз таки пункт под ховером)_

Попытался разобраться в причине происходящего, почему на tech.kontur.ru все нормально работает и в соседнем проекте тоже.

В моем варианте сборки: элементу меню навешиваются следующий классы:
`_3UkzGfAyQkGRMJPbPTKmWj` есть всегда, 
![image](https://user-images.githubusercontent.com/22623111/61841869-9a22ea00-aeaf-11e9-9711-199c461a5280.png)

`react-ui-zqo18d` по ховеру
![image](https://user-images.githubusercontent.com/22623111/61841893-baeb3f80-aeaf-11e9-9834-6dacae474207.png)

Мне не повезло и style-loader поместил код класса `_3UkzGfAyQkGRMJPbPTKmWj`, после `react-ui-zqo18d`. И теперь свойство `background` всегда из `_3UkzGfAyQkGRMJPbPTKmWj`, то есть `transparent`.

Предлагаю добавить `important`, как это сделано со свойством `color`, но там нужно не забыть про остальные состояния selected, link, disabled... 

А еще вариант, чтобы везде не расставлять `important`, поднять специфичность селекторов с состоянием:
```
._3UkzGfAyQkGRMJPbPTKmWj.react-ui-zqo18d {
    background: ...;
}
```
_(но как это сделать с emotion не подскажу)_

**Comment by zhzz** [comment]
Привет! Вероятно, у вас на странице несколько отдельных приложений? Мы уже боремся с этой проблемой #1514. Интересно, какой у вас кейс.

**Comment by slaeme** [comment]
Прошу прощения, не смог найти эту задачу. Отлично, что проблема решается)

У нас SPA с code-splitting через [react-loadable](https://github.com/jamiebuilds/react-loadable).
То есть приложение одно, но подгружается оно частями, по мере необходимости.

Из #1514 это пункт 2:
> lazy-компоненты

**Comment by zhzz** [comment]
@slaeme Ничего, там не очень очевидный заголовок. Спасибо за такое подробное описание и варианты решения!

**Comment by zhzz** [comment]
Duplicate of #1514
