### ISSUE TITLE
[ComboBox] Переход к следующему полю после нажатия на Enter

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#1532]
Привет!

Хотел бы добавить возможность кастомизировать поведение из гайдов:
https://guides.kontur.ru/components/combobox/#67
![image](https://user-images.githubusercontent.com/22623111/62038844-f23f5080-b20f-11e9-9068-5c2f80337ef4.png)

Когда комбобокс в форме, это возможно работает, но когда комбобокс в другой части интерфейса, смена фокуса может помешать. 

Интересный факт, что ни один нативный HTML контрол (input, select ...) не меняет элемент в фокусе по Enter, это происходит только по кнопке Tab. 

Сейчас, если пользователь не работает с клавиатурой, то после выбора элемента из списка он должен кликнуть на следующее поле,  но в случае, когда пользователь работает с клавиатурой, он нажмет Enter, Tab (такое поведение уже в мышечной памяти) и окажется через одно поле в форме.

Предложение, добавить возможность выбора: переносить или нет фокус по нажатию Enter или вообще убрать это поведение.

**Comment by dzekh** [comment]
Сейчас кажется, что правильней было бы убрать это поведение, и делать это отдельной настройкой для полей в принципе, либо отдать эту логику на откуп продукту. Кажется, что это не задача компонента библиотеки.

**Comment by StarLordJ** [comment]
В формах реализован переход по Enter для инпутов. 
Если выбрать значение в комбобоксе нажатием на Enter, сначала срабатывает метод в комбобоксе, фокус переходит на первый попавшийся инпут после комбобокса, и потом отрабатывает метод на событие keyUp у этого инпута (реализация в формах) и фокус ещё раз переходит на следующий инпут.

**Comment by zhzz** [comment]
Изначально это был фикс #907. Стоит тогда оставлять фокус в текущем поле после выбора по Enter, как сейчас происходит с выбором мышкой.

**Comment by dzekh** [comment]
Я исправлю текст в гайдах, можно исправлять поведение в библиотеке. 
Фокус должен оставаться на поле.
