### ISSUE TITLE
[FxInput] Обертка Group не дает выравнять по baseline

### ISSUE THREAD

**Issue by Shururup** [skbkontur/retail-ui#1537]
Сейчас компонент `FxInput` обернут в `Group`. У  `Group` в стилях явно указан `vertical-align: bottom`.  Если обернуть `FxInput ` во флекс-контейнер и задать выравнивание по `baseline`, оно не сработает. Возможно, обертка `Group` в компоненте не требуется (у других инпутов ее нет), и ее можно спокойно удалить. 

![flex](https://user-images.githubusercontent.com/26028761/62269945-08d2eb00-b44e-11e9-8939-8725d4f405f7.JPG)

**Comment by zhzz** [comment]
По поводу vertical-align:

> **Tim Khazamov**:
> Старя проблема, связанная с необходимостью поддерживать ie8
