### ISSUE TITLE
[react-ui-telemetry] Дизайн решения по сбору телеметрии

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#1539]
## Пакет `react-ui-telemetry`
Всю реализацию хочется поместить в отдельный пакет. Который будет легко поставить, и быстро подключить сбор данных "за две минуты".

Основные тезисы реализации:
#### Всем контролам необходимо будет добавить статическое свойство `__REACT_UI__`
Оно будет выполнять 2 функции:
- идентификация компонента, как контрола библиотеки;
- содержать полное название контрола, на случай использования обфускации.
```tsx
public static __REACT_UI__: string = 'Button';
```

#### Значение каждого пропа перед отправкой будет преобразовываться
Всего допустимо 4 типа:
```tsx
enum MetrikaVariableType {
  String = 'string',
  Number = 'number',
  Uuid = 'uuid',
  Base64 = 'base64',
}
```

#### Правила преобразования будут описываться в файлах с именами, повторяющими название контролов
```tsx
/components
    /Button
        Button.ts
    /Input
        Input.ts
```

`Button.ts`
```tsx
export function Button(props: ButtonProps): MetrikaVariables {
  return new ConverterProps<ButtonProps>(props).getConvertedProps();
}
```

#### Для сложных/уникальных преобразований значений пропов будут доступны инструменты:
```tsx
new ConverterProps<ButtonProps>(props).customConvertProp('icon', icon => {
  return icon && icon.type && icon.type.name ? { value: icon.type.name } : null;
})
```

#### Все пользователькие текстовые значение должны будут заменяться аналогичными по длине строками с рандомными символами.
Б - безопасность.
```tsx
ConverterProps.substitutionString('Иван Иванов'); // ek49c086lx5
```
❔ Возможно, такие пропы стоит передавать в виде **числа** - длины строки.

#### В итоге файл с правилами преобразований пропов контрола будет выглядеть примерно так:
```tsx
import { ButtonProps } from 'retail-ui/build/components/Button';
import ConverterProps from '../../ConverterProps';
import { MetrikaVariables } from '../../metrikaTypes';
import reactNodeToString from '../../reactNodeToString';

export function Button(props: ButtonProps): MetrikaVariables {
  return new ConverterProps<ButtonProps>(props)
    .customConvertProp('icon', icon => {
      return icon && icon.type && icon.type.name ? { value: icon.type.name } : null;
    })
    .customConvertProp('children', children => ({
      value: ConverterProps.substitutionString(reactNodeToString(children)),
    }))
    .getConvertedProps();
}
```

## Пакет `react-sorge` (Зорге)

---
UPD. **Справка:**
Сейчас, пакет `react-ui-testing`, для поиска `html-элементов`, использует атрибуты: `data-comp-name` и `data-prop-${name}`. Эти атрибуты, из `react fiber` в `dom`, сеттит специальный скрипт в файле `react-selenium-testing.js`.
Этот скрипт, в части слежения за компонентами, состоит из элементов файла [react-devtools/attachRendererFiber.js](https://github.com/facebook/react-devtools/blob/master/backend/attachRendererFiber.js).
Сам `react-devtools` использует специальный мегахук - `__REACT_DEVTOOLS_GLOBAL_HOOK__`, интерфейс которого, выглядит примерно так:
<details>
<summary>interface Hook</summary>

```ts
interface Hook {
  _renderers?: { [key: string]: unknown };
  _listeners?: { [key: string]: Array<(data: any) => void> };
  helpers?: Dictionary<string, RendererFiber>;
  checkDCE?: unknown;
  inject: (renderer?: ReactRenderer) => string | void;
  sub?: HookAction<HookAction<void>>;
  on?: HookAction<void>;
  off?: HookAction<void>;
  emit?: (evt: string, data: any) => void;
  supportsFiber: boolean;
  _fiberRoots?: { [key: string]: Set<any> };
  getFiberRoots?: (rendererID: string) => Set<any>;
  onCommitFiberUnmount?: (rendererID: string, fiber: Fiber) => void;
  onCommitFiberRoot: (rendererID: string, root: FiberRoot) => void;
}
```

</details>

На первых обсуждениях реализации телеметрии с @wKich было решено использовать этот самый мегахук.
После исследования текущей реализации и возможностей хука, появилась мысль создать отдельный пакет, с блэкджеком и тайпскриптом.

---

Отдельная библиотека, которая, используя `__REACT_DEVTOOLS_GLOBAL_HOOK__`, будет шпионить за виртуальным домом и сообщать "куда следует".
Заменит файл `react-selenium-testing.js`.

Основные тезисы реализации:
- Это выжимка из файла `react-selenium-testing.js` и репы `/facebook/react-devtools`.
- Будут отслеживаться все события `onCommitFiberRoot`.
- Будет покрыто типами(сколько возможно) и экспортить тип `Fiber`.

❔ Возможно, стоит передавать тип `TypeCommit` со значениями: `mount`, `update`, `unmount`.

❔ Возможно, события `onCommitFiberRoot` стоит "поднимать" только если пропы компонента реально изменились. (Само событие срабатывает для всего дерева компонентов при взаимодействии с любым из них)

## Подключение:
Во входном файле проекта надо будет подключить пакет:
```
import 'react-ui-telemetry';
```

И установить один из флагов:
```
REACT_APP_REACT_UI_TELEMETRY    = true     // react-create-app
REACT_UI_TELEMETRY              = true     // все остальные
```

**Comment by k-g-a** [comment]
> Всего допустимо 4 типа

Типов `boolean` и `Date` не будет?

> Правила преобразования будут описываться в файлах с именами, повторяющими название контролов

Эти файлы из какого пакета? Они в retail-ui будут или в retail-ui-telemetry? Если во втором, то матчиться они будут по имени компонента, которое "зашито" в `public static __REACT_UI__`?

> Возможно, такие пропы стоит передавать в виде числа - длины строки.

Смотря, насколько подробная нужна инфа. Зачем вообще знать длины строк? Если в качестве отладочной информации (для поиска багов или крайних случаев?), то может быть лучше заменять с соблюдением локали, пробельных символов и т.п.? Что-то вроде:
```
Иван Иванович 1ый  // -> Отпз Якажончм 4ие
The Call of Ktulhu // -> Mrj Uelx bn Rnuslz
№123-QN // -> №897-FB
```

Про sorge вообще без контекста не понятно :)

**Comment by lossir** [comment]
@k-g-a 

> Типов boolean и Date не будет?

Нет. Если верить [вики метрики](https://wiki.skbkontur.ru/pages/viewpage.action?pageId=214330631).
> **Variables**
Тип переменной. Одно из значений: **String**, **Number**, **Uuid**, **Base64**
---
> Эти файлы из какого пакета? Они в retail-ui будут или в retail-ui-telemetry? Если во втором, то матчиться они будут по имени компонента, которое "зашито" в public static __REACT_UI__?

Ответ на последний вопрос - да)

Примерная реализация:
```tsx
import * as components from '/react-ui-telemetry/components';

const componentName = fiber.type.__REACT_UI__;
if (components.hasOwnProperty(componentName)) {
  return (components as any)[componentName](fiber.memoizedProps);
}
```
---
> Смотря, насколько подробная нужна инфа...

Изначально хотелось знать, на сколько длинные или короткие используются названия кнопок, табов и тому подобное. Эта информация позволила бы "настраивать" дизайн контролов, основываясь на конкретной статистике...
На счёт сохранения пробелов - возможно, сам думал их сохранять. Сохранение других символов кажется не очень безопасным, т.к. возможно заметное повторение структуры значения (как в твоём 3-м примере)

---
`react-sorge` - опишу подронее в первопосте.

**Comment by wKich** [comment]
Выглядит неплохо.

Про `react-sorge`, тянет на отдельную задачу, которая только косвенно связана с телеметрией.

У самой телеметрии смущают два момента.

- Названия файлов с конвертерами, это может привести к путанице.
- Сами конвертеры, их нужно явно описывать для каждого компонента или они нужны только для некоторых пропов, а с остальными сбор метрик будет работать без конвертеров пересылая данные 1:1?

**Comment by lossir** [comment]
@wKich 

Предполагается. что для каждого компонента будет создан файл с правилами конвертации.
Наличие этого файла, будет также говорить о необходимости "следить" за конкретным контролом.
Можно добавить к названию файла постфикс: `Button.telemetry.ts`. И избавиться от папок.
Т.е. cделать такую структуру:
```
/components
    Button.telemetry.ts
    Input.telemetryts
```
Папки добавил на всякий случай, если реализация для какого-нибудь контрола потребует несколько файлов. Но, возможно, это преждевременно.

---

Да, большинство пропов будет конвертироваться автоматически.
Правила, описанные для `Button` выше, требуют уникальной конвертации только для `icon` и `children`:

`React:`
```tsx
<Button
  warning
  narrow
  loading={false}
  width={200}
  icon={<IconOk />}
  onKeyDown={console.log}
  onClick={console.log}
>
  <span>Click me</span>
</Button>
```
`Конвертированные данные:`
```js
{
  children: {type: "string", value: "btzjlw7s"}
  icon: {type: "string", value: "OkIcon"}
  loading: {type: "string", value: "false"}
  narrow: {type: "string", value: "true"}
  onClick: {type: "string", value: "true"}
  onKeyDown: {type: "string", value: "true"}
  size: {type: "string", value: "small"}
  type: {type: "string", value: "button"}
  use: {type: "string", value: "default"}
  warning: {type: "string", value: "true"}
  width: {type: "number", value: "200"}
}
```

**Comment by dzekh** [comment]
@lossir перенеси в отдельный проект в гитлаб, плиз

**Comment by dzekh** [comment]
все

**Comment by dzekh** [comment]
задачи

**Comment by dzekh** [comment]
@lossir Максим, если перенес, закрой тут и ссылку поставь на новую таску.

**Comment by dzekh** [comment]
[Перенес в ютрек](https://yt.skbkontur.ru/issue/IF-84), здесь закрываю.
