### ISSUE TITLE
[react-ui-telemetry] Этапы реализации

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#1555]
Общие этапы:
- [ ] Разработать и согласовать дизайн решения сбора данных (#1539)
- [ ] Разработать и согласовать дизайн решения отправки данных в Контур.Метрика (#1566 (1/2))

Этапы реализации сбора данных:
- [ ] Составить и согласовать правила конвертации пропов (кроме очевидных, типа строк и чисел, есть ещё колбэки, `html/jsx` элементы и т.п.)
- [ ] Составить и согласовать список отслеживаемых **контролов**
- [ ] Составить и согласовать список пропов с правила конвертации для отслеживаемых **контролов**
- [ ] Реализовать правила конвертации по-умолчанию
- [ ] Реализовать инструменты кастомной конвертации
- [ ] Создать файлы с правилами конвертации пропов для всех отслеживаемых **контролов**

**Comment by wKich** [comment]
Кажется одним из начальных этапов реализации телеметрии должна быть задачка по вынесению `react-selenium-testing` в отдельный пакет https://github.com/skbkontur/retail-ui/issues/1288

**Comment by lossir** [comment]
Думаю нет, т.к. с телеметрией эту задачу связывает только пакет `react-sorge`. После его реализации, эти задачи даже можно распараллелить.

**Comment by wKich** [comment]
Ты имеешь в виду так?
```
+---------------+         +----------------------+
|               |         |                      |
|  react-sorge  +-------->+  react-ui-telemetry  |
|               |         |                      |
+-------+-------+         +----------------------+
        |
        |
        |                 +--------------------------+
        |                 |                          |
        +---------------->+  react-selenium-testing  |
                          |                          |
                          +--------------------------+
```

**Comment by lossir** [comment]
Именно)

**Comment by dzekh** [comment]
Задачка пеереехала в ютрек: https://yt.skbkontur.ru/issue/IF-83
