### ISSUE TITLE
[DatePicker] Баг с кликом на день календаря в Edge

### ISSUE THREAD

**Issue by sergeyshmakov** [skbkontur/retail-ui#1557]
Открываем официальную документацию (на момент обнаружения - версия 1.1.2)
https://tech.skbkontur.ru/react-ui/#/Components/DatePicker

Заходим в Edge (у меня версия 44.17763.1.0) - пытаемся выбрать день в любом из календарей - он не выбирается.

При этом кликая на ссылку "Сегодня..." дата выбирается.
Т.е. не срабатывает хэндлер на клик именно по дню в календаре.

Открываем консоль, вставляем `console.log("value: " + value);` в `handleChange`, видим следующее:
 * Была пустая дата, пытаемся выбрать новую, видим вывод
```
value: 02.08.2019
value: 
```

* Нажимаем на ссылку сегодня - проставляется дата (в моем случае 15.08.2019), пытаемся выбрать новую, но кликая на конкретный день, видим:
```
value: 11.04.2018
value: 15.08.2019
```

Вывод такой, что два раза срабатывает onChange - первый раз с правильной датой. второй раз с предыдущей, в итоге это выглядит, как будто дата не выбирается.

**Comment by sergeyshmakov** [comment]
Еще коммент небольшой - Производственный календарь в примерах не проставляет значение, потому что его банально нет в пропсах.

`<DatePicker isHoliday={isHoliday} enableTodayLink />`

**Comment by sergeyshmakov** [comment]
Баг тесно связанный с этим и касающийся всех браузеров - это `restore` значения, если оно было заполнено не полностью или не полностью удалено:

* Выбираем первую дату, затем меняем ее на вторую
* Удаляем день, убираем фокус - должно появится значение второй даты, но появляется значение первой.

**Comment by sergeyshmakov** [comment]
#1561

**Comment by lossir** [comment]
> Еще коммент небольшой - Производственный календарь в примерах не проставляет значение, потому что его банально нет в пропсах.

Не очень понял о каком значении речь?
Если речь про `value`, то оно не нужно для демонстрации использования производственного календаря.

---
Обращай, пожалуйста, внимание на поле `Assignees` у `Issue`. Получается мы оба делали один и тот же баг. После ревью PR'а решим, что делать.

**Comment by sergeyshmakov** [comment]
@lossir Если что, можно на мой PR забить, там микроправки по части этого бага.

Насколько понял из работы кода - там в целом много чего не стыкуется в обертке компонента для Edge и в любом случае делать кому-то из инфраструктуры.

Мы откатили версию до `retail-ui 0.45` т.к. во всех версиях выше не работает `Edge`. Соотв. пришлось отказаться от использования `ThemeProvider`.

**Comment by lossir** [comment]
@sergeyshmakov Хорошо, ПР закрою. Постараемся выпустить исправление в ближайших релизах.
