### ISSUE TITLE
[Currencylabel] При указании fractionDigits=0 и дробном значении выкидывается ошибка и ломается рендер

### ISSUE THREAD

**Issue by vandal-x** [skbkontur/retail-ui#1558]
Привет! Если передать `fractionDigits={0}` и в value передать дробное число компонент кидает эксепшен. То же самое случается если передать, например, число с двумя знаками после запятой и `fractionDigits={1}`.
 
Пример:
```jsx
<CurrencyLabel value={12356.1} fractionDigits={0} currencySymbol={'₽'} />
```

Судя по коду это было сделано намеренно:
https://github.com/skbkontur/retail-ui/blob/b51825058fbb4811105604a4625165d2ad0ac305/packages/retail-ui/components/CurrencyInput/CurrencyHelper.tsx#L116-L118

Хотелось бы узнать зачем.

**Comment by zhzz** [comment]
@slawwan подскажешь?

**Comment by wKich** [comment]
Предположу что в сценарии `value={0.5} fractionDigits={0}` не понятно в какую сторону округлять значение. @vandal-x, что ты ожидаешь увидеть, когда передаешь 0.5? А когда 0.4 или 0.6?

Кажется что ошибка тут вполне уместна, единственное, что текст ошибки мог быть более адекватным. Идеальный вариант использовать `custom PropType validation`, потому что выкидывание ошибки ломает рендер.

**Comment by vandal-x** [comment]
Проблема скорее в том, что компонент именно кидает эксепшен.
Лично я бы предпочел чтобы компонент просто обрезал бы значение, т.к. округление лежит в области бизнес логики приложения, а не ломал рендер страницы.

**Comment by wKich** [comment]
То что ошибка ломает рендер это очень плохо. Нужно будет на PropType validation переделать
