### ISSUE TITLE
[DatePicker] - Вероятно неверная работа restore во всех браузерах

### ISSUE THREAD

**Issue by sergeyshmakov** [skbkontur/retail-ui#1559]
Баг касающийся всех браузеров - это `restore` значения, если оно было заполнено не полностью или не полностью удалено:

* Вводим дату (не сегодня)
* Удаляем день в инпуте, убираем фокус - должно появится значение ранее введенной  даты (насколько я понял логику, потому что в гайдах инфы об этом не нашел), но появляется значение сегодняшней даты.

_Originally posted by @sergeyshmakov in https://github.com/skbkontur/retail-ui/issues/1557#issuecomment-522010298_

**Comment by lossir** [comment]
Если при потере фокуса дата неполная, то пустые значения заполняются значениями текущей даты. Это фича такая. К сожалению, гайды и контролы не до конца согласованы.

Если считаешь такое поведение неверным, то пригласим @dzekh.

**Comment by sergeyshmakov** [comment]
@dzekh Кажется подставлять значения текущей даты не совсем верно. Если я выбрал дату например в другом месяце, потом удалил только месяц, передумал, вышел, то кажется логичным подставлять введенный ранее мой месяц, а не месяц текущий, который может быть никак не согласован вообще с годом и днем моей даты (например текущий месяц февраль, а день выбран 31). Да и в принципе кажется нелогичным подставлять части текущей даты в дату которая находится в другом месяце или даже годе.

**Comment by dzekh** [comment]
Вообще, на мой взгляд, если по хорошему, то нельзя как-то менять данные введенные пользователем — ни подставлять старые, ни заполнять текущую дату. Мы не сможем предусмотреть всех сценариев использования, и пользователей любое автоматическое изменение чаще всего будет вводить в недоумение. 
Фича с подставлением текущей даты подразумевает сценарий когда пользователь только начал вводить дату в пустое поле. только тогда это, возможно удобно, и то когда пользователь привык и знает об этом. 

В общем я бы ничего за пользователя не заполнял, и изменил бы этот пункт в гайдах. 

@sergeyshmakov А почему должна вернуться старая дата если я стер ее часть?

**Comment by dzekh** [comment]
Пересоздадим, когда перепишем гайд по вводу даты
