### ISSUE TITLE
[Button]Некорректное отображение кнопок-стрелок в темной теме

### ISSUE THREAD

**Issue by Nevenq** [skbkontur/retail-ui#1562]
Столкнулся с тем, что для цвета "стрелки" не накладывается тот же цвет фона, что и для основной части кнопки. Есть один класс который накладывает одинаковые цвета стрелки для темной и светлых тем :
![image](https://user-images.githubusercontent.com/38163651/63241356-dce89f80-c26c-11e9-902c-8d90c39a3de7.png)
![image](https://user-images.githubusercontent.com/38163651/63241942-fc80c780-c26e-11e9-9042-cbed08ab4a20.png)

**Comment by zhzz** [comment]
Это, похоже, все еще отголоски #1514.

**Comment by zhzz** [comment]
Привет @Nevenq. Можешь подробнее сценарий описать?
1. Вы кастомизируте тему своими цветами?
2. На скрине дефолтное состояние кнопки или hover/active/disabled?
3. Применяется ли на проекте code-splitting?

**Comment by Nevenq** [comment]
> Привет @Nevenq. Можешь подробнее сценарий описать?
> 
> 1. Вы кастомизируте тему своими цветами?
> 2. На скрине дефолтное состояние кнопки или hover/active/disabled?
> 3. Применяется ли на проекте code-splitting?

Привет @zhzz. 
1. Да
2. В состоянии disabled
3. Да

**Comment by zhzz** [comment]
После фикса возникает дополнительная проблема #1599.
