### ISSUE TITLE
[DatePicker] Не работает выделение текста поля когда оно в фокусе

### ISSUE THREAD

**Issue by Griboedoff** [skbkontur/retail-ui#1564]
- на поле стоит валидатор
- ставлю фокус в поле с датой
- жму ctrl+A
- выделяется вся страница будто фокус не установлен

браузер chrome
react-ui 1.1.1
react-ui-validations 1.0.1

**Comment by sergeyshmakov** [comment]
@wKich DatePicker issues up!

**Comment by lossir** [comment]
Баг был исправлен в 1.4.0 ([витрина@1.4.0](https://tech.skbkontur.ru/react-ui/1.4.0/#/Components/DatePicker)), с внедрением библиотеки идентификации клавиш.
Дело было в том, что комбинация `ctrl+A` корректно работала только в английской раскладке..

https://github.com/skbkontur/retail-ui/pull/1639/commits/3d89716fd8f8cc88fb77a3bf0933a0892a5e54e7#diff-d724fbae8f2b397b5f92abe0f4eabe49L28

**Comment by wKich** [comment]
Было исправлено в #1429
