### ISSUE TITLE
[react-ui-validations] [checkbox] не сбасывается валидация вокруг чекбокса

### ISSUE THREAD

**Issue by aagordienko** [skbkontur/retail-ui#1565]
Гифка №1 - два чекбокса, если выбран хотя бы один - валидации нет.
Валидация работает по submit. 
Если развыбрать оба чекбокса, сабмитнуть, а затем выбрать один, то во втором ValidationWrapper принимает null в validationInfo (как и должно быть), но на тултип сброс валидации почему-то не влияет (продолжает появляться при наведении, красная рамка остается).
При этом наблюдается значительная задержка в моменте смены значения validationInfo на null.

Гифка №2 - все те же условия, Checkbox поменяны на Input. При наличии валидаций на обоих, после заполнения одного из них validationInfo второго меняется на null без задержки, по расфокусу тултипы пропадают на совсем, красная рамка тоже.

На гифке с чекбоксами на запечатлен момент, когда, при наличии валидации на обоих, выбирается один, то валидация на втором не пропадает в том числе и по расфокусу.

"retail-ui": "^0.52.0"
"react-ui-validations": "^1.0.1"

![ezgif-5-206fb6e7dfe2](https://user-images.githubusercontent.com/30799122/63273032-daef0280-c2a5-11e9-9b05-99d728445659.gif)

![ezgif-5-cd0f3da69044](https://user-images.githubusercontent.com/30799122/63273048-e5110100-c2a5-11e9-9061-bb2a86957ad7.gif)

**Comment by Lelchik** [comment]
В react-ui-validations@1.0.3 тоже воспроизводится. 
Сценарий воспроизведения еще проще:
- в форме есть 2 чекбокса и валидация "Должен быть выбран хотя бы один"
- сабмит формы (подсвечиваются оба чекбокса, появляется тултип)
- выбираем один чекбокс. Тултип остается, хотя остальные чекбоксы перестают быть красными
![Редактор организаций - Google Chrome 2019-10-08 18-27-30](https://user-images.githubusercontent.com/11275614/66399698-87717900-e9f9-11e9-883b-c70c03824cb8.gif)
