### ISSUE TITLE
[react-ui-telemetry] Дизайн решения по отправке телеметрии (1/2)

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#1566]
#### Будем использовать Pipe.API

Метрика предоставляет два способа отправки событий: **Трекер** и **Pipe.API** ([Сравнительная таблица Трекера Метрики и Pipe.API](https://wiki.skbkontur.ru/pages/viewpage.action?pageId=277808189)).

Нам подходит Pipe.API, т.к:
- Не собирает данные автоматически
- Не отправляет события автоматически
- Нет ограничений на размер передаваемых параметров. У Трекера это 2 Кб, с учётом данных собираемых автоматически

Из недостатков:
- Отсутствие готового клиента (только на `С#` и на `1С`)

#### Условный путь вложенности события: `infrontend` → `reactui` → `button` → `mount`

Для нас будет всего 2 события - `Mount` и `Update`. Других не придумал.

Для верхнеуровневой идентификации события существует **Топик**.
Топик состоит из двух компонент:
- `TopiсSource` - строковый идентификатор источника событий. Позволяет определить к какому сервису, клиенту и т.д. относится данное событие.
- `TopiсKey` - строковый идентификатор топика. `TopiсKey` – это более крупное разбиение типов событий, чем категория событий (`Category` см. ниже), к которой относится данное событие. Сильно разнородные события с разным набором полей лучше отправлять с разным `TopicKey`.

Их надо выбирать заранее, т.к. добавляются командой Метрики вручную.
Также у каждого события существует свойство `EventPath`, которое, вместе с Топиком, можно представить в таком виде:
<a name="topic" />
```
                          -------------- EventPath -------------
TopiсSource → TopiсKey → Category → Action [ → Label → View ]
```

Предлагаю такие названия ([Допустимые символы](https://wiki.skbkontur.ru/pages/viewpage.action?pageId=265976334)):

| key | value |
| --- | --- |
| TopiсSource  | **`infrontend`** |
| TopiсKey | **`reactui`** |
| Category | **`button`**/**`input`**/**`select`**/etc. |
| Action | **`mount`**/**`update`** |
| *Label* |  Название команды (Свободная форма?) |
| *View* |  *- пропуск -* |

#### Отправляемые данные:

```json
{
    "id": "62a1c25f-b5f0-4f49-bbc9-59e192692d1c",
    "time": {
        "clientTime": "2017-01-01T00:00:00Z",
        "sendFromClientTime": "2017-01-01T00:01:00Z"
    },
    "path": {
        "category": "Button",
        "action": "Mount",
        "label": "Контур.Отель"
    },
    "variables": {
        "children": {
            "type": "string",
            "value": "btzjlw7s"
        },
        "icon": {
            "type": "string",
            "value": "OkIcon"
        },
        "onClick": {
            "type": "string",
            "value": "true"
        },
        "width": {
            "type": "number",
            "value": "200"
        }
    }
}
```

#### Кастомный клиент для Pipe.API
У команды Контур.Метрики создание js-клиент для **Pipe.API** только в планах. Поэтому необходимо реализовать логику отправки данных самостоятельно.
Для сокращения количества `http`-запросов, клиент будет:
- отправлять запрос **1** раз в **1** мин
- отправлять запрос при превышении кол-ва накопленных событий в **1000** шт
- отправлять запрос не чаще **1** раза в **5** сек
- игнорировать события, если превышен лимит в **1000** шт, и не прошло **5** сек с предыдущего запроса

Возможно, при испытаниях значения ещё скорректируются.

---

Команда Метрики планирует создать универсальный js-клиент, который заменит Трекер и будет, также, работать с Pipe.API. Они заинтересованы посмотреть нашу реализацию, хоть она и коснётся только части с Pipe.API.

При реализации можно учитывать только нагрузку на клиента. Сервер сам регулируют оптимальную вставку данных в `ClickHouse`.

Детали реализации будут отдельно.

**Comment by wKich** [comment]
Голосовалка за название `TopicSource`
- `infrontend` 👍 
- `infrantend` 😄
- `frontend` 🎉
- `front-infra` 🚀

**Comment by wKich** [comment]
По поводу событий, возможно стоит ещё учитывать `unmount` и хорошо бы ещё где-то передавать id элемента, чтобы можно было в случае чего выстраивать цепочку обновлений того или иного компоненте, если таких компонентов несколько на странице.

При первоначальном рендеринге страницы с 99% вероятностью мы будем упираться в лимит по событиям и можем какие-то события пропустить. Может быть не парится и в первой реализации не использовать лимиты?

**Comment by lossir** [comment]
Соглашусь, `unmount` тоже может пригодится. В любом случае, пока это "ожидаемые" возможности `__REACT_DEVTOOLS_GLOBAL_HOOK__`, наряду с отслеживанием `mount`/`update`.

Тогда можно оставить только одно правило - отправлять запрос каждые 5 секунд.

**Comment by zhzz** [comment]
> Голосовалка за название `TopicSource`

Еще как вариант:

| key | value |
| --- | --- |
| TopiсSource  | **`reactui`** |
| TopiсKey | **`telemetry`** |

**Comment by lossir** [comment]
@zhzz 
`TopiсSource` -  идентифицирует проект, команду. Предполагается, что правильно выбранный идентификатор не придётся "расширять". Поэтому вариант `reactui` не подходит.
`TopicKey` - это тип, тема события. Вариант `telemetry` кажется весьма подходящим.

Тогда, итоговый вариант может выглядеть так:

| key | value |
| --- | --- |
| TopiсSource  | **`infrontend`** / **`front_infra`** |
| TopiсKey | **`telemetry`** |
| Category | **`button`**/**`input`**/**`select`**/etc. |
| Action | **`mount`**/**`update`** |
| *Label* | **`reactui`** |
| *View* | Название команды (Свободная форма?) |

**Comment by zhzz** [comment]
`reactui` тоже вполне подходит под проект. Мне просто кажется, что остальные варианты мало кому о чем-то скажут. Но если это и не нужно, то ок.

**Comment by lossir** [comment]
@zhzz 
После дополнительных [пояснений от команды Метрики](https://app.slack.com/client/T02A9SVQ1/C53UMKYKD/thread/C53UMKYKD-1566461039.001200), можно представить source/key как **`Команда_Продукт`/`Ключ`** или **`Команда`/`Продукт_ключ`**.
Также, обсудив с @wKich, решили пока не сохранять имя команды/продукта, использующей контролы.

Получается следующее:

| key | value |
| --- | --- |
| TopiсSource  | **`front_infra`** |
| TopiсKey | **`reactui_telemetry`** |
| Category | **`button`**/**`input`**/**`select`**/etc. |
| Action | **`mount`**/**`update`**/**`unmount`** |

**Comment by dzekh** [comment]
Я перенес задачку в ютрек: https://yt.skbkontur.ru/issue/IF-82 если важна инфа из комментариев, перенесите плиз. @lossir @zhzz
