### ISSUE TITLE
[react-ui-validations] [input]  Поле в фокусе подсвечивается синей рамкой, а не красной

### ISSUE THREAD

**Issue by antonrychkov** [skbkontur/retail-ui#1569]
Судя по документации и [примерам](http://tech.skbkontur.ru/react-ui-validations/#/guides-example) поле с валидацией должно подсвечиваться красной рамкой даже когда поле находится в фокусе.
В плоской версии контролов поле со сработавшей валидацией подсвечивается синим цветом, когда находится в фокусе.

- retail-ui: 0.52.1, react-ui-validations: 0.9.1;

![изображение](https://user-images.githubusercontent.com/14177302/63403156-865b9c80-c3f7-11e9-8862-e8fdafdecbbf.png)

**Comment by zhzz** [comment]
Это до редактирования значения в поле? [По гайдам](https://guides.kontur.ru/principles/validation/#13), поле с валидацией и в фокусе подсвечивается красным только до редактирования, а после уже синим. В последней версии работает норм.
