### ISSUE TITLE
[Input] Нельзя использовать как uncontrolled component IF-623

### ISSUE THREAD

**Issue by nulladdict** [skbkontur/retail-ui#1570]
- Библиотека с витрины 1.1.2
- Последний ИЕ

При изменении defaultValue инпут в ИЕ начинает показывать placeholder и defaultValue одновременно.

![ie](https://user-images.githubusercontent.com/26379644/63491082-be361300-c4cf-11e9-8253-74831e5f0468.gif)

**Comment by wKich** [comment]
Ты хочешь использовать `Input` как `uncontrolled component`?

**Comment by nulladdict** [comment]
Да, всё верно

**Comment by wKich** [comment]
В таком случае проблема несколько шире нежели отображение плейсхолдера с defaultValue в ИЕ. Сейчас API Input'а не позволяет использовать его как `uncontrolled component`

**Comment by nulladdict** [comment]
У нас это не первый uncontrolled Input из библиотеки. Пока вроде ни с чем проблем не наблюдалось (но наши инпуты в таком случае очень простые, только текст и никаких других надстроек)

**Comment by wKich** [comment]
А значение как из него достаете? `ref.state.value`? Внутри он всё равно controlled

**Comment by nulladdict** [comment]
По `onChange` производим какие-то операции с новым значением, иногда с сохранением значения куда-нибудь

**Comment by wKich** [comment]
Ок, я понял

**Comment by dzekh** [comment]
Исправлено в #2777
