### ISSUE TITLE
[DatePicker]: DatePicker.validate учитывает maxDate по-умолчанию 2099

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1573]
Версия: 0.52.0

```javascript
<DatePicker
  value={state.value}
  onChange={handleChange}
  enableTodayLink
/>;
```

Выполнить на onChange `DatePicker.validate(state.value)`.
Метод будет возвращать false при вводе 01.01.9000, т.к. по-умолчанию ограничен 2099

**Comment by nextgennexia** [comment]
В версии 1.2.0 не изменилось. Все еще возвращается false на введеную вручную дату 01.01.9000

**Comment by wKich** [comment]
Раньше метод `validate` позволял указывать диапазон дат для валидации, но дело в том что лимиты, по которым тоже происходила валидация, были захардкожены значениями 1900-2099 и их невозможно было изменить извне. В PR были изменены лимиты на 0-9999, а для сохранения текущего поведения в качестве значений диапазонов теперь используются даты из `defaultProps`, чтобы валидировать даты в кастомных диапазонах, их необходимо указывать явно втором аргументов метода `validate`
