### ISSUE TITLE
[LocaleProvider] Ошибка в Safari 9 на iOS при изменении проперти name у функции

### ISSUE THREAD

**Issue by knevostruev** [skbkontur/retail-ui#1582]
Safari 9, iOS 9.3.5

В `LocaleProvider/decorators.tsx` 
на строчке 
`Object.defineProperty(LocaleDecorator, 'name', { value: constructor.name });` 
падает ошибка 
`TypeError: Attempting to change value of a readonly property.`

`Object.getOwnPropertyDescriptor(function test(){}, "name")` выдает 
`{value: "test", writable: false, enumerable: false, configurable: false}`

**Comment by wKich** [comment]
Хм... Похоже на проблему в safari. Максимум что удалось найти похожую ошибку, но в iOS 8 https://github.com/mozilla/pdf.js/issues/5353

По информации из wiki последняя версия iOS9 это 9.3.6. Я предлагаю попробовать обновить и посмотреть воспроизводится ли ошибка. Но вообще 9-я версия уже является устаревшей и не поддерживается компанией Apple, потому будет лучше обновится на одну из последних версий.

По статистике iOS 9 входит в 3% используемых девайсов https://developer.apple.com/support/app-store/, поэтому мы вряд ли будем фиксить специально для 9.3.5, учитывая ещё тот факт что у нас нет в наличии девайсов с такой версией на которых можно было бы проверить.
