### ISSUE TITLE
[TokenInput] Высота не согласуется с другими контролами

### ISSUE THREAD

**Issue by vedernikov-as** [skbkontur/retail-ui#1589]
react-ui: 1.1.2, 0.53   и видимо все другие
react: all
browsers: all

![image](https://user-images.githubusercontent.com/4751836/64153137-9cca1500-ce47-11e9-97fc-36fca7944f1e.png)

**Comment by vedernikov-as** [comment]
а в >0.53 будет фикс?

**Comment by lossir** [comment]
@vedernikov-as - Будет.
`LTS` мы релизим один раз в начале месяца. Как раз на грядущей неделе.
В [этой колонке](https://github.com/skbkontur/retail-ui/projects/2#column-5943035) можно посмотреть, что туда попадёт.
