### ISSUE TITLE
[DatePicker, Modal] Появляется полоса прокрутки в момент изменения даты, помещенной в попап

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1595]
Версия: 1.2.0

https://recordit.co/wshj48RLN0
Из изменений видно, что добавляется класс  HideBodyVerticalScroll-dom-{hash}
Появляется такой баг не на всякой странице, Видать все-таки что-то зависит от верстки.
Кажется это срабатывает, когда появляется скрол модалки https://recordit.co/pQYIXp6zFM
В то время, когда его нет, то все нормально https://recordit.co/fEo8na9fFv

**Comment by nextgennexia** [comment]
Хмм, в версии 1.5.0 не воспроизводится

**Comment by wKich** [comment]
Тогда можно закрыть :)
