### ISSUE TITLE
[Button] стрелки и фон с прозрачностью

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#1599]
Так как стрелки немного пересекаются с телом самой кнопки, то возникает наложение фонов и проблемы с прозрачностью.

![image](https://user-images.githubusercontent.com/4607770/64509068-63d2ea00-d2f8-11e9-85db-6b3f44454590.png)

Актуально для disabled состояния в темной теме и default + hover в плоской (невооруженным глазом не видно).

Нужно попробовать как-то избежать наложения.

**Comment by dzekh** [comment]
Мы на самом деле не поддерживаем пока темную тему.
