### ISSUE TITLE
[DatePicker] Не меняется цвет нижнего подчеркивания месяца 

### ISSUE THREAD

**Issue by Nevenq** [skbkontur/retail-ui#1605]
Переменная calendarMonthTitleBorderBottom не изменяет цвет нижней границы месяца, но меняет ширину и тип.
В темной теме по умолчанию подчеркивание вообще отсутствует, так как ширина задана 0px. 
![image](https://user-images.githubusercontent.com/38163651/64673128-bf32e280-d486-11e9-9420-8a7a991e2f60.png)
![image](https://user-images.githubusercontent.com/38163651/64673162-d7a2fd00-d486-11e9-8f9f-d7ae94aa52ca.png)

**Comment by dzekh** [comment]
Нужно убрать возможность менять тип и ширину, а возможность менять цвет нужно добавить.
