### ISSUE TITLE
[retail-ui] 1.1.2 -> 1.2.0 Ломаются стили у кнопок

### ISSUE THREAD

**Issue by AlexanderLevenskikh** [skbkontur/retail-ui#1622]
**Браузер**: Google Chrome Версия 76.0.3809.132 (Официальная сборка), (64 бит)/ IE11
**ОС**: Windows 10 Pro, Версия	10.0.18362 Сборка 18362

**Сценарий:**
При обновлении пакета @skbkontur/react-ui с версии 1.1.2 до следующей версии 1.2.0 ломаются стили у кнопок и некоторых других контролов.

**Примеры:**

- Стили кнопок:

![image](https://user-images.githubusercontent.com/15143813/64849110-1d4cfa80-d62c-11e9-93db-4160dcc0410e.png)

- Тень у SidePage:
![image](https://user-images.githubusercontent.com/15143813/64849227-5e450f00-d62c-11e9-815a-5f583db32e1f.png)

- Стили у Paging и Switcher:
![image](https://user-images.githubusercontent.com/15143813/64849291-83398200-d62c-11e9-9147-cc46db6fe3f7.png)

**Comment by zhzz** [comment]
А можешь еще заскриншотить стили, которые там на элементе button?

**Comment by AlexanderLevenskikh** [comment]
![image](https://user-images.githubusercontent.com/15143813/64861773-4086a280-d64a-11e9-91a3-a456c0ad9d04.png)

Заметил еще, что в production mode работает нормально (используется MiniCssExtractPlugin.loader)

**Comment by zhzz** [comment]
Да, воспроизводится с css-loader `3.0.0-3.1.0`. Нужно обновится до `3.2.0`.

**Comment by AlexanderLevenskikh** [comment]
3.0.0
спасибо!
