### ISSUE TITLE
[Gapped] Увеличение gap увеличивает высоту Gapped-контейнера

### ISSUE THREAD

**Issue by ilearnf** [skbkontur/retail-ui#1624]
Привет! Опиши, пожалуйста, проблему, которая возникла:
1. При увеличении числа в пропе gap увеличивается расстояние до верхнего элемента. Таким же образом увеличивается перекрытие верхних элементов, и на них не получается кликнуть.
2. Если gapped не vertical, то margin-top к элементам все равно добавляется.
3. margin добавляется даже к первому элементу содержимого контейнера.

- react-ui 1.3.0 (предыдущие также)
- Chrome 76.0.3809.132, Firefox 68.0.1, windows 10;
- 
1. увеличить gap
2 и 3. Просто использовать gapped.
- Прикрепи скриншот или гифку с примером;
![image](https://user-images.githubusercontent.com/11571410/64856702-162de880-d63c-11e9-8426-b99b305da2a0.png)
![image](https://user-images.githubusercontent.com/11571410/64856735-28a82200-d63c-11e9-8a24-ddc2bdd8b8fc.png)

**Comment by wKich** [comment]
Элементы, которые перекрываются отступом, создаваемым с помощью Gapped перестают быть кликабельными в случаях, когда Gapped располагается в выделенном Stack контексте, например при установке position отличным от static или isolation: isolate
