### ISSUE TITLE
Input, DatePickerOld. Криво вставляется дата

### ISSUE THREAD

**Issue by KozlovAlexanderS** [skbkontur/retail-ui#1635]
Привет! Опиши, пожалуйста, проблему, которая возникла:

- retail-ui 0,30.
- ie11, chrome 77.0.3865.90, win10;
- Если вставлять скопированную дату в уже заполненное поле, то она вставляется криво. Дата вставится правильно, если курсор будет расположен в первом отделении даты;
-https://www.screencast.com/t/wkmiF7vk;

**Comment by dzekh** [comment]
DatePickerOld — не поддерживаем, и в следющем году вообще из библиотеки удалим. Переходите на DatePicker. Если нужна помощь для перехода — поможем.
