### ISSUE TITLE
[Button] Прокидывать атрибуты до нативной кнопки, как в Input

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#1643]
Хотим использовать data-атрибуты, чтобы помечать контролы для браузерных тестов. В инпуте эти атрибуты прокидываются, в кнопке - нет. В идеале нужно чтобы у всех контролов это как-то работало. Можно завести специальный набор пропсов для этого.

**Comment by zhzz** [comment]
data-атрибуты прокидываются во все компоненты начиная с 2.14.0
