### ISSUE TITLE
[DarkTheme | Input] когда нажимаешь backspace сверкает белым

### ISSUE THREAD

**Issue by hukopo** [skbkontur/retail-ui#1646]
https://tech.skbkontur.ru/react-ui/#/Customization/ThemeProvider 
когда нажимаешь backspaceв пустом input на темной темме, blink остается белым
![123](https://user-images.githubusercontent.com/32922001/66023945-0bb09180-e50c-11e9-89f3-a6ab0be01f73.gif)

**Comment by zhzz** [comment]
Цвет `#cde4f8`. Он просто одинаковый для всех тем и настраивается переменной `blinkColor`. А какой цвет будет лучше?

**Comment by dzekh** [comment]
Можно использовать цвет 0088FF с прозрачностью 20% для белой и 40% для темной темы
либо сделать 40 для обеих тем
