### ISSUE TITLE
[retail-ui] экспортировать ThemeContext

### ISSUE THREAD

**Issue by vandal-x** [skbkontur/retail-ui#1656]
Привет!
Было бы удобно использовать для кастомизации своих компонентах не `ThemeProvider`, а hook `useContext`. Но для этого нужно экспортировать контекст из библиотеки напрямую.

**Comment by vandal-x** [comment]
Но есть небольшая проблема с типами из `create-react-context`. Они не совпадают с типами из `React`.

Я создал новый проект и попробовали использовать контекст из `create-react-context` через хук. Хук работает как ожидалось, но typescript выдал такую ошибку:
```
 Argument of type 'import("/tmp/my-app/node_modules/create-react-context/lib/index").Context<string>' is not assignable to parameter of type 'React.Context<string>'.
  Types of property 'Provider' are incompatible.
    Property '$$typeof' is missing in type 'ComponentClass<ProviderProps<string>, any>' but required in type 'ProviderExoticComponent<ProviderProps<string>>'.
```

Я бы предложил при экспорте контекста кастануть на него нужный тип, но мне кажется вы не одобрите это решение.

**Comment by zhzz** [comment]
Без `ThemeProvider` в контексте будет лежать только дефолтная тема. Кастомизировать придется самому через `ThemeFactory.create()`.

Для кастомизации своих компонентов мы экспортируем `ThemeConsumer`. Чем он не подходит?

**Comment by vandal-x** [comment]
Извните, немного перепутал компоненты: я говорил про `ThemeConsumer`.
Мне кажется `ThemeConsumer` немного неудобно пользоваться, в сравнении с хуком `useContext`. Для сравнения:

```tsx
return (
  <ThemeConsumer>
    {theme => <div className={style(theme)}>}
  </ThemeConumser>
)
```

против
```tsx
const theme => useContext(ThemeContext);

return <div className={style(theme)} />
```

**Comment by zhzz** [comment]
В таком случае, почему бы и нет.

И похоже что да, тайпинги `create-react-context` не очень актуальны.

Можно сделать PR с чем-то вроде такого:
```
export const ThemeContext = (React.createContext || createReactContext)(ThemeFactory.getDefaultTheme());
```
