### ISSUE TITLE
[Input]

### ISSUE THREAD

**Issue by IrinaSkb** [skbkontur/retail-ui#1657]
Привет! Опиши, пожалуйста, проблему, которая возникла:

- retail-ui 1.4.0;
- Google Chrome Версия 77.0.3865.90
- При наведении на инпут курсор меняет вид, но при выделении текста выделяется что-то другое, не тот текст который в инпуте

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41990507/66191426-bad5a000-e6a7-11e9-8135-7b258f6c0ac4.gif)

**Comment by dzekh** [comment]
Дубликат #1196

**Comment by dzekh** [comment]
в примере поле не получило фокус, если кликнуть справа от префикса — поле получает фокус и выделение работает нормально только в поле, не переходит на другой текст. Но тогда нельзя выделить префикс, и про это отдельный баг, на который я сослался выше.

**Comment by zhzz** [comment]
Я так понял, что тут вопрос про то, что курсор "текст" появляется не только непосредственно над текстом, а над всем инпутом целиком. Поэтому имеются зоны, где курсор есть, а текст не выделяется, например, в самом низу инпута.

**Comment by IrinaSkb** [comment]
Да, плохо что курсор "текст" появляется не в самом теге 
input, но раз курсор появился, я как пользователь ожидаю выделение текста внутри инпута (не тега, а формы), а я могу выделить чуть ли не весь текст на странице
 
Sent from 
Mail for Windows 10
 

From: Egor Pogadaev
Sent: 4 октября 2019 г. 13:43
To: skbkontur/retail-ui
Cc: Седова Ирина Евгеньевна; 
Author
Subject: Re: [skbkontur/retail-ui] [Input] (#1657)

 


Я так понял, что тут вопрос про то, что курсор "текст" появляется не только непосредственно над текстом, а над всем инпутом целиком. Поэтому имеются зоны, где курсор есть, а текст не выделяется, например, в самом низу инпута.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by wKich** [comment]
На самом деле это как раз дубль #1196. Префикс рисуется внутри `span` элемента вне нативного инпута.
