### ISSUE TITLE
DropdownContainer не учитывает margin при расчете высоты позиционирования

### ISSUE THREAD

**Issue by ivsware** [skbkontur/retail-ui#1664]
![combobox_pos](https://user-images.githubusercontent.com/14371276/66330770-b88a7480-e939-11e9-94fb-a5991a45db34.gif)

DropdownContainer не учитывает margin при расчете позиционирования
Начинать смотреть можно с этой строки: _https://github.com/skbkontur/retail-ui/blob/master/packages/retail-ui/components/DropdownContainer/DropdownContainer.tsx#L64_

**Библиотека: retail-ui 0.53.0**
**Браузеры: Chrome, Firefox, IE11**

**Сценарий врспроизведения на витрине:**
- перейти на компонент Combobox на витрине, добавить в последний комбобокс на странице 5-15 элементов
-  навесить на body страницы:  **position: relative**
- на первый div внутри body навесить: **margin-bottom: 50px**

**Comment by lossir** [comment]
@ivanshio Тест обязательно добавим.

**Comment by zhzz** [comment]
Из-за особенностей позиционирования DropdownContainer не удалось выработать решение, которое бы учло все возможные отступы и не сломало текущее поведение. 

Но, данная проблема должна решиться в скором времени заменой DropdownContainer на Popup  #913.

В процессе был создан тест 62e833b5f3c9, который можно будет заиспользовать с попапом.

**Comment by zhzz** [comment]
Пока закрою в пользу #913
