### ISSUE TITLE
[react-ui-validations][RadioGroup] не исчезает тултип

### ISSUE THREAD

**Issue by Lelchik** [skbkontur/retail-ui#1670]
- react-ui@1.3.1, react-ui-validations@1.0.3

Сценарий: есть обязательные радиокнопки. После сабмита формы выбираем один из вариантов. После этого кнопки перестают быть красными, но тултип не пропадает. 
Также при получении фокуса тултип опять показывается.
![Заказ №orders1 - Google Chrome 2019-10-08 18-32-25](https://user-images.githubusercontent.com/11275614/66400287-a290b880-e9fa-11e9-817f-1a20b3a2a36d.gif)

**Comment by dzekh** [comment]
Действительно, по гайдам должен скрываться: https://guides.kontur.ru/principles/validation/#22
