### ISSUE TITLE
[Tooltip] Перестал перепозиционироваться относительно свободного пространства

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1673]
Версия: 1.5.0 (моему началось с 1.3.1)
Браузер: хром 77.0.3865.90

Такое ощущение, что он не перерендеривается, потому что если изначально не влез, то меняет положение, а потом если появилось пространство, то все равно рендерится там где первый раз.

https://recordit.co/qsO4E1ABdE

**Comment by zhzz** [comment]
Да, в 1.3.1 изменилось, возможно после [cb6772](https://github.com/skbkontur/retail-ui/pull/1632/files#diff-cb6772a06e5224f48535ac40112bd489L204-L206).  @wKich
