### ISSUE TITLE
[Button] Возможность сделать квадратную кнопку только с иконкой внутри

### ISSUE THREAD

**Issue by sergeyshmakov** [skbkontur/retail-ui#1675]
В проекте встала необходимость сделать квадратную кнопку, в которой была бы только иконка, без всякого текста. Пришлось навесить доп. стили, чтобы реализовать, казалось бы простую функциональность.

Проверял пример на свежей версии [тут](https://tech.skbkontur.ru/react-ui/#/Components/Button)

```javascript
const OkIcon = require('@skbkontur/react-icons/Ok').default;
<Button width={34}>
    <span style={{marginLeft: -5}}><OkIcon /></span>
</Button>;
```

Хотелось бы иметь возможность вствлять только иконку и сразу получать равные отступы побокам, чтобы кнопка была квадратной.

В примере указана ширина `width={34}`, поскольку видимая высота кнопки вместе с `padding`-ами равна 34.

**Comment by zhzz** [comment]
Кастомизация позволяет настроить паддинги:
```
<ThemeProvider value={{ btnPaddingXSmall: '9px' }}>
  <Button><Ok/></Button>
</ThemeProvider>
```
https://codesandbox.io/s/zealous-sea-lonom

**Comment by wKich** [comment]
> ...казалось бы простую функциональность.

Мы будем рады, если ты или тестировщики из твоей команды накинут набор сценариев использования контролов очевидных для вас, но про которые ни мы, ни проектировщики, к сожалению, не подумали.

**Comment by sergeyshmakov** [comment]
@zhzz 
* Этот вариант мало чем лучше того, что я описал, хотелось бы получить более легкое использование
* `ThemeProvider` доступен в новой версии, на которую мы еще не успели перейти в этом проекте из-за недавно обнаруженного бага - полной неработоспособности `DateInput` в Edge с мая месяца. Да, мы его пофиксили и PR был принят, но перейти еще не успели.

**Comment by sergeyshmakov** [comment]
@wKich Возможно, однажды, если таких моментов будет много. Если интересно - нам нужна была квадратная кнопка с иконкой прямо слева от инпута, при нажатии на нее открывается лайтбокс.

**Comment by zhzz** [comment]
Есть еще такой вариант:
```
<Button width={34} narrow>
  <Ok />
</Button>
```

**Comment by sergeyshmakov** [comment]
@zhzz Выглядит неплохо, спасибо, попробуем
