### ISSUE TITLE
[Tooltip] В safari нет теней и они сливаются с фоном страницы

### ISSUE THREAD

**Issue by MikhailKornilov** [skbkontur/retail-ui#1677]
- Библиотека retail-ui 0.52.1;
- Браузер: safari 13.1.2;
- Сценарий:
    1. Нажимаем на значок вопросительного знака.
     У появляющегося тултипа отсутствуют тени по краям из-за чего сливается с фоном страницы.
- Скриншот: http://prntscr.com/pjip1f ;

**Comment by wKich** [comment]
Привет. Есть такая беда в safari, не только на iPad. А можешь подсказать, вы у себя в команде как на mac os / ios тестите? Ручками или есть какая-то автоматизация?

**Comment by MikhailKornilov** [comment]
> Привет. Есть такая беда в safari, не только на iPad. А можешь подсказать, вы у себя в команде как на mac os / ios тестите? Ручками или есть какая-то автоматизация?

руками тестируем.

**Comment by ahaodas** [comment]
такая же беда и в 1.6.2 + Safari 13.0.2
еще наблюдаются баги с триггером по ховеру: при уходе ховера тултип остаётся, а текст внутри становится невидимым
![image](https://user-images.githubusercontent.com/13942198/68599835-23901380-04c3-11ea-8b57-fb67c9fff76a.png)
