### ISSUE TITLE
Если в поле можно вводить только цифры, может выводить цифирную клавиатуру

### ISSUE THREAD

**Issue by MikhailKornilov** [skbkontur/retail-ui#1678]
- Библиотека retail-ui  0.52.1;
- Браузер,safari 13.1.2, Chrome 77.0.3865.103. ios;
- Если в поле можно вводить только цифры, можем ли мы выводить клавиатуру с цифрами (как при вводе номера)? Сейчас выводится клавиатура с буквами.
- Скриншот: http://prntscr.com/pjista;

**Comment by nulladdict** [comment]
`<Input />` прокидывает аттрибуты, на ios (новой) к цифровой клавиатуре приводит набор из таких аттрибутов: `inputMode="numeric" pattern="[0-9]*"`, на ios (cтарой) это приведет к переключению клавиатуры на вкладку с цифрами.
Такое же поведение если явно сказать `<input type="number"`

**Comment by Na1ve** [comment]
Для дробных `inputMode="decimal"`

**Comment by zhzz** [comment]
Дубликат #675

**Comment by wKich** [comment]
@nulladdict, может в доку добавить примеров? :)

**Comment by Na1ve** [comment]
> @nulladdict, может в доку добавить примеров? :)

мне кажется это стоит сделать дефолтным поведением для CurrencyInput
