### ISSUE TITLE
[MenuItem] Ломается ховер при использовании фрагментов

### ISSUE THREAD

**Issue by halfee** [skbkontur/retail-ui#1680]
- react-ui@1.5.0

В Dropdown, DropdownMenu и остальных компонентах, которые работают с MenuItem, ломается ховер на элементе списка при использовании фрагментов.

Пример кода для [tech.skbkontur.ru](https://tech.skbkontur.ru/react-ui/#/Components/Dropdown)
```
<Dropdown caption="Click">
  <MenuItem>Hover</MenuItem>
  <MenuSeparator />
  <MenuHeader>Here goes the header</MenuHeader>
  <MenuItem>Hover</MenuItem>
  <>
    <MenuItem>No hover</MenuItem>
    <MenuItem>No hover</MenuItem>
  </>
</Dropdown>
```

**Comment by zhzz** [comment]
Привет! 
Вместо фрагмента сейчас можно использовать массив MenuItem'ов. И интересно было бы узнать ваш конкретный сценарий.

**Comment by halfee** [comment]
Про массив не догадался, настолько синтаксис фрагментов стал привычен. Буду использовать их.
Сценарий был довольно тривиален, например, в зависимости от фазы луны или другого условия нужно скрывать часть пунктов меню:

```
<Dropdown caption="Click">
  <MenuItem>Hover</MenuItem>
  <MenuSeparator />
  <MenuHeader>Here goes the header</MenuHeader>
  <MenuItem>Hover</MenuItem>
  {moonInAries && <>
    <MenuItem>No hover</MenuItem>
    <MenuItem>No hover</MenuItem>
  </>}
</Dropdown>;
```

**Comment by wKich** [comment]
Тогда закрываю ишью. Мы не будем рекурсивно ходить по детям, чтобы найти все `MenuItem`.
