### ISSUE TITLE
[Tooltip] При оборачивании Combobox и trigger="hover&focus" тултип не исчезает при потере фокуса

### ISSUE THREAD

**Issue by sorovlad** [skbkontur/retail-ui#1685]
Воспроизводится, если не изменять значение или выбрать из выпадашки.
На витрине воспроизводится в Firefox и ie11.
В chrome появляется если выбрать из выпадашки.

**Comment by wKich** [comment]
А `hover` при этом остается или нет?

**Comment by sorovlad** [comment]
1) Наводим на комбокс
2) Появляется тултип
3) Кликаем в комбобокс
4) Кликаем снаружи
5) Тултип остается открытым

1) Наводим на комбокс
2) Появляется тултип
3) Кликаем в комбобокс
4) Выбираем значение в выпадашке
5) Значение попадает в комбобокс, а тултип остается
6) Кликаем снаружу, расфокусируется. Тултип остается

Тултип модифицировал в разделе "С подсветкой результата поиска:" на странице комбобокса

**Comment by lossir** [comment]
@sorovlad Можешь проверить ещё раз?
Не могу воспроизвести в FF. Если я всё правильно делаю, то есть вероятность, что в этом ПРе #1891 было исправлено.

**Comment by sorovlad** [comment]
Сейчас корректно работает, вы молодцы:fire:

Если придираться, то при выборе тултип прыгает.
![React UI - Mozilla Firefox 2020-08-13 18-51-46](https://user-images.githubusercontent.com/14935625/90142855-53dc4980-dd96-11ea-94f3-351dd3bfd7af.gif)

**Comment by lossir** [comment]
@sorovlad Придраться можешь, но в новом ишью =) Этот закрываю
