### ISSUE TITLE
У Fias контрола нет en_GB локализации. (react-ui 1.5.0)

### ISSUE THREAD

**Issue by artmon** [skbkontur/retail-ui#1686]
![image](https://user-images.githubusercontent.com/5512957/67397576-e4903180-f598-11e9-93db-3f1bb1211771.png)

**Comment by lossir** [comment]
Есть такое. Решили, что необходимость иметь английскую локализацию *крайне мала*, т.к. база российская.
Но через механизм локализации сейчас реализуется и простая кастомизация текста в интерфейсе, которая ранее уже была сделана.
Есть реальная необходимость в английской версии?

**Comment by artmon** [comment]
Мы в Контур.Отеле используем этот компонент. Возможна такая ситуация - гостиница российская, но вдруг пользуется английским интерфейсом и тогда было бы хорошо иметь полностью английский компонент. Для иностранных гостиниц мы показываем компонент, как просто поле адреса - 
![image](https://user-images.githubusercontent.com/5512957/67402087-9599ca80-f59f-11e9-83cb-ef08d593800c.png)

**Comment by lossir** [comment]
Пока можете самостоятельно кастомизировать необходимый текст.
Вот необходимый набор переменных для кастомизации примера выше:
```ts
const customLocaleEN = {
   Fias: {
     modalTitle: 'modalTitle',
     modalButtonOk: 'modalButtonOk',
     modalButtonCancel: 'modalButtonCancel',
     addressFill: 'addressFill',
     foreignAddressLabel: 'foreignAddressLabel',
   },
}
```

**Comment by artmon** [comment]
Ок, попробую, спасибо.
