### ISSUE TITLE
ИЕ11. Внутри MenuItem не работают ссылки и title

### ISSUE THREAD

**Issue by Ame-N** [skbkontur/retail-ui#1689]
Воспроизводится на витрине компонентов.
ИЕ11.

У элементов в MenuItem есть ссылка (`<a>`) или атрибут `title`. Примерно так:
```
<div>
  <span title="some long text">Some text.</span>
  <a href="some.link.com">Some link</a>
</div>
```
В ИЕ11 при наведении не всплывает тайтл, и при нажатии на ссылку ничего не происходит.
В Хроме и FF все норм.

Конкретные сценарии, которые ломаются.
В комбобоксе в списке значений могут быть длинные значения, которые мы сокращаем до нужного количества символов, а в `title` указываем полный текст.
Если ничего не найдено, то передаем (в `renderNotFound`) некоторый текст-пояснение, где есть ссылка, по которой пользователь может решить свою проблему.

**Comment by dzekh** [comment]
Можно реализовать, но немного по другому, через проп renderItem, если будут вопросы — пишите.
