### ISSUE TITLE
[Button] css-modules ломают анимацию

### ISSUE THREAD

**Issue by halfee** [skbkontur/retail-ui#1690]
- retail-ui@1.5.0

Сценарий:
- Создаем проект с помощью [create-react-app](https://github.com/facebook/create-react-app)
- Добавляем кнопку с состоянием `loading`
```
<Button loading>Button</Button>;
```

Состояние загрузки рисуется без анимации.

**Comment by rustho** [comment]
@halfee На данный момент это можно пофиксить, если в webpack.config.js  create-react-app поменять правило `modules:true` на `modules: 'global'`
``` js
{
  test: cssModuleRegex, 
  use: getStyleLoaders({
    importLoaders: 1,
    sourceMap: isEnvProduction && shouldUseSourceMap,
    modules: true, // -> modules:'global'
    getLocalIdent: getCSSModuleLocalIdent,
  }),
},
