### ISSUE TITLE
[Loader] Отступы у лоадера не совпадают с отступами у ссылки с иконкой

### ISSUE THREAD

**Issue by polecat89** [skbkontur/retail-ui#1704]
Сейчас текст у ссылки прыгает, когда иконка заменяется на спиннер
https://guides.kontur.ru/components/hyperlink/#25

**Comment by dzekh** [comment]
Дежурному проверить.

**Comment by zhzz** [comment]
В 2.0 [пофиксили](https://codesandbox.io/s/stupefied-violet-kwuu3?file=/src/index.js). Стоит ли править в LTS?

**Comment by dzekh** [comment]
не, не стоит.

**Comment by zhzz** [comment]
Тогда закрываем
