### ISSUE TITLE
[Hint] Смещение хинта в Chrome и FF

### ISSUE THREAD

**Issue by pikhnova** [skbkontur/retail-ui#171]
В документации в зависимости от браузера разное расположение хинта:
В Chrome и FF хинт смещен влево.
![23](https://cloud.githubusercontent.com/assets/25151439/24957708/0564cd56-1fa6-11e7-9c2e-4e38c4d5116c.png)

В IE 9/11 хинт отцентрирован как нужно:
![55](https://cloud.githubusercontent.com/assets/25151439/24957673/e04b41c6-1fa5-11e7-97a7-46f64cf926ad.png)

**Comment by nanot1m** [comment]
полечили
