### ISSUE TITLE
[DropdownMenu] Добавить свойство showPin

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1710]
`DropdownMenu` и `TooltipMenu` дублируют друг друга и отличаются лишь наличием пина. Имеет смысл пометить `TooltipMenu` как устаревший компонент и добавить свойство `showPin` в `DropdownMenu`

**Comment by rustho** [comment]
Задепрекейтить в 3.0.0 и удалить в 4.0.0
