### ISSUE TITLE
Autocomplete ненужный span

### ISSUE THREAD

**Issue by vedernikov-as** [skbkontur/retail-ui#1713]
Тег label зачем-то завернут в span с inline-block. Поэтому width="100%" для Autocomplete, не работает

- react-ui 0.53.4
- Chrome, но вероятно все

![image](https://user-images.githubusercontent.com/4751836/68091152-01ccd600-fe9e-11e9-8cee-612f63636513.png)

**Comment by dzekh** [comment]
Нужно разобраться баг или нет.

**Comment by sergeyshmakov** [comment]
Столкнулись с этим тоже, будем костылить чтобы обойти. Версия `1.11.2`
