### ISSUE TITLE
[Modal] Тень на футере

### ISSUE THREAD

**Issue by Soheevich** [skbkontur/retail-ui#1717]
- retail-ui, версия 1.5.0
- Хром Версия 77.0.3865.120 (Официальная сборка), (64 бит), ОС Windows 10
- У модалки есть Footer с panel, высота окна меньше высоты модалки. Поэтому у хэдера и у футера появляется тень. Но если у футера есть panel, то тень делает размытой границу самого футера

![modalShadowBug](https://user-images.githubusercontent.com/32847359/68199390-c63a2500-ffdf-11e9-8d4f-7881f7085c96.jpg)

**Comment by dzekh** [comment]
Чтоб получилась нормальная тень в хроме помогает исправить в стиле элемента :before height: 1px; на height: 2px;

Нужно исправить тень: 
- [ ] у нижней залипающей плашки 
- [ ] у верхней залипающей плашки
- [ ] исправить цвет нижней серой плашки с rgb(233, 233, 233); на rgb(229, 229, 229);
- [ ] проверить все эти параметры в сайдпейдже. 


Тень должна в результате получиться такая: 
<img width="742" alt="Modal" src="https://user-images.githubusercontent.com/26383080/85004052-85f37580-b170-11ea-9607-4579a97b3bbe.png">

- [ ] Нужно проверить в остальных браузерах как будет отображаться и работать такое изменение.

**Comment by dzekh** [comment]
Та тень которая на скрине выше слишком темная получается если залипшая панель белая. 
Давайте сделаем как [сейчас тут в Фигме](https://www.figma.com/file/On4a4hXijhkMe3ym368LIR/%E2%9A%A1%EF%B8%8F-Kontur-UI-8px-Flat?node-id=4520%3A165)

Там такие параметры:

![image](https://user-images.githubusercontent.com/26383080/121681070-c2cc2100-cad3-11eb-8b77-0c2abc67afcd.png)

А выглядит она так:

![image](https://user-images.githubusercontent.com/26383080/121681119-d5def100-cad3-11eb-9883-47d9570b2d10.png)

Но, скорее всего если оставлять ту же верстку с элементом `:before` в один пиксель нужно будет подобрать другие параметры. Потому что там тень как-то совсем по другому рисуется.
