### ISSUE TITLE
[Toggle] Добавить проп children

### ISSUE THREAD

**Issue by slawwan** [skbkontur/retail-ui#1723]
В компонент CheckBox можно передать children - они будут отбражаться как label, по которму можно кликнуть и переключить чекбокс.

В Toggle никак label передать нельзя.

Предлагаю добавить возможность задавать label в children как у CheckBox.

если предложение годное, можно будет и пулреквест запилить

**Comment by nanot1m** [comment]
Накину еще вариантов
```jsx
<Toggle checked={toggleIsChecked}>
  {toggleIsChecked ? 'On' : 'Off'}
</Toggle>
```

```jsx
<Toggle>
  {toggleIsOn => toggleIsOn ? 'On' : 'Off'}
</Toggle>
```

**Comment by wKich** [comment]
@nanot1m, и как ты во-втором варианте начальное значение задашь?

**Comment by nanot1m** [comment]
Например также как и в случае с  `<input type="checkbox" />`
```jsx
<Toggle defaultChecked={true}>
  {toggleIsOn => toggleIsOn ? 'On' : 'Off'}
</Toggle>
```

**Comment by slawwan** [comment]
предлагаю как минималочку хотябы запилить возможность засунуть label в children, чтобы подпись отрисовалась справа с нужным отступом и возможно имеет смысл сделать чтобы по клику на нее происходил onChange как при клике на сам Toggle

**Comment by rustho** [comment]
Судя по гайдам, в таком случае еще нужен проп с какой стороны отрисовать этот чилдрен

**Comment by dzekh** [comment]
Давайте сделаем уже, мелочь вроде.
