### ISSUE TITLE
[Topbar.User]Mеню юзера в топ баре

### ISSUE THREAD

**Issue by komap54** [skbkontur/retail-ui#1726]
В выпадающем меню юзера заголовок так и должен быть по центру ? 
В гайдах вроде бы по левому краю
![image](https://user-images.githubusercontent.com/31661288/68575691-2d078480-049f-11ea-8209-b94cfc9c4d6c.png)

**Comment by dzekh** [comment]
Нет, должен быть слева

**Comment by dzekh** [comment]
Обсудили выпадаху голосом, решили что заголовок тут особо не нужен, так как всего один блок ссылок. Можно переименовать «Настройки входа в сервисы» в «Личный кабинет Контура», а заголовок убрать.
