### ISSUE TITLE
[Loader] Научится рисовать в портале

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1731]
По итогам обсуждения в #1724 было выявлено, что любая выпадашка, которая выступает за границу модалки, при активации лоадера скрываясь за модалкой остается видимой под модалкой. Было бы не так топорно, если бы выпадашка оставалась между модалкой и лоадером. Но без вынесения `Loader` в портал из-за особенностей работы контекстов наложения нельзя отрисовать элемент из другого портала между элементами первого.

**Comment by zhzz** [comment]
Без лоадера в портале, любые попытки поместить выпадашку между активным лоадером и модалкой, в которой они могут находиться - тщетны. Попап оказывается над шторкой лоадера.

![image](https://user-images.githubusercontent.com/4607770/68939813-5425c500-07c3-11ea-9984-2e61daac556b.png)

**Comment by zhzz** [comment]
Если вернуться к варианту с закрытием выпадашек под активным лоадером, то можно обойтись установкой/снятием `display: none` на RenderContainer по флагу в контексте. Мне кажется тоже норм вариант. Модалки/SidePage можно оставлять.

**Comment by wKich** [comment]
Есть альтернативный вариант решения, в котором мы сможем реализовать позиционирование выпадах между модалкой и лоадером.

Для этого надо будет перенести логику с ZIndex в компонент RenderContainer, а так же научиться отрисовывать вложенные порталы не в body, а в родительский портал. Тем самым контекст наложения будет создаваться в портал контейнере и выпадаха будет находиться внутри этого контекста.
