### ISSUE TITLE
[retail-ui][Customization] Доработки кастомизации для перехода на 8px сетку

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#1733]
В новой [библиотеке в Фигме](https://www.figma.com/file/4vh3dHXmD8Ae4IGfIIApbC/%E2%9A%A1%EF%B8%8F-Kontur-UI-8px?node-id=0%3A1&viewport=-817%2C-33%2C0.5072223544120789) изменились размеры компонентов, и появились новые размеры у радиокнопок, чекбоксов, тоглов, выпадающих меню и табов и др. Все изменения размеров должны быть сделаны через кастомизацию, для этого нужно доработать список переменных и связи между ними. 

[В этом файле](https://www.figma.com/file/HXJFs6glLNxfoTburQbgP3/React-UI-Theming?node-id=0%3A1) есть описание всех переменных размеров, как реализовано сейчас и как нужно реализовать зависимости. 

Этапы в порядке приоритетов, которые нужно реализовать в версии 2.4 — 3.0:

## Добавить в компоненты новые переменные и их зависимости

Первый этап — основные компоненты находящиеся непосредственно на слое страницы: поля, кнопки, радиокнопки, чекбоксы и прочие.

- [x] Добавить общие переменные
- [x] Добавить новые переменные в компоненты
- [x] Создать новую тему с новыми значениями и связями с общими переменные

Второй этап — компоненты, которые появляются новым слоем и не влияют на компоновку страницы. Это выпадающие меню, тултипы, хинты, модалка, сайдпейдж и прочие, сделанные на их основе.

- [x] Дописать [ТЗ в Фигме](https://www.figma.com/file/HXJFs6glLNxfoTburQbgP3/React-UI-Theming?node-id=0%3A1)
- [x] Добавить новые переменные в компоненты

## Поменять иконки

[Поменять иконки](https://www.figma.com/file/HXJFs6glLNxfoTburQbgP3/React-UI-Theming?node-id=289%3A770) во всех компонентах обозначающие выпадающие списки

<img width="273" alt="Group 61" src="https://user-images.githubusercontent.com/26383080/83732757-f3c67a00-a665-11ea-807d-b7dfc4ace216.png">

- [x] Кнопка-меню
- [x] Селект (раскрывающийся список)
- [x] Инпут (автокомплит, комбобокс)

## Проблемы, которые нужно решить параллельно

- [x] [~~Смещение базовой линии~~](https://www.figma.com/file/HXJFs6glLNxfoTburQbgP3/React-UI-Theming?node-id=163%3A496) ~~во всех компонентах, функция shiftUp.~~ Неактуально для Segoe, базовая линия Lab будет изучаться позже
- [x] [Кликабельные области иконок](https://www.figma.com/file/HXJFs6glLNxfoTburQbgP3/React-UI-Theming?node-id=163%3A545)
- [x] Плейсхолдеры смещаются относительно текста в полях при изменении размера шрифта переменными fontSizeLarge, fontSizeMedium и fontSizeSmall
- [x] Текст не всех типов кнопок или состояний кнопок зависит от переменных fontSizeLarge, fontSizeMedium и fontSizeSmall — не меняются кнопки-стрелки и кнопка в состоянии загрузки
- [x] size="large" и "medium" ломает FxInput — меняется только инпут. [PR](https://github.com/skbkontur/retail-ui/pull/2373)

**Comment by lossir** [comment]
Ещё `size` нет у `Paging` и `Link`

**Comment by dzekh** [comment]
> Ещё `size` нет у `Paging` и `Link`

по задумке линк должен зависеть от основного текста, а пэйджингу не нужно нескольких размеров.

**Comment by dzekh** [comment]
#1840

**Comment by dzekh** [comment]
#1849

**Comment by dzekh** [comment]
#1849

**Comment by dzekh** [comment]
#1875

**Comment by dzekh** [comment]
@StathamJason тут есть еще несколько прилинкованных тасков в комментариях  )

**Comment by dzekh** [comment]
Всё прочекал, всё сделано, закрываю!
