### ISSUE TITLE
[Switcher] Добавить свойство loading

### ISSUE THREAD

**Issue by denexapp** [skbkontur/retail-ui#1741]
Хочется иметь свойство loading у Switcher. 

Сценарий: при нажатии на Switcher пользователь переключает свойство объекта. При переключении выполняется сетевой запрос, хочется на это время отображать состояние загрузки на свитчере без отрисовки дополнительного лоадера.

**Comment by lossir** [comment]
@dzekh что скажешь?

**Comment by dzekh** [comment]
@denexapp а у вас есть вариант как это может выглядеть? Использовать то же состояние что есть сейчас кнопке — с бегущими косыми полосками?

**Comment by wKich** [comment]
@denexapp, какое API хочешь чтобы было у `Switcher`? Устроить если в `items` будешь передавать объекты со нужными свойствами `loading/disabled`? Типа такого:

```jsx
<Switcher
  items={[
    { label: 'foo', value: '0', loading: true },
    { label: 'bar', value: '1', disabled: true },
    { label: 'baz', value: '2', use: 'primary' },
  ]}
/>
```

**Comment by denexapp** [comment]
Для меня это будет даже слишком широкое апи, мне хватит пропсов loading/disabled у самого контрола. Но и такой вариант вполне подойдёт

**Comment by dzekh** [comment]
Мне тоже кажется что такое API излишне. use: 'primary' отдельным кнопкам точно не нужны. disabled — возможны. loading кажется должен на весь компонент работать.

**Comment by dzekh** [comment]
![Switcher](https://user-images.githubusercontent.com/26383080/69153616-55772a80-0b00-11ea-8e36-dba3d72f3412.png)
Типа того?

**Comment by lossir** [comment]
И для выделенного надо

![image](https://user-images.githubusercontent.com/2708211/69154256-7ab86880-0b01-11ea-938b-0cb9de345fb8.png)

**Comment by dzekh** [comment]
<img width="229" alt="Switcher2" src="https://user-images.githubusercontent.com/26383080/69155131-fa930280-0b02-11ea-8587-6cfc341db310.png">
типа того? 

Вроде бы да, но у нас все кнопки в состоянии лоадинга одинаково отображаются, даже active — как заблокированные с бегущими полосками.

**Comment by lossir** [comment]
ну ок, тогда совсем изи, кнопка уже всё это имеет.

**Comment by wKich** [comment]
Подозреваю что полоски будут рисоваться иначе. Границы не будут совпадать

**Comment by dzekh** [comment]
Мы тут еще с дизайнерами пока обсуждаем, законно ли это вообще в принципе. 
@denexapp а можешь кинуть кусок интерфейса целиком, где такое поведение нужно.

**Comment by denexapp** [comment]
@dzekh упс, проглядел уведомление

Вот кусок интерфейса, где нужен loading для свитчера. Это страница в админке, основной сценарий -- проверить много оценок и для каждой выбрать один из трёх статусов "Правильно", "Допустимо" или "Неправильно"

![image](https://user-images.githubusercontent.com/3131467/69836799-2170d780-126d-11ea-8819-efe33b5901d0.png)

**Comment by dzekh** [comment]
Еще актуально? Как-то решили в проекте? 

Могу пока предложить пару вариантов, как решить:
1) Выбирать и дизеблить свитчер до момента получения ответа от сервера. Как получили ответ — разблокировали показываем уже актуальное состояние. 
2) Можно использовать принцип «оптимистичного интерфейса», если не критично — выбираем сразу нажатый пункт, если вернулась ошибка развыбираем.

Мы если и будем реализовывать лоадинг на свитче, то не скоро.

**Comment by denexapp** [comment]
> Еще актуально? Как-то решили в проекте?

Я добавил лоадер рядом со свитчером, и стал блокировать контрол на время запроса. Получается, для моего проекта сейчас не актуально

**Comment by wKich** [comment]
Предлагаю закрыть, так как сценарий довольно специфичный и есть несколько вариантов как это можно реализовать по другому. @dzekh
