### ISSUE TITLE
[Hint] Не успевает исчезнуть

### ISSUE THREAD

**Issue by pravosud** [skbkontur/retail-ui#175]
Если по соседству с элементом, который открывает хинт есть еще такие же элементы, то при потере фокуса старый хинт не успевает исчезнуть

![icon](https://cloud.githubusercontent.com/assets/5364762/25133930/9c462ab0-2467-11e7-9df1-e1dca0ccb9c3.gif)

**Comment by nanot1m** [comment]
Fixed
