### ISSUE TITLE
[react-ui] Переименовать флаг enableReactTesting

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1755]
В контролах при установке флага `process.env.enableReactTesting` отключаются анимации. Пока флаг используется только для внутренних скриншотных тестов. Надо переименовать его во что-то более очевидное или вместо него использовать `NODE_ENV == 'testing'`. Так же описать этот момент в документации.

**Comment by rustho** [comment]
а, дак вот оно для чего...
так может enableAnimations?

**Comment by lossir** [comment]
он же ещё курсор мыши отключает, вроде.
