### ISSUE TITLE
Реорганизовать структуру компонентов react-ui

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1772]
В директории `packages/retail-ui/components` творится полный бардак, нет никакой систематизации чтобы понять какие компоненты публичные и их можно использовать, какие приватные и их API может меняться в любой момент.

Есть негласное соглашение, которое говорит, что компоненты для которых не генерируется документация являются приватными, но в данный момент для некоторых явно публичных компонентов это правило не соблюдается (PasswordInput, Modal.{Header,Body,Footer}, etc)

Необходимо перенести явно внутренние компоненты, используемые в нескольких компонентах, в директорию internal, остальные поместить в директорию рядом с компонентом, который непосредственно их использует, например:

```
root
├── components
│   ├── ...
│   ├── ComboBox
│   │   ├── ...
│   │   └── ComboBox
│   ├── DatePicker
│   │   ├── ...
│   │   └── Picker
├── internal
│   ├── ...
│   ├── CustomComboBox
│   └── ZIndex
└──lib
    └── ...
```

Публичные импорты будут в виде:
```js
import {Button} from '@skbkontur/react-ui'
import {RenderLayer} from '@skbkontur/react-ui/internal'
import {layoutEvents} from '@skbkontur/react-ui/lib'
```

**Comment by rustho** [comment]
![image](https://user-images.githubusercontent.com/26579566/71079311-db909a80-21ac-11ea-8b37-f92c88c96c22.png)

**Comment by dzekh** [comment]
кажется что связано #1028
