### ISSUE TITLE
[Datepicker] Не сбрасывается на ближайшее валидное значение

### ISSUE THREAD

**Issue by sergeyshmakov** [skbkontur/retail-ui#1775]
Смотрю на https://tech.skbkontur.ru/react-ui/#/Components/DatePicker

* Выбираем любую дату ноября
* Кликаем на день в инпуте
* Вводим 31, уходим с инпута

Фактическое поведение - дата 31 ноября остается
Ожидаемое поведение - дата сбрасывается на последний день месяца 30 ноября

Кажется можно рулить это на уровне календаря. не пилить же нам валидацию на такое ))
Равносильно можно отнести и к `DateInput`

![image](https://user-images.githubusercontent.com/7429684/69885317-5f6a0c00-12fe-11ea-8e4c-aafd3483a2ac.png)

**Comment by wKich** [comment]
@sergeyshmakov, а если мы добавим в `DatePicker/DateInput` проп `onUnexpectedInput`, куда будет прилетать значение и результат валидации? А ты подписавшись на него можешь делать что хочешь, оставить `31.11.2019` и подсветить красным или сбросить на 30-е ноября или 1-е декабря.

**Comment by sergeyshmakov** [comment]
@wKich Не говорю, что хочу прям этот вариант. Просто кажется это относится к логике с полем даты и должно быть там инкапсулировано. Кому понадобиться вводить даты типа `56.11.2019`. Возможно, сперва стоит понять с точки зрения гайдов как реагировать на это. 

На ум приходит два варианта:
1. Давать вводить что угодно, сбрасывать при блюре
2. Не давать вводить цифру, если ее ввод приведет к невалидной дате

Первый вариант кажется слегка устаревшим. Второй более продвинутым. Но тут хорошо бы услышать мнение @dzekh

**Comment by wKich** [comment]
Тут дело не в том что кому-то хочется вводить невалидные даты, а в том что пользователь не увидит ошибки и не заметит, что поле ввода само решило какую дату подставить.

2-й вариант плох тем, что ухудшается UX, если ты хочешь исправить дату с 30.11.2019 на 31.12.2019, тебе сначала нужно исправить месяц, а только потом ты сможешь ввести число 31.

**Comment by sergeyshmakov** [comment]
@wKich  Об этом я не подумал ))) Тогда да, лучше как то подсвечивать, если что-то пошло не так. Другое дело, надо ли это во внешний интерфейс выводить, если и так понятно, что надо подсвечивать.

Наверняка не все люди, кто будет юзать в командах поставят обработчик на этот кейс. А если это будет "в коробке", то никому не придется парится ))

**Comment by lossir** [comment]
Для проверки даты есть статический метод `DatePicker.validate()`. Его можно использовать как с пакетом валидациий, так и самостоятельно.
Мы не можем вшить логику подсвечивания в контрол, т.к. за это уже отвечает отдельный пакет.

**Comment by sergeyshmakov** [comment]
@lossir Последний вопрос - этот метод учитывает локализацию?

**Comment by lossir** [comment]
@sergeyshmakov Локализация влияет исключительно на отображение в контроле. Формат `value`,`minDate` и `maxDate` всегда один - `дд.мм.гггг`(формат исторически сложился). Поэтому валидации ничего не надо знать о локализации.

**Comment by sergeyshmakov** [comment]
@lossir Понял, спасибо за ответы!
