### ISSUE TITLE
react-sorge

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#1778]
Репа - https://github.com/skbkontur/react-sorge
- [x] Трансляция пропов в `html`-атрибуты:
  - [x] Реализовать механизм транляции
  - [x] Повторить все особенности трансляции из `react-selenium-testing`
  - [x] Протестировать в `react-ui-validation`
  - [ ] ✖️Протестировать в `react-ui-testing`.
Не удалось реализовать. В первой версии не получиться заменить `react-selenium-testing.js`
- [ ] Тесты
  - [ ] Добавить возможность тестировать несколько версий реакта. >=16.9
- [ ] Аудит
  - [x] Подготовить к аудиту
  - [ ] Доработать после аудита (https://github.com/skbkontur/react-sorge/issues/1)
- [ ] Настроить паблиш в `npm`

**Comment by dzekh** [comment]
Переехала в ютрек https://yt.skbkontur.ru/issue/IF-8
