### ISSUE TITLE
Generate docs for TopBar.Dropdown, Modal.Header, etc

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#1780]
- [x] Создать список компонентов, которые остались без документации
- [x] Добавить документацию для подкомпонентов, аля TopBar.Dropdown
- [x] Добавить с styleguidist функцию поиска документации для подкомпонентов

**Comment by rustho** [comment]
Список компонентов без документации, лежащих в папке components
- [ ] Calendar - перенести в internal | DatePicker
- [ ] CustomComboBox - добавить доку
- [ ] DateSelect - ? 
- [ ] Dropdown Container - перенести или нет 
- [ ] Hide BodyVertical scroll - добавить доку
- [ ] Ignore Layer Click - добавить доку
- [ ] LocaleProvider - документация лежит вне компонента
- [ ] Menu - добавить доку
- [ ] ModalStack - перенести в internal
- [ ] PasswordInput - добавит доку
- [ ] Perfomance Metrics - добавить доку
- [ ] Phone Input - мож выпилим?
- [ ] Popup - добавить доку или в internal
- [ ] Render Container - в internal 
- [ ] Render Layer - в internal
- [ ] ThemeConsumer - документация лежит вне компонента
- [ ] ZIndex - в internal

**Comment by wKich** [comment]
Из всех перечисленных дока нужна только для PasswordInput. Остальные internal компоненты. Дока так же нужна для компонентов типа Modal.*, SidePage.*, TopBar.*, Tabs.*

**Comment by wKich** [comment]
Вынести в отдельную задачу логику с IgnoreLayerClick, передавать список элементов для игнора в RenderLayer или выкидывать аргументом в requestClose

**Comment by rustho** [comment]
Решили сделать кастомное создание секций, а не общее решение. В виду того, что необходимо подумать над структурой файлов и папок.
