### ISSUE TITLE
[MenuItem] Не всегда срабатывает onMouseLeave в состоянии disabled

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1783]
![Screen Recording 2019-12-03 at 10 07 53](https://user-images.githubusercontent.com/6397708/70022846-6f604500-15b7-11ea-8b60-7a992a35a3a2.gif)
```tsx
export function SuiteLink({ title, suite }: SuiteLinkProps): JSX.Element {
  const [hover, setHover] = useState(false);

  const handleMouseEnter = (): void => setHover(true);
  const handleMouseLeave = (): void => setHover(false);

  return (
    <MenuItem
      state={hover ? 'selected' : null}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      disabled={/* condition */}
    >
    {/* content */}
    </MenuItem>
  );
}
```

**Comment by zhzz** [comment]
Возможно связано c #1422

**Comment by dzekh** [comment]
а в состоянии disabled пункт меню должен вообще подсвечиваться

**Comment by wKich** [comment]
@dzekh дело же не в подсвечивании, а в том что обработчик не вызвался

**Comment by JackUait** [comment]
Вообще странно, что он когда-то срабатывал. На `DOM` элементах, которые могут находиться в состоянии `disabled` (`button`, `input`, `select`, `textarea`, `optgroup`, `option` и `fieldset`) не должны вызываться никакие события, в том числе `onMouseEnter` и `onMouseLeave`.

Сейчас, если в `MenuItem` передаётся проп `disabled`, то `MenuItem` принудительно превращается в кнопку и нативно отключается.

**Comment by lossir** [comment]
Это старый баг в React - https://github.com/facebook/react/issues/10109

Суть его в том, что есть обернуть выключенную кнопку, например, в спан, то на этом самом спане перестанут вызываться некоторые события мыши.
```tsx
<span onMouseEnter={/* если кнопка занимает всю площадь, то никогда не вызовется */}>
   <button disabled>button</button>
</span>
```
В нативных элементах такого нет. Там события нормально всплывают.
Сделал небольшой пример: [react-bug-mouseenter-button-disabled](https://codesandbox.io/s/react-bug-mouseenter-button-disabled-ivtcs?file=/src/App.tsx:271-301)

**Comment by JackUait** [comment]
В оригинальном `issue` идёт речь о том, что при переходе с активного элемента на отключенный перестают вызываться события `onMouseEnter` (если оставаться внутри этих двух элементов)

**Пример №1:** _Элементы стоят вплотную друг к другу_
_На видео:_ навожу мышку на активную кнопку (вызывается событие `onMouseEnter`), затем перевожу мышку на отключенную кнопку, затем возвращаю мышку на активную кнопку (событие `onMouseEnter` уже не вызывается).

https://user-images.githubusercontent.com/48599460/153559192-7b82d0e1-1b39-434c-91a0-1a0c37ff1c57.mov

**Пример №2:** _Между элементами есть два пикселя расстояния_
_На видео:_ навожу мышку на активную кнопку (вызывается событие `onMouseEnter`), затем перевожу мышку на отключенную кнопку, затем возвращаю мышку на активную кнопку (снова вызывается событие `onMouseEnter`).

https://user-images.githubusercontent.com/48599460/153560707-1af8475b-78f2-4a2b-ad5b-2af2fad10113.mov

В этом `issue` как раз происходят события из первого примера.

Но самое интересное происходит в следующем примере. В нём я воспроизвожу логику первых двух примеров, но уже внутри библиотеки. Красный и синий прямоугольники служат обозначением границ элементов.

**Пример №3:** _Элементы стоят вплотную друг к другу, но уже внутри библиотеки_
_На видео:_ навожу мышку на активную кнопку (вызывается событие `onMouseEnter`), затем перевожу мышку на отключенную кнопку, затем возвращаю мышку на активную кнопку (снова вызывается событие `onMouseEnter`).

https://user-images.githubusercontent.com/48599460/153564323-3d0e8cde-6a39-49f1-ba2a-428b258b0ecb.mov

То есть поведение из этого `issue` действительно не воспроизводится в текущей версии библиотеки, по крайней мере на `MenuItem`.

<hr />

Как ты отметил, это происходит потому, что ломается [стандартное поведение](https://stackoverflow.com/a/3100395/17647873) и событие `onMouseEnter` не всплывает, но на самом деле нас не особо волнует юзкейс с оборачиванием в `span` и вызыванием `onMouseEnter` непосредственно на этом `span`'е, так как это ломает очень многие механизмы внутри `HTML`, которые в основном связаны с доступностью интерфейсов. В текущей реализации события происходят там, где они должны происходить - непосредственно на элементе кнопки.

Механизм всплытия событий в принципе нужен `HTML` для внутреннего пользования, мы - как пользователи `HTML` должны прикасаться к нему, только если по-другому никак.

**Comment by JackUait** [comment]
P.S.
 
Не уверен, что это поведение когда-либо пофиксят внутри самого `React`, а если и пофиксят это случится минимум в 19-ой версии `React`, то есть через 2-3 года. Уже предпринимались [попытки](https://github.com/facebook/react/pull/10149) исправить это поведение, но они не увенчались успехом.

**Comment by lossir** [comment]
У нас не воспроизводится, потому-что я пофиксил это 3 года назад ))
https://github.com/skbkontur/retail-ui/commit/1c88969eb93a0057973f3fcd70aa513a8867857d

**Comment by JackUait** [comment]
Хах, тогда тем более, зачем держать открытое `issue`)
