### ISSUE TITLE
[DatePicker, ValidationWrapper]: Не подсвечивается ошибка при "00.12.2019"

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1788]
Версия: 1.6.6

Сценарий:
1) Ставим фокус на DatePicker
2) нажимаем 0 => происходит onChange
3) кликаем вне DatePicker => происходит onBlur
4) снова происходит onChange, т.к. значение становится "00.12.2019"
5) при этом датапикер не подсвечивается красным

Контейнер
```javascript
export class TestContainer extends React.Component {
  this.state = {
    testValue: "",
    testError: false,
  }

  onChangeTest = (_, value) => {
    this.setState({ testValue: value });
  };

  onBlurTest = () => {
    this.setState(state => {
      return {
        testError: !DatePicker.validate(state.testValue)
      }
    });
  };

  render() {
    return <TestView testValue={this.state.testValue} testError={this.state.testError} onChangeTest={this.onChangeTest} onBlurTest={this.onBlurTest} />
  }
}
```

Вью:
```javascript
import { ValidationWrapper, ValidationContainer } from "@skbkontur/react-ui-validations";

const View = ({testValue, testError, onChangeTest, onBlurTest}) => (
  <ValidationContainer>
      <ValidationWrapper validationInfo={testError && { type: "lostfocus" }}>
        <DatePicker
          value={testValue}
          onChange={onChangeTest}
          onBlur={onBlurTest}
        />
      </ValidationWrapper>
    </ValidationContainer>
)
export default View;
```

Результат: https://recordit.co/7K1kssyNks

Если сначала выбрать корректную дату, а потом проделать тот же сценарий, чтобы получилось "00.12.2019", то ошибка сразу подсветится.

Из переписки с Егором:
- Это регрес в валидациях после 1.0.0. Старое поведение вернуть не долго. Но оно, получается, тоже не совсем корректно. Нужно подумать, как лучше поправить.

Может сделать, чтобы не заполнялось 00 для дней/месяцев, или 0000 для лет? Т.е. по-умолчанию было бы 01 для дней/месяцев, и 0001 для лет

**Comment by zhzz** [comment]
Проблема именно в том, что приходит onChange после onBlur. В валидациях это сбрасывает обводку. Раньше там было подперто [косылем](https://github.com/skbkontur/retail-ui/commit/0b3f6300693fb747cf70712d921f95f6fc18d2fa#diff-4a3824d4d4eafab86a5d799de2016898L272), но в 1.0.0 отрефачилось. 

Недавно [предлагалось](https://github.com/skbkontur/retail-ui/issues/1775#issuecomment-560240524) сделать onUnexpectedInput, как в ComboBox. Вроде норм вариант.

**Comment by nextgennexia** [comment]
а в чем будет отличие от onBlur? Не будет ли достаточно вызывать валидацию только на onUnexpectedInput?

**Comment by zhzz** [comment]
Вообще, валидацию пересчитывать нужно на `onChange` всегда. А момент, в который она сработает, выбирается исходя из `validationInfo.type`. 

Если мы запилим `onUnexpectedInput`, то не будет принудительного заполнения недостающих частей даты на `onBlur` и этого лишнего `onChange` в конце.

Но когда до этого руки дойдут - не известно. А пока у меня есть идея другого костыля. Постараюсь в ближайшем времени внедрить.

**Comment by nextgennexia** [comment]
Все понял, спасибо!

**Comment by slawwan** [comment]
я медитировал на эту штуку  кажется странным вызывать onChange после onBlur. onBlur как бы намекает что вышли из контрола, а значит закончили редактирование. такая же проблема всплывает в комбобоксе, там тоже onChange может быть вызван после onBlur, это происходит если из onUnexpectedInput возвращается значение, с этим значением потом и поджигается onBlur.

я все же предлагаю подумать в сторону того, чтобы все onChange поджигались до onBlur

**Comment by wKich** [comment]
@slawwan, закинь отдельное ишью. Вроде бы звучит логично, надо будет везде тогда сделать одинаковое поведение.

**Comment by lossir** [comment]
@slawwan @wKich 
Согласен, что `onBlur()` должен гарантировано вызываться единожды и после всех `onChange()`.
Касательно `DateInput`/`DatePicker` проблема возникала при авто-восстановлении значения при потере фокуса.
Это удалось исправить, и теперь `onBlur()` всегда вызывается последним и только один раз.

**Comment by nextgennexia** [comment]
Кажется проблема еще осталась. Обновился до:
"@skbkontur/react-ui": "1.8.1",
"@skbkontur/react-ui-validations": "1.1.1",

Сценарий тот же. onChange действительно больше не вызывается после onBlur и это здорово. Но кажется все равно что-то идет не так, где дата пикер обернут в компонент валидаций. Без обертки все работает

**Comment by lossir** [comment]
@nextgennexia, да, исправление было решено выпустить в 2.0 версии. Её релиза ещё не было.
