### ISSUE TITLE
[Kladr] Отсутствую коды регионов в документации

### ISSUE THREAD

**Issue by pikhnova** [skbkontur/retail-ui#179]
Коды должны отражаться как при поиске по ним, так и при поиске по наименованию.
В документации:
![default](https://cloud.githubusercontent.com/assets/25151439/25227952/dc25cfc8-25e3-11e7-90e4-d541e2932f1a.jpg)

В гайдах:
![default](https://cloud.githubusercontent.com/assets/25151439/25227212/397874f8-25e1-11e7-95fd-3fc1c9974190.jpg)

**Comment by 21alexander21** [comment]
Будет заменено фиасом
