### ISSUE TITLE
Обновить prettier и прогнать по всем файлам

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#1794]
Отпочковано от #1770 и #1578

**Comment by wKich** [comment]
Перед влитием PR для этого issue, надо чтобы у всех в команде стояла одна версия prettier. В ином случае мы снова будем получать расхождения в форматировании. Ну и в ближайшее время стоит взять задачку #1009

**Comment by zhzz** [comment]
Пишут, что расширения (по крайней мере для [VS Code](https://github.com/prettier/prettier-vscode#prettier-resolution)), используют версию, установленную в проекте.
