### ISSUE TITLE
[Modal] Кнопка закрытия реализована не по прототипам

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1797]
В Modal и SidePage кнопка закрытия реализована по разному. В SidePage это svg иконка, тогда как в Modal это кнопка с размерами 65х75 и сам крестик, это стилизованные ::before и ::after элементы. Размеры которых не совпадают с прототипами. При этом у SidePage область для клика составляет 24x30 и реализована через anchor элемент.

@dzekh В библиотеке figma нет прототипа для SidePage, так же для Modal не указано должен ли быть у неё область клика.

**Comment by dzekh** [comment]
Описал кликабельные области в [файле в Фигме](https://www.figma.com/file/HXJFs6glLNxfoTburQbgP3/React-UI-Theming?node-id=473%3A812).

То же в картинке:

<img width="700" alt="Сlose icons" src="https://user-images.githubusercontent.com/26383080/84938600-e3e37700-b0f6-11ea-9cee-541d5829d0ac.png">
