### ISSUE TITLE
[Tooltip] Отсутствует область клика иконки закрытия

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1798]
Согласно словам @dzekh у иконки закрытия должна быть область для клика размером 24x24px

**Comment by dzekh** [comment]
да, так и есть:
![image](https://user-images.githubusercontent.com/26383080/84358929-51684280-abe1-11ea-8271-011c46a460db.png)
[Подробности в Фигме](https://www.figma.com/file/HXJFs6glLNxfoTburQbgP3/React-UI-Theming?node-id=163%3A545)
