### ISSUE TITLE
[react-ui] Доработки прототипов в фигме

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1799]
В рамках работы над #1793 сформирован список доработок к прототипам и библиотеке контролов. Нужно создать спецификации для компонентов описывающие все размеры и цвета и включающие все возможные состояния:

- [x] `SidePage` 
- [x] `Modal`
  - Отсутствует указание области клика для кнопки закрытия
  - Отсутствует пример с залипающей шапкой
  - Отсутствует пример с ховером на кнопке закрытия
- [x] `Loader`
  - Ширина спинера в размере S должна быть равной ширине иконки
  - Отсутствует пример для размера S в состоянии `dimmed`
- [x] `LogoType` размеры иконки не соответствуют 8-пиксельной сетке
- [ ] `Toast`
  - Отсутствует указание области клика для кнопки закрытия
  - Иконка закрытия имеет цвет `#fff` с `opacity: 0.6`, тогда как для других иконок цвет задан в rgba
  - Отсутствует пример с ховером на кнопке закрытия
- [x] `Token`
  - Отсутствует указание области клика для кнопки закрытия
  - Иконка закрытия для цветного токена имеет цвет `#fff` с `opacity: 0.6`, тогда как для других иконок цвет задан в rgba
  - Отсутствует пример с ховером на кнопке закрытия
  - В состоянии `disabled` отсутствует иконка (#1445)
- [x] `Tooltip`
  - Отсутствует указание области клика для кнопки закрытия
  - Отсутствует пример с ховером на кнопке закрытия

Нестыковки с реализацией библиотеки:
- [x] `Modal` размер, цвет и отступы кнопки закрытия не соответствуют прототипам #1797
- [x] `Spinner` размеры и края обводки не соответствуют прототипам
- [ ] `Modal/SidePage/Token/Tooltip` различия в реализации кнопки закрытия/удаления реализована (где-то просто `span/div`, где-то `a`, а где-то `button`)

**Comment by dzekh** [comment]
Спецификация пока [будет жить здесь](https://www.figma.com/file/hg7OggB5Akt4OU8Ku8k0h6/React-UI-Specs?node-id=484%3A850), вместе с переменными темы.

**Comment by dzekh** [comment]
Большинство пунктов закрыли, часть неактуально. Все подобные задачи будем вести в Ютреке. Тут закрываю
