### ISSUE TITLE
[react-icons] Extract open source icons in separate package

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1815]
@dzekh, нужно составить список иконок, которые можно считать свободными.
Вынести эти иконки в отдельный пакет и использовать его как обычную зависимость в react-ui

**Comment by dzekh** [comment]
Мы выделили и интегрировали свг иконок прямо в компоненты. Я пометил у себя в макетах эти иконки, пока что этого достаточно. Если вдруг обновятся эти иконки, обновим просто вручную в компонентах. Если устанем обновлять - автоматизируем. Пока закрываю эту задачку.
