### ISSUE TITLE
[Button] Артефакты в анимации загрузки при size="large"

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1819]
![Screenshot 2019-12-23 at 13 33 28](https://user-images.githubusercontent.com/6397708/71347433-31d65280-258c-11ea-8323-43c19eeff9b4.png)

**Comment by dzekh** [comment]
Они там и в медиуме есть

**Comment by dzekh** [comment]
Поменяется способ отображения состояния загрузки
