### ISSUE TITLE
[TokenInput] OnKeyPress IF-212

### ISSUE THREAD

**Issue by bdskrur** [skbkontur/retail-ui#1825]
- react-ui

Есть необходимость покрыть 2 сценария работы с компонентом:

1. По нажатию на Enter внутри поля TokenInput, запускать действие
2. Иметь какой-либо дополнительное свойство (например OnChangeCurrent), чтобы знать что ввел пользователь перед тем как пропал фокус с инпута и тег не сформировался

**Comment by rustho** [comment]
#1335

**Comment by dzekh** [comment]
Кажется что уже добавленые `onInputValueChange` и `onUnexpectedInput` в [#1980](https://github.com/skbkontur/retail-ui/pull/1980) и [#2279](https://github.com/skbkontur/retail-ui/pull/2279) решают проблему. Переоткройте, если нет.
