### ISSUE TITLE
[Button] синхронизировать состояние checked в Flat

### ISSUE THREAD

**Issue by rustho** [skbkontur/retail-ui#1826]
Сейчас у use: 'default' есть border, а у use:'primary' и т.д. нет
По прототипам везде должна быть border. 

![image](https://user-images.githubusercontent.com/26579566/71466799-88d56500-27e2-11ea-8ee4-f4475d00220d.png)

**Comment by lossir** [comment]
@dzekh, кто тут прав, прототипы или контролы?

**Comment by dzekh** [comment]
Убрали обводку у дефолтных

**Comment by dzekh** [comment]
Вроде здесь исправлено: https://github.com/skbkontur/retail-ui/pull/1846
