### ISSUE TITLE
[Kladr] Не работают поля в IE9

### ISSUE THREAD

**Issue by pikhnova** [skbkontur/retail-ui#183]
Поля с выпадающими списками получают фокус (в том числе и табом), но не дают возможность для редактирования. Выпадающие списки также не появляются:
![9](https://cloud.githubusercontent.com/assets/25151439/25272207/7921a59c-26a0-11e7-8c93-f7220596facf.gif)

**Comment by 21alexander21** [comment]
не поддерживаем ие до 11
