### ISSUE TITLE
[Tooltip, react-ui-validation] Тултип исчезает частями.

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1835]
"@skbkontur/react-ui": "1.5.0",
"@skbkontur/react-ui-validations": "1.0.4",

или что есть на странице http://tech.skbkontur.ru/react-ui-validations/#/form-validity

Браузер: хром

Ввести не валидное значение, затем валидное: тултип пропадает частями, последним исчезает хвост. 

https://recordit.co/7kkrpQl87C

**Comment by dzekh** [comment]
Фиксили глючную тень для сафари, может это помогло.
