### ISSUE TITLE
[Button, Switcher] моргающие тесты

### ISSUE THREAD

**Issue by rustho** [skbkontur/retail-ui#1837]
Начали мигать скриншотные тесты chrome
Button - Arrow with error - clicked, pressed
Button - with error - clicked, pressed
Switcher - horizontal - clicked
![image](https://user-images.githubusercontent.com/26579566/72236512-fd890b80-35f8-11ea-84b7-4bff3f31fdc6.png)
![image](https://user-images.githubusercontent.com/26579566/72236519-0a0d6400-35f9-11ea-812e-5ce40b8d8ca7.png)

**Comment by lossir** [comment]
А на какой ветке? У меня как раз с ними была проблема в ветке датаинпута, которая теперь в `next`. Локально всё проходило, а на сервере стабильно падали.
