### ISSUE TITLE
[Kladr] Нет валидации индекса

### ISSUE THREAD

**Issue by pikhnova** [skbkontur/retail-ui#184]
Согласно https://guides.kontur.ru/components/KLADR/ "В поле «Индекс» можно ввести только цифры.".
В документации валидация отсутствует, позволяет вводить буквы, символы, в том числе и пробелы.
![default](https://cloud.githubusercontent.com/assets/25151439/25273539/96a4a3a8-26a5-11e7-9711-f46a92a10109.jpg)

**Comment by 21alexander21** [comment]
будет заменено фиасом
