### ISSUE TITLE
[Token] Добавить кастомизацию

### ISSUE THREAD

**Issue by mshatikhin** [skbkontur/retail-ui#1840]
Есть потребность кастомизировать компонент Token (вне TokenInput)

Например падинги, бордер радиус, фон, обводку,.. Токен часто используется как компонент для фильтров. Городить очередной раз новый компонент не айс. Компонент Token работает неплохо, да и цвета есть из коробки.. Буду благодарен за кастомизацию например через ThemeProvider.

Если что, хотелось бы получить такую фичу в версию 1.*.*, желательно до 24 января 2020.

![image](https://user-images.githubusercontent.com/1788385/72407653-196be900-3782-11ea-9738-2587e0feacd7.png)

**Comment by dzekh** [comment]
@mshatikhin новые переменные добавятся в 2.5 или 2.6, для 1.X всё еще актуально?

**Comment by mshatikhin** [comment]
> @mshatikhin новые переменные добавятся в 2.5 или 2.6, для 1.X всё еще актуально?

у нас 1.х.х пока не планировали переезжать на 2, если не сильно сложно докинете?

**Comment by dzekh** [comment]
Тут какие-то два пиара в LTS старый открыты, но наверное уже ничего не актуально. 
Все настройки в последних версиях (2.17 и 3.0) уже есть.
В 1.X мы уже не будем добавлять их. Закрываю таску. Если не будем вливать пиары Миши, предлагаю и их закрыть.
