### ISSUE TITLE
[react-ui] change signatures of callbacks

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#1843]
### Новые правила работы с событиями:
- Нативный `onChange()` не должен модифицироваться и вызываться "искусственно".
- Все кастомные событие должны именоваться отлично от общих нативных.
- Не использовать `FakeEvent`.
*В некоторых контролах коллбэки, типа `onChange()`, первым аргументом передают т.н. `FakeEvent`; с подобной сигнатурой `{ target: { value: string } }`. Вторым аргументом идёт `value`.*

### Задачи:
- Переименовать кастомные события:
  - ~`onChange`~ -> `onValueChange`.
  - ~`onInputChange`~ -> `onInputValueChange`.
- В кастомных событиях удалить `FakeEvent` и первым аргументом всегда передавать `value`.

---
### Компоненты и методы:

❋ - Внутренние компоненты 

| Было | Стало | Новый метод |
| --- | --- | --- |
| **Autocomplete** |  |  |
| `onChange(FakeEv, value)` | `onChange(SynthEv)` | `onValueChange(value)` | 
| **Checkbox** |  |  |
| `onChange(SynthEv, value)` | `onChange(SynthEv)` | `onValueChange(value)` | 
| **ComboBox** |  |  |
| `onChange(FakeEv, value)` | *-удалён-* |  `onValueChange(value)` |
| `onInputChange(value)` | *-удалён-* | `onInputValueChange(value)` |
| ❋ **CustomComboBox** |  |  |
| `onChange(FakeEv, value)` | *-удалён-* |  `onValueChange(value)` |
| `onInputChange(value)` | *-удалён-* | `onInputValueChange(value)` |
| **DateInput** |  |  |
| `onChange(FakeEv, value)` | *-удалён-* | `onValueChange(value)` |
| **DatePicker** |  |  |
| `onChange(FakeEv, value)` | *-удалён-* | `onValueChange(value)` |
| ❋ **DateSelect** |  |  |
| `onChange(value)` | *-удалён-* |  `onValueChange(value)` |
| **Fias** |  |  |
| `onChange(FakeEv, value)` | *-удалён-* |  `onValueChange(value)` |
| **FiasSearch** |  |  |
| `onChange(FakeEv, value)` | *-удалён-* |  `onValueChange(value)` |
| `onInputChange(value)` | *-удалён-* | `onInputValueChange(value)` |
| **Radio** |  |  |
| `onChange(FakeEv, value)` | `onChange(SynthEv)` | `onValueChange(value)` | 
| **RadioGroup** |  |  |
| `onChange(FakeEv, value)` | *-удалён-* | `onValueChange(value)` | 
| **Select** |  |  |
| `onChange(FakeEv, value)` | *-удалён-* |  `onValueChange(value)` |
| **Switcher** |  |  |
| `onChange(FakeEv, value)` | *-удалён-* |  `onValueChange(value)` |
| **Tabs** |  |  |
| `onChange(FakeEv, value)` | *-удалён-* |  `onValueChange(value)` |
| **Textarea** |  |  |
| `onChange(SynthEv, value)` | `onChange(SynthEv)` | `onValueChange(value)` | 
| **Toggle** |  |  |
| `onChange(value)` | `onChange(SynthEv)` |  `onValueChange(value)` |
| `changeEventHandler(SynthEv)` | *-удалён-* | *-* | 
| **TokenInput** |  |  |
| `onChange(value)` | *-удалён-* |  `onValueChange(value)` |
| **Input** |  |  |
| `onChange(SynthEv, value)` | `onChange(SynthEv)` | `onValueChange(value)` | 
| `onUnexpectedInput()` | `onUnexpectedInput(value)` | *-* | 
| **CurrencyInput** |  |  |
| `onChange(FakeEv, value)` | `onChange(SynthEv)` | `onValueChange(value)` | 
| **FxInput** |  |  |
| `onChange(FakeEv\|SynthEv, value)` | `onChange(SynthEv)` | `onValueChange(value)` | 
| **PasswordInput** |  |  |
| `onChange(SynthEv, value)` | `onChange(SynthEv)` | `onValueChange(value)` | 
| ❋ **InputLikeText** |  |  |
| `onChange(SynthEv, value)` | `onChange(SynthEv)` | `onValueChange(value)` | 
| ❋ **MaskedInput** |  |  |
| `onChange(SynthEv)` | `onChange(SynthEv)` | `onValueChange(value)` | 
| `onUnexpectedInput()` | `onUnexpectedInput(value)` | *-* |

**Comment by wKich** [comment]
```
const [value, handler] = useState('')

<ComboBox onValueChange={handler} />
```

**Comment by zhzz** [comment]
#1859
