### ISSUE TITLE
[CurrencyInput, FxInput] Не удаляются значения через экранную клавиатуру на телефоне

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#1865]
Версия: 1.7.0

Пробовал непосредственно на витрине. При нажатии на <x, цифры не удаляются, а позиция курсора смещается влево.

На простом инпуте не повторяется

UPD: если изменить inputMode на numeric, то работает

**Comment by dzekh** [comment]
Кажется что дубль #1523

**Comment by zhzz** [comment]
В `FxInput` не воспроизвелось. А `CurrencyInput` мы починили в 2.16.0 установкой  `inputMode` `decimal` по умолчанию. Пока закрою. Если баг все-таки остался - пиши снова.
