### ISSUE TITLE
[Tooltip] Нельзя выделить текст для `trigger="focus"`

### ISSUE THREAD

**Issue by slawwan** [skbkontur/retail-ui#1867]
react-ui v1.8.0
https://tech.skbkontur.ru/react-ui/#/Components/Tooltip

Сценарий:
1. Выбираем триггер `focus`
1. Кликаем на квадрат, он получает фокус, открывается тултип
1. Начинаем выделять текст в тултипе
1. Квадрат теряет фокус, **тултип закрывается**

Несмотря на закрытие тултипа, если в тултипе есть ссылка, то клик по ссылке обработается и от левой кнопки мыши и от кнопки-колеса.

![image](https://user-images.githubusercontent.com/5162965/73337139-8bb9ee80-4295-11ea-8eef-4d40959bdeda.png)

Для триггера `hover` есть задержка, благодаря которой можно переместить курсор в тултип и выделить текст. пока курсор в тултипе - он не скроется.

Возможно для открытия по фокусу стоит накрутить логику подобную той что работает по ховеру.

**Comment by dzekh** [comment]
Кажется, что тут даже задержка не спасет. Какая бы она длинная ни была он рано или поздно закроется и это будет бесить. 
Нужно делать как-то так чтоб когда ховер или фокус перемещается в тултип он не закрывался пока фокус на тултипе, или пока мышь над ним.

**Comment by slawwan** [comment]
@dzekh да, основная идея в этом

> Нужно делать как-то так чтоб когда ховер или фокус перемещается в тултип он не закрывался пока фокус на тултипе, или пока мышь над ним.

Думаю это стоит в гайд добавить

**Comment by dzekh** [comment]
Нужно добавить в гайды, да. Займусь на следующей неделе.

**Comment by dzekh** [comment]
> Только сейчас тултип с триггером hover закрывается если он теряет ховер, даже если фокус был в нем.

Ну кажется это нормально, нет? Если фокус на тултипе или на элементе внутри тултипа считаешь что он должен оставаться видимым? 
Ну в общем то это логично, если в тултипе какое-то поле ввода например.

**Comment by slawwan** [comment]
@dzekh просто обратил внимание на то, как работает сейчас

**Comment by wKich** [comment]
Есть несколько нюансов которые меня смущают, если мы будем переделывать поведение.
1. Кроме `trigger="focus"` есть ещё значение `click`, должны ли изменения поведения для focus изменится и для click?
1. Рассмотрим сценарий, есть инпут при фокусе которого открывается тултип. В тултипе кроме текста присутствуют кнопки, клик по которым выполняет какое-то действие. Сейчас поведение очевидное, при клике на кнопку тултип закрывается. Если мы изменим поведение тултип останется висеть.
1. Если мы меняем поведение по click в соответствии с focus у нас перестает работать сценарий с закрытием выпадах в TooltipMenu и др, когда пользователь кликнул на элемент меню.

У нас уже есть значение `trigger="hover&focus"`. Возможно правильным решением будет использовать это значение. При это есть недоработка в логике этого триггера, пока элемент не зафокушен тултип ведет себя как если бы trigger имел значение hover и позволяет выделять текст, но как только элемент был зафокушен, логика триггера меняется на focus и тултип закрывается при клике на содержимом.

**Comment by dzekh** [comment]
Внес правки в гайд по тултипам, пока только на тестовой, дизайнеры смотрят:
https://guides.dev.kontur/components/tooltip/#Poyavlenie_i_skritie_tultipov
Добавил раздел «Появление и скрытие тултипов»

**Comment by dzekh** [comment]
Еще нужно сделать задержку на появление по ховеру, чтоб не было моргания. В гайде про это давно уже написано, а в библиотеке не реализовано.

**Comment by dzekh** [comment]
Давайте изменим логику trigger="hover&focus" чтобы при фокусе тоже была задержка и можно было кликать. 

trigger="focus" видимо придется оставить как есть, если это сломает поведение выпадающих меню.

**Comment by lossir** [comment]
На первый взгляд, между задержкой 0 и 100 разницы не видно.

<details><summary>задержка 0</summary>

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2708211/74324389-cbf69200-4da8-11ea-8a8e-317798fe9505.gif)

</details>


<details><summary>задержка 100</summary>

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/2708211/74324398-cef18280-4da8-11ea-9c13-99de0c2f5386.gif)

</details>


<details><summary>задержка 200</summary>

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/2708211/74325514-9488e500-4daa-11ea-8401-db81cc723694.gif)

</details>


<details><summary>задержка 300</summary>

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/2708211/74325276-20e6d800-4daa-11ea-9d0c-49890955b7ee.gif)

</details>

**Comment by dzekh** [comment]
Не совсем правильно так тестировать — туда сюда. Нужно просто проводить над объектом  заходя с одной стороны а выходя с другой. 
Когда ты водишь туда-сюда у тебя невольно на дольше задерживается курсор пока меняется направление движения.
