### ISSUE TITLE
[Modal] [Input] Тормозит при печати в лайтбоксе на больших страницах

### ISSUE THREAD

**Issue by original001** [skbkontur/retail-ui#1870]
Сценарий:
1. Открываем `Modal` с `Input` на странице, где много элементов. Например, форма
2. Печатаем в `Input`
3. Видим, что набор текста не отзывчивый

Хорошо воспроизводится в ИЕ
Можно воспроизвести в хром, если поставить CPU throttle 6x

Версия библиотеки: LTS 0.53.3

Ждем правки в LTS

![image](https://user-images.githubusercontent.com/8949234/73643707-cce73f80-4695-11ea-87c1-2fa49236c95c.png)

**Comment by tihonove** [comment]
Пацаны, скоро годовщина бага. Это, вообще, нормально?

**Comment by dzekh** [comment]
Это плохо, и таких багов очень много, у нас не хватает ресурсов справляться со всеми. У этого бага приоритет был низкий. Если сильно мешает жить — поднимем приоритет.

**Comment by tihonove** [comment]
Кажется что модальное окно -- популярный компонент.
По факту сейчас почти во всех модалках (прости господи, контура) даже на разработческих машинах (даже в хроме!) тормозит ввод. Если модальное окно чуть сложнее чем с одним инпутом, то тормоза очень явные.

**Comment by lossir** [comment]
Постараемся взять его в работу сразу, после текущих задач. Сейчас мы готовимся к релизу, поэтому нет возможности переключиться на этот баг. Т.к. по первой проверке кажется, что корни бага сидят довольно глубоко, и его исправление может затянуться.

**Comment by zhzz** [comment]
Выкачено в `2.17.2` и `3.2.1`.
