### ISSUE TITLE
[Theme] Добавление новых переменных

### ISSUE THREAD

**Issue by rustho** [skbkontur/retail-ui#1875]
Ишью для того, чтобы не забыть добавить новые переменные в тему

- [ ] Logotype - переменная для цвета стрелочки вниз
- [ ] Topbar -
  - [ ] @active-background: rgba(0, 0, 0, 0.06);
  - [ ] @buttonSidePadding: 10px;
  - [ ] @danger-color: #ffe3e3;
  - [ ] @height: 50px;
  - [ ] @pay-color: #ffeca9;

**Comment by dzekh** [comment]
Logotype - в качестве названия переменной для стрелочки так себе имя. Нада чото более осознанное. А какие там еще переменные уже есть?

**Comment by rustho** [comment]
> Logotype - в качестве названия переменной для стрелочки так себе имя. Нада чото более осознанное. А какие там еще переменные уже есть?

Это название самого компонента, думаю что еще надо будет вытащить переменные, в процессе буду пополнять ишью

**Comment by dzekh** [comment]
@zhzz мы добавили эти переменные на парковку же?

**Comment by zhzz** [comment]
Переменные размеров - да, цвета - нет.
