### ISSUE TITLE
[Tooltip] Добавить возможность изменять размеры отступов в теле тултипа

### ISSUE THREAD

**Issue by ando771** [skbkontur/retail-ui#1877]
retail-ui@1.8.0, Windows 10, Chrome 79

Сейчас для Tooltip нельзя изменить значение padding в теле тултипа. Они захардкожены в значении `padding: 15px 20px`. Хотелось бы иметь возможность каким-то образом изменять их.

Обойти проблему можно установкой отрицательных `margin: -15px -20px` у содержимого тултипа, переданного через пропс render.

Какие я вижу решения:
1. Передавать размер отступа явно через пропсы Tooltip
2. Через ThemeProvider, но не уверен, насколько это верно архитектурно
3. Убрать полностью дефолтные, захардкоженные отступы из тултипа и считать, что пользователь библиотеки сам будет проставлять нужные ему через render.

Готов закинуть pr, если кто-то подскажет, какое решение лучше.

**Comment by wKich** [comment]
Tooltip отрисовывает отступы согласно гайдам, в 99% сценариев дает возможность не задумывать над отступами и просто выводить контент. Поэтому 3-й пункт мало того что ведет к ломающим изменениям, так обязывает всех кто сейчас использует тултипы начать явно задавать отступы по гайдам.

1-й пункт вполне возможное решение, но с учетом наличия механизма кастомизации внешнего вида через ThemeProvider, а так же то что некоторые компоненты уже позволяют кастомизировать отступы через него, например Button. Считаю что реализация через 2-й пункт наиболее правильная.

**Comment by ando771** [comment]
@wKich я тебя понял, постараюсь на этой неделе кинуть pr со вторым вариантом.

**Comment by dzekh** [comment]
в 3.0 и 2.17 реализована возможность кастомизировать отступы тултипов, закрываю.
