### ISSUE TITLE
[Tokeninput] Подсветка и выбор пункта по Enter

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#1878]
После [обсуждения](https://staff.skbkontur.ru/post/2d545c4bfd724d4a89a1d190921c6053) решили внести изменения в Гайды, нужно реализовать это в компоненте. 

Сейчас, после ввода текста в поле и фильтрации списка не подсвечивается первая строка, а при нажатии 'Enter' добавляется новое значение в справочник.  
Текст подсказки в низу выпадающего списка сейчас — «Нажмите Enter или поставьте запятую»

Нужно сделать так чтоб после ввода текста в поле и фильтрации списка подсвечивалась первая строка выпадающего списка, при нажатии 'Enter' выбиралось подсвеченное значение. Новое значение добавляется только если перевели на него подсветку или оно осталось одно, соответственно больше нет совпадений, и подсветка на нем.  
Текст подсказки новый — «Введите запятую или пробел».

**Comment by dzekh** [comment]
Еще одна особенность поведения: сейчас если выбирать с клавиатуры какой-то пункт, например второй по счету, то при следующем появлении выпадающего списка выделение будет стоять на нем же — на втором по счету, хотя на втором месте уже другое значение и смысла в этом нет. Выделение должно сбрасываться каждый раз после выбора.

**Comment by wKich** [comment]
Выходит ли это, что подобная логика должна быть и при работе с ComboBox?

Вот насчет "пробела" не уверен. А если текст элемента списка содержит пробел, что тогда? Конечно он может содержать и запятую. Но в любом случае не понимаю необходимости в этом изменении.

**Comment by wKich** [comment]
> Выделение должно сбрасываться каждый раз после выбора.

Про это уже есть ишью https://github.com/skbkontur/retail-ui/issues/1187

**Comment by dzekh** [comment]
Да, мы вроде как раз синхронизировали токен с поведением комбобокса. Сейчас должно быть одинаково по крайней мере с выбором и добавлением.

**Comment by dzekh** [comment]
> > Выделение должно сбрасываться каждый раз после выбора.
> ]
> Про это уже есть ишью #1187

Там кстати описания нет, а из видео не очень понятно что происходит, возможно оно же.

**Comment by wKich** [comment]
Первая строка в TokenInput не подсвечивается только если задан тип `type={TokenInputType.Combined}`. Вообще наверно будет правильно избавиться от этого пропа и дать возможность кастомизировать поведение

**Comment by dzekh** [comment]
> Первая строка в TokenInput не подсвечивается только если задан тип `type={TokenInputType.Combined}`. 

Это поведение не должно зависеть от типа

> Вообще наверно будет правильно избавиться от этого пропа и дать возможность кастомизировать поведение

Возможно. Что ты имеешь ввиду под этим?

**Comment by wKich** [comment]
Не спорю. Поэтому и предлагаю выпилить проп `type` и дать разработчику нужный рабор ручек для повторения той логики что есть сейчас + исправить подсветку первого элемента.

Сейчас с помощью типов задается различное поведение TokenInput'а:
- `WithReference` - Возможность выбрать значение только из выпадающего списка, добавлять свои значения нельзя.
- `WithoutReference` - Возможность работы без справочника, отсутствует выпадашка со списком значений, можно только добавлять свои значения.
- `Combined` - Режим который совмещает в себе два предыдущих, есть возможность выбора значений из выпадашки, так и добавление своих.
}

**Comment by dzekh** [comment]
> Выходит ли это, что подобная логика должна быть и при работе с ComboBox?
> 
> Вот насчет "пробела" не уверен. А если текст элемента списка содержит пробел, что тогда? Конечно он может содержать и запятую. Но в любом случае не понимаю необходимости в этом изменении.

Логика с вводом пробела или запятой должна касаться только токенинпута, в комбобоксе нет множественного выбора, разделители там не нужны. 

Будет круто если м дадим управлять символоми разделителей и текстом подписи. В гайдах про это есть: «Например, при вводе электронной почты, в качестве разделителя уместно использовать запятую и пробел, поскольку эти символы в ней не встречаются. В случае с телефоном пробел нельзя использовать, поскольку пользователь может сам ввести его для удобочитаемости или скопировать его из места, где он уже был.»

**Comment by wKich** [comment]
> Логика с вводом пробела или запятой должна касаться только токенинпута, в комбобоксе нет множественного выбора, разделители там не нужны.

Когда я говорил про Combobox, я не имел в виду именно работу разделителей. Ведь ишью-то про подсветку всё же.

**Comment by wKich** [comment]
Давай кастомизацию разделителей вынесем отдельным ишью

**Comment by dzekh** [comment]
> Давай кастомизацию разделителей вынесем отдельным ишью

да, давайте. 

Было бы прикольно закатить это в 1.9, это нужно Экстерну а они сидят на LTS. Если появится только в 2.0 они будут этой фичи ждать год. 

А в 2.0 можно менять пропы и делать кастомизацию разделителей.
И изменение пропов тоже можно вынести в отдельное ишью и проработать аналитику подробней по ним.  

По подсветке достаточно аналитики?
