### ISSUE TITLE
Сломаны реэкспорты интерфейсов в next

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#1883]
Babel не может вырезать реэкспорты типов, если они описаны в другом файле. https://github.com/babel/babel/issues/8361

https://github.com/skbkontur/retail-ui/blob/cf4c2c7504c1f75c8b76d7e2a260699595c936cd/packages/retail-ui/components/Button/index.ts#L1

Варианты решения:

1. Использовать динамические реэкспорты `export * from 'Button'`
2. Ждать babel@7.9 и typescript@3.8 с поддержкой `export type { Interface }`

**Comment by wKich** [comment]
Вот это надо же было так напороться :)

Кажется 1-й вариант надежнее выглядит, да и ждать не надо.

**Comment by zhzz** [comment]
#1889
