### ISSUE TITLE
[Toast] хардкод cssTransition.

### ISSUE THREAD

**Issue by zokeer** [skbkontur/retail-ui#1884]
retail.ui@1.3.0, смотрел в Chrome 79, скорее всего везде проблема есть.

Хотим собирать в webpack бандл стили retail.ui, меняя css классы с [local] на [name]-[local]--[hash:base64:8] лоадером. Из-за этого у тоста пропадают анимации появления и исчезновения.

Я так понимаю, проблема возникает из-за хардкода [вот тут](https://github.com/skbkontur/retail-ui/blob/master/packages/retail-ui/components/Toast/Toast.tsx#L115). Мы меняем класс при сборке в бандл, а в коде на тост все ещё навешиваются slide-and-fade-enter-active и прочие без хешей и имени.

**Comment by wKich** [comment]
Исправлено в #1846
