### ISSUE TITLE
[ComboBox] Повторно не предлагает список после его закрытия

### ISSUE THREAD

**Issue by pikhnova** [skbkontur/retail-ui#189]
Согласно https://guides.kontur.ru/controls/autocomplete/ 
Esc: Скрывает список, фокус не исчезает. _Подсказка вновь появится при вводе или удалении символа._
В новом combobox в документации этого не происходит и после ввода значения, которое точно есть в списке, уведомляет нас, что мы ничего не выбрали.
![default](https://cloud.githubusercontent.com/assets/25151439/25390505/1b083160-29ed-11e7-9343-c6d079bb6f0c.gif)

**Comment by nanot1m** [comment]
значение не выбирается про причине того, что списка (выпадающего) еще нет

**Comment by pikhnova** [comment]
Список повторно появляется при нажатии клавиш вниз/вверх
