### ISSUE TITLE
[eslint-config] Добавить eslint плагин `@skbkontur/react-ui:recomended`

### ISSUE THREAD

**Issue by Laiff** [skbkontur/retail-ui#1895]
Добавить плагин для eslint с набором правил для типичного использования таких как
 - [ ] Сообщение об использование устаревших компонентов (с предложением замены)
 - [ ] Использование устаревших пропов в конкретных компонентах
 - [ ] Блокирование несемантичного или непредполагаемого использования компонетов между собой
 - [ ] Продвижение общих конвенций по именованию или использованию (нужно расширить)

**Comment by asukhar** [comment]
Есть задача в YT - IF-404
