### ISSUE TITLE
Lookup не находит Modal по tid

### ISSUE THREAD

**Issue by callmekoo** [skbkontur/retail-ui#19]
Есть модал, который открывается по ссылке из комбобокса, у него прописан tid:

    <Modal tid="NewContractorModal"></Modal>

При выполнении `Lookup.findOne('NewContractorModal')` находится элемент в теге noscript, внутри которого ничего нет.

Перенесли tid внутрь модала вот так:

    <Modal><div tid="NewContractorModal"></div></Modal>

и Lookup стал находить модал правильно.

Очень хочется, чтобы в первом случае скрипт находил модал правильно.

**Comment by nanot1m** [comment]
Lookup находит компонент модалки правильно. Проблема в том что модалка рендерит в портал. А поиск портала становится довольно нетривиальной задачей.
Можете рассказать подробнее зачем это нужно?

**Comment by callmekoo** [comment]
У нас есть старое приложение с фронтом на MVC, в которое встроили мастер, написанный на реакте. В этом мастере открывается модал, в котором есть, например, селект. Проблема как раз в том, чтобы найти селект внутри модала и взаимодействовать с ним.

Попробую еще раз разобраться в проблеме, возможно, проблема в нашем тестовом фреймворке.

**Comment by nanot1m** [comment]
@callmekoo, почему не хотите пометить содержимое модалки тидом?

**Comment by callmekoo** [comment]
@nanot1m мы так и сделали, но это выглядит как костыль, потому что с остальными модалами такой проблемы не возникало
