### ISSUE TITLE
[Testing] add data-tid to components

### ISSUE THREAD

**Issue by rustho** [skbkontur/retail-ui#1912]
Выработать общий стиль написания data-tid 
Порефачить тесты и компоненты в связи с предложенными data-tid

**Comment by wKich** [comment]
@lossir предлагал использовать БЭМ нотацию. Мне кажется вполне приемлемо, в качестве названия блока использовать название компонента, а в качестве элемента уже конкретный элемент во внутренней верстке компонента, например `Button__icon` или `Modal__close`

**Comment by JackUait** [comment]
@lossir кажется, это стоит упоминания в новых доках.

**Comment by asukhar** [comment]
Исправлено в #2900
