### ISSUE TITLE
tooltip валидации не учитывает размеры tokenInput

### ISSUE THREAD

**Issue by grommi** [skbkontur/retail-ui#1918]
В tooltip валидации вокруг TokenInput не учитывает его размеры, из-за чего для многих положений закрывает TokenInput. Отмечу, что из-за этого с полем практически невозможно работать.

- validations: 1.0.7 ; react-ui: 1.6.9
- chrome, в ie все ок.
- поместить tokenInput в validationWrapper и validationContainer
- Прикрепи скриншот или гифку с примером;
![Screenshot_13](https://user-images.githubusercontent.com/18192781/75970248-e0363680-5ef1-11ea-89f3-6f656e8b09fa.png)

**Comment by MariaShmakova** [comment]
Договорились обсудить дополнительно в рамках этой задачи доработку tokenInput:
при потере фокуса превращать последнюю запись в токен.
