### ISSUE TITLE
Какая лицензия у проекта?

### ISSUE THREAD

**Issue by egorsmkv** [skbkontur/retail-ui#1922]
Этот проект вообще можно использовать сторонним компаниям/разработчикам?

**Comment by wKich** [comment]
Привет. Спасибо за проявленный интерес. У проекта лицензия MIT и да, его можно использовать в сторонних проектах. Единственный нюанс это компоненты `Fias`, `FiasSearch`, `Logotype` и `TopBar` их использование не рекомендуется. Они используют внутреннее API Контура или содержат логотип/фирменный стиль компании. И в данный момент мы их переносим в приватный проект. Таким образом в следующей мажорной версии в этом проекте останутся полностью свободные к использованию компоненты.

**Comment by egorsmkv** [comment]
А если я не буду в этих компонентах использовать фирменные вещи и использовать свои апи?

**Comment by dzekh** [comment]
Если я не будете использовать фирменные вещи и использовать апи Контура, тогда можно. Используйте =)
