### ISSUE TITLE
[ScrollContainer] Добавить горизонтальный скролл

### ISSUE THREAD

**Issue by denexapp** [skbkontur/retail-ui#1931]
Появилось потребность использовать горизонтальный скролл в ScrollContainer. Сценарий - внутри контейнера с фиксированным размером отображать картинку (в канвасе) любого размера с возможностью скролла по вертикали и по горизонтали одновременно.

**Comment by wKich** [comment]
В формах что-то подобное делал. Можно попробовать вытащить от туда код. Если есть желание, можешь помочь с внедрением.

**Comment by denexapp** [comment]
@wKich Подскажи репозиторий форм, не могу найти

**Comment by dzekh** [comment]
@sorovlad help

**Comment by wKich** [comment]
Можно ещё @tihonove позвать

**Comment by tihonove** [comment]
Ну раз меня позвали, позволю себе изложить своё видение ситуации.
**TL;DR**: просто используй встроенный в браузер склол (ну то есть вот просто `overflow: auto`).

Почему: ScrollContainer вроде как рисует маковский скролл, я считаю это неправильно т.к.:
1. Нативный скролл проще, стабильнее и в каждом браузере будет отображаться привычный пользователю скролл.
2. Есть подозрение, что случилось недопонимание: проектировщики (которые на маках все) нарисовали скролл, который они видят всегда, а фронтендеры закодили "как на картинке было".
3. И если маленький маковский скрол в выпадашке комбобокса ещё оправдан: (а) пространства и так мало, (б) может сильно отвлекать от основного контента и (с) не сильно востребован (все просто поиском ищут), то для больших контролов не могу придумать аргументов перерисовывать нативный скролл. 


Если тебя это не убедило, пиши в телегу покажу, что где. Но! 
1. В формах мы уже отказались от маковского скрола и используем нативный (но можно в истории найти, помогу если что). 
2. Там реализован доп. сценарий с залипанием скрола.

**Comment by dzekh** [comment]
@denexapp если вдруг решите использовать из форм — закидывай PR

**Comment by dzekh** [comment]
Залипание скролла? Это как? Зачем?

**Comment by tihonove** [comment]
> Залипание скролла? Это как? Зачем?

![image](https://user-images.githubusercontent.com/2770182/98335672-37fbe300-2027-11eb-864c-bf05af947354.png)

**Comment by dzekh** [comment]
А, ну в смысле что скролл всегда должен быть на экране, в видимой области. Да.
