### ISSUE TITLE
[Hint] Клюв не по центру

### ISSUE THREAD

**Issue by govorukhin-do** [skbkontur/retail-ui#1933]
Когда хинт открывается рядом с краем экрана, его позиция пересчитывается так чтобы он все же  мог полностью отобразиться. При этом стрелочка указывающая на элемент триггер этого хинта будет не по центру триггера. 
В примере на скрине, у хинта, свойство position="top"
![image](https://user-images.githubusercontent.com/9696631/76679367-bf609600-6601-11ea-95be-3c4a15727077.png)

**Comment by wKich** [comment]
Ммм... В текущем сценарии выглядит как баг, но на самом деле такое положение является предсказуемым исходя из логики работы позиционирования.

![](https://user-images.githubusercontent.com/26383080/54685626-1344b600-4b39-11e9-815b-69a32ece50ee.png)

В данной ситуации хинт позиционируется в положении `top right`, это когда правая граница хинта совпадает с правой границей элемента, на котором триггерится хинт. На данном скриншоте предположу, что у кнопки есть падинги, этим можно объяснить то почему правая граница уехала дальше чем правый край круга выделения кнопки.

Свойство `pos="top"` подразумевает, что хинт должен пытаться спозиционироваться в одном из доступных положения из `['top center', 'top left', 'top right']`. В соответствии того как представлено на скриншоте выше, `top left` и `top center` не подходят, так как в таком случае текст начинает выезжать за границы вьюпорта.

Сместить pin к центру элемента для положений `top left` и `top right` мы не можем, так как это сломает другие сценарии использования.

Есть альтернативный вариант, форсить позицию в значении `top center` и расширить логику позиционирования pin таким образом, чтобы он мог смещаться, если контент тултипа оказывается у границы экрана. Но у такого решения есть нюансы, например, контент тултипа будет находится вплотную к границе.

![Screenshot 2020-03-17 at 10 25 00](https://user-images.githubusercontent.com/6397708/76824644-91659680-6839-11ea-9426-53655d6db558.png)

Ещё один вариант, это разделить логику позиционирования, добавив свойство `align`, с помощью которого можно было бы задавать выравнивание pin тултипа. В таком случае `align="center" pos="top"` должны приводить к тому что контент тултипа в текущей логике позиционируется в положении `top right`, а свойство `align="center"` говорит pin'у, что тот должен находится по центру элемента.

Надо обсудить вопрос с @dzekh

**Comment by dzekh** [comment]
Мне кажется что с позиционированием самого тултипа и хинта нужно оставить все так как есть, можно изменить логику позиционирования клюва хинта, относительно объекта на который он указывает. Если это возможно. Но это тоже не во всех случаях нужно и не всегда будет хорошо.

Логика такая — хинт позиционируется и выравнивается так как ему указано в параметрах, как раньше, а клюв выравнивается по центру объекта на который он указывает, но нужно видимо будет  управлять этим отдельным просом: 


![хинт](https://user-images.githubusercontent.com/26383080/76832312-ef4eaa00-684a-11ea-908d-62907b3902a7.png)

**Comment by dzekh** [comment]
Но тут похоже нужно будет еще накрутить логику, которая бы отслеживала размеры хинта, чтоб в случаях когда хинт меньше родительского объекта клюв от него не оторвался:

![Хинт3](https://user-images.githubusercontent.com/26383080/76835436-e8c33100-6850-11ea-8710-ea1ad5454949.png)

**Comment by dzekh** [comment]
Снимаю тег баг, потому как это улучшение. Закрываю тут, так как завел задачу в ютреке: IF-640 Hint, Tooltip: Улучшение позиционирования клюва.

**Comment by JackUait** [comment]
> IF-640

Не вижу такой задачи на YT, последняя задача - IF-639

**Comment by dzekh** [comment]
> Не вижу такой задачи 

проверил, есть

**Comment by JackUait** [comment]
А можешь скинуть ссылку на неё в телеге? Ибо у меня идёт IF-639 и следующая за ней - IF-643 (которую я создавал) и затем IF-644 (которую создавал ты). У меня где-то три задачи потерялись: IF-640, IF-641 и IF-642. Беклог проверял, их там нет
