### ISSUE TITLE
[Sidepage] Закрывается при клике на скролбар

### ISSUE THREAD

**Issue by govorukhin-do** [skbkontur/retail-ui#1934]
Если открыть сайдпейдж на странице, у которой есть горизантальные или вертикальный скролбары, тогда сайдпейдж закроется при клике в любом месте скролбара.
Проблемы нет если скролить колесом мыши или через жесты тачпада. 
Ожидаемое поведение. сайдпейдж не закрывается по клику на скролбары. содержимое страницы при этом скроллится. 

Проблема возникает когда ignoreBackgroundClick disabled

**Comment by wKich** [comment]
Можешь предоставить код для воспроизведения?

Так как у меня не получается воспроизвести:
<details>

```jsx
let initialState = { opened: false };

function renderSidePage() {
  return (
    <SidePage blockBackground={false}>
      <SidePage.Header>Title</SidePage.Header>
      <SidePage.Body>
        <p>Use rxjs operators with react hooks</p>
      </SidePage.Body>
      <SidePage.Footer panel>
        <Button onClick={close}>Close</Button>
      </SidePage.Footer>
    </SidePage>
  );
}

function open() {
  setState({ opened: true });
}

function close() {
  setState({ opened: false });
}

<div>
  {state.opened && renderSidePage()}
  <Button onClick={open}>Open</Button>
</div>;
```

</details>

**Comment by govorukhin-do** [comment]
`
export const SidePageTestComponent = () => {
  const [isOpened, updateIsOpened] = React.useState(true);

  return (
    <div style={{ width: '4000px', height: '4000px' }}>
      <Button onClick={() => updateIsOpened(true)}>Open</Button>
      <div id="sidepage-wrapper" style={{ width: '40px', height: '40px' }}>
        {isOpened && (
          <SidePage width={385} onClose={() => updateIsOpened(false)}>
            <SidePage.Header>Title</SidePage.Header>
            <SidePage.Body>
              <div style={{ padding: '0 35px 35px 35px' }}></div>
            </SidePage.Body>
            <SidePage.Footer>
              <Button size="large">Close</Button>
            </SidePage.Footer>
          </SidePage>
        )}
      </div>
    </div>
  );
};
`

**Comment by wKich** [comment]
Ага. В таком случае при клике вне SidePage срабатывает вызов свойства `onClose={() => updateIsOpened(false)}`.

Как в твоём понимании должен ли SidePage закрываться при клике вне самого SidePage и вне скроллбара?

Будет ли для тебя достаточным, если мы в `onClose` будем передавать элемент по которому произошло нажатие, а дальше ты сам будешь определять стоит ли закрывать SidePage или нет?

**Comment by govorukhin-do** [comment]
> Как в твоём понимании должен ли SidePage закрываться при клике вне самого SidePage и вне скроллбара?
да, должен

> Будет ли для тебя достаточным, если мы в onClose будем передавать элемент по которому произошло нажатие, а дальше ты сам будешь определять стоит ли закрывать SidePage или нет?
Не будет. Допустим скролбары есть у элемента `body`.   Событие `onClose ` будет срабатывать как по клику на его скролбар, так и внутри элемента. Только в одном случае мне нужно закрыть SidePage, а в другом нет.  Посмотрел на код RabderLayer там используется событие `mousedown`, которое вызывается по клике на скролл, попробовал использовать событие `cliсk`   в том же случае оно не вызывается. Проверял в хроме .

Но знать об элементе, на котором произошел клик полезно для другого кейса. Когда нужно чтобы SidePage закрывался при клике вне самого SidePage и вне скроллбара, но кроме кликов на определенные элементы на страницы.
