### ISSUE TITLE
[Textarea] Ошибка в консоли, если пропс value равен null

### ISSUE THREAD

**Issue by kostyabushuev** [skbkontur/retail-ui#1937]
- Библиотека и её версия: **retail-ui**
- Браузер, его версию, ОС: **Chrome 80.0.3987.132** / **Firefox 73.0.1**; **Window 10** / **Linux**
- Сценарий или произведенные действия: Если в пропс **value** будет значение, равное `null`, то то при следующем нажатии клавиши в консоли выпадет ошибка `Cannot read property 'toString' of null`

**Comment by wKich** [comment]
Компонент `Textarea` использует типы нативного HTML элемента `textarea`. В типах value может быть `undefined | string | string[] | number`. Поэтому у тебя скорее всего при передаче `null` в value должна быть ошибка типов в typescript
<img width="590" alt="Screenshot 2020-03-17 at 11 04 26" src="https://user-images.githubusercontent.com/6397708/76826799-2c14a400-683f-11ea-8347-65672095c0a2.png">
