### ISSUE TITLE
[SidePage] блокирует содержимое страницы с выключенным blockBackground

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#1949]
После коммита 1c6e71a в версии 1.10.0 SidePage не позволяет взаимодействовать с остальной страницей без blockBackground (и с ignoreBackgroundClick).

**Comment by govorukhin-do** [comment]
да мне эта проблема тоже сильно  мешать начала, когда версию библиотеки поднял

**Comment by zhzz** [comment]
Фикс уже в пути.
