### ISSUE TITLE
[Button] Не срабатывает стиль :focus при возврате на страницу из другого окна

### ISSUE THREAD

**Issue by Ollisteka** [skbkontur/retail-ui#1950]
Привет! 

Есть кнопка, при клике на которую открывается новое окно.

При клике происходит `onFocus`, при открытии нового окна `onBlur`, а если закрыть новое окно — снова происходит `onFocus` на эту же кнопку. Но только сама кнопка не обновляет свои стили, и не выглядит как сфокусированная. И так при любом `use`

![ButtonBug](https://user-images.githubusercontent.com/27495566/77040358-95c8b580-69d9-11ea-841c-6ed406a75a91.gif)

retail-ui, 1.9.0
Google Chrome 80.0.3987.132, Windows 10

**Comment by wKich** [comment]
Достаточно спорный момент. Учитывая ещё тот факт, что разные браузеры ведут себя по разному даже с нативными кнопками.

![Screen Recording 2020-03-20 at 11 11 48](https://user-images.githubusercontent.com/6397708/77140846-b86fd280-6a9c-11ea-8559-5d830e77bd20.gif)

![Screen Recording 2020-03-20 at 11 19 17](https://user-images.githubusercontent.com/6397708/77140949-0a185d00-6a9d-11ea-957a-7ac235e31caa.gif)
