### ISSUE TITLE
[react-ui] unpredictable theming

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#1952]
Ветка `next`
Странный эффект, при попытке кастомизировать кнопку.

<details><summary>Странный эффект .gif</summary>

| ![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/2708211/77287418-59f26080-6cf7-11ea-9f93-8fd78513298c.gif) |
| --- |

</details>

В данном примере, переменная `btnSmallBorderRadius` меняет название класса `sizeSmall(t)`, т.к. название зависит от содержимого (поведение `emotion`).
Название класса `sizeSmall(t)` используется в классе `root(t)`, из-за чего класс `root(t)` с "новым" содержимым создаёт новый тэг `<style>`, с теми же стилями по сути, но уже с большим приоритетом.
Класс `root(t)` включает в себя миксин `resetButton()`, стили которого и перебивают стили темизации..

---

Есть два сомнительный решения:
1. #1959 - быстрый и простой.
2. #1951 - долгий и сложный.

Оба заставляют задуматься об избавлении от каскада в стилях, или поиска альтернативы для `Emotion`.

3. #2128 - другие альтернативы

**Comment by zhzz** [comment]
#2061
