### ISSUE TITLE
[Input] Добавить возможность "нормализации" строки перед onBlur

### ISSUE THREAD

**Issue by slawwan** [skbkontur/retail-ui#1960]
Иногда есть потребность нормализовать пробелы в веденной в input строке

- убрать висячие пробелы в начале и в конце строки
- схлопнуть двойные/тройные пробельные символы в одинаные пробелы

предлагаю решить это новым пропом `normalize?: Nullable<"none" | "trim" | "whitespaces">`

если указаны `"trim"` или `"whitespaces"` то перед вызовом `onBlur` вызывать `onChange` с нормализованным значением.

пропс `normalize` можно будет доработать со времнем, например, он может принимать массив "правил нормализации" и правилом может быть функция `(value: string) => string`

нормализация может касаться не только пробелов, но например:

- изменение регистра символов в строке
- приведение кавычек к единому виду
- исключение "лишних" символов
- любые трансформации строк

**Comment by mortifer** [comment]
а должен ли это все-таки контрол делать?

**Comment by wKich** [comment]
Я согласен с Мишей, это не задача контрола. Не будет ли это конфликтовать с валидацией на onBlur?

**Comment by slawwan** [comment]
@wKich с валидацией не конфликтует, я сейчас запилил это руками по месту:

- на onChange обычный setState
- на onBlur setState нормальзованного значения, в моем случае это trim того что сейчас в state

валидация подхватывает уже нормализованное значение

**Comment by dzekh** [comment]
Решили не делать.
