### ISSUE TITLE
[Toggle] кастомизация цвета

### ISSUE THREAD

**Issue by govorukhin-do** [skbkontur/retail-ui#1986]
Судя по гайдам можно кастомизировать цвет тогла. 
Сейчас эта фича реализована с визуальными косяками. Если задать проп `color`, то с правой и с левой стороны становится видна синяя обводка
![image](https://user-images.githubusercontent.com/9696631/78668303-e2762100-78f3-11ea-8699-682a95783b1a.png)

**Comment by zhzz** [comment]
Фиксится в #1987, но

> проп стоит задеприкейтить, и реализовать функциональность через темизацию.

Нужно обратить внимание на то, что проп `color` перекрывает стили `error` и `warning`.

**Comment by dzekh** [comment]
Нужно будет задиприкейтить в 3.0 а потом удалить

**Comment by dzekh** [comment]
Кажется что сделано, закрываю.
