### ISSUE TITLE
[Currencylabel] Не работает кругление с fractionDigits

### ISSUE THREAD

**Issue by rchkv** [skbkontur/retail-ui#1998]
- react-ui 1.6.9, 2.1.1
- Любое значение fractionDigits не работает

![изображение](https://user-images.githubusercontent.com/18264667/79430957-28fa0880-7fe3-11ea-89be-59460a1b04c6.png)

**Comment by zhzz** [comment]
Интересный вопрос. А в какую сторону нужно округлять, или просто отбрасывать?

**Comment by lossir** [comment]
Думаю, что контрол должен округлять значение к меньшему по модулю, т.е. отбрасывать лишние разряды. При вставке значения в `CurrencyInput` мы уже так делаем (`Currencylabel` использует хелперы `CurrencyInput`).
`CurrencyInput` тоже пропускает первичное значение как есть.

**Comment by rchkv** [comment]
> Думаю, что контрол должен округлять значение к меньшему по модулю, т.е. отбрасывать лишние разряды

Предполагал такой вариант

**Comment by wKich** [comment]
Там же вроде должна быть proptypes валидация, как раз по этому поводу.

**Comment by dzekh** [comment]
Кажется опасно делать что-то с данными в контроле — везде разные правила скругления. Если нужно округлить значение лучше реализовать это отдельной функцией в продукте, этот проп нужен, чтобы зарезервировать нулями необходимое количество знаков после запятой. 

Пока закрываю. Если будут еще подобные запросы — вернемся к этой теме.

**Comment by JackUait** [comment]
Максим (@lossir), а на твоём дежурстве не подобный вопрос пару недель назад прилетал?
