### ISSUE TITLE
[Toggle] Не меняет значение нажатие Enter во время фокуса 

### ISSUE THREAD

**Issue by chervyakovru** [skbkontur/retail-ui#2000]
- @skbkontur/react-ui 2.1.1 (2020-04-14)
- При фокусе на тоггле не меняется значение на нажатие Enter;

![image](https://user-images.githubusercontent.com/14909082/79467383-29ac9200-8017-11ea-8dab-951eca12b672.png)

https://tech.skbkontur.ru/react-ui/#/Components/Toggle

**Comment by rustho** [comment]
А почему должно менять значение на Enter? Нативный меняет значение на Space
@dzekh нужна твоя помощь

**Comment by dzekh** [comment]
Нативный на Space, да. Enter обычно либо отправляет форму, открывает модалку, либо в таблицах переносит фокус на следующее поле, либо переводит в режим редактирования какие-то сложные контролы. 

Кажется тут только Space должен быть.

**Comment by dzekh** [comment]
Пока у нас гайда по работе с клавиатурой нет, давайте на нативные контролы смотреть.

**Comment by chervyakovru** [comment]
Сейчас на пробел значение меняется. Тогда можно закрывать issue?
