### ISSUE TITLE
[Hint]  Не изменяется курсор на курсор с вопросом

### ISSUE THREAD

**Issue by chervyakovru** [skbkontur/retail-ui#2001]
Привет! Опиши, пожалуйста, проблему, которая возникла:

- @skbkontur/react-ui 2.1.1 (2020-04-14)
При наведении не изменяется курсор на курсор с вопросом в соответствии с Гайдом https://guides.kontur.ru/principles/cursor/#Kursor_%C2%ABvopros%C2%BB

![image](https://user-images.githubusercontent.com/14909082/79474176-83b15580-801f-11ea-993e-d05d6c514554.png)

https://tech.skbkontur.ru/react-ui/#/Components/Hint

**Comment by zhzz** [comment]
В гайде ничего не говорится конкретно про Хинт. А подсказки легко можно делать и Тултипами. Но это не единственное применение этих контролов. Нельзя же всем по умолчанию ставить такой курсор. Однако, его легко сделать самому:

```jsx
<Hint text="World"><span style={{ cursor: 'help' }}>Hello</span></Hint>
```

**Comment by chervyakovru** [comment]
В гайде говорится обо всех подсказках, появляющихся не по клику, а при наведению по таймауту. Хинт как раз является частной реализацией такой подсказки.

В примере в документации как раз наглядный пример, когда пользователь не ожидает увидеть подсказку и может так и не узнать о том, что она есть на этом элементе.
В Тултипе, открывающимся при наведении тоже, на мой взгляд, нужно реализовать изменение курсора.
Не понимаю почему нельзя установить такое поведение по умолчанию. Оно же напрямую выходит из Гайдов

**Comment by dzekh** [comment]
Хинты используются не только для подсказок, хинт может появиться как подсказка к пункту меню — это обычный интерактивный элемент, при наведении на него должен появляться палец. Библиотека не может реализовать всё, что написано в гайдах, гайды в большинстве случаев это рекомендации — как правильно использовать контролы.  Я считаю не правильным делать такое поведение по умолчанию.

Ну и гайд про курсор — устаревший черновик, там в самом верху на желтой плашке сообщение про это. Я бы не стал на него ориентироваться пока, он может измениться.
