### ISSUE TITLE
[validations] Тултипы right-middle заезжают на инупт

### ISSUE THREAD

**Issue by rustho** [skbkontur/retail-ui#2005]
На витрине валидаций съехали тултипы 
![image](https://user-images.githubusercontent.com/26579566/79733359-670e6980-830e-11ea-962c-9218c6990b7e.png)
кажется, что это может быть большой проблемой

**Comment by aagordienko** [comment]
у нас не только для валидаций, но вообще все тултипы

![Screenshot_3](https://user-images.githubusercontent.com/30799122/79744073-670e6980-830e-11ea-83d0-4980f4ff2a6f.png)
![Screenshot_2](https://user-images.githubusercontent.com/30799122/79744074-67a70000-830e-11ea-8021-0b8eee0ee14a.png)
![Screenshot_1](https://user-images.githubusercontent.com/30799122/79744076-683f9680-830e-11ea-93ce-091216ec2b87.png)
![Screenshot_4](https://user-images.githubusercontent.com/30799122/79744354-e308b180-830e-11ea-8771-3ef472cb6330.png)

**Comment by lossir** [comment]
@aagordienko Привет.
Напиши, пожалуйста, версии пакетов и фрагмент кода. Не могу воспроизвести где-то ещё, кроме валидаций.
Если в проекте есть какой-нибудь `reset.css`, его тоже скинь.

**Comment by wKich** [comment]
А разве мы не переключили значение `useWrapper` для тултипов в 2.0?

**Comment by zhzz** [comment]
> А разве мы не переключили значение `useWrapper` для тултипов в 2.0?

Нет, он еще `true`. Мы собирались?

**Comment by zhzz** [comment]
Все из-за того, что после перехода с `cx()` на  `cn()`, в некоторых случаях нарушается порядок применения стилей анимации.

https://github.com/skbkontur/retail-ui/blob/9698d021b5ea677ae35cb55b9b07e683ce0ffce2/packages/react-ui/internal/Popup/Popup.styles.ts#L69

Подпадают все попапы с анимацией, не только тултипы.

**Comment by zhzz** [comment]
В качестве временного решения можно отключать анимацию у контролов.

**Comment by Aspromist** [comment]
Обнаружил так же наезжание меню в компоненте DropdownMenu. на текущий момент повторяется в последней версии react-ui 2.3.1. Можно воспроизвести при копировании базового примера из документации этого компонента.

Вот скрин:
![dropdownmenu](https://user-images.githubusercontent.com/15010291/86350233-d17f4680-bc7b-11ea-8b49-7d2c55c6404a.png)

**Comment by Ollisteka** [comment]
У нас тоже поехали тултипы:
![image](https://user-images.githubusercontent.com/27495566/91017815-269a6180-e608-11ea-8244-a5563a27a70d.png)
![image](https://user-images.githubusercontent.com/27495566/91017874-3ca82200-e608-11ea-912c-03b6fec97465.png)

И пример [с витрины](https://tech.skbkontur.ru/react-ui/#/Components/Tooltip) не работает:
![image](https://user-images.githubusercontent.com/27495566/91018055-8264ea80-e608-11ea-84c1-60846db2d703.png)

(react-ui — 2.2.0)

**Comment by zhzz** [comment]
Уже работаем над решением.
