### ISSUE TITLE
[Currencyinput] Указать ссылку ссылку на react-ui-validations

### ISSUE THREAD

**Issue by chervyakovru** [skbkontur/retail-ui#2006]
Было бы удобно указать в документации к компонентам инпутов ссылку на библиотеку валидации [react-ui-validations](http://tech.skbkontur.ru/react-ui-validations)

**Comment by dzekh** [comment]
Наверное не только в карренсиинпуте а где-то еще, на верхнем уровне. Так же как и ссылку на парковку.
