### ISSUE TITLE
[Tooltip] Пропал крестик для закрытия после апдейта major версии

### ISSUE THREAD

**Issue by Rozentor** [skbkontur/retail-ui#2008]
**Setup**
@skbkontur/react-ui 2.1.1
Win10, Google Chrome 81.0.4044.113 

**Анамнез**
Обновил react-ui с 1.6.6 до 2.1.1
Появился баг в тултипе - пропал крестик для закрытия.

**Исследование**
Посмотрел стили.
![image](https://user-images.githubusercontent.com/36932390/79833863-8916f300-83c5-11ea-98e8-9b16c9db96de.png)
![image](https://user-images.githubusercontent.com/36932390/79835463-33901580-83c8-11ea-8927-a3e82a332580.png)
div, который содержит svg с крестиком, "схлопнулся". Его width 8px, padding 4px и из-за того, что у меня присутствует стиль 
```
*  {
    box-sizing: border-box;
}
```
Размер контента этого дива = 0, что скрывает показ крестика.

**Почему работало ранее?**
Раньше у этого div-а был прописан ```box-sizing: content-box;```

**Почему я считаю, что стоит поменять стили у вас, а не у себя?**
Стиль ```* box-sizing``` довольно популярен, он позволяет "меньше думать" при написании стилей. Многие проекты его используют.

**Возможное решение**
- Вернуть ```box-sizing: content-box;```, как это было раньше 
- Добавить больше стилей для кастомизации в ThemeContext для Tooltip

Как я понимаю, изменения были сделаны в коммите "fix(Tooltip): update close icon by guides"
https://github.com/skbkontur/retail-ui/commit/65a662668ce30154135ed7c9e4ef6bd052886258
И вмержены в ПР https://github.com/skbkontur/retail-ui/pull/1793 
Я не нашёл там объяснений почему удалили стиль. Может я что-то не понял? Может есть причина почему это должно быть так, а не иначе?

**Comment by lossir** [comment]
Привет. Спасибо за такой развёрнутый вопрос. Очень удобно и приятно читать)

Думаю, что причина, по которой это плавило было удалено, в том, что это значение по умолчанию. При возможности мы удаляем такие правила, т.к. они бессмысленны.
Но мы не используем никаких `reset.css`, из-за чего и пропустили этот случай.

Соглашусь, что это правило надо добавить на нашей стороне. Считаю, что нам в принципе стоит подключить самый популярный `reset.css`, для избежания таких случаев в будущем.
