### ISSUE TITLE
[react-ui / Button] !important в стилях

### ISSUE THREAD

**Issue by coolassassin** [skbkontur/retail-ui#2018]
@skbkontur/react-ui 2.2.0
Браузер и ОС любые.

После перехода на 2-ую версию библиотеки в коде стилей кнопки появился `!important`:
**[Button.mixins.ts](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/components/Button/Button.mixins.ts#L140)**

В КабУЦ разрабатывается **[компонент подписания DSS сертификатом](https://git.skbkontur.ru/cacabinet/cloudcrypt-js)**. И в его реализации при использовании библиотеки ниже 2.0 была кастомизация, которая сломалась из-за этого `!important`. И для перехода на новую версию мы вынуждены писать `!important` в своем коде.

**[Вот](https://git.skbkontur.ru/cacabinet/cloudcrypt-js/-/blob/master/src/DSSInfo/DSSInfo.tsx#L48)** использование кнопки в коде. **[Вот](https://git.skbkontur.ru/cacabinet/cloudcrypt-js/-/blob/master/src/DSSInfo/DSSInfo.css#L43)** стили которые сломались.

В телеграм-чате контролов мне не смогли объяснить необходимости этого `!important`.
Если причин в этом important нет, то кажется его правильнее убрать, поскольку в целом это не красивое решение и вынуждает делать такие же решения остальных.

**Comment by zhzz** [comment]
Я вижу проблему в том, что кнопка-ссылка не наследует font-size, как обычная ссылка. Это можно обсудить с @dzeh и поправить. 

И действительно, `!important` в стилях, вероятно, излишний. Можно его убрать ради чистоты кода.

Но стоит еще заметить, что такой способ кастомизации через прямое вмешательство в стили не рекомендуется, используется на свой страх и риск, и может сломаться в любой момент. Что, собственно, тут и произошло. 

Всегда лучше использовать стандартную кастомизацию, и сообщать нам, если что-то не получается.

**Comment by dzekh** [comment]
А можно подробней про: «кнопка-ссылка не наследует font-size, как обычная ссылка» не наследует откуда и что это значит?

**Comment by agelico** [comment]
Не наследует из окружения.
Это значит, что когда ссылка стоит в тексте, размер шрифта такой же, что и у окружающего текста. Для кнопки-ссылки в react-ui это не работает, у неё фиксированный размер шрифта, из-за чего она может отличаться по размеру от окружающего текста. Это приходится обкостыливать.

**Comment by dzekh** [comment]
Кажется нужно сделать чтобы кнопка-ссылка наследовала. И в идеале еще и переносилась, если длинная, не целиком, а так же как обычная ссылка.

**Comment by rustho** [comment]
А в чем проблема сделать наследование фонт-сайза? 
Механизм для этого есть (темизация) просто добавить в тему переменную для font-size inherit

**Comment by coolassassin** [comment]
> А в чем проблема сделать наследование фонт-сайза?
> Механизм для этого есть (темизация) просто добавить в тему переменную для font-size inherit

Да нет никакой проблемы в том чтобы закрыть эту проблему, будь то такой же `!important` в стилях перебивающий этот или темизация через контекст для одной небольшой кнопки, похожей на ссылку.
Только любое из этих решений выглядит как костыль из-за до сих пор непонятного решения.
Тут не столько речь про конкретно эту ситуацию, а в целом, мы сейчас отказываемся от перехода на новую версию библиотеки, поскольку не уверены что она нам не поломает что-то еще.
Это выстрелило только в одном маленьком проекте, а у нас в команде есть как минимум 6 проектов использующих вашу библиотеку и очень досадно что видимо тестировщикам придется проверять их целиком и полностью чтобы быть уверенными что ничего не сломалось.

**Comment by agelico** [comment]
Астанавитес.

@rustho проблема в том, что даже если игнорировать слона в помещении про пушку по воробьям, повлиять на размер шрифта в кнопке можно, переопределяя `fontSizeSmall` — а это, мягко говоря, вообще не то, что нужно.

@dzekh звучит опасненько: наверняка примерно все интеграторы осознанно или нет полагаются на существующую логику, и у них поломается больше, чем у кого-то починится. Разве что какой-то 100500-ый флаг на кнопку, но сомнительно, что случай настолько частотный, чтобы пилить ему флаги.

Безотносительно костылей, которые кому-то где-то приходится втыкать, ставить `!important`, где он не нужен — просто плохая практика, зачем она вам?

**Comment by rustho** [comment]
> @rustho проблема в том, что даже если игнорировать слона в помещении про пушку по воробьям, повлиять на размер шрифта в кнопке можно, переопределяя `fontSizeSmall` — а это, мягко говоря, вообще не то, что нужно.

Можно использовать `<Link>,` а не `<Button use="link">`. А как ты считаешь нужно менять размер шрифта в кнопке?

> Безотносительно костылей, которые кому-то где-то приходится втыкать, ставить `!important`, где он не нужен — просто плохая практика, зачем она вам?

Понятно, что от него мы избавимся в скором времени, но это не отменяет того факта, что нужно использовать кастомизацию через themecontext

**Comment by agelico** [comment]
> Можно использовать `<Link>`, а не `<Button use="link">`
Это же просто ещё один тип костыля, а не решение. Этот приносит в жертву семантику.

> А как ты считаешь нужно менять размер шрифта в кнопке?
Я считаю не надо мешать людям навешивать классы, но для вас это вопрос религиозный и не стоит о нём.
В таких случаях в своём проекте я просто не использую react-ui кнопки. Но в особом случае из топикстартера это невозможно, к сожалению.
