### ISSUE TITLE
[Tooltip] Показывается сразу после того как скрылся

### ISSUE THREAD

**Issue by RomanGorgol** [skbkontur/retail-ui#2022]
Привет! Тултип показывается сразу после того как скрылся, если вести мышкой в направлении тултипа (т е если тултип снизу, то сверху вниз, тултип справа - слева направо и т д)

- @skbkontur/react-ui 2.2.0, @skbkontur/react-icons 4.3.0 
- Windows  10, Chrome 81.0.4044.122 64 bit;
- Сценарий:
Есть тултип, который показывается по наведению на элемент
Вести мышкой по элементу в направлении тултипа (если тултип показывается снизу относительно элемента, то сверху вниз, справа - слева направо и т д)
- Пример
![2020-04-30_08-33-11](https://user-images.githubusercontent.com/5558706/80670112-856b2680-8abf-11ea-8e1e-cd453cd1d9e1.gif)

**Comment by dzekh** [comment]
Привет! 
Да, это нормально. По другому пока никак не реализовать. Пока мышь над тултипом он не должен исчезать, поэтому он появляется снова, как только мышь попадает на тултип. Можно увеличить задержку перед исчезновением, но всё равно можно будет подобрать такую скорость курсора при котором это будет воспроизводиться.

**Comment by dzekh** [comment]
Если есть понимание как от этого избавиться, закинь PR или предложи в комментах

**Comment by wKich** [comment]
Можно некий таймаут выставить. Тут скорее ещё проблема в том, что при проигрывании анимации скрытия тултип ловит события на ховер и начинает появляться снова. Кажется сценарий должен быть примерно такой:
- Курсор покидает область trigger элемента
- Активируется таймаут равным по времени анимации или около того
- Если курсор попадает в область trigger элемент или область контента тултипа, таймаут сбрасывается
- Иначе по окончании таймаута начинает проигрываться анмация скрытия, все последующие события на области контента тултипа игнорируются.

**Comment by dzekh** [comment]
Начиная c 3.9.4 отключена анимация исчезновения и не воспроизводится. Но почему пропала анимация не понятно. Кажется что она пропала не законно.
