### ISSUE TITLE
[react-ui][DatePicker] Ширина поля не зависит от size

### ISSUE THREAD

**Issue by coolassassin** [skbkontur/retail-ui#2025]
@skbkontur/react-ui 2.1.1
Браузер: любой

Изменяя пропс size у DatePicker не изменяется стандартная ширина DatePicker из-за чего, если указать `size="large"` то дата не помещается в input.

Ожидаемое поведение:
При изменении size менять ширину, в том числе и для `small`

**Comment by coolassassin** [comment]
Кажется проблема исключительно в том что в новом react-ui появился паддинг слева от иконки, которого раньше не было. Размер не менялся и раньше, но и календарь не перекрывал дату, как сейчас.

**Comment by dzekh** [comment]
@lossir, а что у нас тестов на этот размер не было?

**Comment by lossir** [comment]
@dzekh есть, судя по стори. И для `medium` и для `large`. Будем разбираться, что пошло не так.

**Comment by coolassassin** [comment]
А можно как-то поднять приоритет бага?
Он просто влияет на визуал и мы уже не первый месяц с релиза библиотеки не можем обновиться :(

**Comment by lossir** [comment]
@coolassassin можно)
Завтра возьму в работу. В ближайшее время постараемся выпустить.

**Comment by dzekh** [comment]
Я что-то не так делаю может, но у меня дата для `size="large"` и `size="medium"` [в доке](https://tech.skbkontur.ru/react-ui/#/Components/DatePicker) до сих пор не помещается в инпут и его дефолтная ширина не зависит от `size`:
![image](https://user-images.githubusercontent.com/26383080/139622983-f17f8205-5f82-40d1-a7d4-9ce47043c665.png)
![image](https://user-images.githubusercontent.com/26383080/139623039-67df693e-cf1b-4dd9-8ebf-917e601b0778.png)

**Comment by zhzz** [comment]
Правили для темы со старыми размерами, сломалось в 8px с новыми отступами.

**Comment by dzekh** [comment]
Тестировал в хроме на маке — в доке, в размерах  `size="large"` и  `size="medium"` пустое поле при фокусе меняет размер — без фокуса меньше, в фокусе и заполненное без фокуса — больше.
