### ISSUE TITLE
[ComboBox / SeleniumTesting] Проблема с тестированием

### ISSUE THREAD

**Issue by RomanKhasanov** [skbkontur/retail-ui#2029]
При обновлении **ComboBoxOld** на **ComboBox** падают тесты, тест перестал дожидаться меню комбобокса.

Библиотека **Kontur.ReactUI.SeleniumTesting 3.0.0**
Можно воспроизвести с помощью метода **InputTextAndSelectFirst**
**retail-ui 1.9.0**
chrome 69 для тестов, вручную воспроизводил на chrome 81

stacktrace одного из тестов
> SKBKontur.SeleniumTesting.ElementNotFoundException : Элемент SKBKontur.SeleniumTesting.Controls.ControlListBase`1[SKBKontur.SeleniumTesting.Controls.Label] по правилу Menu не найден внутри элемента Portal
  ----> OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"css selector","selector":"[data-comp-name~='Menu']"}
  (Session info: chrome=53.0.2785.116)
  (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 10.0.17763 x86_64)
   at SKBKontur.SeleniumTesting.ControlBase.GetNativeElement()
   at SKBKontur.SeleniumTesting.ControlBase.GetValueFromElement[TResult](Func`2 action)
   at SKBKontur.SeleniumTesting.Controls.ControlListBase`1.<get_Count>b__2_0()
   at Kontur.RetryableAssertions.ValueProviding.ValueProvider.ValueProviderImplementation`2.GetValue()
   at Kontur.RetryableAssertions.Wait.Assertion[T,TSource](IValueProvider`2 valueProvider, IAssertionConfiguration`1 configuration)
   at SKBKontur.SeleniumTesting.Controls.ComboBox.InputTextAndSelectFirst(String inputText, Timings timings)

Другой кейс.
Прикладываю 3 скриншота. 
1 - начальное состояние
![1](https://user-images.githubusercontent.com/19207164/82188815-e2603c80-9907-11ea-8d4e-e6096c6d84f8.PNG)

2 - после `ComboBox.InputTextAndSelectFirst("66")` в тесте
![2](https://user-images.githubusercontent.com/19207164/82188817-e3916980-9907-11ea-852f-f8501df3f9db.PNG)

3 - после ручного ввода
![3](https://user-images.githubusercontent.com/19207164/82188819-e42a0000-9907-11ea-9957-b8260f16a319.PNG)

Update.
Метод **InputTextAndSelectSingle** работает. Показалось, что тестовая обвязка дружила со старым комбо из-за того что комбо перед выдачей занулял список. Нашел вот такой код в **ComboBoxOldRenderer**:
> componentWillReceiveProps = function componentWillReceiveProps(newProps) {
    this._maybeRefetchInfo(newProps.value, newProps.info);
  };_proto.

> _maybeRefetchInfo = function _maybeRefetchInfo(value, info) {
    if (typeof info !== 'function') {
      return;
    }
    var props = this.props;
    if (value === props.value && typeof props.info === 'function') {
      // Values hasn't changed and info is still a function. So we are already
      // fetching info.
      return;
    }
    this.setState({ info: null });
    this._fetchInfo(value, info);
  };_proto.

**Comment by zhzz** [comment]
У нового комбобокса при текущих настройках функции debounce есть задержка 300мс перед запуском поиска. Из-за нее на скриншоте 2 выбирается Карелия, а не Свердловская область. Задержка скорее всего лишняя и была добавлена неосознанно.  Если от нее избавиться, то в купе с правками из #2032 должно помочь с этим issue.

**Comment by dzekh** [comment]
@zhzz почему ты думаешь лишняя? 
Эта задержка нужна, чтоб не отправлялся запрос после ввода каждого символа, чтоб только после того как введено подряд несколько и мы немного более уверены, что пользователь закончил вводить и ждёт ответа. Насколько я понимаю.

**Comment by zhzz** [comment]
@dzekh на каждый символ запрос отправляться не будет. Я хотел предложить пропускать без задержки только самый первый запрос (ввод первого символа или вставку из буфера обмена). Тогда комбобокс стал бы более отзывчивым. Сейчас может сложиться впечатление, что он тормозит, когда его первая реакция происходит только через 300+ мс после окончания ввода. И открытие по фокусу тоже из-за этого отстает.

Есть еще вариант дополнительно пропускать запрос каждые N мс во время ввода.

**Comment by rustho** [comment]
согласен с @zhzz 
Кажется логика с задержкой должна быть сделана на стороне человека, который использует нашу библиотеку, а не на нашей, так как мы покрываем разные сценарии. Либо вообще сделать отдельный проп для задержки.
