### ISSUE TITLE
[validations] Библиотека валидаций не работает в Codesandbox

### ISSUE THREAD

**Issue by denexapp** [skbkontur/retail-ui#2039]
При попытке импорта ValidationsWrapper из '@skbkontur/react-ui-validations' появляется ошибка ModuleNotFoundError.

Пример ошибки: https://codesandbox.io/s/test-fplfh

Версии:
@skbkontur/react-ui 2.3.0
@skbkontur/react-ui-validations 1.1.5

![image](https://user-images.githubusercontent.com/3131467/83258648-0a855080-a1d0-11ea-9db5-096533ea9311.png)

**Comment by zhzz** [comment]
Да, это из-за [динамического импорта](https://github.com/skbkontur/retail-ui/blob/478618384260cdd91787a8d68e94ccc243727c7a/packages/react-ui-validations/src/ReactUiDetection.ts#L8). Есть в планах что-нибудь с этим сделать.
