### ISSUE TITLE
[DatePicker] Не синхронизируются настоящее значение даты и строка в инпуте IF-203

### ISSUE THREAD

**Issue by Shururup** [skbkontur/retail-ui#2041]
@skbkontur/react-ui: "1.9.0"
Сценарий: В контролле даты есть валидация на минимальную дату через пропс minDate (например, 1.05.2020).  Если ввести руками в инпут даты невалидное значение (например, 1.04.2020), то оно визуально останется в строке, но под капотом сохранится прежнее валидное значение.

Судя по всему, так происходит, потому что мы отдаем наверх один и тот же `value` в пропсах (потому что он не поменялся на валидный и остался таким же), и вот эта проверка не проходит: https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/components/DateInput/DateInput.tsx#L114
Поэтому метод `this.updateFromProps()` не вызывается

**Comment by lossir** [comment]
Привет. Спасибо за подробное описание)
Сразу хочу уточнить. Указана версия `1.9.0`, но ссылка ведёт на `master` (`2.х`). В последней версии компонент был серьёзно отрефачен.

Однако, указанное поведение считается ожидаемым по нескольким причинам:
1. исторически так сложилось.
2. менять поведение таких сложных компонентов проблемно.

Проблемно, в первую очередь потому, что нет однозначного понимания, как именно *должно быть*. Во вторую очередь, это сложность миграции с одного, привычного многим поведения, на новое, непривычное. И без железных обоснований это превращается в неконструктивный спор, а ля "ну лично мне удобнее вот так".
Мы будет крайне благодарны, если ты подробно опишешь поведение, которое ожидаешь в подобных случаях. И приведёшь аргументы, плюсы и минусы такого поведения.

Это уже не первой подобный вопрос по `DateInput`/`DatePicker`, и мы планируем серьёзно взяться за детальную проработку сценариев его использования и поведения. И аргументы непосредственных пользователей нам будут очень полезны.

**Comment by dzekh** [comment]
Закрываю, потому что кажется, что вопрос отвечен. Ссылку на кейс добавил в ютрек.
