### ISSUE TITLE
[Modal,ZIndex] ModalFooter наезжает на DropdownContainer в режиме disablePortal IF-644

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#2067]
![image](https://user-images.githubusercontent.com/4607770/87033740-3a2c6d00-c200-11ea-97d2-ea5147632253.png)

Есть предположение, что ModalFooter и ModalHeader не должны перекрывать содержимое ModalBody, пока они не залипли к верху или низу страницы, как они уже умеют.

Прототип решения накидан в ветке `modal-zindex-fix`, и отдан на тест @aagordienko в версии `@skbkontur/react-ui@0.0.0-1215609799`.

**Comment by aagordienko** [comment]
При незалипших шапке-футере всё ок, с залипшими тоже, в целом, выглядит неплохо.
Обертки над айтемами, фиксирующей их ширину нет.

![-001](https://user-images.githubusercontent.com/30799122/87139423-a19df780-c2a8-11ea-981a-ff91e12010f3.png)
![-002](https://user-images.githubusercontent.com/30799122/87139432-a5317e80-c2a8-11ea-8942-9b5110e6173d.png)
![изображение](https://user-images.githubusercontent.com/30799122/87139591-ecb80a80-c2a8-11ea-9319-16e9271ad5b5.png)

**Comment by dzekh** [comment]
А это точно еще не влито? 
Вроде уже протестировано. Нет только ссылок на пулл-реквесты. @zhzz ?

**Comment by zhzz** [comment]
Не влито

**Comment by JackUait** [comment]
Может добьём задачку? Помню не так давно (пару месяцев назад) на это поведение уже жаловались
