### ISSUE TITLE
[Checkbox] Неправильно трекается состояние фокуса IF-641

### ISSUE THREAD

**Issue by nulladdict** [skbkontur/retail-ui#2069]
- @skbkontur/react-ui на стенде
- Сценарий или произведенные действия: нажимать tab в комбинации с другой клавишей (?)
- Прикрепи скриншот или гифку с примером: [Screen Recording 2020-07-16 at 7.45.52 PM.zip](https://github.com/skbkontur/retail-ui/files/4932191/Screen.Recording.2020-07-16.at.7.45.52.PM.zip)

**Comment by dzekh** [comment]
Попробовал в хроме на маке, не смог воспроизвести.

**Comment by JackUait** [comment]
> Попробовал в хроме на маке, не смог воспроизвести.

Плюсик, тоже не получилось воспроизвести. В названии указана 641-ая задача, но я не нашёл её на ютреке, последняя - 639

**Comment by dzekh** [comment]
@nulladdict получается воспроизвести сейчас?

**Comment by nulladdict** [comment]
тоже больше не получается воспроизвести
