### ISSUE TITLE
Несколько приложений на странице. Ломается отображение компонентов. 

### ISSUE THREAD

**Issue by tokrqui** [skbkontur/retail-ui#2070]
Библиотека @skbkontur/react-ui 2.3.2
Проверено в GoogleChrome и Mozilla Firefox

На странице два рута с разными приложениями на react-ui. При рендеринге компонентов в одном приложении портится отображение компонентов в другом приложении. 

В реальной жизни выглядит так
![header](https://user-images.githubusercontent.com/53790400/87700041-2ad49300-c7af-11ea-8a65-c50ba962f183.gif)

Для воспроизведения сделал тестовый проект.
https://github.com/tokrqui/react-ui-three-apps-test

Выглядит так
![three-apps](https://user-images.githubusercontent.com/53790400/87701121-db8f6200-c7b0-11ea-9f95-5ae0521d39ce.gif)

В этом примере в разных аппках используется Button с разным use.В момент рендера второй кнопки портится отображение кнопки в первой аппке. Select тоже портится.

Возможно причина в этом https://github.com/skbkontur/retail-ui/issues/1952

**Comment by zhzz** [comment]
Причина действительно в #1952 и использовании разных тем. Мы пофиксили Button и Select в 2.3.2. Если обнаружатся другие места, можно создать новое issue.
