### ISSUE TITLE
Link не реагирует на linkHoverTextDecoration и linkHoverColor из темы

### ISSUE THREAD

**Issue by Ame-N** [skbkontur/retail-ui#2072]
@skbkontur/react-ui 2.3.2
Воспроизводится на ThemePlayground на витрине.

В теме передаем `linkHoverTextDecoration: none` и `linkHoverColor` с любым произвольным цветом.

Результат:
`Link` не меняет цвет при наведении, подчеркивание тоже остается.
`Button use="link"` не меняет цвет при наведении.

**Comment by zhzz** [comment]
Сделал [демо](https://codesandbox.io/s/react-ui-template-63wck?file=/src/index.js), линк цвет вроде меняет. Остальное воспроизводится.

**Comment by Ame-N** [comment]
Точно, Link меняет цвет, только Button не меняет.
