### ISSUE TITLE
Проблемы 8px

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#2087]
Предлагаю собирать здесь все проблемы с 8px, которые будут всплывать после релиза 2.4.0.

- [x] Цвет disabled-инпута в 8px, [источник](https://t.me/react_ui/6680).
- [x] Сломанные переменные controlHeight* в старых темах #2079.
- [x] По умолчанию Табы маленького размера, а должны быть large.
- [x] Нет переменных чтобы управлять высотой строки и размером шрифта в токен-инпуте (когда просто вводишь текст). Всё должно быть как в текстэрии. И на эти переменные должны смотреть переменные токенов. 
- [x] У Switcher есть label но его размер не зависит от переменных.
- [x] Привести размеры Switcher в соответствие с 8px-макетами.

**Comment by rustho** [comment]
- [ ] по умолчанию Табы маленького размера, а должны быть large

**Comment by zhzz** [comment]
Чиню в #2088.

**Comment by zhzz** [comment]
По поводу TokenInput.

Я наладил переменные `tokenInputFontSize` и `tokenInputLineHeight`, но токены внутри автоматически подгонять под размер не получится. У их S/M/L размеров отличается не только line-height и font-size, но еще и паддинги. Сейчас токены можно кастомизировать отдельными переменными. А потом проще потом будет все-таки сделать проп `size` для TokenInput и Token, и его можно будет автоматически в токен прокидывать.

**Comment by dzekh** [comment]
Ну ок, хоть так, но вообще странно что отличаются  line-height и font-size. font-size точно должен совпадать.  line-height, если отличается можно компенсировать, изменив отступы сверху и снизу.

**Comment by dzekh** [comment]
В пиаре по ссылке все работает как я описал — всё ок.

**Comment by zhzz** [comment]
> Ну ок, хоть так, но вообще странно что отличаются line-height и font-size. font-size точно должен совпадать. line-height, если отличается можно компенсировать, изменив отступы сверху и снизу.

Не, я имел в виду, что пытаясь переменные Токена завязать на переменные ТокенИнпута, не понятно, что делать с паддингами, они у них не связаны. А font-size и line-height могут быть равны, да.
