### ISSUE TITLE
[Customization] Конфликт цветов при реализации темной темы

### ISSUE THREAD

**Issue by coolassassin** [skbkontur/retail-ui#2089]
@skbkontur/react-ui: 2.4.1
Любой браузер, Win 10

Существует проблема при прописывании стилей для темной темы.
Если в дропдауне указать темный фон то не выходит корректно стилизовать текст внутри.
Если же сделать в дропдауне фон белым, то это приводит к тому что фон в модальном окне тоже становится белым и приходится писать костыли либо для модалок, либо для селектов.

![Вот пример](https://user-images.githubusercontent.com/2708211/89666536-f8244300-d8f3-11ea-83b4-56b6802e0fbe.png)

Проблема с дропдауном проявляется на [Playground](https://tech.skbkontur.ru/react-ui/#/Customization/ThemePlayground) для темной темы.

**Comment by dzekh** [comment]
исправлено в 4.0
