### ISSUE TITLE
[Loader] Не обновляется положение спинера при смене пропа active

### ISSUE THREAD

**Issue by Beywer** [skbkontur/retail-ui#2092]
Библиотека: @skbkontur/react-ui": "2.4.1" / "@skbkontur/react-ui-addons": "1.2.0"
Браузер: любой
ОС: любая

Когда внутри Loader находится большой контент, при смене пропа active на true спинер отображается не в зоне видимости по центру большого контента. Чинится скролом, пока лоадер активен.

```
<Loader active={usersLoadStatus === 'REQUEST'} caption="">
    <UsersTable users={users} />
</Loader>
```

![ActiveChange](https://user-images.githubusercontent.com/8099209/89902814-fa3e1880-dbf7-11ea-9311-1ed321e341e8.gif)

**Comment by zhzz** [comment]
Нужно продублировать в LTS.
