### ISSUE TITLE
[Customization] Человеко-читаемые названия классов

### ISSUE THREAD

**Issue by nulladdict** [skbkontur/retail-ui#2093]
При переходе на `css-in-js` пропала прикольная особенность сгенерированных названий классов.
Раньше, благодаря магии вебпака и css модулей имена классов имели примерно такой вид: `Button_root__[hash]`, теперь сгенерированные имена не имеют указания на исходный файл и класс.

Вроде emotion [позволяет](https://emotion.sh/docs/babel-plugin-emotion#labelformat) задать формат названий.

Это прикольную особенность можно использовать как для дебага (сразу видно что за класс если что-то пошло не так), так и например для тестов, если писать селекторы вида: `[class*='Button_root']`.

**Comment by zhzz** [comment]
Да и вообще полезный плагин. Попробуем втащить.

**Comment by asukhar** [comment]
Исправлено в #2900
