### ISSUE TITLE
[babel] Обновить до 7.8.7

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#2105]
[источник](https://t.me/react_ui/6978)

В ноде > 12.16.1 (или около того) вылетает ошибка при сборке:

> No "exports" main resolved in /Users/vtolstikov/works/retail-ui-fork/node_modules/@babel/helper-compilation-targets/package.json

Нужно обновить babel.

**Comment by chervyakovru** [comment]
https://github.com/babel/babel/issues/11216

related issue in babel repo
