### ISSUE TITLE
Проброс пользовательских пропов

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#2107]
Нужно подумать над тем, чтобы пробрасывать пользовательские пропы до элементов. В том числе className, style, data-атрибуты и тд.

Всего в api не предусмотришь. А блокировать пользователям сценарии (по религиозным причинам и не давая альтернативы) - плохо.

Аргументы:

- кастомизация там, где стандартные механизмы пока не работают
- data-tid'ы из коробки
- поддержка нативного поведения элементов https://t.me/react_ui/6987
- [material-ui](https://material-ui.com/) и другие ребята так делают

Если есть мысли за или против, давайте тут обсудим.

**Comment by Crazymax11** [comment]
Текущая ситуация выглядит примерно так

![](https://lh3.googleusercontent.com/proxy/S6gKjd4qQFgHzs9PLNlkf6Zmt2c74bYXbPtjNB0SZGbF21wpJ3R1W5zTELd_zIe4hzoHwcZpiJ3bw0XV-oVtSpxkX6Y_OsCbO4fWVBjTmNEn4Cqmm5Q)

- Стили можно перебить css каскадом
- data-test набросить оборачиванием в `<span>` , а там уже через селекторы добраться до цели
- атрибутов можно накинуть через рефы и нативное dom-api

Это создает проблемы на ровном месте нормальным людям и никак не защищает дураков. Первые корячатся, чтобы реализовать свои хотелки. Вторые не видят проблем похачить всё через `!important` и dom-api.

Может быть проблема с конфликтом css-классов. Например, не каждый конфиг Webpack гарантирует детерминированный порядок стилей в CSS, из-за чего порядок классов может плясать в результирующем css. Если есть 2 конфликтующих класса с одинаковой специфичностью, можно нарватся на то, что конфликт будет проявлятся не во всех релизах.

Лично у меня пока сильно болит только от невозможности спокойно кидать data-test атрибуты.

С другой стороны, то что нельзя перебивать стили - дополнительный аргумент в общении с проектировщиками, когда "ну у нас особенный кейс и нам тут нужно немного не так, как в react-ui".

**Comment by zhzz** [comment]
Я тоже за то, чтобы не вставлять никому палки в колеса.

К тому же, дополнительные стили могут быть вполне законными, например, с отступами или позиционированием.

А вот перебивка стилей по прежнему останется нерекомендуемой практикой, чреватой поломками, только на свой страх и риск, в качестве крайней меры. Так что аргумент для проектировщиков сохранится. Или еще в таких случаях можно ссылаться на противоречие Гайдам и общему стилю, что тоже не приветствуется.

**Comment by nulladdict** [comment]
Я считаю, что неправильно полагать, что гайды и библиотека покрывают все возможные сценарии. К примеру, есть большое количество не-резиновых компонентов, и прокинуть им резиновые стили через `className` вполне себе законное желание. Перебивка через каскад заставляет оборачивать в лишние компоненты и молиться при каждом обновлении библиотеки, что не нужно все стили переписывать.

Конфликт стилей не страшен и решается простым увеличением специфичности. Плюс mini-css плагин умеет писать о конфликтах при билде.

Ставить аттрибуты через `ref` плохая затея. Его не на все компоненты можно взять, а на те, которые можно, нужно ещё порыться в реализации компонента, что хрупко и неудобно.

Если давать всем возможность прокидывать стили страшно, можно спрятать это в TS типах, или переназвать пропсу

**Comment by halex2005** [comment]
Признаться честно, мне сначала захотелось пробросить атрибут name в скрытый внутренний input при работе с формой.

Вот что хотелось получить:

```
<form onSubmit={handleSubmit}>
    <input type="checkbox" name="someCheckbox" />
    <DatePicker name="someDate" />
    <button type="submit">Найти</button>
</form>
```

Суть в том, что в handleSubmit может лежать общий код, который достанет данные из формы, и что-нибудь с ними сделает (например, отправит запрос на бэк через API, передавая данные формы в параметрах).

Это сейчас невозможно как минимум по двум причинам:
- `name` не пробросить во внутренний скрытый `input`, поэтому данные в форму не попадают по нужному ключу
- `DatePicker` не умеет работать без указания `value` и `onValueChange`

В итоге, я пришел к такому решению - написал враппер, который нарисует рядом с `DatePicker` скрытый `input` с нужным именем + хранит в стейте текущее выбранное значение для `DatePicker`. Тут же смог прикрутить свою логику для формирования значения, которое в итоге в форму по нужному ключу попадет (`convertToIsoDate`):

```
interface IDatePickerWrapperProps {
    name: string
    defaultValue?: string
    disabled?: boolean
}
const DatePickerFormValueWrapper: React.FC<IDatePickerWrapperProps> = ({ name, defaultValue, disabled }) => {
    const [value, setValue] = useState(defaultValue)
    return (
        <>
            <DatePicker value={value} disabled={disabled} onValueChange={setValue} enableTodayLink={true}/>
            <input type="hidden" name={name} value={convertToIsoDate(value)} />
        </>
    )
}
function convertToIsoDate(dateStr: string|undefined = '') { /* code omitted for clarity */ }
```

По итогу: мне хватает возможностей `DatePicker` для работы с формами. Может быть и хорошо, что атрибут name мне не удалось прокинуть через API - тогда бы я был привязан к внутреннему формату даты во внутреннем input.

Как развитие, могу предложить в `DatePicker` получать не просто строковое значение даты, а нативный `Date`.

**Comment by zhzz** [comment]
# RFC по пробросу пропов
Ребята, мы приступаем к задаче, планируем зарелизить ее в 3.0.0. Можем предварительно обсудить детали и идеи.

## В общих чертах
Добавляется возможность передавать в компоненты произвольные пропы из списка допустимых [HTML-аттрибутов](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes) с целью тонкой настройки внутренних HTML-элементов. 

## Примеры
Начнут работать следующие сценарии:

```jsx
  <Input className="w-25 m-3" type="number" />
  <ComboBox data-tid="my-combobox" />
  <Button form="my-form" />
  <Toggle tabIndex="-1" />
  <DatePicker name="date" />
``` 

## Мотивация
1. У пользователей библиотеки есть необходимость применять к компонентам собственные значения некоторых общих атрибутов, например:
    - `data-tid`, `data-testid` - для идентификации элементов на странице во время тестирования
    - `className` и `style` - для тонкой настройки стилей компонентов там, где встроенные механизмы не работают, либо неудобны
    - `onKeyDown` и остальные обработчики событий тоже потенциально могут быть полезны непосредственно на компоненте 
2. Многие компоненты, являясь элементами форм, не поддерживают всех атрибутов аналогичных нативных элементов. Таким образом блокируются естественные сценарии, такие как:
   
    - привязка элементов друг к другу через атрибуты `id`, `for`, `from`
    - разметка полей формы атрибутом `name`
    - настройка фокусируемости элементов с помощью `tabIndex`
    - тонкая настройка полей ввода на мобильных и не только через атрибут `type`

В отсутствии таких возможностей, пользователи вынуждены изобретать грязные пути обхода ограничений через дополнительные обертки и вмешательство во внутренне устройство компонентов. Это не только тратит дополнительное время и силы, но и приводит к ненадежным решениям, которые подвержены поломкам.

## Решение
Проблему предлагается решить следующим образом. Пользователям предоставится возможность передавать все разрешенные для конкретного типа элемента атрибуты непосредственно в компонент.
При наличии внутри компонента нативного контрола, часть пропов необходимо будет перенаправить в него. Разделение пропов можно осуществлять по следующему принципу. Все пропы, специфичные для элементов форм, таких как [input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), [button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button), [select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select), [textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea), извлекаются из общего объекта переданных пропов и передаются в нативный элемент.
Также, к этим специфичным пропам следует добавить некоторые из [общего списка](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) (id, tabIndex, aria-label, aria-labelledby) для обеспечения озвученных выше сценариев. Оставшиеся пропы пойдут на корневой элемент компонента.

Таким образом, на корневой элемент пойдут любые data-атрибуты, className, style и обработчики событий. А в нативные контролы все релевантные именно для них пропы.

Это обеспечит компоненты библиотеки максимально схожим с нативными элементами поведением и возможностями.

На уровне типов все будет решаться через расширение/переопределение интерфейсов пропов соответствующих нативных HTML-элементов.
```ts
type ComboBoxProps<T> = Override<React.InputHTMLAttributes<HTMLInputElement>, {...}>;

```
data-атрибуты typescript пропускает [без ошибок](https://www.typescriptlang.org/docs/handbook/jsx.html#attribute-type-checking).


## Потенциальные проблемы
- Изменения будут частично ломающими. 

  Дело в том, что в данный момент, такие компоненты, как `Input`, `Autocomplete`, `CurrencyInput`, `FxInput`, `PasswordInput`, `Checkbox` и `Radio` уже прокидывают произвольные пропы до нативных инпутов.
  Это значит, что пользовательские data-атрибуты, в случае их использования, применяются именно к ним. А после обновления такие атрибуты переедут на корневой элемент. В результате тесты пользователей могут сломаться.

  Но, починить их должно быть довольно легко, обновив соответствующие селекторы с `[data-tid="my-data-tid"]` на `[data-tid="my-data-tid"] input`.

  Поясню, что перенос data-атрибутов на корень предлагается сделать для консистентности с другими компонентами, в которых вложенных инпутов нет. В них корень - единственное логичное место для таких атрибутов. Соответственно, поведение лучше сделать однообразным среди всех компонентов.

  Если же описанная тут возможность не использовалась, то обновление должно пройти без проблем.

- Также, есть вероятность неожиданного и нерекомендуемого использования новой функциональности. Например, злоупотребление пропами `className` и `style`, которые до сих пор оставались под запретом. Или использование `type="range|file"` на инпуте, что не предусмотрено нашими стилями. Предлагаю оставить это на усмотрение самих пользователей, с соответствующими пометками в документации.

## Альтернативы
1. Можно предусмотреть все нужные пропы в собственном api компонентов. Это дает больше контроля над тем, что можно, а что нельзя передавать в пропах. Но часто ведет к наличию непредусмотренных сценариев и постоянным доработкам. Либо к большему объему кода и документации. Я предлагаю попробовать противоположный путь.

2. Есть вариант предоставить пользователю самому решать, какие пропы передать в инпут, а какие в корень, через отдельный проп:
```jsx
  <Input className="" inputProps={{ tabIndex: 0, 'data-tid': 'my-input', ... }} />
```

Такой подход используется в material-ui. Он немного отдаляет компоненты от нативных элементов в плане одинаковости api. Плюс, имеет проблемы с pure-компонентами, т.к. нужно предпринимать особые меры, чтобы объект в пропах не приводил к лишним перерисовкам.
  
Потребуется больше усилий для переезда.

3. Идейно схожий со вторым вариант, но без проблемы с перерисовками.
  ```jsx
  <Input className="">
    <input tabIndex="0" data-tid="my-input" ... />
  </Input>
  ```
  Вложенный input не рисуется, а служит только для сбора пропов. Самый неочевидный подход. Не понятно, насколько это будет удобно.

## Адаптация изменений пользователями
В существующем коде приложений изменения скорей всего не потребуются. Возможно, придется слегка порефакторить тесты. Зато новый код можно будет писать с меньшим количеством костылей. При желании, также можно будет отрефакторить старый.

## Документация
Нужно будет упомянуть в документации о расширенных возможностях передачи пропов. Также, добавить заметку о нерекомендуемых способах вмешательства в стили компонентов и их последствиях.

## Оставшиеся вопросы
Возможно, будут особые случаи с RadioGroup, т.к. он может содержать несколько инпутов.

**Comment by hukopo** [comment]
Я хотел пробросить в combobox проп onPaste. Сценарий: комбобокс является элементом таблицы и я реализовал задачку чтобы при вставки в любую ячейку таблицы из excel перехватить вставку и вставить эту таблицу в соседние ячейки тоже

**Comment by halex2005** [comment]
Вероятно, полезно будет прокинуть в `input` атрибут `autocomplete="one-time-code"`.
Например, аутентификатор мог бы его использовать для заполнения одноразового кода из смс https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

**Comment by dzekh** [comment]
Закрываю, ибо обсудили
