### ISSUE TITLE
[Tokeninput] Добавить возможность редактирования введенных токенов

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#2112]
Нужно добавить в токен-инпут возможность редактирования токенов:

![token-1](https://user-images.githubusercontent.com/26383080/91822518-59200c00-ec51-11ea-8feb-b470cc60b37c.png)

В скором времени добавлю этот блок в гайды, как добавлю, поставлю сюда ссылку. 

[Обсуждение в стаффе](https://staff.skbkontur.ru/post/b22c1661c99c4cfa8fbe2cb8bff1475d).

**Comment by zhzz** [comment]
Я бы сказал - пара недель, с запасом. Хорошо подойдет для небольшой стажировки или внешнего контрибьютера.

**Comment by dzekh** [comment]
У нас так то по токену уже [14 задачек](https://github.com/skbkontur/retail-ui/issues?q=[TokenInput]+in:title+is:open+) в беклоге. Было бы круто если б смогли взять в работу хотя бы эту.

**Comment by polecat89** [comment]
В Эльбе совсем скоро зайдёт в разработку задачка, в которой мы прикрутим токены, хочется уметь их редактировать
