### ISSUE TITLE
[contibuting.md] акутализировать

### ISSUE THREAD

**Issue by rustho** [skbkontur/retail-ui#2114]
- [ ] Обновить команду для запуска creevey в краткой инструкции (в разделе "Скриншотные тесты" инфа корректная )
- [ ] Убрать Less из списка технологий и структуры файлов
- [ ] Обновить п. 2 в инструкции по созданию скриншотного теста. Тесты теперь лежат не в отдельных файлах, а в историях
- [ ] Создание story в разделе Storybook через именованный экспорт, а не через `.add(...)`

**Comment by YakOFF19** [comment]
- [ ] Обновить ссылку на Roadmap

**Comment by zhzz** [comment]
Все сделано
