### ISSUE TITLE
[Textarea] Высота многострочного поля и проп rows

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#2120]
По умолчанию высота поля [должна быть равна 3 строкам](https://guides.kontur.ru/components/textarea/#Razmer_i_raspolozhenie), это 72px (20*3 + отступы по 5 сверху и снизу + обводка 1) Cейчас же она равна 86px, что больше похоже на 4 строки, хотя rows по умолчанию = 3.
Изменение `rows` работает странно:
- Указание `rows` меньше 3 не влияет на высоту поля, хотя кажется должно влиять. 
- При `rows="4"` высота поля 92px, каждое следующее приращение на 1 увеличивает высоту на 20px от 92

Должно быть:
- Можно указать любое значение `rows` от 1. Поле меняет дефолтный размер в зависимости от этого значения. 
- Высота поля равна `(rows* высота строки (20px)) + отступы сверху и снизу (по 5px) + рамка (по 1px)`, каждое приращение rows на 1 увеличивает высоту на 20px.
- Значения высоты строки, отступов и толщины рамки поля конечно же берутся из темы.

**Comment by chervyakovru** [comment]
>Указание rows меньше 3 не влияет на высоту поля, хотя кажется должно влиять.

Действительно не влияет потому что в подсчетах минимальной высоты поля было умножение на 3. Убрал в упомянутом PR

**Comment by chervyakovru** [comment]
>При rows="4" высота поля 92px, каждое следующее приращение на 1 увеличивает высоту на 20px от 92

В хелпере подсчета высоты поля к ожидаемой высоте `(rows* высота строки (20px)) + отступы сверху и снизу (по 5px) + рамка (по 1px)` прибавляется еще одна `высота строки (20px)`.
Это сделано для компенсации эффекта "дергания" текста при увеличении высоты при авторесайзе.

`TextareaHelper.tsx:8`

**Comment by dzekh** [comment]
Круто что закинул PR, спасибо! 

Не понимаю, как компенсирует эффект "дергания" добавление еще одной? 

Вообще правильно, что всегда должна быть снизу пустая строка. То есть когда у тебя три строчки набранного текста — высота поля должна быть размером в 4 строки. Но как это влияет на эффект дерганья не понятно. 

Но высота поля по умолчанию, даже если текста в поле нет — 3 строки, и это значение может меняться пропом. Минимальная высота при этом — 1 строка.

**Comment by chervyakovru** [comment]
>Вообще правильно, что всегда должна быть снизу пустая строка. То есть когда у тебя три строчки набранного текста — высота поля должна быть размером в 4 строки.

Получается Textarea не может быть одной строкой? Если напечатана одна строка, то компонент должен быть высотой в 2 строки?

**Comment by dzekh** [comment]
Может, если ему в пропы передать значение rows = 1 (которое по дефолту 3).
Это не минимальное значение высоты, а количество строк у незаполненного поля. Насколько я понимаю.

**Comment by dzekh** [comment]
Щас начало доходить, что в случае если указано rows=1 не нужно добавлять заранее строку, только в тот момент когда она становится нужна, и текст переносится. Если же указано rows=2 и больше — строка дополнительная должна всегда добавляться.

**Comment by zhzz** [comment]
Эффект дергания там действительно возникает из-за запоздалого пересчета высоты после изменения текста (если убрать вставку доп строки).

![3228dd6c-9c1a-48f4-a31e-58d35df80f2e](https://user-images.githubusercontent.com/4607770/93297551-e98e4d00-f80a-11ea-9896-fad13968513e.gif)

Но эта доп строка, я думаю, там скорее чтобы зафорсить [пункт 14](https://guides.kontur.ru/components/textarea/#14) гайдов. 

Может вообще сделать эту доп строку опциональной, через новый проп? А дерганье пофиксим, убрав задержку (вроде не сказывается заметно на производительности).

**Comment by zhzz** [comment]
@dzekh @chervyakovru Как вам вариант с опциональной доп строкой? В ПРе сейчас высоту в одну строку нельзя сделать.

**Comment by dzekh** [comment]
Опциональная доп страока — ты имеешь ввиду вынести этот параметр и сделать для него отдельный проп? Я не против, но по умолчанию она должна быть включена. 

Еще про скакание — а нельзя сделать выравнивание текста не по центру а по верхнему краю? Чтоб дополнительная строка вниз уходила, тогда и скакания не будет.

**Comment by zhzz** [comment]
> Опциональная доп строка — ты имеешь ввиду вынести этот параметр и сделать для него отдельный проп? Я не против, но по умолчанию она должна быть включена.

Да, именно так и имел в виду.

> Еще про скакание — а нельзя сделать выравнивание текста не по центру а по верхнему краю? Чтоб дополнительная строка вниз уходила, тогда и скакания не будет.

А скачки не из-за выравнивания происходят, а из-за того, что текст в узком поле прокручивается вниз при переносе на новую строку. Затем высота пересчитывается, и он в вроде как встает на место.

**Comment by chervyakovru** [comment]
>Может вообще сделать эту доп строку опциональной, через новый проп? А дерганье пофиксим, убрав задержку (вроде не сказывается заметно на производительности).

Что значит убрав задержку? Убрав анимацию?

**Comment by chervyakovru** [comment]
Чтобы дать возможность (добавить проп) *Опциональная доп строка* нужно понять как нивелировать "дергание" при увеличении высоты, при этом сохранив анимацию.

**Comment by zhzz** [comment]
Изначально думал, что чтобы нивелировать "дергание" хватит отказа от троттлинга функции авторесайза. Но теперь вижу, что и анимация тоже вносит вклад. Может и от нее тоже избавится? 🙂 @dzekh что скажешь? Про анимацию в гайдах ничего нет)

**Comment by dzekh** [comment]
Анимацию можно оставить только если доп строка есть. Если выключаешь допстроку — выключать анимацию.

**Comment by dzekh** [comment]
Добавим комментарий к пропу в доку. 
Если есть путь лучше — можно реализовать его =)

**Comment by zhzz** [comment]
Я думаю, что анимация в данном случае не такая уж критичная фича. Полноценное управление высотой важнее.
