### ISSUE TITLE
[DatePicker] react v15.x

### ISSUE THREAD

**Issue by mortifer** [skbkontur/retail-ui#213]
В общем есть ощущение, что это баг контрола именно в 15 реакте.
Фокусируемся на поле мышкой так чтоб выпадающая чать была скрыта.
Пытаемся нажимать на иконку чтоб открыть контрол - выходит раз на десятый.
При нажатии на иконку, когда фокус вне контрола - всё в порядке

**Comment by nanot1m** [comment]
Fixed
