### ISSUE TITLE
[Link] Добавить проп loading

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#2133]
Есть запрос на проп, реализующий состояние загрузки из гайдов: https://guides.kontur.ru/components/hyperlink/#25

Возможно, стоит также поддержать это поведение в кнопке-ссылке.

Обсуждение: https://t.me/react_ui/7119.

**Comment by zhzz** [comment]
Поставил `wait design`, чтобы получить одобрение @dzekh.

**Comment by dzekh** [comment]
Да, все ок, только вроде как в гайдах нет описания как делать ссылку в состоянии загрузки без иконки, нужно будет нарисовать и еще тогда и у кнопки сделать такое-же поведение. Есть обсуждение [про кнопки тут](https://staff.skbkontur.ru/article/5dd50429fae04f0c3cd8f624).

**Comment by zhzz** [comment]
Если будем менять состояние и для обычной кнопки, то можно приурочить к 3.0.0. 
Отказ от анимированных полосок, кстати, позволит переверстать кнопки-стрелки и сделать их намного проще.

**Comment by dzekh** [comment]
А про это уже есть пиар: https://github.com/skbkontur/retail-ui/pull/2271
