### ISSUE TITLE
[Kebab] Возможность задавать иконку

### ISSUE THREAD

**Issue by slawwan** [skbkontur/retail-ui#2141]
Хочется иметь возможность задавать иконку.
А может быть имеет смысл отдельно поставлять кнопку кебаба с вохможностью задавать иконку и отдельно поставлять выпадаху кебаба и поставлять контрол Kebab который будет собран из кнопки и выпадахи. сама по себе круглая иконка-кнопка с фокусом и ховерами может быть переиспользована, ну и выпадаха тоже может быть переиспользована.

**Comment by zhzz** [comment]
Кастомную иконку можно сделать. Уже не первый запрос на нее.

А на отдельную кнопку какие есть сценарии? В качестве выпадахи может подойти TooltipMenu (или DropdownMenu). Это по сути она и есть.
