### ISSUE TITLE
[Theme] Не работает color

### ISSUE THREAD

**Issue by rustho** [skbkontur/retail-ui#2145]
[Logotype] - В переменных темы есть logoColor, и logoHoverColor, но в верстке напрямую указываются стили в объект style. в итоге проп textColor перебивает logoColor;
[Checkbox] - checkboxTextColorDefault не работает. В переменных темы есть checkboxTextColorDefault, но этот стиль находится в box, а не root стилях.
[Combobox/DropdownMenu] - нельзя поменять color внутренних айтемов

**Comment by zhzz** [comment]
Логотип поменялся, цвет задается иным образом. Остальное реализовали в #2543.
