### ISSUE TITLE
Баг при открытии Dropdown

### ISSUE THREAD

**Issue by kostyabushuev** [skbkontur/retail-ui#2147]
Привет! Обнаружил баг при использовании компонента `<DropdownMenu />` и пропсов `header` и `menuMaxHeight`

- Библиотека и её версия; react-ui@1.11.6 (В последней версии 2.x воспроизвести не смог)
- Браузер, его версию, ОС: Windows 10, Chrome 85

Для того, чтобы воспроизвести баг, необходимо для окна страницы подобрать такой размер, чтобы `Dropdown` открылся сверху, а не снизу. В результате `Dropdown` некорректно высчитывает позицию и открывается таким образом, что перекрывает `caption`. При повторном открытии позиция высчитывается корректно и `Dropdown` открывается как нужно

**Снипет кода**:
```js
<DropdownMenu caption={<Button use="primary">Открыть меню</Button>} header="HEADER" menuMaxHeight={302}>
  {new Array(200).fill().map((item, index) => <MenuItem>Меню { index }</MenuItem>)}
</DropdownMenu>
```

**Пример:**
![Screenshot_120](https://user-images.githubusercontent.com/31274471/94008607-b6c0f780-fdbc-11ea-9a60-a034e363712c.png)

**Comment by zhzz** [comment]
Да, есть такое. Разберемся.

**Comment by zhzz** [comment]
В актуальных версиях не воспроизводится. Закроем.
