### ISSUE TITLE
[Fias] Добавить маппинг из Alpha3 в FiasCountry и наоборот

### ISSUE THREAD

**Issue by sergeyshmakov** [skbkontur/retail-ui#2155]
- @skbkontur/react-ui LTS

Храним страну в формате Alpha3 (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3)
Хочется уметь конвертить Alpha3 в FiasCountry и наоборот.
Для Alpha3 справочника используем библиотеку `i18n-iso-countries`.

**Comment by zhzz** [comment]
А можешь описать поподробней сценарии, для которых нужны конверторы? 

Может быть нам нужно просто научить контрол восстанавливать полный FiasCountry по его полю `code`, который как раз и есть numeric code по ISO 3166-1.

**Comment by zhzz** [comment]
Пока закрою, если что - пиши снова.
