### ISSUE TITLE
[Textarea] Textarea имеет прозрачный фон вместо белого

### ISSUE THREAD

**Issue by denexapp** [skbkontur/retail-ui#2160]
В компоненте Textarea вместо белого фона (как в Input или DateInput) отображается прозрачный фон.

Воспроизводится в галерее контролов: https://tech.skbkontur.ru/react-ui/#/Components/Textarea

Библиотека @skbkontur/react-ui@2.5.0
Firefox 81 / Chrome 85

![image](https://user-images.githubusercontent.com/3131467/95276028-86b93000-0863-11eb-8a49-1957e128e4c6.png)

**Comment by zhzz** [comment]
В 2.0 при переносе стилей из less в дефолтной теме появилась переменная `textareaBg = 'none'`, которая раньше работала только в темной теме. Она перебила белый фон, который задают браузеры по умолчанию. 

Нужно поменять значение 'none' на переменную `bgDefault`.

Тесты не нашли, потому что в сторибуке фон тоже белый. Стоит подумать как это подправить.

**Comment by zhzz** [comment]
А еще она увеличилась по высоте при наличии пропа `autoResize`. На него у нас теста нет.
