### ISSUE TITLE
[react-ui-validations] Тултип с ошибкой валидации не исчезает после выбора

### ISSUE THREAD

**Issue by Raykeen** [skbkontur/retail-ui#2161]
При выборе значение в селекте, отчекивании обязательных чекбоксов и радиобаттонов, выборе в компбобоксе почему-то остается висеть тултип с ошибкой. Это может вводить в заблуждение. В гайдах описано именно такое поведение но кажется это логично только для инпута.
При всем этом календарь ведет себя не так и убирает тултип сразу после выбора.

- @skbkontur/react-ui@2.4.2, @skbkontur/react-ui-validations@1.2.0;
- Windows 10, Chrome 85.0.4183.121
- Пример можно увидеть тут http://tech.skbkontur.ru/react-ui-validations/#/editors

![ОО](https://user-images.githubusercontent.com/20644051/95292411-d65f2200-088a-11eb-82c0-78e3dac94c01.gif)

**Comment by dzekh** [comment]
Так сделано потому, что в этих сообщениях об ошибках могут содержаться важные рекомендации о том как заполнить поле или что выбрать из списка. Тултипы снимаются сразу после того как снимается фокус с контрола. Мы считаем что это ок, и не будем исправлять это поведение, оно может казаться странным и не логичным, но иногда оправдано и необходимо. С ним интерфейс в целом безопасней — меньше возможностей повторно совершить ошибку.
