### ISSUE TITLE
[ComboBox] Дать возможность полностью отключать сообщение "Не найдено" 

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#2163]
Запрос из [чатика](https://t.me/react_ui/7368).

Проверить, не противоречит ли существующим сценариям (кнопка добавления, например) или гайдам. Можно реализовать через `renderNotFound={() => null}`.

**Comment by dzekh** [comment]
На первый взгляд не противоречит, можно реализовать.

**Comment by zhzz** [comment]
Ок, подвину наверх в очереди для дежурного.

**Comment by zhzz** [comment]
Закрыто в #2174
