### ISSUE TITLE
Пропадает вуаль у Modal при открытии SidePage 

### ISSUE THREAD

**Issue by Edheltur** [skbkontur/retail-ui#2175]
- @skbkontur/react-ui 2.6.0
- Microsoft Edge 86.0.622.43

Если открыть SidePage из модалки, то вуаль модалки пропадает. Судя по коду - модалка рендерит вуаль только если находится в верху ModalStack. SidePage же кладёт себя поверх и модалка перестаёт рендерить вуаль.

### Минимальный пример для воспроизведения
https://codesandbox.io/s/reactui-modal-sidepanel-veil-bug-13vqi

<details>
<summary>Скрин</summary>
<img src="https://user-images.githubusercontent.com/4038984/96455633-e8e83c80-1236-11eb-9984-914225a27310.png">
</details>
<details>
<summary>Код из примера</summary>

```jsx
import * as React from "react";
import { Modal, SidePage } from "@skbkontur/react-ui";

import "./styles.css";

export default function App() {
  const [isModalOpen, setModalOpen] = React.useState(false);
  const [isSidePanelOpen, setSidePanelOpen] = React.useState(false);

  return (
    <div className="App">
      <button onClick={() => setModalOpen(true)}>Open Modal</button>
      {isModalOpen && (
        <Modal onClose={() => setModalOpen(false)}>
          <Modal.Body>
            <div style={{ height: 300, width: 200, background: "lightgrey" }} />
            <button onClick={() => setSidePanelOpen(true)}>
              Open Side Page
            </button>
          </Modal.Body>
        </Modal>
      )}

      {isSidePanelOpen && (
        <SidePage onClose={() => setSidePanelOpen(false)}>
        </SidePage>
      )}
    </div>
  );
}

```

</details>

**Comment by Edheltur** [comment]
@rustho Привет, подскажи, а этот баг возьмут в работу в ближайшее время?

**Comment by rustho** [comment]
@Edheltur перенес в задачи дежурного, так что да
