### ISSUE TITLE
[Switcher]  проблемы с валидацией

### ISSUE THREAD

**Issue by dpeshkin** [skbkontur/retail-ui#2191]
react-ui 2.5.0 + react-ui-validations 1.2.0
У Switcher есть какие то проблемы при взаимодействии с @skbkontur/react-ui-validations. Такое ощущение что тултип не может нормально спозиционироваться и вызывает бесконечный ререндер, когда текст кнопки под ховером.
![switcher](https://user-images.githubusercontent.com/13113273/97563012-4da85180-1a04-11eb-85e0-48d20c26ec44.gif)

**Comment by zhzz** [comment]
Исправили в 2.16.1
