### ISSUE TITLE
[ModalStack] Сломалась совместимость 1.х и 0.х с 2.х версией

### ISSUE THREAD

**Issue by rustho** [skbkontur/retail-ui#2197]
продукт использует версию контроллов A, встраивает себе приложение, которое использует версию B (А и B - разные мажорные версии). И использует встроенное приложение следующим образом: открывает у себя модалку, и по клику на кнопку в своей модалке открывает приложение (приложение - сайдпейдж). После чего закрывает приложение и получает ошибку emitter.removeListener is not a function (ошибка падает из ModalStack.js)
нужно починить связки 2.* - 1.* и 2.* - 0.*

**Comment by lossir** [comment]
Версии с фиксами совместимы между собой при использовании в любом порядке

| 1\2 | `>=0.53.13` | `>=1.11.7` | `>=2.8` |
| --- | :---: | :---: | :---: |
| `>=0.53.13` | ✅ | ✅ | ✅ |
| `>=1.11.7` | ✅ | ✅ | ✅ |
| `>=2.8` | ✅ | ✅ | ✅ |

**Comment by lossir** [comment]
## Полная картина
Сообщение [выше](https://github.com/skbkontur/retail-ui/issues/2197#issuecomment-725395272) показывает только версии с фиксами. Это не отражает ситуации по другим версиях. Проблема до сих пор актуальна, хоть и всплывает редко.

...*текст для поиска по issues*...

```diff
// Текст ошибки, если первым в глобальный emitter попал `fbemitter`
-     this.stackSubscription.remove is not a function   

// Текст ошибки, если первым в глобальный emitter попал `eventemitter3`
-     emitter.removeListener is not a function          

```


| Ветка релизов | Таблица совместимости |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2708211/177149536-727848dc-5c92-4b85-9acb-e125af58549a.png) | ![image](https://user-images.githubusercontent.com/2708211/177179125-eaba2d7e-71ea-47fc-adb7-e5c3532a2591.png) <br>1 - сохранил глобальный emitter <br>2 - использовал глобальный emitter <br> _* - версия с workaround_|

## Самостоятельное исправление

Если у вас синяя ![image](https://user-images.githubusercontent.com/2708211/177176773-503412a2-cccb-4713-b2ba-339eb78e4534.png) или фиолетовая ![image](https://user-images.githubusercontent.com/2708211/177176832-0dff9dc5-a53d-43ca-81e7-0a6b00b9626a.png) версия, то ошибку можно исправить самостоятельно, без обновления контролов у вас или у приложения, который вы встраиваете. Для этого понадобиться модифицировать `eventemitter3` или `fbemitter` соответственно.
Workaround должен выполниться до самого первого монтирования `Modal` или `SidePage`. Именно при монтировании `emitter` сохраняется глобально в `window.__ReactUIStackInfo` и никогда не удаляется.

### workaround для синих версий
```js
import EventEmitter from 'eventemitter3';

EventEmitter.prototype.addListener = function (this: { remove(): void } & EventEmitter, ...args) {
  this.remove = () => this.removeListener(...args);
  return this.on(...args);
};
```

### workaround для фиолетовых* версий
```js
import { EventEmitter } from "fbemitter";

const addListener = EventEmitter.prototype.addListener;
EventEmitter.prototype.addListener = function (...args) {
  const subscriber = addListener.bind(this)(...args);
  this.removeListener = subscriber.remove;
  return subscriber;
};
```

### workaround для красных версий
Это тоже можно сделать самостоятельно. Понадобиться повторить workaround для фиолетовых версий, и модифицировать метод `add` внутреннего компонента `ModalStack`, как это делается в тех же фиолетовых версиях.

```js
...  повторить workaround для фиолетовых версий ...

ModalStack.add = function(component, onChange) {
  const { emitter, mounted } = ModalStack.getStackInfo();
  mounted.unshift(component);
  const changeHandler = () => onChange([...mounted]);
  const subscription = emitter.addListener("change", changeHandler);
  emitter.emit("change");
  return {
    remove(): void {
      if ("removeListener" in subscription) {
        emitter.removeListener("change", changeHandler);
        return;
      }
      subscription.remove();
    }
  };
}
```

## Ресурсы

Проверить совместимость версий и workaround'ов можно в этой дэмке
https://doeurp.csb.app/playgound

Посмотреть реализацию workaround для синих ![image](https://user-images.githubusercontent.com/2708211/177176773-503412a2-cccb-4713-b2ba-339eb78e4534.png) версий можно здесь
https://codesandbox.io/s/fbemitter-and-eventemitter3-doeurp?file=/fakes/FakeMegafix.tsx

Для фиолетовых ![image](https://user-images.githubusercontent.com/2708211/177176832-0dff9dc5-a53d-43ca-81e7-0a6b00b9626a.png) версий workaround лежит тут
https://codesandbox.io/s/fbemitter-and-eventemitter3-doeurp?file=/fakes/FakeOlderWorkaround.tsx
