### ISSUE TITLE
[Tooltip] При включеном AdBlock-е перестают показываться тултипы

### ISSUE THREAD

**Issue by tihonove** [skbkontur/retail-ui#22]
Ну и дела. Кто-нибудь считает, что это проблема?
![image](https://cloud.githubusercontent.com/assets/2770182/20099363/f69370e8-a5d9-11e6-9931-026302b3772b.png)

**Comment by mortifer** [comment]
Так то пиздец :)

**Comment by mortifer** [comment]
Но решается то вроде бы просто

**Comment by nanot1m** [comment]
@mortifer убрать "_" в названиях классов?

**Comment by mortifer** [comment]
Да не - тут просто надо в style тултипа писать display: block. Можно даже с !important. Мало ли как себя adblock в следующий раз поведёт

**Comment by molokovev** [comment]
@nanot1m, у нас в сервисе всё ещё эта проблема возникает, возможно из-за того, что Adblock Plus использует очень сильное колдунство:
![image](https://cloud.githubusercontent.com/assets/9248122/21356189/816ae08c-c6f2-11e6-922c-198f82ed8f23.png)

Видимо, придётся через js display: block!important ставить
