### ISSUE TITLE
[theme] радио, чекбоксов и тоггла в плоской теме просвечаивает бекграунд 

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2201]
Из чата https://t.me/react_ui/7558

> Привет, а расскажите, то что у радио, чекбоксов и тоггла в плоской теме просвечаивает бекграунд так и задумано?
Если нет, есть ли переменная в теме для этого?

Думаю, что так не задумывалось. И c помощью темизации, к сожалению, это тоже не исправить - отсутствуют соответствующие переменные.
Надо бы добавить переменные, и это очередной камень в нашу темизацию.

**Comment by HelenaIsh** [comment]
О, я забыл написать про тогл. прости. Там с ним всё сложно. Он конечно не правильно реализован, заливка должна быть белая, а заблокированность должна быть реализована без прозрачности. Единственное что должно сохранять прозрачность это обводка. Это касается кстати всех контролов. Сейчас проверю как тогл сделан в библиотеках и дам ссылку. оттуда можно будет параметры брать.

**Comment by HelenaIsh** [comment]
Комментарий от Лёши по поводу тоггла в темной теме:
