### ISSUE TITLE
[TokenInput] Нет легального способа контролировать введённое пользователем значение, которое ещё не превратилось в токен

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2205]
Из телеги: https://t.me/react_ui/7534

> В Гайдах есть параграф про то, что "если текст не подходит по формату, то токен не формируется" ([tokens/#38](https://guides.kontur.ru/components/tokens/#38))
Можете подсказать, как реализовать этот сценарий? 
Пробовал в обработчике onValueChange удалять неподходящий токен, но кажется, до вызова обработчика еще куча всего происходит, напр. очищается инпут
![image](https://user-images.githubusercontent.com/2708211/98362735-92a93500-204f-11eb-8b34-12b8171ac20c.png)

Главная проблема, это отсутствие легального способа контролировать введённое пользователем значение, которое ещё не "превратилось" в токен.

Тем не менее, в гайдах тоже не всё однозначно. Сначала стоит уточнить формулировки для гайдов, а затем убедиться, что `TokenInput` позволят безболезненного всё реализовать.

**Comment by dzekh** [comment]
Кажется что `onUnexpectedInput` уже есть и он решает эту проблему. Закрываю, если я не прав, переоткройте.
