### ISSUE TITLE
[TokenInput] переменная темы tokenInputLineHeight не влияет на токен

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2206]
| ![image](https://user-images.githubusercontent.com/2708211/98507485-7e4b7f00-227f-11eb-89b9-4ace7067eeb5.png) |
| --- |

**Comment by dzekh** [comment]
Там есть сейчас tokenLineHeight: и он влияет (и в 2.17 и в 3.0). Нужно просто синхронно менять tokenInputLineHeight и tokenLineHeight или залинковать их. Но таких мест, которые можно залинковать в кастомизации много, кажется что это не проблема и тем более не баг. Закрываю.
