### ISSUE TITLE
[Textarea] Добавить счетчик оставшихся символов

### ISSUE THREAD

**Issue by tsypilov** [skbkontur/retail-ui#2208]
@skbkontur/react-ui
Описание: https://guides.kontur.ru/components/textarea/#Schetchik_kolichestva_vvedennih_simvolov

**Comment by dzekh** [comment]
Было бы круто и в обычный инпут добавить, если получится.

**Comment by tsypilov** [comment]
> Было бы круто и в обычный инпут добавить, если получится.

Думаю получится :)

**Comment by tsypilov** [comment]
С Евгенией приняли решение, что Input нужно прорабатывать отдельно.
