### ISSUE TITLE
[Button] Актуализировать цвета обводок во всех темах

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#2209]
Во флет теме у заблокированных кнопок не полупрозрачная обводка.

Из-за этого они сливаются с фоном, когда фон серый:

![image](https://user-images.githubusercontent.com/26383080/98641699-00a27480-234e-11eb-81ad-839858c162d8.png)

Хотя в переменных и в стилях обводка с прозрачностью.

**Comment by zhzz** [comment]
Плюс, в других состояниях и темах тоже нужно обновить цвета: [таблица](https://www.figma.com/file/YEOImn7GAFzsNX3BTgzjMtRY/Guides-illustration?node-id=886%3A0).
