### ISSUE TITLE
[Modal] Разрешить вложенность Header/Body/Footer на любом уровне

### ISSUE THREAD

**Issue by Edheltur** [skbkontur/retail-ui#2219]
В Sticky режиме крестик не залипает, если ModalHeader вынесен в отдельный компонент. Перекликается с #2034, кейс такой же.

- @skbkontur/react-ui 2.7.0, 2.9.0
- Win 10 Pro, Microsoft Edge 86.0.622.69 (Official build) (64-bit)
- [Минимальный код](https://codesandbox.io/s/good-bye-close-button-ubs62?file=/src/App.tsx) для воспроизведения. Достаточно прокрутить контент модалки вниз.

![image](https://user-images.githubusercontent.com/4038984/99806848-679b0700-2b60-11eb-99e4-acd2764c0ecf.png)

**Comment by zhzz** [comment]
Вообще, это одна из причин, почему в Modal не рекомендуется вкладывать ничего, кроме Header/Body/Footer. Об этом говорит warning в консоли.

Расскажи, зачем вам нужен Header в отдельном компоненте?

**Comment by Edheltur** [comment]
У нас есть своя обёртка над модалкой (и её частями), которая используется по всему проекту. Header Footer Body являются тонкими обёртками, докидывающими div со стилями. Стили разные, но в основном там ресеты цвета, отступов, шрифтов, чтобы отменить действие глобальных стилей из старого кода.

```tsx
export const Header: React.FC = (props): React.ReactElement => (
  <Modal.Header>
    <div className={style.header}>{props.children}</div>
  </Modal.Header>
);

```

**Comment by zhzz** [comment]
Пока что хедер, боди и футер должны быть на первом уровне в модалке для корректной работы. Могу только посоветовать использовать ваши компоненты как функции:
```jsx
<Modal>
  {Header(props)}
</Modal>
```

Мы подумаем над тем, чтобы убрать это требование, начав детектить части модалки через контекст. Это довольно популярный вопрос среди пользователей.
