### ISSUE TITLE
[Modal] Пропал крест при box-sizing: border-box

### ISSUE THREAD

**Issue by ConstantineC** [skbkontur/retail-ui#2222]
Библиотека: @skbkontur/react-ui 2.8.0
ОС: Windows 10
Браузер: Chrome 86.0.4240.198
Сценарий: открываем модалку, лицезрим отсутствие крестика
[пример](https://codesandbox.io/s/invisible-cross-w60h2?file=/src/App.tsx)

При глобальном стиле `box-sizing: border-box` пропадает крест закрытия модального окна. Используем `FLAT_THEME`, но та же проблема и на `DEFAULT_THEME`. При этом на место, где должен быть крест нажать можно, появляется `outline`, но самой иконки нет.

**Comment by zhzz** [comment]
Все понятно, спасибо, поправим.
