### ISSUE TITLE
[DatePicker] Календарь уходит за экран, если дейтпикер находится внтури сайдпейджа

### ISSUE THREAD

**Issue by artsaban** [skbkontur/retail-ui#2229]
* @skbkontur/react-ui: 2.9.0
* хром, ие11 (остальные браузеры не проверял, но видимо везде так)

Есть такая форма внутри сайдпейджа. Если использовать дейтпикеры где-то близко к правому краю сайдпейджа, то возникает такая беда:

![photo_2020-09-08_16-40-00](https://user-images.githubusercontent.com/21331173/100580659-f0603280-3318-11eb-91ce-c553dd4bd8ff.jpg)

**Comment by zhzz** [comment]
Может `<DatePicker menuAlign="right" />` подойдет?

Внутри DatePicker'а - старый компонент DropdownMenu. Можно было бы научить его выравниваться по горизонтали автоматически. Но ему на смену когда-то должен прийти Popup, который это уже умеет. Будет это, правда, не скоро. Поэтому, если `menuAlign` не достаточно, то сделаем.

**Comment by artsaban** [comment]
Да, `menuAlign="right"` подходит 👍. Спасибо :)
