### ISSUE TITLE
[react-ui-testing] Добавить Switcher в библиотеку тестирования

### ISSUE THREAD

**Issue by Shururup** [skbkontur/retail-ui#2238]
Привет!
У нас появились сценарии, где на переключении Switcher завязана довольно важная функциональность, и хочется, чтобы она была покрыта тестами. 
Но сейчас в библиотеке тестирования нет контролла для Switcher, поэтому нет возможности написать тесты с его участием. Возможно ли будет его добавить в библиотеку тестирования?

**Comment by lossir** [comment]
Привет. В нашей команде нет бекендера, к сожалению. И на стажировку они приходят крайне редко. Поэтому работать над `react-ui-testing` попросту некому.
Но мы будем совсем не против, если кто-нибудь из вашей команды решит законтрибьютить это дело =)
