### ISSUE TITLE
[Input] Кривая карретка в safari

### ISSUE THREAD

**Issue by slogger** [skbkontur/retail-ui#224]
Привет! Опиши, пожалуйста, подробней проблему, которая возникла:

  — Safari, macOS & iOS;
  — как минимум две последние;
  — зафокусироваться, печати текста :)
  — Не выставлять line-height, равный высоте контролла 

![screen shot 2017-06-22 at 14 31 33](https://user-images.githubusercontent.com/983652/27427203-8f1a790e-5757-11e7-9813-7c6f6f33b5e7.png)
![screen shot 2017-06-22 at 14 31 37](https://user-images.githubusercontent.com/983652/27427204-8f67e2e8-5757-11e7-8497-2ab9826c01b2.png)

**Comment by nanot1m** [comment]
Fixed in #456
