### ISSUE TITLE
[ScrollContainer] Баг с onScrollStateChange

### ISSUE THREAD

**Issue by Torokhov** [skbkontur/retail-ui#2247]
![example1](https://user-images.githubusercontent.com/17142864/102190827-1544d000-3eeb-11eb-9590-faa81914c31f.gif)
@skbkontur/react-ui@2.10.0
Google Chrome Version 87.0.4280.88 (Official Build) (64-bit), Windows 10
Не срабатывает событие onScrollStateChange, если из ScrollContainer удалить все элементы. При удалении всех элементов полоса прокрутки пропадает и соотвественно onScrollStateChange должен вернуть "top", но этого не происходит. В примере при srollState === "top" должен пропадать разделитель

**Comment by Raykeen** [comment]
Аналогичный баг по той же причине есть в [виджете из парковки](http://ui.gitlab-pages.kontur.host/docs/#/choose-sale-point/ChooseSalePoint)
Когда получаем из onScrollStateChange - top убираем разделитель. 

![ОО](https://user-images.githubusercontent.com/20644051/102191581-6cdb3f80-3edb-11eb-8a65-78d8ec4a2650.gif)
