### ISSUE TITLE
[Button] артефакты у стрелок

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2259]
Источник: https://t.me/react_ui/7921

| small | medium | large |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/2708211/103118869-a9086000-4692-11eb-9e16-903474d7655b.png) | ![image](https://user-images.githubusercontent.com/2708211/103118892-ba516c80-4692-11eb-9627-4b19de0e5b0f.png) | ![image](https://user-images.githubusercontent.com/2708211/103118910-d0f7c380-4692-11eb-97b9-4448f8031fd9.png) |

**Comment by dzekh** [comment]
Кажется проблема в основном в том, что все переменные типа btn(Use)(State)ShadowArrow и btn(Use)(State)ShadowArrowLeft смотрят на btn(Use)(State)Bg а должны на btn(Use)(State)Shadow

**Comment by lossir** [comment]
Думаю, проблема в размерах самого уголка. Его размеры немного больше, чем надо. Например, для `large` стоит уменьшить его буквально на `1px` по высоте; сдвинуть на `1px` ниже, и вроде всё норм становится.

| сейчас | уменьшил и сдвинул |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2708211/103262830-dc672980-49c7-11eb-9f52-cd01dd94f716.png) | ![image](https://user-images.githubusercontent.com/2708211/103263011-7333e600-49c8-11eb-882a-42e055a2b211.png) |

**Comment by dzekh** [comment]
А там точно у уголка должна быть эта обводка в виде тени? Просто у самой кнопки её нет, а есть только у уголка. От неё тоже размер зависит.

**Comment by zhzz** [comment]
Кнопки [переверстали](https://github.com/skbkontur/retail-ui/pull/2263), больше не актуально.
