### ISSUE TITLE
[ComboBox] [Tooltip] не скрывается тултип с trigger 'focus' по потере фокуса в FF

### ISSUE THREAD

**Issue by evifox** [skbkontur/retail-ui#2269]
- @skbkontur/react-ui 0.53.9, 1.6.6, 2.12.1 (видимо во всех);
- Firefox 84.0.2, Windows;

## Пример
![tooltip-combobox-focus-example](https://user-images.githubusercontent.com/37307872/104593977-4f43f600-5692-11eb-8457-c52b368b153a.gif)

**Comment by zhzz** [comment]
Воспроизводится. Разберемся.
