### ISSUE TITLE
[Select] Опечатка в плейсхолдере — «ничего не выбрано» с маленькой буквы

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#2270]
Дизайнеры жалуются что в примере в плейсхолдере текст «ничего не выбрано» с маленькой буквы. Нужно исправить  в локалях дефолтный текст на «Ничего не выбрано» и «Nothing selected». 

Или правильно делать с маленькой?

**Comment by zhzz** [comment]
Можно исправить, думаю тут правил не было)
