### ISSUE TITLE
[Loader] [GlobalLoader] Создать новый компонент «глобальный лоадер»

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#2272]
Есть новый гайд описывающий поведение [глобального лоадера](https://guides.kontur.ru/components/global-loader/), нужно на его основе понять, какую логику можно вынести в компонент и сделать сначала верстку и если получится — отделный компонент. [Анимированный прототип](https://www.figma.com/proto/igS9KiYFsoQ7zF0S0wzB4H/%D0%9B%D0%BE%D0%B0%D0%B4%D0%B5%D1%80-%D0%B8-%D1%81%D0%BA%D0%B5%D0%BB%D0%B5%D1%82%D0%BE%D0%BD?node-id=223%3A4597&viewport=965%2C-260%2C0.10800599306821823&scaling=min-zoom).

**Comment by zhzz** [comment]
Duplicated #2202

**Comment by mighty-peach** [comment]
Такой компонент есть у Контур.Документов. Может взять оттуда?

**Comment by dzekh** [comment]
Интересно. А где можно посмотреть на него и его код?

**Comment by zhzz** [comment]
Реализовали в 4.0
