### ISSUE TITLE
[ComboBox] поправить типы

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2273]
Из чата https://t.me/react_ui/8019

> Кажется, у ComboBox-а не совсем честные типы у просов, или я чего-то не понимаю. <br/>
Например, там есть getItems: (query: string) => Promise<T[]>;, однако getItems может легально возвращать реактовые элементы. <br/>
Если добавить реакт элемент к типу T, то начинает выглядеть так, что он может поступить на вход целой кучи функций типа valueToString, renderValue, onValueChange, и т.п. Целая куча мест где используется T, но судя по всему далеко не во всех действительно может оказаться реакт элемент. При этом сходу не очевидно где может, а где нет.  <br/>
Может есть смысл как-то заточить тайпинги так, чтоб они отражали настоящее поведение, а то практически невозможно написать строгий код)

**Comment by dzekh** [comment]
А в упомянутом [2563](https://github.com/skbkontur/retail-ui/pull/2563) не поправлена эта проблема?

**Comment by dzekh** [comment]
Перенес на ютрек в IF-642
