### ISSUE TITLE
[Button] Реализовать бордер через border

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2276]
Сейчас в кнопке "тени" и "границы"(бордеры) реализованы через `box-shadow`.  Из-за чего стили `box-shadow` получаются довольно мудрёнными. При этом свойство `border` в основном указано как `none`.
Хотелось бы, чтобы бордеры кнопки были реализованы через `border`. Так будет проще поддерживать и вообще.

**Comment by lossir** [comment]
Добавлю, что так бордюры реализованы только в дефолтной теме. В плоской сделано через `border`. Это только добавляет проблем.

**Comment by dzekh** [comment]
> Добавлю, что так бордеры реализованы только в дефолтной теме.

Как тени ты хотел сказать, через `box-shadow`?
