### ISSUE TITLE
[TopBar] Пропсы noMargin и noShadow игнорируются при переключении темы

### ISSUE THREAD

**Issue by denexapp** [skbkontur/retail-ui#2277]
Пропсы noMargin и noShadow игнорируются в TopBar при переключении темы

Шаги воспроизведения:
1. Добавить ContextProvider
2. Добавить переключение темы
3. Добавить TopBar с пропсом noMargin или noShadow
2. Запустить приложение
3. Переключить тему

Ожидаемое поведение: 
Менятеся тема

Фактическое поведение:
Менятеся тема, у TopBar появляется отсуп или тень

Возможная причина:
Класс со второй темой, в котором указан стандартный отступ в 20 пикселей, указывается после класса, отвечающего за включение noMargin или noShadow. Поэтому класс со второй темой более специфичен и перезаписывает значения от пропсов noMargin и noShadow

CodeSandbox: https://codesandbox.io/s/naughty-roentgen-h4fq4?file=/src/App.js

@skbkontur/react-ui: 2.11.0
@skbkontur/react-ui-addons: 1.4.0
Chrome 87.0.4280.141, Windows 10

**Comment by lossir** [comment]
Вероятно, дело всё дело в этом https://github.com/skbkontur/retail-ui/issues/1952.
Причин заняться Emotion/каскадом основательнее, становится всё больше.

**Comment by zhzz** [comment]
Пофиксили в @skbkontur/react-ui-addons@2.1.2 и @skbkontur/react-ui-addons@1.6.1
