### ISSUE TITLE
[Dropdown] [DatePicker] Если в Dropdown засунуть DatePicker то в IE11 при клике на последний дропдаун закрывается

### ISSUE THREAD

**Issue by tihonove** [skbkontur/retail-ui#2281]
Привет! Опиши, пожалуйста, проблему, которая возникла:

- Библиотека: react-ui@2.12.1 и меньше
- Браузер: только ie11
- Сценарий: в заголовке
Пример кода для воспроизведения в песочнице (https://tech.skbkontur.ru/react-ui/#/Components/Dropdown):

```
import { DatePicker, Dropdown } from '@skbkontur/react-ui';

<Dropdown caption="Click">
  <DatePicker />
</Dropdown>;
```

**Comment by zhzz** [comment]
Выкатили тестовую версию на основе 2.17.1: @skbkontur/react-ui@0.0.0-6a047cca2c с фиксом. Подробнее #2458.

**Comment by zhzz** [comment]
Выкатили в `2.17.2` и `3.3.1`.
