### ISSUE TITLE
[Button] слетают стили

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2284]
https://t.me/react_ui/8048

В эльбе столкнулся с интересным эффектом
Используем `react-ui@2.5.0`
На  странице есть кнопка, у нее обычный вид
На этой же странице загружается скрипт candy-редактора https://api.testkontur.ru/candy/v1/client.js (`react-ui@2.1.2`)
Пока у кнопки по прежнему нормальный вид.
Говорим редактору нарисоваться  `window.CF.start({})`.
После этого у кнопки слетают стили.

Пока нашел следующее:
В react-ui  где-то внутри используется `emotion-js`
Из-за этого в head появляется куча `<style data-emotion="react-ui" ></style>`
В этих `style` в ч т есть стили для кнопки
Но эти теги как бы "пустые", вроде emition использует `insertRule`

Когда вызываю `window.CF.start({})`, то `emotion` хочет все такие теги "переложить" с атрибутом `data-s`: 

```javascript
  if ( key === 'css') {
    var ssrStyles = document.querySelectorAll("style[data-emotion]:not([data-s])"); // get SSRed styles out of the way of React's hydration
    // document.head is a safe place to move them to

    Array.prototype.forEach.call(ssrStyles, function (node) {
      document.head.appendChild(node);
      node.setAttribute('data-s', '');
    });
  }
```

**Comment by lossir** [comment]
Вероятно, причина в этом https://github.com/skbkontur/retail-ui/issues/1952

**Comment by RomanGorgol** [comment]
Выглядит так
![2021-02-01_17-10-05](https://user-images.githubusercontent.com/5558706/106704466-025a9c00-660e-11eb-8e7b-30720385c2fe.gif)

Очень похоже на то, что было в https://github.com/skbkontur/retail-ui/issues/2070
Но обновление до 2.3.2 не помогло. Оба приложения обновлены до 2.13
Кажется, проблема в emotion js и в том, что он внутри делает перекладывание стилей в head `document.head.appendChild(node);`

Если так повторно добавлять тег style, в который стили уже были вставлены через insertRule, то такие стили слетают и больше не применяются после повторного добавления https://stackoverflow.com/questions/36638076/why-are-styles-invisible-and-style-tags-not-re-appendable-after-using-insertrul

**Comment by RomanGorgol** [comment]
Нашел, что, возможно, проблема в том, что внутри react-ui сейчас используется emotion 10, а внутри кенди уже emotion 11 https://github.com/emotion-js/emotion/issues/2210 Но еще точно не уверен, разбираюсь дальше

**Comment by zhzz** [comment]
Привет @RomanGorgol! Удалось ли в итоге разобраться с проблемой?

**Comment by RomanGorgol** [comment]
Да, но костыльно, взял отсюда https://github.com/emotion-js/emotion/issues/2210

Перед подгрузкой candy-редактора делаем так

```js
        const emotion10Styles = document.querySelectorAll(`style[data-emotion]:not([data-s])`);
        Array.prototype.forEach.call(emotion10Styles, (node) => {
            node.setAttribute("data-s", "");
        });
```

**Comment by zhzz** [comment]
Нужно попросить ребят из кенди обновить свои зависимости на использование [@emotion/cache@11.4.0](https://github.com/emotion-js/emotion/pull/2365), в котором выпустили фикс. Должно решить эту проблему.

**Comment by zhzz** [comment]
Пока закрою.
