### ISSUE TITLE
Button use = 'link' занимает две строчки в случае, если текст в кнопке длиннее заданной ширины 

### ISSUE THREAD

**Issue by bae1** [skbkontur/retail-ui#2290]
В случае, когда текст кнопки длиннее заданной ширины, button use = 'link' занимает две строчки вместо одной:

![linkbutton](https://user-images.githubusercontent.com/12893644/107333426-47337680-6ad7-11eb-8bc2-e8da0d6ea774.png)

Необходимо, чтобы поведение кнопки-ссылки было такое же как у обычной кнопки, т е текст не должен вылезать за пределы отведенной ему строки.

**Comment by dzekh** [comment]
А это всё еще так? Я попробовал в доке на 3.0 воспроизвести, не получилось, всё так же одна строчка.

**Comment by dzekh** [comment]
Исправлено в 3.0
