### ISSUE TITLE
[Sticky] Если меняется размер стики, когда она закреплена, добавляется лишний margin-top

### ISSUE THREAD

**Issue by original001** [skbkontur/retail-ui#2291]
react-ui@lts

Суть:
Если `Sticky` закреплено и в этот момент увеличивается размер содержимого, то при достижении stop, добавляется некорректный `margin-top`. После этого залипание перестает работать

https://user-images.githubusercontent.com/8949234/107375859-06edeb80-6b0b-11eb-891c-08bb433acdc2.mov

после расследования обнаружил, что виновата `deltaHeight` из этого [коммита](https://github.com/skbkontur/retail-ui/commit/75fb581d22db1a9ab346e9351cecd3a3941c8ebe). попробовал убрать - все стало нормально работать. проверил кейсы в сторибуке либы на этот кейс - тоже норм.

**Comment by zhzz** [comment]
Предназначение `deltaHeight` как раз в том, чтобы компенсировать разницу размеров в зафиксированном и незафиксированном состоянии при достижении стопа. В наших историях без нее видны проблемы. Например, в [сторибуке](https://sticky-fix-delta-height.vercel.app/?path=/story/sticky--top) из ПРа, если очень медленно скролить вверх, то в момент достижения стопа можно заметить, как весь контент дергается вверх. [Раньше](https://default-rust.vercel.app/?path=/story/sticky--top) этого не было. Тесты это тоже поймали.

Вероятно дело в другом, или сценарий посложнее. Я не смог воспроизвести ваш по описанию. А на видео не очень понятно, что происходит. Можешь воспроизвести на [этом примере](https://codesandbox.io/s/eager-feistel-wu7ey?file=/src/index.js) в codesandbox? Смотрел в хроме/сафари.

**Comment by original001** [comment]
Я не смог воспроизвести в CodeSandbox, буду продолжать дебажить в своем сервисе

**Comment by original001** [comment]
Проблема оказалась в неочевидном поведении отрицательного отступа. у меня есть стоп элемент, который имеет прикрепляется книзу контейнера через `position: absolute, bottom: 0`. Но когда у стики появляется отрицательный отступ, то он передается на уровень выше. соответственно, и стоп элемент тоже смещается. По [спецификации](https://www.w3.org/TR/CSS2/box.html#margin-properties) марджин не передается наверх, если у родителя есть padding или border. 

Прикладываю codesandbox
https://codesandbox.io/s/distracted-haibt-2u82n?file=/src/index.js

В своем проекте я пока сделаю padding-top: 1

Почему используется именно `margin-top`? кажется, если менять только `top` для компенсации проблемы не будет

**Comment by original001** [comment]
Обнаружил еще один баг. Тоже связан с изменением размера стики
https://codesandbox.io/s/silly-agnesi-22obx

сценарий
1. проскролить до залипания
2. нажать раскрыть
3. контент залип книзу и не расширился как ожидалось

в сервисе визуально выглядит также, как на видео, но причина уже другая

**Comment by zhzz** [comment]
Поразбираемся

**Comment by original001** [comment]
пока сделал так, чтобы `Sticky` рендерилось, когда все данные получены. так размер стики не меняется динамически.

**Comment by zhzz** [comment]
Выяснилось, что `margin-top`  используется, потому что он позволяет двигать элемент вместе с соседями, в отличии от `top`. Это как раз то что нужно для компенсации разницы высот.

Но похоже, что можно починить эту проблему с `margin-top`, переверстав контейнер на флексах. В них марджины тоже не схлопываются.

Как только у себя протестируем, выкатим бету вам попробовать.

**Comment by zhzz** [comment]
Выкатил тестовую версию `0.0.0-a8072451c2` с фиксом, на основе 1.11.7. Можно потыкать на том же примере в [codesandbox](https://codesandbox.io/s/adoring-wood-7oiux). Проверьте у себя пожалуйста, все ли в порядке. Если да, то выкатим с ближайшим релизом.

> Обнаружил еще один баг. Тоже связан с изменением размера стики
https://codesandbox.io/s/silly-agnesi-22obx

Этот сценарий вроде тоже выглядит норм сейчас. Если я правильно понял и воспроизвел.

**Comment by zhzz** [comment]
@original001 не было возможности проверить? Тогда мы сперва в 2.х это выкатим, а потом уже в lts.

**Comment by original001** [comment]
> @original001 не было возможности проверить? Тогда мы сперва в 2.х это выкатим, а потом уже в lts.

не нашел время, планировал только в конце недели

**Comment by zhzz** [comment]
Исправлено в `1.11.8` и `2.14.0`.
