### ISSUE TITLE
[Input] [MaskedInput] В Сафари на Маке маска не той ширины чем символ цифры. С Лабом проблемы во всех браузерах.

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#2296]
Проявляется на https://guides.kontur.ru/components/mask/ в последней версии Сафари, на Mac OS Big Sur. Там символ примерно 2 пикселя шириной. 

На предыдущих версиях Сафари маска тоже не той ширины чем символ цифры, но это не так заметно. Скорее всего проявляется в 2.8.0 и выше после #2187

**Comment by dzekh** [comment]
А теперь с Лаб Гротеском есть проблема во всех браузерах, потому что по умолчанию в этом шрифте используются не моноширинные цифры, ширина 1 и 0 разная и маска все равно смещается. Нужно переключать символы поля на моноширинные цифры.

**Comment by lossir** [comment]
К сожалению, переключиться отдельно на моноширинные цифры нельзя.
Поддержка моноширинности в любом виде (все символы, или только цифры) должна быть заложена в самом шрифте. Если её нет, то придётся переключать шрифт целиком.

| шрифт | инпут |
| --- | --- |
| Lab | ![image](https://user-images.githubusercontent.com/2708211/160384306-c706eaae-d5a5-4f86-b1a0-50e7de07562b.png) |
| monospace (Win) | ![image](https://user-images.githubusercontent.com/2708211/160384243-1a278a99-bb7a-46d7-8ea3-805466052a2b.png) |
| monospace (Mac) | ![image](https://user-images.githubusercontent.com/2708211/160385699-70072801-f02e-4c4b-b7f0-5d859272e17f.png) |

---

### Первая мысль - отредактировать сам шрифт
т.е. сделать цифры моношириными. Но это слишком запарно. Надо будет править для разных стилей... Звучит не очень =)

### Другая мысль - уменьшить ширину маски
Сейчас она как-будто берётся по самой широкой цифре. По умолчанию `FIGURE SPACE` равен ширине цифр, если они моноширинные. Но в Лабе он скорее равен ширине "нуля".
Вместо него, можно использовать `EN SPACE`, который по ширине всегда равен половине от em (1em – текущий размер шрифта).
Тогда маска будет на так "дергаться" при вводе.

По-моему это приемлемо:
![ezgif com-gif-maker (28)](https://user-images.githubusercontent.com/2708211/160392572-95f02987-0451-440d-8a94-2054b58b3360.gif)


| символ | инпут |
| --- | --- |
| `FIGURE SPACE` (сейчас) | ![image](https://user-images.githubusercontent.com/2708211/160388827-7921dc4e-13db-4861-a070-cce12423a23a.png) |
| `EN SPACE` (половина от em) | ![image](https://user-images.githubusercontent.com/2708211/160388889-a81c47d1-a6f8-4123-b82a-edfec15e2a16.png) |

**Comment by dzekh** [comment]
вот [тут пишут](https://staff.skbkontur.ru/article/609d11026c99bb1a184cfb2c#sta-2) что что-то можно сделать.
В шрифте есть моно и обычные цифры, по умолчанию работают обычные, моно цифры можно включить в графическом редакторе или в верстке` font-feature-settings: 'tnum' on, 'lnum' on;`.

**Comment by lossir** [comment]
Нифига... Впервые вижу это свойство 😮
Да, в таком случае всё будет круто

**Comment by dzekh** [comment]
Перенес на ютрек в IF-639, здесь закрываю потому что сами создали
