### ISSUE TITLE
[Toggle] Состояние ошибки и предупреждения в тогле реализовано не правильно

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#2298]
![image](https://user-images.githubusercontent.com/26383080/108593597-6b743a80-7396-11eb-9083-183bb4503fb6.png)

Нужно сделать не заливкой а обводкой, так же как фокус.

**Comment by StathamJason** [comment]
@zhzz @dzekh в 3.0 пофикшено. В LTS надо исправлять?

**Comment by zhzz** [comment]
Не, не нужно. Можно закрывать.
