### ISSUE TITLE
[ComboBox] Не работает во всех браузерах кроме лисы в React 17.0.1

### ISSUE THREAD

**Issue by ConstantineC** [skbkontur/retail-ui#2318]
библиотека: react-ui: 2.14.1;
браузер: Chrome, Edge, IE;
сценарий: при нажатии на комбобокс ничего не происходит, как будто задизейблен, но без стилей;
![Animation (11)](https://user-images.githubusercontent.com/23449652/111309835-26ce7d00-867e-11eb-8b6a-57162a1ebc3c.gif)

**Comment by zhzz** [comment]
Да, полной поддержки React 17 пока нет, но мы уже работаем над ней.
