### ISSUE TITLE
[ComboBox] Фокус на кнопке добавления в ComboBox

### ISSUE THREAD

**Issue by ant-d-skb** [skbkontur/retail-ui#2325]
- Библиотека: react-ui
- Браузер: любой
- Проблема: при добавлении карточки должна быть возможность выбрать пункт "добавить" по умолчанию
- https://guides.kontur.ru/components/combobox/#Dobavlenie_kartochki_v_spravochnik

**Comment by dzekh** [comment]
Там сейчас работает единая логика для комбобокса — если есть совпадения со списком, в первую очередь подсвечиваются и выбираются они, и когда совпадений нет — подсветка переходит на пункт «добавить». Можно посмотреть пример в [доке](https://tech.skbkontur.ru/react-ui/#/Components/ComboBox) в разделе «Добавление элементов в меню».

Если добавление сущностей в отдельном окне или модалке до начала ввода текста частый сценарий, то лучше вынести действие на отдельный новый контрол — кнопку или иконку рядом. Но по хорошему прежде чем добавлять сущность пользователь должен убедиться, что такой еще нет в списке. Для этого нужно набрать текст, и если не будет совпадений — последний пункт добавления подсветится автоматически. Сейчас уже совет из Гайдов кажется не очень правильным и релевантным, скорее перепишем гайд чем будем реализовывать такое поведение. 

Я закрываю таску, если принципиально именно такое поведение можем переоткрыть и продолжить обсуждение.
