### ISSUE TITLE
[Modal] Рендеринг модального окна в любом месте

### ISSUE THREAD

**Issue by kostyabushuev** [skbkontur/retail-ui#2326]
Привет!

Есть потребность рендерить модальное окно не только внутри `body`, но и внутри любого контейнера. 
В некоторых случаях необходимо оставлять возможность пользователю просматривать другой контент на сайте, при этом не закрыв модальное окно.

[Наглядный пример, как это может выглядеть](https://codesandbox.io/s/gifted-shape-2iukr). Само модальное окно находится внутри блока, а не на все приложение и при этом кнопки таб активны для пользователя.

Данная реализация преимущественно интересует в версии 1.х
Есть ли в планах такое реализовать или может когда-то обсуждали что-то подобное?

**Comment by dzekh** [comment]
На первый взгляд достаточно спорный запрос, потому что «[модальное окно](https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D0%B4%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D0%BE%D0%BA%D0%BD%D0%BE)» оно на то и модальное, чтобы погрузить пользователя в определенный контекст не давая ему отвлечься и совершить ошибку. Оно блокирует остальной интерфейс и возвращает пользователя после того как он выполнил задачу в модалке. 

А есть прототипы интерфейса где подобные модальные окна используются?
