### ISSUE TITLE
Изменить цвет фона пунктов меню при наведении и цвет обводки фокуса

### ISSUE THREAD

**Issue by draugi** [skbkontur/retail-ui#2329]
![image](https://user-images.githubusercontent.com/26383080/112332405-87436700-8cdb-11eb-8709-0700e4901548.png)

Нужно изменить цвет фона активных пунктов меню с #5199db на #1D85D0. Это переменная bgActive которая смотрит на blueLight в теме. Нужно изменить blueLight.

borderColorFocus по тому же принципу — должна смотреть на blueLight, значение которой должно быть #1D85D0.

Потом проверяем, во всех ли контролах это применилось, ищем где отдельно может используется этот цвет #5199db, и там решаем, менять его или нет. Плюсом заапрувить новые скриншоты в тестах.

**Comment by dzekh** [comment]
Исправлено в 3.0
