### ISSUE TITLE
[react-ui] React 17 и npm 7.7

### ISSUE THREAD

**Issue by Ant-VAV** [skbkontur/retail-ui#2348]
Привет!
Суть проблемы: обновил npm с версии 6.9 до 7.7 и теперь он ругается на конфликт версии реакта для библиотеки.
Npm версии 6.9 игнорировал проблемы с версиями и просто ставил пакеты.

![image](https://user-images.githubusercontent.com/24953026/114386252-a5dda500-9b99-11eb-885a-6e94600a0e14.png)

@skbkontur/react-ui: 2.16.0
react: 17.0.2
ОС: Вин 10.

**Comment by lossir** [comment]
Привет.
Сейчас библиотека не поддерживает `react@17` и при его установке некоторые контролы будут падать.
Но мы как раз занимаемся реализацией этой самой поддержки. Планируем за время бета-стадии релиза что-нибудь придумать.
