### ISSUE TITLE
[SidePage] Добавить проп `offset`

### ISSUE THREAD

**Issue by chervyakovru** [skbkontur/retail-ui#2352]
Бывает нужно нарисовать `SidePage` не с самого края, а на каком-то расстоянии. Тогда проп `offset` был бы кстати.

Пример дизайна:
![image](https://user-images.githubusercontent.com/14909082/114703060-44a30680-9d3e-11eb-8ff4-22dc22f9b5a1.png)

**Comment by chervyakovru** [comment]
Решить можно прокинув значение пропа в стили компонента `SidePage.styles.ts`:

![image](https://user-images.githubusercontent.com/14909082/114703323-90ee4680-9d3e-11eb-88d6-33a4c262eb61.png)

**Comment by lossir** [comment]
По-моему, звучит вполне законно. Но нужна дизайн-аналитика @dzekh.

**Comment by dzekh** [comment]
Немного странно, что для такой сущности используется сайдпейдж, но в принципе, почему бы и нет. А можно увидеть гдето сценарий целиком, или другие состояния этого списка, как он открывается, как взаимодействует со страницей?

**Comment by chervyakovru** [comment]
Сценарий использования такой:

Мы открываем его по кнопке 🔎, закрыть можем по крестику
В нем вводим поисковый запрос - выпадают 2 сущности: сделка и клиент

При клике на клиента открывается сайдпейдж справа с информацией о клиенте
При клике на сделку закрываются все сайдпейджи и переходим на страницу сделки

**Comment by chervyakovru** [comment]
@dzekh Что скажешь? Добавляем проп?

**Comment by dzekh** [comment]
Да, кажется норм сценарий. Можно добавить проп для смещения.
