### ISSUE TITLE
[react-ui-validations] Валидация `lostfocus` срабатывает сразу после рендера

### ISSUE THREAD

**Issue by XrustS** [skbkontur/retail-ui#2355]
https://t.me/react_ui/8670
> Ребята настраиваю валидацию через "@skbkontur/react-ui-validations": "1.1.5" тип для объекта с ошибкой установлен в type: "lostfocus". При первичной отрисовке формы все поля краснеют. Как это исправить? Форма рисуется 1 раз.

Ожидается, что валидация с типом `lostfocus` всегда должна происходить только после потери фокуса конкретным элементом. 

Для воспроизведения достаточно задать подобное правило для `validationInfo`:
```typescript
!value ? { message: 'Error msg', type: 'lostfocus' } : null;
```

**Comment by zhzz** [comment]
Исправили в react-ui-validations@1.4.3
