### ISSUE TITLE
[Tabs] Неправильное позиционирование подсветки активной вкладки при первом рендере

### ISSUE THREAD

**Issue by AndrewVdovichenko** [skbkontur/retail-ui#2357]
Если во вкладках использовать только картинки без видимого текста, при первом рендере подсветка активной вкладки отображается между компонентами.

 - библиотека: @skbkontur/react-ui@2.15.0;
 - браузер: Firefox 87, Chrome 89 (скорее всего проблема во всех браузерах);
 - ОС: Win 10, MacOS;

![kontur-react-ui-tabs-bug](https://user-images.githubusercontent.com/10368397/115135194-e02ec280-a02f-11eb-8a3c-49df734797d3.gif)

**Comment by lossir** [comment]
@AndrewVdovichenko Привет.
Не удалось воспроизвести на витрине. Можешь приложить код вкладок?
Ещё кажется, будто они рендерятся в `SidePage` - это так?

**Comment by AndrewVdovichenko** [comment]
@lossir 
Я сделал демку https://github.com/AndrewVdovichenko/react-ui-tabs-bug

**Comment by lossir** [comment]
@AndrewKostousov Спасибо за демку. Вроде всё также сделал на [codesandbox.io](https://codesandbox.io/s/react-ui-tabs-9dt6u?file=/src/index.js), но баг не воспроизводится.
Пока помечу пока как `can't reproduce`.

**Comment by AndrewVdovichenko** [comment]
@lossir Весь прикол в том, что не должно быть текста, только картинки. Так же как и в гифке. Поправил вашу демку, чтобы увидели баг - [codesandbox.io](https://codesandbox.io/s/react-ui-tabs-forked-2lgdm?file=/src/index.js)
