### ISSUE TITLE
[CurrencyInput] Не работает выделение двойным кликом в IE

### ISSUE THREAD

**Issue by StathamJason** [skbkontur/retail-ui#2361]
Источник - [сообщение в телеге](https://t.me/react_ui/8682)

**Проблемы в  CurrencyInput:**
1. Выделение по двойному клику в IE не работает
1. ~~В IE, если добавить проп `selectAllOnFocus`, то после фокусирования, фокус не снимается последующими нажатиями на значение~~ (отдельная задача https://github.com/skbkontur/retail-ui/issues/2362)

_В Chrome описанный баг не воспроизводится_

**Comment by hukopo** [comment]
Насчет 2-го пункта если к инпуту прийти табами, то тоже не работает "развыделение"

**Comment by hukopo** [comment]
Кажется я нашел решение, возможно оно есть костыль, но можно дальше поразбираться, у CurrencyInput Есть метод ```handleMouseUp``` который передается в проп ```handleMouseUp``` input-у в него приходит реактовский евент из таргета которого позже достается selectionStart и selectionEnd . которые там немного обрабатываются в CurrencyInput после чего сетяться в стейт из-за чего вызывается componentDidUpdate в котором есть строчка this.input.setSelectionRange(start, end); которая собственно меняет Selection у input-а внутри CurrencyInput из-за чего в ие не работает. Я не могу однозначно обьяснить почему сейчас работает в хроме, но не работает в ие, но локально у себя я завернул вызов setSelectionRange в дебаунс с 2000 мс и у меня все заработало! возможно это не лучшее решение, но я бы это обсудил с кем-то...

**Comment by hukopo** [comment]
Я создал пулл реквест https://github.com/skbkontur/retail-ui/pull/2363 не уверен, что он сходу заработает(локально не могу у себя ничего запустиь:с) Хотя вроде должен так-то

**Comment by StathamJason** [comment]
> Я создал пулл реквест #2363 не уверен, что он сходу заработает(локально не могу у себя ничего запустиь:с) Хотя вроде должен так-то

ок, пр проверим и фибдбек дадим
