### ISSUE TITLE
[CurrencyInput] При клике на выделенный фрагмент выделение не снимается в IE11

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2362]
Источник: https://t.me/react_ui/8682

> 3 в ие, если добавить опцию selectAllOnFocus то после фокусированию через курсор, фокус не снимается последующими жмаками, даже не в первоначальное место, но и между другим буквами тоже

**Comment by hukopo** [comment]
Я думаю, что эту задачу можно поставить дубликейтед, потомучто это та же самая проблема, что и в задаче https://github.com/skbkontur/retail-ui/issues/2361

**Comment by lossir** [comment]
Проблемы похожи, но, думаю, исправляются по разному.
Например, этот баг можно исправить добавив сброс выделения на событие `onMouseDown`.

**Comment by lossir** [comment]
Но если обе проблемы получится вылечить одним решением, то не будет проблем просто закрыть сразу 2-е ишью =)

**Comment by hukopo** [comment]
Я во второй ишью написал решение, которое мне лечит все, поэтому что баг один и тот же) правда я не понимаю как этот баг вообще работает...
