### ISSUE TITLE
[react-ui-validation, Modal]: Не правильно скролится к ошибке

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#2367]
"@skbkontur/react-ui-validations": "^1.4.0",
"@skbkontur/react-ui": "^2.16.0",

Если в модалке много полей обернутых библиотекой валидации, то при ошибке проскролится контент и поле улетит под шапку.

![image](https://user-images.githubusercontent.com/9654622/115836094-8152ba00-a430-11eb-8780-71254706ea3e.png)

Также бы хотелось указывать offset если например вместо модалки будет залипающий контент на странице

**Comment by StathamJason** [comment]
Не смог воспроизвести

**Comment by zhzz** [comment]
У `ValidationContainer` есть проп [`scrollOffset`](https://github.com/skbkontur/retail-ui/blob/8a7825c2cf16cc804a0dcd3bd63c35ecc36e74c3/packages/react-ui-validations/src/ValidationContainer.tsx#L15), который служит как раз для этого. К сожалению в доке пока не описан.

**Comment by zhzz** [comment]
Пока закрою. Если не поможет - пиши снова.
