### ISSUE TITLE
[docs] не работает кастомизация тёмной темы

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2368]
Источник: https://t.me/react_ui/8689

> если выбрать темную тему и нажать "Настроить тему" страница падает с ошибкой "Error: none is not a valid hex color string"

https://tech.skbkontur.ru/react-ui/#/Customization/ThemePlayground

| ![image](https://user-images.githubusercontent.com/2708211/116084469-457d5600-a6b7-11eb-92ac-ad146b57f708.png) |
| --- |

**Comment by StathamJason** [comment]
Кажется уже починилось (ну в мастере точно работает)
