### ISSUE TITLE
[Button] В Safari остаются disabled стили после их снятия IF-637

### ISSUE THREAD

**Issue by StathamJason** [skbkontur/retail-ui#2422]
Скинули Sandbox: https://codesandbox.io/s/icy-cloud-98z42?file=/src/index.js

> У человек проявляется баг, на кнопке. После снятия флага disbaled на кнопке остаётся часть стилей от disabled.
Если конкретно, то цвет текста кнопки остаётся как будто она всё ещё disabled.

Проверил на мастере, в последней версии Big Sur и сафари, воспроизвелось. Видео ниже: по вводу текста в область проп `disabled` устанавливается в `false`, видно что цвет текста в кнопке остается серым, а после нажатия на нее норм

https://user-images.githubusercontent.com/31249664/120615291-8d8b5780-c471-11eb-9405-403158dc7a52.mov

**Comment by dzekh** [comment]
Проверили, не воспроизводится
