### ISSUE TITLE
[react-ui-testing] Сборка с минификацией

### ISSUE THREAD

**Issue by Raykeen** [skbkontur/retail-ui#2432]
У нас в проекте функциональные тесты гоняются на production сборке. Это сделано для оптимизации, эта же сборка может быть отправлена в релиз. Также тесты могут гоняться на тестовых стендах, где тоже prod сборка. 
В prod сборке названия компонентов минифицируются. При этом  бибилотека для тестирования образается к элементам по названию компонентов. Таким образом становится невозможно тестировать компоненты. Можно ли отвязать библиотеку от названий компонентов и переехать с них на data-tid?
Ещё один аргумент против использования названий компонентов состоит в том что некоторые баги могут проявлятся только в production сборке.

**Comment by zhzz** [comment]
Спасибо за issue, подумаем над этим. Но вряд ли в ближайшее время. Можем помочь затащить Pull Request.

**Comment by asukhar** [comment]
Исправлено в #2900
