### ISSUE TITLE
[DatePicker] Съезжают иконки календарей

### ISSUE THREAD

**Issue by alivekenny** [skbkontur/retail-ui#244]
Съезжают иконки календарей. Можно посмотреть на https://keadmin.dev.kontur/Letters в разделе «Сообщения техподдержки» в поиске. Проявляется в Сафари, Хроме и в ФФ на винде. 

![bitmap](https://user-images.githubusercontent.com/21039303/27821079-68042934-60ba-11e7-8e1e-2b2a81755f86.png)

**Comment by nanot1m** [comment]
Привет! Никак не могу воспроизвести данную проблему, можешь накидать сниппет на http://tech.skbkontur.ru/react-ui/#/components/DatePicker?

**Comment by nanot1m** [comment]
@alivekenny подскажи, проблема актуальна?

**Comment by alivekenny** [comment]
@nanot1m наверняка. На https://keadmin.dev.kontur/Letters все еще висит баг. Про то, как так получилось, наверное, лучше расскажет [Сережа Королев](https://staff.skbkontur.ru/profile/skorolyov), он делал эту часть админки

**Comment by nanot1m** [comment]
Обновили DatePicker, баг должен был пропасть
