### ISSUE TITLE
[Input] Сделать левый и правый отступы по 10рх

### ISSUE THREAD

**Issue by alivekenny** [skbkontur/retail-ui#245]
Сейчас согласно скетчевой библиотеке контролов отступ от левого и правого края инпута и селекта должен быть равен 8рх. При этом отступ в селекте сейчас заверстан 10рх.

Решено, что лучше везде сделать отступ в 10рх.

Это же касается всех элментов вроде DatePicker, TextArea, ComboBox и так далее.

**Comment by nanot1m** [comment]
Исправлено
