### ISSUE TITLE
[DatePicker] внутри DropdownMenu при клике на дату, дропдаун закрывается

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2456]
Источник: https://t.me/react_ui/9048

> в ИЕ не могу сделать DatePicker внутри DropdownMenu. при клике на дату, дропдаун закрывается. воспроизводится на витрине.

```javascript

import { Button, MenuHeader, MenuItem, MenuSeparator, DatePicker } from '@skbkontur/react-ui';

<DropdownMenu caption={<Button use="primary">Открыть меню</Button>}>
  <MenuItem>Раз</MenuItem>
  <MenuItem
    component={() => (
      <DatePicker
        width={110}
        value={""}
      />
    )}
  >
  </MenuItem>
</DropdownMenu>;

```

Воспроизводится и в Хроме

**Comment by original001** [comment]
возьмите, пожалуйста, в работу. задача, которая зависит от этого бага подвисла.

**Comment by zhzz** [comment]
@original001 В какую версию нужен фикс?

**Comment by original001** [comment]
2 lts

**Comment by zhzz** [comment]
Выкатил тестовую версию на основе 2.17.1: `@skbkontur/react-ui@0.0.0-6a047cca2c`.

В lts, как обычно, появится попозже.

**Comment by original001** [comment]
Проверил, работает

**Comment by zhzz** [comment]
Выкатили в `2.17.2` и `3.3.1`.
