### ISSUE TITLE
Проблема с тенями у тултипа в браузере Safari

### ISSUE THREAD

**Issue by Nevenq** [skbkontur/retail-ui#2459]
Привет, появился неприятный баг после обновления до React UI 3.2.0. Воспроизводится вроде только в браузере Safari
 
https://user-images.githubusercontent.com/38163651/124091725-902c9d00-da6f-11eb-8529-6ec26e0dee20.mov

**Comment by dzekh** [comment]
про то же в #1677 и #1495
