### ISSUE TITLE
[Select] Страница скачет, если список раскрывается у нижней границы экрана

### ISSUE THREAD

**Issue by alivekenny** [skbkontur/retail-ui#247]
Когда выпадающий список находится слишком близко к низу экрана, то при открытии список уходит за границу, а у экрана появляется дополнительное пространство для скроллинга.

**Проблема:** Если после этого закрыть список, а потом повторно его открыть, то экран сдвинется на высоту списка, из-за чего вся страница скачет. 

**Возможное решение:** не сдвигать страницу автоматически и давать пользователю самому докрутить до нужного пункта.

**Дополнительно:** Сейчас раскрывающийся список упирается в самый низ экрана, из-за чего может сложится ощущение, что за границей экрана есть еще пункты, до которых не добраться. Чтобы этого избежать нужно сделать небольшой отступ от раскрытого списка до края экрана.

![giphy](https://user-images.githubusercontent.com/21039303/27831435-217296c0-60e4-11e7-9691-775d17932dca.gif)

**Comment by nanot1m** [comment]
Это не наш селект
