### ISSUE TITLE
[Tabs] IE. Артефакты на табах при задании меньшего line-height

### ISSUE THREAD

**Issue by a-nadya** [skbkontur/retail-ui#2500]
Привет! Опиши, пожалуйста, проблему, которая возникла:

- @skbkontur/react-ui 3.3.1
- IE
- при задании меньшего line-height появляется артефакт. 
![image](https://user-images.githubusercontent.com/54811044/128192048-3ec433a8-a42d-4291-a263-fcf2ba65b0ed.png)
артефакт представляет собой iframe <iframe tabindex="-1" title="resizeDetector" class="react-ui-17gu5je"></iframe>

**Comment by zhzz** [comment]
Да, есть такое. Это появляется скроллбар у скрытого `iframe`. Можно легко полечить, например, сделав iframe прозрачным.
