### ISSUE TITLE
[TokenInput] Не работает Enter в состоянии WithoutReference

### ISSUE THREAD

**Issue by vansosnin** [skbkontur/retail-ui#2527]
- @skbkontur/react-ui проверял на 2.16.0 и на актуальной версии в документации
- Chrome 92, Win10

Если сделать TokenInput с `type={TokenInputType.WithoutReference}`, то у него не срабатывает превращение введенного текста в Token при нажатии на `Enter`. Судя по пункту [07 в гайдах](https://guides.kontur.ru/components/tokens/#07), это должно работать.

**Дополнение**: в состоянии редактирования токена `enter` также не срабатывает, хотя [должен](https://guides.kontur.ru/components/tokens/#37)

**Comment by zhzz** [comment]
Пофикшено в 3.10.0
