### ISSUE TITLE
[DatePicker] на скролится календарь тачпадом в IE11

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2532]
https://user-images.githubusercontent.com/2708211/132330605-ca66ddd4-8af6-410f-9bf4-4a365b9dfbdf.mp4

**Comment by zhzz** [comment]
Думаю, довольно серьезная проблема, чтобы заняться в первую очередь.

**Comment by dzekh** [comment]
Кажется, учитывая количество пользователей ИЕ11 сейчас, тенденцию к отказу от ИЕ, и то, что сценарий выбора даты в принципе не ломается (можно ввести с клавиатуры или выбрать месяц и год в выпадающих меню) — можно не исправлять это поведение. Закрою баг до следующего подобного обращения.
