### ISSUE TITLE
[Chekbox, Radio] Не работает состояние :active для вложенных элементов в IE11

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2546]
Проблема в том, что стили элемента для состояния `:active` игнорируются, при клике на вложенные в него элементы. Т.е. чтобы сработало, надо кликнуть непосредственно на элемент для которого заданы такие стили.

Ранее уже лечили этот баг в рамках общего пачта после выхода `3.0` (#2397). Но [решение](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/components/Checkbox/Checkbox.styles.ts#L50-L53) найденное на [stackoverflow](https://stackoverflow.com/questions/31061544/active-selector-in-ie11-doesnt-work-if-there-are-nested-elements-how-do-i-mak) оказалось неудачным, т.к. игнорируются события мыши на переданных `children`.

Есть 2 варианта:
1. Переделать на `js` с отдельным классом для состояния `:active`.
2. Забить и вернуть как было, т.к. до этого патча, состояние `:active` в IE11 вовсе не было. И вроде никто не жаловался)

**Comment by dzekh** [comment]
Перенес в IF-631 в ютрек.
