### ISSUE TITLE
[Checkbox] обводка фокуса перебивает ошибку при валидации

### ISSUE THREAD

**Issue by lossir** [skbkontur/retail-ui#2550]
Кажется, после этого https://github.com/skbkontur/retail-ui/pull/2528 исправления в `3.7.0`, сломались стили при валидации.
При валидации чекбокс получает фокус, но должен оставаться красным.

> _Красная подсветка снимается с поля, как только пользователь начал исправлять ошибочное значение._
©️ [Контур.Гайды](https://guides.kontur.ru/principles/validation/#13)

---

Но сейчас стили фокуса перебивают стили ошибки: [Пример на codesandbox.io](https://codesandbox.io/s/validations-checkbox-p6y0c)

| `Checkbox` | `Radio` |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2708211/134944679-f4be350a-19f0-4adc-b079-df1bfd60b4da.png) | ![image](https://user-images.githubusercontent.com/2708211/134944725-9383cefa-8811-4066-9192-5911db898e72.png) |

**Comment by dzekh** [comment]
Тут есть тонкость похожая на тот же кейс что есть при работе с клавиатурой/мышью. 
При работе с мышью мы не показываем фокус на контролах кроме полей, а при работе с клавиатурой показываем, При программном фокусировании должно быть так же как с мышью — фокус не должен перекрывать ошибку. Но если фокус ставится на контрол в состоянии ошибки умышленно табом он должен перебивать стиль ошибки. Кажется так должно работать, иначе как я пойму где сейчас мой фокус если я управляю с клавиатуры? 
Либо нужно придумывать совмещенное состояние ошибки/фокуса. Но это уже отдельная история.

**Comment by lossir** [comment]
>  Кажется так должно работать, иначе как я пойму где сейчас мой фокус если я управляю с клавиатуры?

@dzekh , нужно в более утвердительной форме написать, как в итоге исправлять)

**Comment by dzekh** [comment]
При программном фокусировании должно быть так же как с мышью: визуально фокус не должен появляться и перекрывать ошибку. Подсветка красным должна остаться. 
Но если фокус ставится на контрол в состоянии ошибки при переходе табом — фокус должен перебить стиль ошибки: красная обводка должна становиться синей. 
При этом, если пользователь снова нажал таб и фокус перешел на следующий контрол — тот с которого фокус ушел должен: 1) если его состояние не изменено (не изменено значение в поле, не выбрана другая радиокнопка, или не изменено состояние чекбокса (это как примеры, вариантов может быть много)) — Продолжать подсвечиваться красным; 2) если его состояние или значение изменено — сбросить состояние ошибки и подсветку красным.
