### ISSUE TITLE
[React UI] Math.trunc не поддерживается в IE11

### ISSUE THREAD

**Issue by sergeyshmakov** [skbkontur/retail-ui#2552]
- 3.7.0
- IE11
- https://caniuse.com/?search=Math.trunc

Сейчас приходится включать entry-полифиллы специально для `react-ui` или прогонять папку через `babel` в случае `usage`, чтобы обеспечить поддержку в IE11. 

Нужно обеспечить поддержку `Math.trunc` для IE11 из коробки без дополнительных преобразований на стороне пользователя библиотеки.

**Comment by zhzz** [comment]
Библиотека использует многое из того, у чего в IE11 [нет поддержки](https://kangax.github.io/compat-table/es6/#ie11), но для чего есть полифиллы. Не только `Math.trunc`. Также `Promise`, `String.prototype methods`, `Array.prototype methods` и др.

Политика библиотеки всегда была в том, чтобы не тащить в бандлы пользователей лишние полифиллы, если они им не нужны. Т.е. они должны подключаться на стороне пользователей, при необходимости. Уже многие не поддерживают IE11. А остальные часто сами используют полифиллы для своего кода.

Вроде бы в ваших методах нет ничего плохого.

**Comment by sergeyshmakov** [comment]
В принципе позиция понятная и имеет право на жизнь. Почему то я думал, что у нас все поддерживают IE11 пока это делает auth,
