### ISSUE TITLE
[React UI] Обеспечить явное указание необязательности пропсов для интерфейсов IF-634

### ISSUE THREAD

**Issue by sergeyshmakov** [skbkontur/retail-ui#2553]
- 3.7.0

Сейчас наблюдается несоблюдение указания необязательности пропсов в интерфейсах компонентов в сравнении с официальной документацией.

На примере [`Hint.tsx`](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/components/Hint/Hint.tsx) видно, что свойства `disableAnimations` и `useWrapper` являются необязательными в соответствии с [документацией](https://tech.skbkontur.ru/react-ui/#/Components/Hint), однако в интерфейсе компонента они указаны как обязательные, в то время как остальные необязательные пропсы указаны в интерфейсе верно.

На примере [`Tooltip.tsx`](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/components/Tooltip/Tooltip.tsx) видно, что свойства `disableAnimations`, `useWrapper` и `allowedPositions` являются необязательными в соответствии с [документацией](https://tech.skbkontur.ru/react-ui/#/Components/Tooltip), однако в интерфейсе компонента они указаны как обязательные, в то время как остальные необязательные пропсы указаны в интерфейсе верно.

### Наша мотивация 

Мы много где наследуемся от пропсов ваших компонентов, чтобы одновременно предоставлять типизируемые, необходимые для `react-ui`, пропсы на местах использования и прокидывать свои. Но это становится сложно и напряжно, когда обязательные пропсы начинают не совпадать с документацией. Это приводит к костылям в нашем коде и для нас недопустимо в долгосрочной перспективе.

### Что еще странно

У части пропсов необязательность указана явно через "вопросики", у другой части этого нет. Т.е. у вас произошла смена стиля описания типов, при этом прошлая схема описания с "вопросиками" осталась.

Для нас это выглядит так, будто в какой-то момент кто-то забил на явное указание необязательности и решил что указания в `defaultProps` достаточно. Но на самом деле этого недостаточно, если мы хотим использовать ваши типы у нас в проекте.

### Что мы предлагаем

Пройтись по всем компонентам и проставить явно необязательность свойств в интерфейсе.
От вас требуется лишь решение, согласны вы или нет, проставить мы можем и своими силами.

**Comment by zhzz** [comment]
Возможное решение через `defaultProps` и нашу мотивацию я привел в [слаке](https://kontur.slack.com/archives/C013HTCE18Q/p1632471013212700). Если кратко, нам так писать код было удобнее. Но я согласен обменять наше удобство на удобство пользователей. Можно и переписать.

**Comment by zhzz** [comment]
Ваше предложение с правкой интерфейсов на явную необязательность считаю норм. Но придется тогда и код еще кое-где дополнить проверками на `undefined`. Линтеры подскажут.
