### ISSUE TITLE
[Button] Белая обводка на углах кнопок

### ISSUE THREAD

**Issue by evilPaprika** [skbkontur/retail-ui#2559]
Библиотека: 
**@skbkontur/react-ui@3.7.1**
Браузер, его версия, ОС: 
**Хром 94.0.4606.81, Windows 10**

Белая обводка на углах кнопок:
![image](https://user-images.githubusercontent.com/27489220/137438983-6b3fe7b9-0dcd-4f78-ae39-b8a3b47d90bf.png)

Особенно заметно на Flat теме, и если например увеличить border-radius
![image](https://user-images.githubusercontent.com/27489220/137439616-556899f4-e576-4cc7-91de-b62cf233ab8c.png)

https://tech.skbkontur.ru/react-ui/#/Customization/ThemePlayground

Я выяснил проблема возникает из за свойства  
```
    background-clip: padding-box;
```
И проблема исчезает если поменять его на 
```
background-clip: border-box
```

**Comment by evilPaprika** [comment]
> на сколько эта проблема критична для вас?

Сейчас прямо не горит, но все равно неприятно что так выглядит.

А что ты думаешь про https://github.com/skbkontur/retail-ui/pull/2560 ?
Совсем небольшое измнение, и судя по скриншотам нужно поправить только Switcher немного. Пользу полупрозрачных обводок я не понял, они точно где-то используются и нужны? Я не нашел использований.

**Comment by zhzz** [comment]
В ПРе пострадали плоские заблокированные кнопки. На скриншотах их не видно, потому что оказывается у нас настройка чувствительности понизилась недавно.

| было | стало | дифф |
| - | - | - |
| ![image](https://user-images.githubusercontent.com/4607770/137918455-d9e3d610-cd88-4746-81ae-7cab7f82dfff.png) | ![image](https://user-images.githubusercontent.com/4607770/137918524-821ce51c-d325-4ea0-8216-b3dc1541beb0.png) | ![image](https://user-images.githubusercontent.com/4607770/137918565-5d6e6afa-cb70-42da-9f37-e03729fa4167.png) |

Полупрозрачные обводки нужны плоским заблокированным кнопкам. На белом фоне обводки не должны выделяться, а на сером они не должны сливаться с фоном.

Например, в \<SidePage.Footer />, с пропом panel и без. Первая кнопка с padding-box, вторая с border-box. Первая ведет себя корректно.

![image](https://user-images.githubusercontent.com/4607770/137921867-8e69c9cb-915a-49ca-96ab-97c08bd19fa2.png)
![image](https://user-images.githubusercontent.com/4607770/137921657-ce7cbf33-eb4c-4702-a488-7947d35799ae.png)

---
Но, если вы бы сейчас предпочли у себя `border-box`, то можно просто вынести это в переменную, вы у себя переопределите. А мы починим как следует позже.
