### ISSUE TITLE
[TokenInput] Подсказка, которая есть в пустом поле пропадает, когда выбран токен

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#2585]
«[Плейсхолдер подсказывает, что в поле можно ввести несколько значений](https://guides.kontur.ru/components/tokens/#08)» - но плейсхолдер не отображается, если есть хотя бы одно значение => если инпут заполнили давно или автоматически при обновлении, то такой подсказки недостаточно — её по просту уже не видно.

**Comment by lamergood** [comment]
Обновил примеры в гайдах, добавил описание к элементу в библиотеке в фигме. Пример есть в иллюстрациях к гайду: https://www.figma.com/file/YEOImn7GAFzsNX3BTgzjMtRY/Guides-Illustration?node-id=3057%3A20587

**Comment by dzekh** [comment]
Вот что пишут дизайнеры:
![image](https://user-images.githubusercontent.com/26383080/145805403-769e4f81-e301-4187-b632-40872bbd18a1.png)

Я предложил бы в итоге: 

- [ ] Убрать из гайдов примеры когда плейсхолдер остается после выбора токена (извини Леша :)
- [ ] Добавить абзац, рекомендующий использовать в лейбле множественные числа. 
- [ ] Исправить лейбл в примере в самом начале, и везде где они есть в тексте. 
- [ ] Добавить абзац про то, как поступать в том случае, если поле уже заполнено кем-то другим, когда-то давно, и есть опасения что новый пользователь не поймет как взаимодействовать с полем, и нет возможности показать плейсхолдер. Например, что можно делать пояснительную подпись под полем.
