### ISSUE TITLE
[TokenInput] Удалить референсы на разрешённые issues из гайда

### ISSUE THREAD

**Issue by JackUait** [skbkontur/retail-ui#2589]
В гайде про [поле с токенами](https://guides.kontur.ru/components/tokens/) остались ссылки на уже **закрытые** `issues`.

Речь идёт о [шестом](https://guides.kontur.ru/components/tokens/#06) и [двадцать пятом](https://guides.kontur.ru/components/tokens/#25) пунктах гайда.
 
| Название                                                     | Issue    | PR         |
|:-----------------------------------------| -------|-------|
| Запятая ведет себя не как разделитель | #1860 | #2539  |
| Подсветка и выбор пункта по Enter        | #1878  |   #2183 |

**Comment by dzekh** [comment]
убрали
