### ISSUE TITLE
[Button] Состояния `error` и `warning`

### ISSUE THREAD

**Issue by JackUait** [skbkontur/retail-ui#2599]
В [гайдах](https://guides.kontur.ru/components/button/#26) чётко прописано, что _"Кнопка не может быть неправильной или обязательной для нажатия"_.

При этом `API` контрола [`Button`](https://tech.skbkontur.ru/react-ui/#/Components/Button) предусматривает состояния `error` и `warning` создающие красную и оранжевую обводки вокруг кнопки соответсвенно.

**Comment by zhzz** [comment]
Эти состояния нужны не для самой кнопки, а для компонентов, которые на ней построены, например, Select. Дизайн этих состояний содержит внутреннюю белую обводку, которую, видимо, проще было реализовать в кнопке. К тому же, кнопка еще может быть в виде стрелки и там вообще нет других вариантов реализации, если такое понадобится.

**Comment by JackUait** [comment]
Тогда закрываю issue.
