### ISSUE TITLE
[Loader] Позиционирование 

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#260]
Сейчас лоадер позиционируется по центру контента, а не по центру видимой области. Если область контента, который обновляется, больше экрана, или смещена — лоадер не видно. Нужно чтобы он висел по центру видимой области блока, который загружается или обновляется. В том числе и по горизонтали и по вертикали. 
![2017-07-24 12 15 24](https://user-images.githubusercontent.com/26383080/28512647-37be28b2-706c-11e7-9f26-ea480041d7b4.jpg)

**Comment by slawwan** [comment]
#333
