### ISSUE TITLE
[DatePicker] onValueChange в DatePicker передает значение не по шаблону dd.mm.yyyy, если ввел дату не до конца с клавиатуры

### ISSUE THREAD

**Issue by vorkulsky** [skbkontur/retail-ui#2600]
- @skbkontur/react-ui 3.8.2
- chrome 95.0.4638.54, windows

onValueChange в DatePicker передает значение не по шаблону dd.mm.yyyy, если ввел дату не до конца с клавиатуры. Например, если ввел 0, передается "00". Хотя в документации написано, что аргумент метода должен соответствовать шаблону dd.mm.yyyy.

Сейчас приходится сравнивать с шаблоном, перед тем как использовать эту дату как дату в onValueChange.

Точно стоит об этом написать в документации, а то не очевидно.
И, возможно, полезно будет сделать отдельное событие, которое говорит, что дата введена полностью.

**Comment by zhzz** [comment]
Привет. Да, это известная проблема, есть похожие issue (https://github.com/skbkontur/retail-ui/issues/1971). Мы планируем исправить это. 

Пока можно также использовать метод `DatePicker.validate`:
```ts
DatePicker.validate: (value: string, range?: { minDate?: string; maxDate?: string }) => boolean
```

В документации первый пример об этом.

**Comment by dzekh** [comment]
Закрываю, потому что дубль
