### ISSUE TITLE
[Center] Доработка `API` контрола `Center`

### ISSUE THREAD

**Issue by JackUait** [skbkontur/retail-ui#2616]
В `API` контрола `Center` не хватает двух полезных пропов:
1. `shape` -  позволит менять форму контрола на круг.
2. `size` - сокращение для `width: size; height: size;`.

Аргументация добавления этих пропов:
1. Это расширение `API` покроет частые сценарии использования контрола `Center`. 
2. Новое `API` позволит избавиться от лишних компонентов-обёрток/классов в коде проектов.

## shape
Проп `shape` имеет следующий тип: `shape?: "circle"`. 

Учитывая, что `shape` может принимать только одно значение, может показаться, что логичнее было бы сделать `circle` булевым пропом, но как показывает практика:
1. Подход со строкой более описателен.
2. В текущем виде, проп `shape` можно будет расширить в будущем, например, добавив значение `"ellipse"`. С расширением при булевом `circle` возникнут проблемы с консистентностью `API`. Подобные проблемы с булевыми пропами уже есть в контролах `Radio`(#2606) и `Button`(#2613).
3. Булевые пропы хороши, когда они могут задавать сразу несколько состояний одной сущности. Хороший пример использования булевых пропов - пропы `disabled` и `borderless` из контрола [`Button`](https://tech.skbkontur.ru/react-ui/#/Components/Button). Кнопка может быть одновременно отключённой и не иметь обводки.

Сценарии, в которых пригодился бы `shape="circle"` можно найти на основном [лендинге контура](https://kontur.ru/).
<img width="265" alt="Снимок экрана 2021-11-03 в 23 40 56" src="https://user-images.githubusercontent.com/48599460/140189514-de721b82-f450-49b2-9a2b-97331d2e9e2d.png">

Оба этих элемента могли быть сделаны с помощью `shape="circle"`.

## size
Проп `size` - это удобный способ задания размеров для форм квардата и круга.
<img width="250" alt="Снимок экрана 2021-11-03 в 16 49 26" src="https://user-images.githubusercontent.com/48599460/140072731-159f1f46-4ec3-4c59-a217-6cada31455f4.png">
<img width="206" alt="Снимок экрана 2021-11-03 в 16 42 19" src="https://user-images.githubusercontent.com/48599460/140071822-317f9563-6c9e-4932-8ec2-47db189f34d6.png">

**Comment by lossir** [comment]
Это довольно странно... Будто смешивается тёплое с мягким.
Компонент отвечает исключительно за позиционирование. А при необходимости подобной стилизации уже сейчас можно использовать проп `style`.

Этот компонент можно "улучшить", если сделать полноценный аналог модульной сетки, как в [бутстрапе](https://getbootstrap.com/docs/4.0/layout/grid/) или [material-ui](https://mui.com/components/grid/). Тогда `<Center />` можно будет спокойно выкинуть =)

**Comment by dzekh** [comment]
Согласен с Максимом, выглядит странно. Женя, а есть примеры в других библиотеках подобного применения?

**Comment by JackUait** [comment]
> Компонент отвечает исключительно за позиционирование. А при необходимости подобной стилизации уже сейчас можно использовать проп `style`.

Не совсем понимаю, как компонент может отвечать _"исключительно за позиционирование"_, если в него есть возможность передать проп `style` для стилизации компонента? 

И `style` не покрывает сценарии, которые я описал:
1. `shape="circle"` по задумке должен позволить пользователю создавать форму круга (и капсулы) не задумываясь о том, как это сделать т.к. c этим [есть проблемы](https://codesandbox.io/s/dry-rgb-by9l6?file=/index.html) в CSS.
 	В CSS нельзя создать форму капсулы, указав скругление `50%` или `100%`, зато таким образом можно создать форму эллипса, но мне не приходилось видеть потребность в создании эллипса, зато потребность в создании форм круга и капсулы я вижу постоянно. Даже на странице этого issue очень много элементов в форме круга и капсулы с позиционированием по центру (другой вопрос в том, что должна также быть возможность отрендерить корневой элемент контрола `Center` в произвольный тэг, чуть подробнее об этом в самом конце).
	Самый простой способ создания формы капсулы: продублировать значение ширины компонента в `border-radius`. Задумка `shape="circle"` как раз и состоит в том, чтобы избавиться от этого дублирования.
2. `size` также позволяет уменьшить дублирование кода, и как было сказано, просто является сокращением для `width: x; height: x;`.

Изначально, это issue должно было вносить значительные изменения в `API` контрола `Center`, а тип `shape` был таким: `shape?: "square" | "capsule" | "circle"`. Но по ходу раздумий, я понял, что все основные сценарии этого контрола можно покрыть с помощью двух пропов с типами `shape?: "circle"` и `size?: string | number`.
 
> Этот компонент можно "улучшить", если сделать полноценный аналог...

Но речь же идёт не переосмыслении или удалении контрола `Center`, а о создании удобного `API` для покрытия основных сценариев использования контрола.

<hr />

Хочу отметить, что я всё-таки не учёл тот момент, что пользователю нужно позволить также передавать пропы `width` (а также `height`, чтобы иметь консистентное `API`) для того, чтобы проп `shape` мог работать. Иначе этому пропу не откуда будет брать значение ширины. Либо, как вариант, можно задавать свойству `border-radius` нереально большое значение. Второй вариант выглядит как хак, но возможно есть смысл его обсудить.

<hr />

Как я упомянул выше, чтобы добиться от этого контрола (и не только от этого) стопроцентной отдачи, должна быть возможность отрендерить корневой элемент в произвольный HTML-тэг. Это тема для отдельного issue, но я думаю, что задумка понятна: не всегда элемент, который нужно отцентрировать это `div`, бывают случаи, когда нужно изменить именно тег корневого элемента, а не вложенных. Такую возможность предоставляет, например, [чакра](https://chakra-ui.com/docs/layout/box#as-prop) с помощью пропа "as".

**Comment by JackUait** [comment]
> Женя, а есть примеры в других библиотеках подобного применения?

Да, например, у [чакры](https://chakra-ui.com/docs/layout/center) есть компоненты `Center`, `Square` и `Circle`, которые решают эту же задачу, но мне кажется, что подход с созданием отдельных компонентов для таких сценариев хуже, чем просто использование `shape` и `size`.

Также в SwiftUI есть View, которые позволяют создавать формы [круга](https://developer.apple.com/documentation/swiftui/circle), [капсулы](https://developer.apple.com/documentation/swiftui/capsule), [прямоугольника](https://developer.apple.com/documentation/swiftui/rectangle), [прямоугольника со скруглёнными краями](https://developer.apple.com/documentation/swiftui/roundedrectangle) и [эллипса](https://developer.apple.com/documentation/swiftui/ellipse) (все названия форм ведут на разные ссылки), которые используются там для решения в том числе задачи описанной в этом issue.

**Comment by lossir** [comment]
Проп `style` это скорее "абъюз в законе", и он не отменяется концепцию компонента, а лишь даёт доступ к нативному атрибуту, как `className`. Ведь и позиционирование и внешний вид технически настраивается стилями, тут уж ничего не поделать.

Функциональность, которую ты описываешь, безусловно может быть полезна пользователям. С этим я не спорю)
Но нет причин запихивать это в старый компонент. С этим я спорю.

> Но речь же идёт не переосмыслении или удалении контрола Center, а о создании удобного API для покрытия основных сценариев использования контрола.

Основной его сценарий - центрирование. Он это уже делает. Добавление новых возможностей в контрол `Center` вполне можно назвать его переосмыслением. Ведь он начнёт рисовать фигуры. Если посмотреть на пример из Чакры, то даже интерактивные фигуры (там иконки так и просят свой `onClick`). Тогда возникает мысль, почему бы не добавить этот функционал в тот же в `Button`? Он тоже центрирует своё содержимое.

Думаю, что предлагаемый функционал стоит делать в отдельном компоненте, который ещё позволит менять тег обёртки и не использовать `children` при необходимости. А также будет позволять отключать вертикальное центрирование. 
В таком виде новый контрол будет действительно полезен.

**Comment by JackUait** [comment]
Да, теперь и я согласен. Вынесу свои мысли насчёт нового контрола в новое issue.

**Comment by dzekh** [comment]
Ппредлагаю эту таску тоже закрыть и вернуться если будут подобные запросы со стороны пользователей =)

**Comment by dzekh** [comment]
а, сорри, она закрыта же
