### ISSUE TITLE
Новый контрол `Shape`

### ISSUE THREAD

**Issue by JackUait** [skbkontur/retail-ui#2631]
Это issue является логическим продолжением #2616.

## Синопсис
Сейчас в библиотеке есть утилитарный контрол `Center`. Его задача - центрирование вложенных в него элементов. Есть несколько распространенных сценариев в которых он используется: центрирование контента внутри форм круга, прямоугольника (квадрата) и капсулы (и возможно внутри эллипса). Было решено выделить функционал для покрытия этих сценариев в отдельный компонент с возможностью менять корневой элемент.

## Поведение
По умолчанию контент внутри контрола центрируется по горизонтали и вертикали. Сам контрол по умолчанию рендерится как `div` в форме прямоугольника.

## Пропы
`form?: "rectangle" | "ellipse" | "circle"` - создаёт формы прямоугольника, круга и эллипса:
1. `"rectangle"` - значение по умолчанию. Алиас для `border-radius: 0`.
2. `"ellipse"` - алиас для CSS-свойства `border-radius: 50%`. 
3. `"circle"` - делает CSS-свойство `border-radius` равным `width`. 

С помощью `form="circle"` также можно создать форму капсулы, если задать ширину больше высоты.

`width?: string | number` - задаёт CSS-свойство `width`. Используется для корректной работы формы `circle`.
`height?: string | number` - задаёт CSS-свойство `height`. Дополняет проп `width` для создания консистентного `API`.
`size?: string | number` -  алиас для `width: x; height: x;`: `size="40px"` это то же самое, что `width: 40px; height: 40px`.
`as?: keyof HTMLElementTagNameMap` - меняет корневой элемент на один из HTML-тэгов и наследует его события, атрибуты.

## Вопросы
1. @dzekh, как ты думаешь, есть ли практическое применение форме эллипса? Я добавил эллипс как возможную форму, чтобы понять какую цель преследовали разработчики/дизайнеры SwiftUI, возможно, это действительно полезная фигура, смысл которой ускользает от меня. Не могу вспомнить ни одного стоящего сайта/приложения, где использовалась бы форма эллипса. Может у тебя есть референсы?
2. Есть ли смысл позволять пользователям изменять выравнивание контента? Есть примеры сценариев, в которых это может пригодиться?

**Comment by JackUait** [comment]
Вместо пропов `width` и `height` можно попробовать использовать `window.getComputedStyle`.

**Comment by dzekh** [comment]
Кажется надуманный сценарий, нет реальной потребности в нем, предлагаю закрыть эту таску и вернуться если будут запросы со стороны пользователей =)
