### ISSUE TITLE
[RadioGroup] Есть возможность выбрать сразу несколько радио-кнопок в группе

### ISSUE THREAD

**Issue by JackUait** [skbkontur/retail-ui#2641]
Это потенциально ломающее изменение.

**Текущее поведение:**
1. Ситуация №1
Если у чекбокса в группе задано состояние `checked` (будем звать его **первый**), при переключении на другой, не отмеченный чекбокс, отмеченное состояние сохраняется на **первом** чекбоксе.

	https://user-images.githubusercontent.com/48599460/141658498-259951eb-147d-4a49-aca7-3e0a03098192.mov

2. Ситуация №2
Если в группе есть сразу несколько чекбоксов с состоянием `checked` отмеченными будут все из них.
	<img width="181" alt="Снимок экрана 2021-11-14 в 01 45 11" src="https://user-images.githubusercontent.com/48599460/141658588-46c6f191-32c6-430d-92a4-bab476997b28.png">

**Ожидаемое поведение:**
1. Ситуация №1
Состояние `checked` должно спадать при переключении на другой чекбокс, так как в группе **всегда** должна быть выбрана только одна радио-кнопка.

	https://user-images.githubusercontent.com/48599460/141658735-b9112770-4425-446b-9d00-55c97b8b50aa.mov

2. Ситуация №2
Если несколько кнопок в группе находятся в состоянии `checked`, отмеченной должна быть только последняя из кнопок с состоянием `checked`.

	<img width="180" alt="Снимок экрана 2021-11-14 в 01 58 37" src="https://user-images.githubusercontent.com/48599460/141658886-82640dc5-56fe-4354-a95b-078c59ed2a68.png">

**Comment by dzekh** [comment]
Перенес в IF-630
