### ISSUE TITLE
[ComboBoxOld] В IE теряется фокус при выборе значения с клавиатуры 

### ISSUE THREAD

**Issue by uagafonova** [skbkontur/retail-ui#265]
Замечено в IE8-11

Проблема наблюдается следующим образом:

- переходим в ComboBox. Наблюдаем, что разворачивается справочник допустимых значений;
- стрелочками с клавиатуры выбираем нужное значение из списка;
- жмем Enter, выбранное значение сохраняется в поле. Это правильное поведение.
Но при этом **Bug!**: фокус теряется, и переход по Tab-у происходит не в следующее поле, а в начало формы. 

Такое поведение делает неудобным заполнение форм, особенно, если в них много комбобоксов. Приходится все время использовать мышку

Замечу, что  в Chrome, ff, Yandex проблема не наблюдается.

**Comment by wKich** [comment]
Закрываю в виду неактуальности. Решение, переходить на новый `ComboBox`
