### ISSUE TITLE
[RenderLayer] Каждый инстанс подписывает свой обработчик на событие `mousedown`

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#266]
Всё это приводит к тому что любой клик на форме вне зависимости от кол-ва открытых меню в Combobox или показываемых Tooltip'ах, создает очередь из вызовов обработчиков
<img width="837" alt="screen shot 2017-08-01 at 10 42 57" src="https://user-images.githubusercontent.com/6397708/28811664-1c016654-76aa-11e7-93ee-36ebd41e13d7.png">

Варианты решения:
- Делать только один обработчик
- Осуществлять подписку только в момент открытия меню combobox'а или показа Tooltip'а, после скрытия отписываться

**Comment by nanot1m** [comment]
Поправили добавив пропс active в RenderLayer
