### ISSUE TITLE
Modal поверх горизонтального скролла при зуме страницы

### ISSUE THREAD

**Issue by aagordienko** [skbkontur/retail-ui#271]
Браузер любой.
При зуме и горизонтальном скролле, если модал по высоте становится больше высоты окна, футер модала рисуется поверх горизонтального скролла.

![2017-08-08_182631](https://user-images.githubusercontent.com/30799122/29074233-f01c33ac-7c67-11e7-83f0-dd0ba804e7d0.png)

**Comment by step-off** [comment]
#378
