### ISSUE TITLE
[Paging] Скрывать, если pagesCount меньше 2

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#2761]
В гайды пейджинга добавлен [пункт](https://guides.kontur.ru/components/paging/#05): 

**Пейджинг нужен только для двух и более страниц. Если контента только на одну страницу — не показывайте пейджинг.**

Нужно принудительно скрывать пейджинг, если pagesCount < 2

**Comment by JackUait** [comment]
А как именно должен скрываться пейджинг?
1. Пейджинг должен быть невидимым, но при этом занимать место.
2. Пейджинг должен полностью полностью исчезать со страницы.

Во втором варианте меня беспокоит то, что интерфейсы могут поехать (и скорее всего поедут) т.е. это ломающее изменение.

**Comment by dzekh** [comment]
Есть смысл убирать его только целиком и полностью. Зачем ему место занимать. 
Кажется что это не сильно критично, но можно для спокойствия отправить в некст, в 4.0

**Comment by lossir** [comment]
Да, лучше в некст запулить
