### ISSUE TITLE
[PasswordInput] Скрывать глазик у заблокированного поля

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#2764]
Кажется это не правильно, что можно посмотреть пароль, когда PasswordInput заполнен и заблокирован. 
В заблокированном поле глазик должен отключаться. Возможность посмотреть пароль должна быть только в поле, которое было пустым и только что заполнено, а это незаблокированные поля. 
Если поле заблокированно, скорее всего оно уже предзаполнено и раскрывать пароль опасно.

**Comment by lossir** [comment]
@dzekh А если человек что-то ввёл, либо значение уже было. Он нажал на глазик чтоб посмотреть, и после этого поле выключается.
Должен ли пароль скрываться? И если должен, то должен ли после включения опять показаться?

| ![ezgif com-gif-maker (25)](https://user-images.githubusercontent.com/2708211/152927325-ace04a98-0a50-4b72-ba52-683368a9b99a.gif) |
| --- |

**Comment by JackUait** [comment]
@lossir Что-то не могу представить такой сценарий в жизни, можешь привести примеры?

**Comment by lossir** [comment]
Например, асинхронная авторизация. Пользователь решил проверить пароль перед входом, после чего форма блочится на время запроса.

| ![ezgif com-gif-maker (26)](https://user-images.githubusercontent.com/2708211/152960017-5664d310-0a79-4317-a5d7-717490b7c50d.gif) |
| --- |

**Comment by JackUait** [comment]
Мне кажется, что идеальным вариантом было бы принудительно скрывать пароль при потере фокуса с поля. Что думаете, @lossir, @dzekh? 

Так не внимательный пользователь случайно не спалит свой пароль, в кейсе, который описал Максим, а также это будет удобнее, с той стороны, что пользователю обычно не нужно видеть пароль, после того, как он его ввёл и переключился на что-то другое.

**Comment by dzekh** [comment]
Согласен — скрывать пароль у заблокированного поля. Я бы и саму иконку глаза скрывал. Но иконка — не уверен, не принципиально. Ну то есть если заблокировали — скрыли пароль. Если после этого разблокировали — наверное стоит оставить скрытым, так безопасней. Если нужно включит. 

При потере фокуса — может быть есть сценарий когда все-таки нужно его видеть? Но согласен что скрывать было бы безопасней. У кого-то вон вообще нужно жать на иконку чтоб видеть. Как только отпускаешь он снова скрывается. 

Попытался поискать хороших примеров, но не нашел.

**Comment by JackUait** [comment]
> Я бы и саму иконку глаза скрывал.

Да, не похоже, что она нужна. Такая иконка больше походит на визуальный шум, когда инпут не в фокусе.

> При потере фокуса — может быть есть сценарий когда все-таки нужно его видеть?

Честно говоря, не могу представить себе такой сценарий.
Зато есть сценарий повторного ввода пароля, когда мы хотим, чтобы пользователь не видел пароль из первого инпута, если мы будем скрывать пароль при потере фокуса, то улучшим `UX` в этом сценарии.

> У кого-то вон вообще нужно жать на иконку чтоб видеть. Как только отпускаешь он снова скрывается.

Это моя персональная боль в мире инпутов для паролей. Постоянно по несколько секунд туплю, на таких инпутах. Плюс, иногда мне нужно скопировать пароль из инпута, а инпуты с таким поведением не позволяют это сделать. 

Меня в `PasswordInput` напрягают ещё две вещи относительно "глаза":
1. "Глаз" недоступен с клавиатуры (это вынесу в отдельную задачу, в которой буду копить все проблемы с доступностью компонентов библиотеки).
2. На "глаз" можно нажать только в рамках зелёной области. В красной области ничего не происходит, но при этом в ней нельзя нажать на "глаз". Синяя область - область инпута.
	<img width="231" alt="Снимок экрана 2022-02-08 в 15 41 18" src="https://user-images.githubusercontent.com/48599460/152989662-b2988d6d-ec2e-458d-b11f-aa7125517984.png">

@dzekh Можешь суммировать, что из описанного выше будем брать в работу?

**Comment by JackUait** [comment]
Нашёл упоминание проблемы с кликабельной областью в #1339.

**Comment by dzekh** [comment]
Давайте сделаем так:
Если поле дизейблится, то оно скрывает символы пароля, и скрывает глазик тоже. Поле переходит в режим скрытых символов и при последующем разблокировании символы скрыты — заменены точками. 
Иконка глаза видна всегда, когда поле не заблокировано. На заблокированном она исчезает. 
Потеря фокуса полем принудительно переводит его в режим где символы скрыты. Соответственно меняется иконка. 

Проблему с кликабельной областью кажется что нужно как-то отдельно и системно решать.
