### ISSUE TITLE
[DateInput] Возможен ввод некорректных дат с клавиатуры

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#2839]
Из [чата](https://kontur.slack.com/archives/C013HTCE18Q/p1647933042448549).

Как стрелками вверх/вниз так и простым вводом можно занести некорректные даты: 31.02.2022, 39.01.02, 00.00.0000.

**Comment by Lelchik** [comment]
Не понятно что должно произойти если пользователь сначала ввел дату 31.03, а потом пытается стрелками изменить месяц. Вариантов несколько:
1. Меняем месяц на ближайщий возможный: январь или май. Но на мой взгляд странное поведение для пользователя.
2. Меняем и дату на последний день в месяце. Допустим для февраля ставим 28.02, а для апреля 30.04. Но опять же странное поведение для пользователя, особенно если он хотел вместо 31.03 получить 31.01.
3. Ставим следующий месяц, но тогда проблема не решается и мы даем пользователю выбрать некорректную дату. Возможно в этом случае стоит как-то давать пользователю знать про некорректную дату.

**Comment by zhzz** [comment]
Возможно стоит повторить поведение [нативного инпута](https://codesandbox.io/s/lingering-river-zwmc9p?file=/src/App.js)? Он дает ввести день в пределах [1; 31] для любого месяца, но сбрасывается, если дата стала невалидной. 

Призову @dzekh.
