### ISSUE TITLE
Нет доступа к странице MOBILES.MD 

### ISSUE THREAD

**Issue by modecry** [skbkontur/retail-ui#2854]
"С версии 4.0 многие компоненты умеют адаптироваться под мобильные устройства. Подробнее об управлении этим поведением в [MOBILES.md](https://github.com/skbkontur/retail-ui/packages/react-ui/MOBILES.md)."

Не рабочая ссылка [MOBILES.md](https://github.com/skbkontur/retail-ui/packages/react-ui/MOBILES.md) в документации, на[ странице](https://tech.skbkontur.ru/react-ui/#%D0%BA%D0%B0%D0%BA-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C)

**Comment by zhzz** [comment]
Спасибо, поправим.
