### ISSUE TITLE
[TooltipMenu] Про дочерние элементы

### ISSUE THREAD

**Issue by NataliaR7** [skbkontur/retail-ui#2862]
- @skbkontur/react-ui последняя версия;
Проблема: Если дочерние элементы (MenuItem) являются не прямыми потомками TooltipMenu (обернуты в div например), то ломаются стили ховера и выпадашка не закрывается при нажатии на элемент. Иногда есть потребность кастомизировать выпадающее меню, например обернуть элементы в лоадер

Еще было бы круто добавить к TooltipMenu методы onClose и onOpen, как другим видам меню)

**Comment by JackUait** [comment]
Привет! Уже занимаемся фиксом этой проблемы в #2749.

**Comment by JackUait** [comment]
По поводу методов `onClose`/`onOpen` создал ишью на ютреке, постараемся в ближайшее время им заняться.
