### ISSUE TITLE
[Input]: Выкидывается исключение в инпуте с маской, если value={null} 

### ISSUE THREAD

**Issue by slogger** [skbkontur/retail-ui#2901]
@skbkontur/react-ui 4.1.0

Выкидывается исключение  `TypeError: null is not an object (evaluating 'o.toString')`

```
<Input mask="9" value={null} />;
```

**Comment by JackUait** [comment]
Привет! Спасибо за ишью)

У нас компонент `Input`, как и реактовский инпут официально не может принимать `null`, как значение. Только `undefined`. Обоснование этого поведения есть в реактовском [треде](https://github.com/facebook/react/issues/11417)

Краткий пересказ треда:
`React`'у не нравится когда ты передаёшь ему `null`, для того, чтобы сделать инпут неконтролируемым и `React` выкидывает ворнинг. При этом `React` одинаково относится к `null` и `undefined` (т.е. делает инпут неконтролируемым), так как между этими значениями нет очевидной разницы (со [слов](https://github.com/facebook/react/issues/11417#issuecomment-413240002) Дэна Абрамова и я в принципе с ним согласен)

Так что мы не будем добавлять официальную поддержку `null` для пропа `value`, но баг пофиксил в #2902, там же можно чуть подробнее почитать про то, почему добавление поддержки `null` для `value` в `Input` - это плохая идея
