### ISSUE TITLE
[Button] Отступ иконки пропадает с box-sizing: border-box;

### ISSUE THREAD

**Issue by Eazymov** [skbkontur/retail-ui#2927]
@skbkontur/react-ui@4.1.1
Chrome@103.0.5060.53
Ubuntu@22.04

Нормальное отображение:
![image](https://user-images.githubusercontent.com/26853518/175905113-e41224f6-c908-48f2-a8f2-8db9c6e56fa5.png)

С `* { box-sizing: border-box; }`:
![image](https://user-images.githubusercontent.com/26853518/175905204-b3923c46-2714-4ab4-a7e3-67689918afb9.png)

**Comment by JackUait** [comment]
Привет! Спасибо за ишью. Взяли в работу

**Comment by zhzz** [comment]
Выкачено в @skbkontur/react-ui@4.2.0
