### ISSUE TITLE
[Tooltip] Вызывается onCloseClick при клике на содержимом.

### ISSUE THREAD

**Issue by sorovlad** [skbkontur/retail-ui#295]
Если поставить на странице два тултипа с trigger="click" и onCloseClick, то функции onCloseClick начинают вызываться, при при клике на содержимом тултипа.

**Comment by nanot1m** [comment]
Fixed in https://github.com/skbkontur/retail-ui/commit/a477c7581a20f38780104c09f632b0cebad30fe8
