### ISSUE TITLE
[Tabs] ie8 wrong position of highlight

### ISSUE THREAD

**Issue by Elsee** [skbkontur/retail-ui#296]
При загрузке страницы с табами (Tabs component) в IE8 неверно позиционируется подсветка активного элемента. Версия retail-ui 0.8.6.
![ie8tabs4](https://user-images.githubusercontent.com/7502553/29910747-c30f73be-8e33-11e7-9366-c4018349139b.gif)

**Comment by nanot1m** [comment]
не поддерживаем ie8
