### ISSUE TITLE
[RadioGroup] null не распознаётся как одно из возможных значений

### ISSUE THREAD

**Issue by Eazymov** [skbkontur/retail-ui#2989]
@skbkontur/react-ui@4.5.0
Chrome@103.0.5060.53
Ubuntu@22.04

`null` не распознаётся как выбранное значение, даже если в children есть `<Radio />` с подходящим `value`.
[Codesandbox](https://codesandbox.io/s/bold-jang-p9ez7z?file=/src/App.js).

**Comment by JackUait** [comment]
Привет! А можешь описать кейс в котором нужно такое поведение?

Могу сказать, что `undefined` и `NaN` также не распознаются как выбранное значение. Это не баг и не фича, просто так работает

**Comment by Eazymov** [comment]
Привет. У меня значения радиогруппы - какое-то перечисление + "По умолчанию", то есть `null`, которое тоже является одним из Radio-переключателей.
![image](https://user-images.githubusercontent.com/26853518/186857555-bc0acb66-9a69-41c2-9d9b-b38fa429bfad.png)

Конечно, это не сложно обойти, но вроде нет причины игнорировать `null`, если есть Radio с соответствующим значением. Да и это, наверное, любого значения касается.

**Comment by JackUait** [comment]
Сейчас `null` и `undefined` являются значениями через которые [проверяется](https://github.com/skbkontur/retail-ui/blob/f9f000b0fbc2755771ea7137a3170e0e45a88451/packages/react-ui/components/RadioGroup/RadioGroup.tsx#L215), является ли компонент контролируемым или нет (в прошлом сообщении я ошибся, это всё-таки фича)

С `NaN` же логика не работает, потому что `NaN === NaN => false`
