### ISSUE TITLE
[ComboBox] autoFocus

### ISSUE THREAD

**Issue by Frumcheg** [skbkontur/retail-ui#3]
При передаче в ComboBox `autoFocus={true}`, он должен себя вести так же, как и при получении фокуса.<details><summary>Демонстрация: </summary>
![right](https://cloud.githubusercontent.com/assets/2862206/19557163/f8c3d818-96dd-11e6-8c1f-573fd7a844d9.gif)
</details>

Сейчас при `autoFocus={true}` он ведет себя не совсем корректно.
Появляется фокус, но не ставится курсор, не запускается поиск, не показываются результаты.

<details><summary>Демонстрация: </summary>
![wrong](https://cloud.githubusercontent.com/assets/2862206/19557193/14c418ca-96de-11e6-9fdf-a8d6b028c208.gif)
</details>

**Comment by nanot1m** [comment]
Поправлено в [406de16](https://github.com/skbkontur/retail-ui/commit/406de1642183847986c823d4f566592315490b66)

**Comment by nanot1m** [comment]
Поправлено в 406de16
