### ISSUE TITLE
[Paging]: не работает disabled IF-806

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#3018]
Привет!
Попробовал выставить disabled для Paging, но он не работает. Проверял на [витрине](https://tech.skbkontur.ru/react-ui/4.5.3/#/Components/Paging).

**Comment by JackUait** [comment]
Привет!
После небольшого рисёрча оказалось, что сейчас проп `disabled` отключает только фокус на компоненте
Обсудили с командой это поведение, решили что сейчас проп работает неправильно и по-хорошему должен отключать любое взаимодействие с компонентом, взяли задачу в работу
