### ISSUE TITLE
[Switcher] Поддержка items на ReactElement

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#3022]
Сейчас Switcher поддерживает только строковый тип: items | SwitcherItems[] | Required | Список строк или список элементов типа { label: string, value: string }. Однако хорошо работает если туда передать реактовый элемент, но ругается на тип

Пробовал на витрине:
```
const [value, setValue] = React.useState();

<Switcher
  caption="Switch the switcher"
  items={[{ label: <div style={{ background: "#ccc" }}>On1e</div>, value: "авыа"}, { label: 'Two', value: "fdsf"}, {label: 'Three', value: "sdfsd"}]}
  value={value}
  onValueChange={setValue}
/>;
```

Есть потребность в расширении типов. Например, чтобы сделать такое:
![image](https://user-images.githubusercontent.com/9654622/198188660-57d31531-134f-469f-ae1f-87869e842eb7.png)

**Comment by JackUait** [comment]
Привет! Подскажи, это предложение или у вас в проекте есть кейс, где такое поведение может пригодиться?

**Comment by nextgennexia** [comment]
Да, у нас в проекте, еще не в реактовом исполнении есть такой компонент как на скрине. На [сайте](https://normativ.kontur.ru/?AreaId=2001&Query=%D0%BE%D0%BA%D0%BE%D1%84&SearchSource=1&SearchQuerySource=2&From=Search&searching=true&SortBy=1)

**Comment by nextgennexia** [comment]
В планах перевод этой страницы на реакт

**Comment by JackUait** [comment]
Сейчас в разработке находится проп `renderItem` для `Switcher` (#3021). Он позволит реализовать описываемое тобой поведение менее костыльным способом. Думаю, что правильнее будет дождаться его, чем расширять тип в пропе `items`

**Comment by nextgennexia** [comment]
Хорошо, спасибо
