### ISSUE TITLE
[ComboBoxOld] Неправильно работает сброс значений

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#303]
На onBlur не происходит очистка введенного значения, если таковое отсутствует в справочнике. Если функция recover возвращает null в случае отсутствия значения, то инпут сохраняет введение значение и подсвечивается ошибка. Если recover возвращает пустой объект, при onBlur значение очищается, но если кликнуть снова в инпут, то ранее введеное значение появляется.

```jsx
class Comp extends React.Component {
  constructor() { this.state = { value: '' } }

  render() {
    return (
      <ComboBoxOld
        source={() => Promise.resolve({ values: [], infos: [] })}
        value={this.state.value}
        recover={() => ({})}
        renderValue={value => <span>{value}</span>}
        renderItem={value => <span>{value}</span>}
        valueToString={id => id}
        onChange={e => this.setState({ value: e.target.value })}
      />
    );
  }
};

ReactDOM.render(<Comp />, mountNode);
```

**Comment by nanot1m** [comment]
Актуальна ли проблема?

**Comment by wKich** [comment]
Само собой

**Comment by 21alexander21** [comment]
Нужно уточнить сценарии...

**Comment by wKich** [comment]
@nanot1m, дождался. Закрываю в виду неактуальности.
