### ISSUE TITLE
[Loader] in Modal.Body

### ISSUE THREAD

**Issue by slawwan** [skbkontur/retail-ui#304]
Loader внутри Modal.Body в Chrome 61 64bit выглядит как на картинке, кажется это связано с фоном лайтбокса, в Chrome 60 подобного не наблюдалось
Spinner рисуется нормально, поэтому вероятно это как-то связано с z-index, а с z-index есть еще один связанный баг #302

![image](https://user-images.githubusercontent.com/5162965/30432701-e1faea76-997b-11e7-8798-d54bd19f20d4.png)

![image](https://user-images.githubusercontent.com/5162965/30432812-27c69d98-997c-11e7-816e-b0839adac6cb.png)

**Comment by 21alexander21** [comment]
еще актуально?
