### ISSUE TITLE
[MenuItem] У button не указан type="button"

### ISSUE THREAD

**Issue by Eazymov** [skbkontur/retail-ui#3042]
@skbkontur/react-ui@4.7.0
Chrome@107.0.5304.87
Ubuntu@22.04

1. По умолчанию компонент MenuItem рендерит button, но у этой button не указан тип, а тип по умолчанию - submit. То есть клики по MenuItem сабмитят форму, если находятся внутри неё.
2. В MenuItem де-факто можно передать type, но в MenuItemProps нет такого пропа, получается ошибка от typescript.

**Comment by JackUait** [comment]
Привет!

1. Изменить тип по умолчанию просто так мы не можем - это будет ломающим изменением. Пользователи вполне вероятно могли завязаться на поведении `type="submit"` и это поломает их код
2. Сейчас атрибут `type` (и любой другой нативный атрибут) можно передать через проп `component`:
	```tsx
	<MenuItem component={(props) => <button {...props} type="button" />}>Меню айтем</MenuItem>
	```
