### ISSUE TITLE
[react-ui-testing] Контрол Toast не поддерживается в новых версиях react-ui

### ISSUE THREAD

**Issue by SephVin** [skbkontur/retail-ui#3050]
В какой-то версии react-ui были дополнены/переименованы data-tid'ы к контролам. Это коснулось и тоста. Раньше у него был data-tid="ToastView", в новых версиях реакта data-tid стал "ToastView__root". 

Проблема заключается в том, что SeleniumTesting ищет тост по data-tid="ToastView". Хочется, чтобы появилась возможность работать с тостом и в новых версиях реакта. У нас в команде **react-ui 4.2.2**

![image](https://user-images.githubusercontent.com/29632837/203603238-d3aee75c-24df-48bc-96bf-e02533bdb21d.png)

**Comment by JackUait** [comment]
Привет! У `Toast`'а всегда был `data-tid="ToastView__root"`. Этот `data-tid` был добавлен в #1846 (ищи файл `ToastView`) и с тех пор не менялся

Правда в [@skbkontur/react-ui@4.2.0](https://kontur.slack.com/archives/C02K3H7K5M2/p1657631058863619) мы стали экспортировать все `data-tid`'ы наружу, что вызвало [проблемы](https://yt.skbkontur.ru/agiles/101-1467/current?issue=IF-612) у команды Эврики, с которыми до конца так и не получилось разобраться

Предлагаю поставить более раннюю версию контролов, например, `@skbkontur/react-ui@4.1.2` и проверить воспроизводится ли там этот баг

**Comment by zhzz** [comment]
Привет. 

SeleniumTesting ищет тост не по `data-tid`, а по `data-comp-name`. И в этом плане действительно ничего не менялось. На первый взгляд с библиотекой контролов все в порядке.

Возможно дело в `react-selenium-testing.js` или `@skbkontur/react-props2attrs`, которые добавляют в html эти атрибуты. У нас `@skbkontur/react-props2attrs@0.1.2` и тесты на Тост работают. У вас в проекте что из этого используется?

**Comment by SephVin** [comment]
> SeleniumTesting ищет тост не по data-tid, а по data-comp-name
Да, в этом проблема. В портальной странице регистрации на облаке не прокидывается `data-comp-name`, поэтому и не находился тост. У нас в проекты мы используем `react-selenium-testing.js`, но тут конкретно тестировали регистрацию пользователя + перевод в сервис через страницу другого сервиса.

Проблемы похоже нет, поэтому можно закрыть таску.
