### ISSUE TITLE
[Input/FxInput/...] Добавить props позволяющий программно подсвечивать инпут

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#306]
Необходимо при наведении на инпут иметь возможность подсветить зависимые инпуты, выглядеть должно примерно так:
![screen shot 2017-09-18 at 12 41 32](https://user-images.githubusercontent.com/6397708/30532692-1a40c86a-9c6f-11e7-859f-e5be9ce275ed.png)

Сейчас единственный способ это сделать выглядит очень плохо
<img width="508" alt="screen shot 2017-09-18 at 12 41 52" src="https://user-images.githubusercontent.com/6397708/30532781-7a52355e-9c6f-11e7-9059-b7c26391a4a8.png">

**Comment by nanot1m** [comment]
А нельзя ли сделать вспомогательный компонент для подсветки?
```js
<Highlight active>
  <Input />
</Highlight>
```

**Comment by wKich** [comment]
Это не избавит тебя от необходимости добавлять в Input метод или props для управления подсветкой

**Comment by nanot1m** [comment]
В моем примере компонент Highlight сам рисует подсветку.
Мне не нравится идея подсвечивать компонент, предложенным тобой способом. Только да нам в каждом компоненте придётся делать такой параметр.
Думаю нужно поговорить с дизайнерами и найти более общее решение для подсветки.

**Comment by wKich** [comment]
Поговори с Вовой Дзехом. Он делал прототип для формы 4-ФСС в которой такая подсветка используется

**Comment by dzekh** [comment]
@wKich @nanot1m Вы говорили с Вовой Кутовым? Что решили по этой задачке?

**Comment by nanot1m** [comment]
Насколько актуальна эта задача?

**Comment by wKich** [comment]
На много

**Comment by wKich** [comment]
После PR #530 у нас перестал работать хак со стилями, который мы используем для подсветки инпутов. Мы конечно исправили другим хаком, но всё же хочется иметь нормальный способ программно подсвечивать Input

**Comment by dzekh** [comment]
Давайте уже что-то придумаем? =) 
Что от дизайнеров нужно? 
Может соберемся обсудить?
Дима, зови на встречу меня, Тимура и Сашу.
Вову Кутового, или кого-то из Экстерна, кто в теме.

**Comment by wKich** [comment]
Хорошо. Я думаю на следующей неделе можно, там Света из отпуска вернется

**Comment by wKich** [comment]
@dzekh Давай зафиксируем текущий статус по задаче

**Comment by dzekh** [comment]
Инициировал [обсуждение в Стаффе](https://staff.skbkontur.ru/group/5361?action=discussions&id=f1ce9fd238f346658bcc1af8e3f82bc1). По результатам можно будет принять решение, и начать добавлять во все контролы метод. 

Но нужно будет иметь ввиду и научится отличать два Highlighted. Второй — когда залит весь контрол насыщенным синим и белый инверсный текст контрола. Он пока не реализован, но запросы есть.

**Comment by dzekh** [comment]
Однозначно нужен какой-то способ чтоб подсветить поле извне. Пока дизайнеры договариваются о том, каким цветом подсвечивать поле, можно подумать над механизмом — как это сделать

**Comment by wKich** [comment]
Предложение @nanot1m кажется вполне логичным. Такой компонент можно переиспользовать и на первый взгляд он выглядит достаточно универсальным. Его можно будет использовать для подсветки не только `Input`, но и других компонентов, в том числе и целых групп.

**Comment by dzekh** [comment]
Решили, что пока не будем делать это в рамках библиотеки. Пока закрываем, когда дизайнеры договорятся как это делать правильно, решим как и где это реализовать. Возможно это компонент для парковки велосипедов. Если считаете, что мы не правы комментируйте.
