### ISSUE TITLE
[react-ui] Добавление атрибута aria-describedby IF-954

### ISSUE THREAD

**Issue by MarinaAnisi** [skbkontur/retail-ui#3093]
### Проблема:
У компонентов нет aria-describedby атрибутов, для добавления ссылок на доступное описание компонента (например, если есть тултип или подпись к полю), при добавлении пропса для данного значения разработчики могут самостоятельно связывать элементы и их описание

### Решение:
Необходимо добавить для компонентов, которые могут нуждаться в доп. описании, атрибут aria-desribedby
При этом, нужно прокинуть этот атрибут на те элементы DOM дерева, которые являются основными при чтении страницы с помощью скринридера, например, input, button, при этом, нет смысла прокидывать атрибут на div-ы - обертки или корневой элемент компонента.

**Comment by asukhar** [comment]
[Задача](https://yt.skbkontur.ru/issue/IF-954)
