### ISSUE TITLE
[RadioGroup] Повышение доступности компонента IF-955

### ISSUE THREAD

**Issue by daks01** [skbkontur/retail-ui#3095]
**Аудит доступности:**

| **Проблемы**                                  | **Как исправить**                                              |
| --------------------------------------- | --------------------------------------------------- |
| Радио группа скринридером воспринимается как таблица (из-за `display: table`) | Задать родительскому элементу `role="radiogroup"`, убрать `display: table` |
| Заголовок не связан с радиокнопками | Установить связь между radiogroup и заголовком с помощью aria-labelledby (#3093) |

**Документация, советы:**
ARIA Authoring Practices Guide - https://www.w3.org/WAI/ARIA/apg/patterns/radiobutton/

**Примеры реализаций:**
ARIA Authoring Practices Guide - https://www.w3.org/WAI/ARIA/apg/example-index/radio/radio.html

**Comment by asukhar** [comment]
[Задача](https://yt.skbkontur.ru/issue/IF-955)
