### ISSUE TITLE
[Kladr] Не работают запросы в ИЕ8 на страницах KEWeb'а

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#310]
Реализовать поддержку эвента onreadystatechage для корректной работы запросов на страницах KEWeb'а

Комментарий от Жени Дегтярева
> У вас библиотека некорректно делает http запросы.На наших страницах специальный скрипт обнуляет XDomainRequest чтобы им никто не пользовался. Вместо него правильнее использовать обычный XmlHttpRequest.Ваша библиотека пытается ловить вот такие эвенты:o.onerror = t, o.ontimeout = t, o.onload = function () {А XmlHttpRequest в IE8 проще и знает только эвент onreadystatechage.Прокачайте свою либу, чтобы она поддерживала IE8.

**Comment by nanot1m** [comment]
Вроде как проблема не актуальна?

**Comment by wKich** [comment]
Думаю что можно закрывать
