### ISSUE TITLE
[Paging] Переход с клавиатуры не работает без фокуса на компоненте

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#321]
— Chrome, Win 10;
  — версия retail-ui: 0.9.5
Воспроизводится на http://tech.skbkontur.ru/react-ui/#/components/Paging

**Comment by nanot1m** [comment]
Оно и не должно работать без фокуса

**Comment by nanot1m** [comment]
Если нужно чтобы работало без фокуса, то нужно обработать такую ситуацию самому. На одной страничке может быть несколько пейджингов

**Comment by molokovev** [comment]
Открыл гайды, там не совсем понятно описано: https://guides.kontur.ru/components/paging/#16
Неясно, что значит "всегда можно переключаться".

Да, кажется, что это поломает сценарий с несколькими пейджингами, но такое реально бывает?

**Comment by dzekh** [comment]
Не важно какой элемент в фокусе, переход по страницам с клавиатуры должен работать всегда. Переход осуществляется сразу после нажатия указанного сочетания клавиш.

Если на странице вдруг несколько блоков с постраничной навигацией можно завязаться на видимость блока — листается тот, который сейчас видно. Если точнее, тот, центр которого по вертикали ближе всего к центру окна браузера. 

Видяшки же мы можем запускать только когда они в центре окна браузера появляются.

**Comment by molokovev** [comment]
Bump!

**Comment by 21alexander21** [comment]
Кажется, если на странице уже слушается нажатие соответствующего сочетания клавиш, то будет не очень хорошо. Кажется что такие глобальные вещи проект должен делать самостоятельно. Или я не прав?

**Comment by molokovev** [comment]
У меня мысли на эту тему такие:
1. Текущая ситуация, когда переход с клавиатуры работает только с фокусом на контроле, весьма нелепая — это неочевидно и неудобно.
2. Ситуация, когда в сервисе уже обрабатывается такое же сочетание клавиш, выглядит весьма редкой. Кажется, проще конкретному сервису её обработать самостоятельно.
3. Ситуация, когда на странице несколько контролов пейджинга, мне тоже кажется странной и редкой. И её так же проще обработать конкретному сервису. Например, на такой странице отключить навигацию с клавиатуры у всех — пользователю вряд ли будет с ходу понятно, что переключается тот, который, например, ближе к центру экрана. Это гораздо проще, чем добавлять глобальные обработчики на каждой странице, где есть пейджинг, как сейчас.

**Comment by molokovev** [comment]
И ещё, наверное, лучше это поведение сделать опциональным, чтобы не сломать существующее и позволить это в будущем разруливать

**Comment by dzekh** [comment]
Согласен с Женей, 
1 - точно да, нелепо. 
2 и 3, вполне логично. Сам по себе пейджинг на странице — не круто, а несколько пейджингов вообще адок. Хотя в формах такое есть,  но они, насколько я знаю свой пейджиг используют.

@21alexander21, мы можем добавить какой-то пропс по которому будем включать компоненту управление с клавиатуры не только по фокусу? 
Заодно нужно научиться отключать подпись ←Alt→ в тот момент когда управление с клавиатуры не возможно. Это если мы оставим управление с клавиатуры по фокусу, то не в фокусе такой подписи не должно быть.

**Comment by 21alexander21** [comment]
можно так сделать

**Comment by wKich** [comment]
Я правильно понял, что управление Paging'ом должно включаться когда он появляется в области видимости и если их больше одного, то управление включено у того, который ближе к центру экрана?

**Comment by dzekh** [comment]
> Я правильно понял, что управление Paging'ом должно включаться когда он появляется в области видимости и если их больше одного, то управление включено у того, который ближе к центру экрана? Можно наверно эту особенность отдельной задачей оформить

выборочное включение пэйджинга команды могут сами реализовать, отслеживая видимость пейджинга и передавая компоненту пропс. Предлагаю нам не делать это, но рассказать где-то как сделать и рекомендовать не располагать на странице больше одного пейджинга.
