### ISSUE TITLE
[Tooltip] Closing cross size & position

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#33]
![retail-ui-version](https://cloud.githubusercontent.com/assets/9248122/20745813/d04c85fa-b704-11e6-8b80-348920c52d65.jpg)
![guides-version](https://cloud.githubusercontent.com/assets/9248122/20745819/d6acbbd6-b704-11e6-9e5f-0973551c7b42.jpg)

**Comment by nanot1m** [comment]
Fixed in #56 and #40
