### ISSUE TITLE
import * as React from 'react'

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#331]
При переходе на React 15 в консоли появляются предупреждения о запрете использования React.PropTypes и createClass.
Посел замены `import * as React from 'react'` на `import React from 'react'` всё чинится :)

**Comment by nanot1m** [comment]
Быстрые решения:
1. Обновиться до react@16
2. delete React.createClass; delete React.PropTypes

Долгое решение:
Изменить импорти flow-типов во всех компонентах

**Comment by nanot1m** [comment]
Актуальна ли эта проблема?

**Comment by molokovev** [comment]
Актуальна, но, думаю, скоро обновим React до 16-й версии и заживём!
