### ISSUE TITLE
[Loader] Лоадер не по центру

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#333]
Сейчас лоадер позиционируется по центру контейнера, который обновляется. 
Должен быть по центру **видимой области** контейнера, а не по центру всего контейнера. Часто контейнер больше в экрана в два раза, и лоадер появляется ниже границы — его просто не видно. 

Лоадер должен быть в центре видимой области **и по вертикали и по горизонтали**, так как бывают страницы с горизонтальным скроллом. При скролле он должен оставаться по центру — залипать. 

Если контейнер во время скролла уходит из видимой области — лоадер должен тоже уходить, но не прилипая к границе контейнера, а **с отступом 30px**.

**Comment by sashasushko** [comment]
+1 за такую штуку.

**Comment by nanot1m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Позиционирование лоадера](https://trello.com/c/bfImi0FD/7-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BB%D0%BE%D0%B0%D0%B4%D0%B5%D1%80%D0%B0)

**Comment by slawwan** [comment]
#260
