### ISSUE TITLE
[Checkbox] Проблема отображения на маленьких экранах

### ISSUE THREAD

**Issue by nextgennexia** [skbkontur/retail-ui#3333]
Есть ситуации, когда рядом с чекбоксом хотим вставить тултип с иконкой, чтобы было так:
![image](https://github.com/skbkontur/retail-ui/assets/9654622/682a691c-2689-4104-baff-3c23f3b014bf)
Но на маленьких экранах это выглядит так:
![image](https://github.com/skbkontur/retail-ui/assets/9654622/019403d1-2da5-42f4-bf13-a863db06886a)

**Comment by zhzz** [comment]
Вероятно, сверстано так. Нужно смотреть ваш код. 

Накидал пример как можно сделать:

![image](https://github.com/skbkontur/retail-ui/assets/4607770/9e0c75e3-b3cb-4853-809e-aefd6aab22e8)

**Comment by zhzz** [comment]
Пока закрою
