### ISSUE TITLE
[Sticky] В IE11 при side === 'bottom' происходит зависание при прокрутке вниз

### ISSUE THREAD

**Issue by knevostruev** [skbkontur/retail-ui#343]
При прокрутке в самый низ Sticky начинает прыгать между состояниями fixed.
Значения тройки (wrapRect.bottom, windowHeight, this.props.offset):
(741.260009765625, 741, 0)
(740.75, 741, 0)

**Comment by molokovev** [comment]
Почему-то при изменении `fixed` между `true` и `false` меняется высота содержимого, порой на два-три пикселя.
У нас в `Sticky` обёрнут блок с `display: flex; width: auto`, всякими паддингами и сложным контентом. Пытаюсь понять, где проблема.

**Comment by 21alexander21** [comment]
#67

**Comment by wKich** [comment]
Можно попробовать лечить передавая в `Sticky` функцию, которая первым аргументом будет принимать флаг `fixed` и на основании него навешивать стиль, который будет применять нужный отступ

**Comment by wKich** [comment]
Закрываем
