### ISSUE TITLE
[Tooltip] onCloseClick вызывается всегда

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#345]
У нас есть такой сценарий: хотим закрывать тултип только кликом по крестику. 
Выставили `trigger="opened"` и в `onCloseClick` меняем `trigger` на `"closed"`. 
Но `onCloseClick` (внутри `_handleBoxClose`) вызывается всегда, даже на `onClickOutside` и `onFocusOutside`

**Comment by molokovev** [comment]
Ап!

**Comment by nanot1m** [comment]
Не знаю как безопаснее всего починить данный баг

**Comment by 21alexander21** [comment]
починено
