### ISSUE TITLE
Roadmap или Todo?

### ISSUE THREAD

**Issue by denvist** [skbkontur/retail-ui#373]
День добрый! Подскажите, есть ли где-то roadmap или todo, чтобы отслеживать что и когда будет (планируется) реализовано? Например, тот же [Подвал](https://guides.kontur.ru/components/footer/) или [Сайдпейдж](https://guides.kontur.ru/components/sidepage/)? Сейчас слежу за [Гайдами](https://guides.kontur.ru/) и исходниками, представленными в этом репозитории.

**Comment by nanot1m** [comment]
Привет!
Это довольно сильное упущение, что у нас до сих пор нет никакого Roadmap
В скором времени займемся им
