### ISSUE TITLE
Перевести тесты с jest на mocha и начать запускать в разных браузерах

### ISSUE THREAD

**Issue by vkochev** [skbkontur/retail-ui#39]
Travis CI позволяет интегрироваться с Sauce Labs и BrowserStack.
https://docs.travis-ci.com/user/browserstack/
https://docs.travis-ci.com/user/gui-and-headless-browsers/
Нужно научиться запускать текущие тесты в разных браузерах.

**Comment by nanot1m** [comment]
Решили ограничиться скриншотными тестами в браузере
