### ISSUE TITLE
Добавить компонент для работы с ФИАС

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#391]

**Comment by denvist** [comment]
http://tech.skbkontur.ru/react-ui/#!/Kladr не?

**Comment by nanot1m** [comment]
@denvist он не работает с ФИАС

**Comment by 21alexander21** [comment]
Добавим компонент, но без api. Какой-нибудь api-провайдер будет приниматься  в пропсы.
Примерная дата: ноябрь 2018

**Comment by wKich** [comment]
#779
