### ISSUE TITLE
[Tooltip] Tooltip самопроизвольно закрывается в IE11

### ISSUE THREAD

**Issue by kbondarenko** [skbkontur/retail-ui#401]
Браузер IE 11, версия retial-ui: 0.11.0. Сценарий такой: 
1. помещаем в тултип чекбокс;
2. кликаем на чекбокс, 
3. кликаем в любое свободное место на тултипе;
4. тултип самопроизвольно закрывается.

![ezgif-4-1fc3a87510](https://user-images.githubusercontent.com/7222450/35551491-2e37f590-05b1-11e8-927d-19f7cef319dc.gif)

Причина кроется в том, что на третьем шаге срабатывает фокус на body. Body находится вне тутлипа, поэтому компонент "думает", что фокус с него ушел и пора закрываться. Как вариант решения, можно навесить на контент тултипа атрибут tabIndex равным,например, 0.

**Comment by 21alexander21** [comment]
Пофикшено
