### ISSUE TITLE
[Button] use="link" всегда переопределяет стиль текста

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#417]
В некоторых случаях требуется вывести какой-то текст, содержащий в себе кнопку, при клике на которую должно происходить какое-то действие, но при этом требуется, чтобы кнопка имела вид ссылки. При этом стиль текста может отличаться от стилей используемых по умолчанию для текста внутри кнопки. В результате получается, что кнопка начинает визуально выделятся относительно остального текста не только по цвету но и по размеру. Использование компонента `<Link />` в данной ситуации противоречит семантике, так как такая "ссылка" никуда не ведет, потому что никакого перехода при клике не происходит.

**Comment by nanot1m** [comment]
Fixed in 99201b36b1d2b8bad7e51c83cb7b703c0e849ab0
