### ISSUE TITLE
[Autocomplete] Неправильная работа пропса onBlur

### ISSUE THREAD

**Issue by ando771** [skbkontur/retail-ui#420]
Windows 10, браузеры Firefox 58.0b16, Chrome 63.0, скорее всего во всех остальных та же проблема.
retail-ui@0.12.2
Сценарий: добавить пропс onBlur для Autocomplete, покликать по странице, при этом по какой-то причине вызывается onBlur на каждом клике.
Я посмотрел на код Autocomplete, кажется проблема в RenderLayer, который используется в компоненте.
```jsx
<RenderLayer
  onFocusOutside={this._handleBlur}
  onClickOutside={this._handleBlur}
>
```
Обработка blur выполняется на каждом клике по области. Как решение, я бы убрал отсюда RenderLayer вообще, а метод this._handleBlur прокидывал непосредственно в Input. Могу сделать соответствующий pull request. Но, возможно, в этом компоненте RenderLayer использовался еще и для других целей, поэтому нужен совет, можно ли его так просто выкинуть или нет.

**Comment by ando771** [comment]
Есть гифка, но по ней, наверное, не очень понятно, что происходит.
![gif](http://g.recordit.co/f6mqUEtX06.gif)

**Comment by nanot1m** [comment]
`RenderLayer` тут используется для того чтобы правильно обрабатывать клики по выпадающему меню и снаружи выпадающего меню. Если его убрать то клики по меню перестанут работать.

Лучше будет разделить логику работы меню и вызова onBlur. Например onFocus и onBlur перенести в <Input />, а логику открытия и закрытия меню оставить в RenderLayer
