### ISSUE TITLE
[DatePicker] Праздничные дни

### ISSUE THREAD

**Issue by sergey-soloviev** [skbkontur/retail-ui#423]
По гайду календарь должен содержать инфу по праздничным дням, сейчас таки дни никак не выделены в календаре.

Смотри: https://guides.kontur.ru/controls/calendar/#14

**Comment by 21alexander21** [comment]
Можем сделать пропс для списка праздничных дней

**Comment by 21alexander21** [comment]
К новому 2019 году постараемся сделать
