### ISSUE TITLE
[ComboBox] (async) Меню должно открываться вверх если контрол находится внизу страницы

### ISSUE THREAD

**Issue by BooleT37** [skbkontur/retail-ui#426]
Сейчас это можно воспроизвести на [стенде](http://tech.skbkontur.ru/react-ui/#combobox). Скриншот:
![image](https://user-images.githubusercontent.com/11178479/36071552-80c71afa-0f31-11e8-8628-5f9648657163.png)
Особенно неприятно это, когда под дропдауном на странице больше нет контента, тогда он всегда будет открываться за пределы экрана.

Технически происходит это из-за того, что компонент [DropdownContainer](https://github.com/skbkontur/retail-ui/blob/master/components/DropdownContainer/DropdownContainer.js) [изменяет](https://github.com/skbkontur/retail-ui/blob/5f6b45a3d17d08ecab9acb40187ddf91eb43648a/components/DropdownContainer/DropdownContainer.js#L91) позицию меню только по событиям [LayoutEvents](https://github.com/skbkontur/retail-ui/blob/5f6b45a3d17d08ecab9acb40187ddf91eb43648a/lib/LayoutEvents.js), а получение ответа от сервера таковым не является. Может быть, сделать его таковым? Обработка ответа от сервера осуществляется в [default reducer'е](https://github.com/skbkontur/retail-ui/blob/master/components/CustomComboBox/reducer/default.js), но мои знания по устройству этого файла ограничены, я не могу самостоятельно внести нужное изменение. Need help

**Comment by Frumcheg** [comment]
Можно импортировать emit() из LayoutEvents и самому вызвать событие, когда надо.

**Comment by BooleT37** [comment]
Посовещался с @nanot1m и сделал так как предложил @Frumcheg. Закрываю.
