### ISSUE TITLE
[Modal] При изменении размера окна браузера, отступ справа увеличивается

### ISSUE THREAD

**Issue by sharkerator** [skbkontur/retail-ui#437]
При открытой модалке, если размер окна браузера изменяется, то отступ справа для html увеличивается 
![Image](https://image.prntscr.com/image/BvEzXZbRTL2vaRos0IGSug.png)

При закрытии модалки стили для страницы не восстанавливаются (отступ сохраняется и не появляется скролл)

Замечено в Firefox 58.0.2, windows 10

**Comment by nanot1m** [comment]
Fixed
