### ISSUE TITLE
[Tooltip] валидации перекрывает [Sticky] элемент

### ISSUE THREAD

**Issue by mshatikhin** [skbkontur/retail-ui#440]
у Sticky: z-index: 100;
у Tooltip: z-index: 1000;

![joxi_screenshot_1518603868530](https://user-images.githubusercontent.com/1788385/36199458-7d2c89b8-119b-11e8-9519-0bf6405dc481.png)

**Comment by nanot1m** [comment]
Непонятно как это полечить. Потому что от инпута тултип может открыться вниз, и в этом случае тултип должен быть поверх терминальной плашки.

**Comment by 21alexander21** [comment]
проблема в react-ui-validation: 
- можно закрывать тултип при скролле
- можно блокировать скролл при открытом тултипе

Общего универсального решения кажется нет

**Comment by dzekh** [comment]
#776

**Comment by wKich** [comment]
Утащил пример в связаную задачу, эту закрываю, чтобы не дублировалось
