### ISSUE TITLE
[Input] Не консистентное позиционирование курсора при клике с установленной маской

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#449]
При клике в пустой инпут в котором задано свойство mask иногда курсор может позиционироваться не в начале, а в конце, что приводит к невозможности ввести что-либо, пока курсор не переместить в начало.
![ezgif com-gif-maker-2](https://user-images.githubusercontent.com/6397708/36481160-cc29cbda-1730-11e8-9124-95029d8a9927.gif)

**Comment by 21alexander21** [comment]
#579

**Comment by dzekh** [comment]
Курсор долеж вставать всегда в начало, если значение не заполнено. Полечим вместе с обновлением поля с маской. 
https://staff.skbkontur.ru/group/5361?action=discussions&id=8f386df3c6a6456a816b63d8e4e5925c
