### ISSUE TITLE
[SidePage] Нет внутренних отступов в Body

### ISSUE THREAD

**Issue by halfee** [skbkontur/retail-ui#450]
— retail-ui v0.15.0

В SidePage у компонента Body нет внутренних отступов:
- приходится писать лишний div. Даже в примере на [tech.skbkontur.ru](http://tech.skbkontur.ru/react-ui/#!/SidePage) есть какой-то лишний код чтобы подогнать отступы. 
- если отступы в шапке изменятся - поедет верстка
- Поведение контролов должно быть одинаковым. В Body [модального окна](http://tech.skbkontur.ru/react-ui/#!/Modal) отступы есть.

Сделайте, пожалуйста, как в модалке. Для исключительный ситуаций можно вместо Body использовать div и у него задавать собственный стиль.

![image](https://user-images.githubusercontent.com/1036441/36735410-f5cb1c52-1bf7-11e8-891b-85943f5b374e.png)

**Comment by nanot1m** [comment]
Вариант без отступов в `Body` сделан по той причине, что он покрывает больше сценариев.

Не совсем понятен пункт:
> "если отступы в шапке изменятся - поедет верстка"

Можно поподробнее?

Просто так мы всё поменять не можем, но
я бы предложил добавить другой компонент с паддингами:
```jsx
<SidePage>
  <Header>Header</Header>
  <Body>
    <Container>
      Some content
    </Container>
    <Divider />
    <Container>
      Another content
    </Container>
  </Body>
  <Footer>Footer</Footer>
</SidePage>
```

Вариант с тем, чтобы в крайних случаях не использовать `Body` не нравится тем, что в таком случае мы (как разработчики контролов) теряем контроль над компонентой. И в будущем нам будет тяжелее обновлять данный контрол без ломающих изменений

**Comment by slawwan** [comment]
Можно еще рассмотреть вариант с опциональным `padding` в `props` у `Body`
Надо собрать сценарии, понять их частотность, возможно подтюнить гайды

**Comment by nanot1m** [comment]
@slawwan если ты про булевый пропс `padding`, то может возникнуть проблема с изменением этих отступов в самом контроле, так как на это кто-нибудь может завязаться.

Хочется добиться того, чтобы никто не парился за то, какой у нас отступ в контроле и не делал хаков с отрицательными `margin`

**Comment by slawwan** [comment]
я про числовые пропсы, по умолчанию задано как в гайдах, но можно переопределить хоть на ноль

**Comment by halfee** [comment]
@nanot1m, 

> Не совсем понятен пункт:
>>"если отступы в шапке изменятся - поедет верстка"

Наверно неправильно выразился.
Например, в версии 0.17 в шапке отступы станут 20px, а не 30px.

Контент и шапка будут не выровнены. Придется везде исправлять.
