### ISSUE TITLE
[CurrencyInput] Не работает ввод на Android+Chrome

### ISSUE THREAD

**Issue by slawwan** [skbkontur/retail-ui#451]
Chrome на Android
в контроле не работает ввод ни цифр ни разделителя
копирование/вставка/удаление/курсор/форматирование работают как надо

**Comment by nanot1m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CurrencyInput — проблема с обработкой всех событий по keyDown](https://trello.com/c/3NxigS09/31-currencyinput-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0-%D1%81-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%BE%D0%B9-%D0%B2%D1%81%D0%B5%D1%85-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9-%D0%BF%D0%BE-keydown)

**Comment by nanot1m** [comment]
Ты же вроде починил?

**Comment by slawwan** [comment]
да, починил в PR #575
