### ISSUE TITLE
[DatePicker] Управление выпадающими списками месяцев и лет

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#461]
В гайдах написано: «Список также можно прокручивать колесом мышки, или кнопками вверху и внизу списка: однократное нажатие прокручивает список сразу на 3 строки, если зажать кнопку, список начнет прокручиваться непрерывно. Нажатие клавиши Esc закрывает список, другого управления с клавиатуры у списка нет.» 
https://guides.kontur.ru/controls/calendar/#10

Не работает:
1. Однократное нажатие прокручивает список сразу на 3 строки.
2. Если зажать кнопку, список начнет прокручиваться непрерывно.
3. Нажатие клавиши Esc закрывает список.

Попробовали в нескольких браузерах.

**Comment by Shururup** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[DatePicker] Управление выпадающими списками месяцев и лет](https://trello.com/c/HpaAYHhx/41-datepicker-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2%D1%8B%D0%BF%D0%B0%D0%B4%D0%B0%D1%8E%D1%89%D0%B8%D0%BC%D0%B8-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0%D0%BC%D0%B8-%D0%BC%D0%B5%D1%81%D1%8F%D1%86%D0%B5%D0%B2-%D0%B8-%D0%BB%D0%B5%D1%82)
