### ISSUE TITLE
[Modal] Двойное затенение фона

### ISSUE THREAD

**Issue by iftruereturn** [skbkontur/retail-ui#462]
Привет. В случае, если открыто 2 компонента модалки, и мы заменяем верхнюю на другую модалку, то происходит двойное затенение  фона. 

![gif](https://user-images.githubusercontent.com/13593178/37279221-f2ba90ec-260b-11e8-95fa-a8ac19b11fa8.gif)

Пример - https://iftruereturn.github.io/modal-double-shadow-example/
Код - https://github.com/iftruereturn/modal-double-shadow-example

Я посмотрел в код компонента ``Modal``, и, похоже, что проблема в ``_handleStateChange``, где определяется, что модалка уже затенена (shadowed) и ей не нужно затенять бэкграунд.

Ситуация такая:
 1. При смене верхней модалки сначала выполняется unmount компонента, что приводит к выполнению ``componentWillUnmount``, где она выкидывается из ``stack.mounted`` и синхронно эмиттится событие ``change`` для вызова ``_handleStackChange`` у всех остальных. 
2. В ``_handleStackChange`` определяется, нужно ли ``shadowed`` оставшейся нижней модалке - не нужно, поэтому, вызываем ``setState({ shadowed: false })``.
3. Верхняя модалка заменяется другой, что приводит к новому выполнению ``_handleStackChange``.
Для нижней модалки, оказывается, что апдейт стейта еще не прилетел, т.е. сравнение `if (this.state.shadowed !== shadowed)` вне колбека ``setState`` ссылается на старое состояние ``shadowed: true``.
4. Для верхней модалки апдейтим ``shadowed`` на ``false``. Также прилетает апдейт для нижней модалки ``shadowed: false``;
5. Итого получаем двойное затенение.

При последующей замене верхней модалки двойное затенение не выполняется, поскольку, когда остается только нижняя, условие ``(this.state.shadowed !== shadowed)`` не выполняется, т.к. уже равно ``false`` с предыдущего апдейта.

Воспроизводится на retail-ui@0.16.0, react@0.14.7 и react-dom@0.14.7
в браузерах Firefox 58.0.2, Chrome 64.0.3282.186, IE 11 на Win10.

Возможное решение - в _handleStackChange переместить условие внутрь setState, то есть будет что-то в роде:
```
_handleStackChange = () => {
    const shadowed = stack.mounted[stack.mounted.length - 1] !== this;
    this.setState((state) => {
      if (state.shadowed !== shadowed) {
        return { shadowed };
      }
      return null;
    });
  };
```
В таком случае двойного затенения не будет, т.к. стейт в условии всегда будет актуальным.

**Comment by nanot1m** [comment]
Думаю тут вовсе нужно убрать проверку state.shadowed !== shadowed и всегда вызывать setState
