### ISSUE TITLE
[ComboBox] Текст наезжает на стрелочку

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#466]
— браузер, ОС: Chrome 65, Win 10
— версия retail-ui: 0.16.1
— при каком сценарии: длинное имя у выбранного пункта в ComboBox
![image](https://user-images.githubusercontent.com/22623111/37446800-8e9a62fe-2840-11e8-8c46-79fed7099fa2.png)
— возможно у тебя есть предложения по её решению:
На этом элементе стоит overflow: hidden, padding-right, padding-left
![2018-03-15_10-56-26](https://user-images.githubusercontent.com/22623111/37446847-b8ea9fa6-2840-11e8-9fd1-864cbb591feb.png)
Вижу два решения:
1) Заменить padding-right на margin-right, чтобы сдвинуть границу, тогда получится так:
![margin](https://user-images.githubusercontent.com/22623111/37446903-0cc74d22-2841-11e8-8806-c6b89899872b.PNG)
2) На элемент добавить text-overflow: ellipsis, тогда будет так:
![default](https://user-images.githubusercontent.com/22623111/37446931-383e618e-2841-11e8-9712-8c7a9b27620b.PNG)

**Comment by nanot1m** [comment]
Не очень нравится идея с `ellipsis`, так как по дефолту в инпутах стоит `text-overflow: clip`

**Comment by slaeme** [comment]
Судя по [описанию](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow),
что clip, что ellipsis должны обрезать текст в рамках content area.
Но там же на примерах ниже, видно, что text-overflow: clip наезжает на padding edge, а text-overflow: ellipsis нет.
Так что видимо надо сдвигать границу.
