### ISSUE TITLE
[TopBar] Захардкоженные ссылки в TopBarDropdown

### ISSUE THREAD

**Issue by safiullin-at** [skbkontur/retail-ui#467]
В TopBarDropdown есть такие ссылки как:
-  Настройка входа в сервисы
- Сертификаты
- Оплата сервисов

Эти ссылки сейчас просто захардкожены. Есть некоторые жалобы, что на тестовых площадках эти ссылку ведут в боевой кабинет. Неплохо было бы сделать возможность управлять этим.

**Comment by Shururup** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[TopBar] Захардкоженные ссылки в TopBarDropdown](https://trello.com/c/BCibMdis/39-topbar-%D0%B7%D0%B0%D1%85%D0%B0%D1%80%D0%B4%D0%BA%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B8-%D0%B2-topbardropdown)

**Comment by nanot1m** [comment]
Исправлено
