### ISSUE TITLE
Использование less-функции lighten в variables.less

### ISSUE THREAD

**Issue by step-off** [skbkontur/retail-ui#480]
В недавно добавленных состояниях Tab'ов используются цвета:
@tab-color-hover-error: lighten(@btn-danger-bg, 25%);
@tab-color-hover-warning: lighten(@btn-pay-bg, 25%);
@tab-color-hover-success: lighten(@btn-success-bg, 25%);
@tab-color-hover-primary: lighten(@btn-primary-bg, 25%);

Проблема в том, что если в переменной, передаваемой в lighten, будет linear-gradient, то less-компилятор упадет с ошибкой, так как функции нужен color object. Нужно придумать, как безопасно использовать less-функции в variables.less.

![image](https://user-images.githubusercontent.com/20541685/37852298-eacfae5c-2f03-11e8-8db4-5fc3bf324eab.png)

**Comment by 21alexander21** [comment]
если проблема актуальная, то позовите нас после 14.09.2018. Все починим

**Comment by wKich** [comment]
Закрываю из-за неактуальности. С ходу не понятно каким должно быть универсальное решение.
