### ISSUE TITLE
[Button] у use='link' нет обработки флага "error"

### ISSUE THREAD

**Issue by mshatikhin** [skbkontur/retail-ui#498]
![image](https://user-images.githubusercontent.com/1788385/38249060-d5ca775e-3763-11e8-8851-06c6d37f5647.png)

хочется как-то так, или по гайдам

![image](https://user-images.githubusercontent.com/1788385/38249126-16594610-3764-11e8-9b8b-97329e23f612.png)

**Comment by dzekh** [comment]
Да, нужно добавить цвет фона у такой кнопки/ссылки: #FFD6D6 
Цвет есть в гайдах: https://guides.kontur.ru/principles/color/#17 
Пример использования в КЛАДРе:
https://guides.kontur.ru/components/KLADR/#Validatsiya
