### ISSUE TITLE
[Autocomplete] Ищет совпадения вместе с маской

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#499]
Привет! Опиши, пожалуйста, подробней проблему, которая возникла:
  — браузер, ОС: Chrome 65, Win 10 x64
  — версия retail-ui: 0.16.5
  — при каком сценарии: Autocomplete с заданным props mask 

  — по возможности прикрепи скриншот или гифку с примером:
mask = "99:99" 
![image](https://user-images.githubusercontent.com/22623111/38249283-99c8f658-3764-11e8-8817-7ee12e558a30.png)

  — возможно у тебя есть предложения по её решению:
Возможно так и должно быть и это совсем не баг, но тогда автокомплит не нужен, ты уже введешь всё значение перед тем как он сможет что-нибудь найти. 

Пакет react-input-mask, который используется в Input компоненте имеет event.target.value введенное значение вперемешку с маской, и насколько я понял так реализован нарочно: https://github.com/sanniassin/react-input-mask/issues/116 . 

Для автокомплита, думаю можно попробовать перед поиском убрать маску, например если совсем наивно, то обрезав строку по позиции курсора (e.target.selectionStart). Но это не точно.

**Comment by 21alexander21** [comment]
Починится вместе с новой маской для инпута
