### ISSUE TITLE
В комбобоксе отступ текста слева больше, чем должен быть по гайдам.

### ISSUE THREAD

**Issue by kutovova** [skbkontur/retail-ui#501]
Привет! Опиши, пожалуйста, подробней проблему, которая возникла:
  — Сафари и Хром, может что-то еще;
  — на контур.гайдах;

В комбобоксе отступ текста слева больше, чем должен быть по гайдам. Он почему-то больше, чем в инпуте.

**Comment by nanot1m** [comment]
Сейчас в обоих компонентах одинаковый отступ. Но я не помню чтобы мы правили этот баг
