### ISSUE TITLE
[CurrencyInput] Сбрасывается положение каретки на componentWillReceiveProps

### ISSUE THREAD

**Issue by k-g-a** [skbkontur/retail-ui#502]
Если обернуть CurrencyInput в Tooltip, который открывается на фокус (сценарий использования - валидация):
``` 
<Tooltip ... trigger={this.state.isTooltipOpened ? 'opened' : 'closed'}>
  <CurrencyInput
    value={this.state.value}
    onChange={(e, v) => this.setState({ value: v })}
    ...
    onFocus={() => this.setState({ isTooltipOpened: true })}
    onBlur={() => this.setState({ isTooltipOpened: false })}
  />
</Tooltip>
```
Получаем следующее поведение:
- кликаем в произвольное место в инпуте;
- каретка встает в нужное место;
- срабатывает фокус, у тултипа меняется проп trigger, у вложенного в него CurrencyInput срабатывает componentWillReceiveProps, state.selection.start становится равен 0;
- после любого ввода (удаление символа/любая цифра) каретка "улетает" в самое начало и дальнейший ввод идет совсем не туда, куда хотел пользователь

**Comment by slawwan** [comment]
либо я не понял сценарий, либо что-то упущено. state обновится если прилетит значение отличное от введенного или если изменится количество знаков после запятой, в сценарии не увидел ни того ни другого - не понял...
