### ISSUE TITLE
Выводить значения перечисляемых типов для пропсов на витрине контролов

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#510]
Сейчас на витрине значения пропсов отображаются совсем не очевидно. Выводится только название типа, которое ничего не говорит о том какие значения может принимать тот или иной пропс
![screen shot 2018-04-17 at 11 03 41](https://user-images.githubusercontent.com/6397708/38851450-49fffd58-422f-11e8-9a85-8efb1da33d06.png)

**Comment by nanot1m** [comment]
Поправили с последним релизом
