### ISSUE TITLE
[Dropdown] Адаптировать цвет стрелки "вниз", если указан параметр "use"

### ISSUE THREAD

**Issue by pravosud** [skbkontur/retail-ui#513]
Для примера, проставим use="success", стрелка сливается с бэкграундом

![0](https://user-images.githubusercontent.com/5364762/38918163-4b20ac64-4306-11e8-8b59-b41448d829d0.png)

**Comment by nanot1m** [comment]
Поправили в 9f19977600c784f89ef6738a6b52d730831bd26e
