### ISSUE TITLE
Дать возможность распространять фокус и валидацию на весь компонент Group

### ISSUE THREAD

**Issue by alivekenny** [skbkontur/retail-ui#518]
Сейчас валидация или фокус распространяется на конкретный элемент группы, что иногда выглядит некрасиво. Особенно это видно на поле, которое склеено с кнопкой.

Нужно дать возможность показывать фокус на всей группе сразу, при этом не потерять возможность выделять отдельные элементы группы по нажатию на Tab.

![image](https://user-images.githubusercontent.com/21039303/39302853-78a1a324-496d-11e8-8e23-f7a9e21e90d4.png)

**Comment by dzekh** [comment]
А есть еще варианты? 
Мне кажется вариант справа не очень правильный, так как кнопка та не в фокусе. Да и она не в поле. 
Может поднимать фокус над кнопкой? Когда фокус перенесется на кнопку она же тоже перекроет поле. Тем более ошибки в кнопке нет, ошибка в поле.

**Comment by alivekenny** [comment]
Попробовал. Такой вариант тоже норм, хотя мне кажется, здесь вообще нет смысла рассматривать этот контрол как кнопку + поле, это вполне самодостаточный компонент, такой комбобокс, у которого вместо выпадашки открывается лайтбокс. Поэтому и не вижу ничего плохого в том, что валидация и фокус падают на него целиком.

![image](https://user-images.githubusercontent.com/21039303/39353096-1ad36f44-4a20-11e8-8cad-54a2071d94a0.png)

**Comment by dzekh** [comment]
а мы можем сделать второй?

**Comment by nanot1m** [comment]
Ну третий определенно проще, я бы предложил подождать до июня (там мы откажемся от ie8) и переисмыслить верстку, чтобы сделать второй вариант (:

**Comment by 21alexander21** [comment]
Переосмысляем верстку...

**Comment by dzekh** [comment]
У нас есть [компонент группа](http://tech.skbkontur.ru/react-ui/#!/Group) который делает подобные штуки и соединяет кнопки с полями. Сейчас в ней фокус правильно отображается — поверх кнопок и не перекрывается (3 вариант), а то, что он должен обнимать кнопку — спорно. Выглядит, возможно, лучше, но пользовательский опыт от этого не будет проще. 

Можно посмотреть на [тот же пример](http://tech.skbkontur.ru/react-ui/#!/Group) и спросить себя — если фокус будет у всей группы — как используя только клавиатуру перейти фокусом на нужную кнопку, или на кнопку вообще? Табом он должен уйти на следующий контрол, но никак не внутрь группы. Нажимать Enter? 🤔

Мы наверное смогли бы реализовать требование «при этом не потерять возможность выделять отдельные элементы группы по нажатию на Tab» — но пользователю это будет не очевидно.

Никита, я закрываю баг с тегом  wontfix. Если не согласен и это важно — переоткрой, и напиши почему это важно.
