### ISSUE TITLE
Задать компонентам box-sizing

### ISSUE THREAD

**Issue by Eazymov** [skbkontur/retail-ui#525]
Сейчас (0.17.11) проблемы можно увидеть на примере компонента DatePicker если глобально установлен box-sizing: border-box;

![image](https://user-images.githubusercontent.com/26853518/39621547-95e7920e-4fa8-11e8-9e52-c7570daf82e8.png)

**Comment by pravosud** [comment]
![0](https://user-images.githubusercontent.com/5364762/39621763-47937892-4fa9-11e8-84d1-1b91013f179e.png)

**Comment by Eazymov** [comment]
У контрола нужный стиль просто не задан, при чем здесь специфичность?

**Comment by pravosud** [comment]
Имхо проблема не в том, что у компоненты не задан "нужный стиль", а в том, что все элементы глобально обмазаны border-box'ом, либо еще какими-то другими свойствами.

Это к тому, что если ставишь глобальные стили - будь готов к тому, что они могут сломать стороннюю верстку.

Я не против box-sizing'a в Datepicker'е, просто хотел порекламировать идею того, что лучше использовать css свойства только там, где это необходимо

**Comment by 21alexander21** [comment]
Идея помечать порталы особым классом - хороша
