### ISSUE TITLE
[ComboBox] Прокинуть id до инпута. А то label for не работает

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#530]

**Comment by 21alexander21** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Привести к единообразию параметры компонентов для форм](https://trello.com/c/ikFFUgtz/38-%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%81%D1%82%D0%B8-%D0%BA-%D0%B5%D0%B4%D0%B8%D0%BD%D0%BE%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%B8%D1%8E-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D1%84%D0%BE%D1%80%D0%BC)
