### ISSUE TITLE
[CurrencyInput] не принмает onMouseEnter и onMouseLeave

### ISSUE THREAD

**Issue by 21alexander21** [skbkontur/retail-ui#531]
CurrencyInput не принимает onMouseEnter и onMouseLeave и, соответственно, не прокидывает их дальше в Input. Из-за этого неправильно работает ValidationWrapperV1 из [react-ui-validations](https://github.com/skbkontur/react-ui-validations) (тултип не раскрывается по ховеру)

**Comment by nanot1m** [comment]
#532
