### ISSUE TITLE
[Select] Уменьшить отступ до иконки

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#542]
Нужно уменьшить отступ до иконки, чтоб чуть больше текста входило. А то не рационально используется место. И не соответствует библиотеке в скетче. 

Поправить во всех контролох, где подобное поведение предусмотрено.

<img width="432" alt="screen shot 2018-05-29 at 12 17 41" src="https://user-images.githubusercontent.com/26383080/40643662-54082c22-633a-11e8-8595-122d10d5ede4.png">

**Comment by 21alexander21** [comment]
надо переосмыслить верстку `Button`
