### ISSUE TITLE
[Select] Цвет многоточия в состоянии «не выбрано»

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#543]
Цвет многоточия, которое обрезает текст — черный, в то время как основной цвет текста в состоянии «ничего не выбрано» — серый. 
Нужно сделать так чтоб многоточие всегда было тем же цветом что основной текст.  Проверить другие варианты, где текст меняет цвет, если они есть.
<img width="1119" alt="screen shot 2018-05-29 at 12 24 05" src="https://user-images.githubusercontent.com/26383080/40643986-37b38dfe-633b-11e8-9e06-74bb6a7bea0d.png">

**Comment by 21alexander21** [comment]
#542
