### ISSUE TITLE
[Modal] - Отступы не по гайдам

### ISSUE THREAD

**Issue by byTimo** [skbkontur/retail-ui#565]
Привет. По гайдам так:
![2018-06-27 16 45 13](https://user-images.githubusercontent.com/11138341/42017742-8d16c5ae-7ac9-11e8-93b1-c5168d3ce26b.png)
а по факту так:
![2018-06-27 16 46 37](https://user-images.githubusercontent.com/11138341/42017757-94049a62-7ac9-11e8-826b-6c5fda0b5c9f.png)

Надо починить :)

**Comment by Shururup** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Modal] - Отступы не по гайдам](https://trello.com/c/hb64MEfg/34-modal-%D0%BE%D1%82%D1%81%D1%82%D1%83%D0%BF%D1%8B-%D0%BD%D0%B5-%D0%BF%D0%BE-%D0%B3%D0%B0%D0%B9%D0%B4%D0%B0%D0%BC)

**Comment by Shururup** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Modal] - Отступы не по гайдам](https://trello.com/c/hb64MEfg/34-modal-%D0%BE%D1%82%D1%81%D1%82%D1%83%D0%BF%D1%8B-%D0%BD%D0%B5-%D0%BF%D0%BE-%D0%B3%D0%B0%D0%B9%D0%B4%D0%B0%D0%BC)
