### ISSUE TITLE
Перевести все компоненты с выпадашками на использование порталов

### ISSUE THREAD

**Issue by nanot1m** [skbkontur/retail-ui#57]

**Comment by mshatikhin** [comment]
Столкнулся с неприятной проблемой, [DatePicker] не открывается поверх контролов с overflow.

Кроме [DatePicker] нам потребются [Combobox] и [Autocomplete] 
я правильно понимаю что вы работате над этим? Эта штука просто мастхэв для нас =( 

![2017-02-07_18-07-39](https://cloud.githubusercontent.com/assets/1788385/22692394/9a42c572-ed60-11e6-8b73-af12116f77e1.png)

**Comment by nanot1m** [comment]
Поправлено в 0.6.7

**Comment by nanot1m** [comment]
Забыл автокомплит поправить, переоткрываю

**Comment by mshatikhin** [comment]
@nanot1m после обновления с 0.6.6 на 0.6.7, появился глюк с дэйтпикером, по клику на пикту календарика в инпуте дэйтпикера устанавливается фокус (из-за это не получается поменять стэйт)

![feb 8 2017 11-28 am](https://cloud.githubusercontent.com/assets/1788385/22725993/85e25baa-edf2-11e6-8c7a-222bd99f7284.gif)

**Comment by nanot1m** [comment]
@mshatikhin поправил в 4b4ec96
