### ISSUE TITLE
[Tooltip] нужна возможность управления отступами

### ISSUE THREAD

**Issue by MaxGorshkov** [skbkontur/retail-ui#570]
Конфигурация
  - библеотека  retail-ui
  - версия 0.18.10
  - браузер любой, ОС любая;

Мне нужно управлять отступами в тултипе для использования скрола в тултипе
![image](https://user-images.githubusercontent.com/14037804/42088150-020fa450-7bb2-11e8-86dd-2c8bc8f365fc.png)

Вот где захардкодены параметры, которые я хочу каким то образом поправить
https://github.com/skbkontur/retail-ui/blob/master/packages/retail-ui/components/Tooltip/Tooltip.tsx#L173

Вижу два варианта решения:
1. прокидывать свойство className в эту дивку и вынести заинлайненные стили (padding: 15px 20px;position: relative;) из этой div в css-класс;
чтобы получилось типа такого:
`<div className='autogenerated-class-name ' + {this.props.className}>`

2. добавить свойство для тултипа padding и передавать значение в эту дивку. Если ничего не задано, то вставлять padding: 15px 20px;

**Comment by 21alexander21** [comment]
https://guides.kontur.ru/controls/tooltip/
