### ISSUE TITLE
[Modal] HideBodyVerticalScroll не учитывает что скролл уже скрыт

### ISSUE THREAD

**Issue by halfee** [skbkontur/retail-ui#571]
- библеотека retail-ui@0.18.11
  - chrome, windows;

Сценарий:
 - У html документа скрыт скролл, задан margin-right
 - Открыть модалку

Как есть: контент документа смещается на 17px.
Как должно быть: Контент не должен смещаться.

Модалка не учитывает, что скролл уже скрыт, скрывает его снова и добавляет к margin-right 17px чтобы его компенсировать. Если скролл скрыт, не нужно добавлять еще 17px.

![image](https://user-images.githubusercontent.com/1036441/42147069-565744e8-7de5-11e8-986f-85d368927546.png)

**Comment by wKich** [comment]
Исправлено в #886
