### ISSUE TITLE
[ComboBox + ValidationWrapperV1] Несколько ComboBox'ов, каждый из которых обернут в ValidationWrapperV1, внутри ValidationContainer некорректно валидируются

### ISSUE THREAD

**Issue by Dekree** [skbkontur/retail-ui#574]
Интеграция библиотек retail-ui и react-ui-validation
Браузер: Chrome
ОС: Windows 10

Имеется примерно такая верстка:
```js
<ValidationContainer>

    <ValidationWrapperV1>
        <ComboBox />
    </ValidationWrapperV1>

    <ValidationWrapperV1>
        <ComboBox />
    </ValidationWrapperV1>

    <ValidationWrapperV1>
        <ComboBox />
    </ValidationWrapperV1>

</ValidationContainer>
```

Изначальное состояние:
![combobox_stage_1](https://user-images.githubusercontent.com/13333201/42166106-a512c0ee-7e12-11e8-90de-50f15bdbe61e.jpg)
После первого вызова валидации на контейнере:
![combobox_stage_2](https://user-images.githubusercontent.com/13333201/42166117-b06f051a-7e12-11e8-8ab6-29e2e569b78e.jpg)
После повторного вызова валидации на контейнере:
![combobox_stage_3](https://user-images.githubusercontent.com/13333201/42166127-b9d7374e-7e12-11e8-9479-f90c67ef6b8f.jpg)

При двойном вызове валидации на контейнере раскрываются сразу все комбобоксы на странице, а должен только первый на который происходит программный фокус из ValidationWrapperV1.

Исследуя проблему выяснил что при первой валидации (когда текущее значение проперти validationInfo у ValidationWrapperV1 равно undefined и значение стейта editing у CustomComboBox равно по умолчанию false) автофокус внутри комбокса(в методе componentDidUpdate у ComboBoxView) не срабатывает потому что текущее значение editing остается false. И программный фокус у ValidationWrapperV1 на первом комбобоксе срабатывает правильно(см. вторую картинку). Но при этом во время первой валидации в комбобокс прокидывается проперти error=true из которого при повторной валидации берется значение для editing в CustomComboBox, что вызывает раскрытие всех комбобоксов автоматически при componentDidUpdate у ComboBoxView(см. третью картинку).

Примерная последовательность происходящего в коде:
1) error = false;
editing = false;
2) вызывается валидация у контейнера
3) происходит componentDidUpdate у ComboBoxView(фокус не вызывается, потому что editing еще false)
4) происходит componentDidUpdate у CustomComboBox(проперти editing получает значение true из пришедшего проперти error)
5) вызывается повторная валидация
6) происходит componentDidUpdate у ComboBoxView(фокус вызывается у всех комбобоксов, потому что после первой валидации у них у всех error = true)

Предложение по решению:
Возможно следует разделить программный и пользовательский фокус и вызывать автофокусировку на componentDidUpdate у ComboBoxView только при пользовательском фокусе.

**Comment by nanot1m** [comment]
Подскажи что у тебя приходит в value комбобокса?

**Comment by Dekree** [comment]
В него приходит объект с пустыми полями:
value={{ boxId: props.boxId, name: props.name }}

**Comment by nanot1m** [comment]
@Dekree Если все так как ты написал, то тут каждый раз приходит новое value, потому что создаётся новый объект

**Comment by Dekree** [comment]
@nanot1m, да, так и есть, начал фильтровать value на своей стороне и все заработало. Спасибо!

**Comment by nanot1m** [comment]
@Dekree Но у нас также косяк при сравнении value, возьмём в работу
