### ISSUE TITLE
[Modal] Maximum update depth exceeded

### ISSUE THREAD

**Issue by Eazymov** [skbkontur/retail-ui#577]
### Браузер
Google Chrome, 67.0.3396.99

### OS
Windows 10

### Описание проблемы
Если положить в компонент <Modal.Footer /> любой элемент и задать ему вертикальный margin, то при скролле модального окна появляется ошибка, скриншот:

![image](https://user-images.githubusercontent.com/26853518/42205342-a2b835da-7ebd-11e8-9aee-99f16d6b06a6.png)

**Comment by nanot1m** [comment]
Дублирует #67
