### ISSUE TITLE
В FF и IE ломается vertical-align: baseline рядом с кнопками и селектами

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#58]
Если поставить текст рядом с кнопкой или селектом, то фаерфокс и ИЕ делают так:
![image](https://cloud.githubusercontent.com/assets/9248122/21451908/a9dd7942-c924-11e6-9461-8efdfcb172ee.png)
![image](https://cloud.githubusercontent.com/assets/9248122/21452018/b7db8dee-c925-11e6-87c4-25200ca1f60b.png)
Оказывается, проблема эта известна давно, и, мало того, так и надо, даже в [спеке так написано (последняя строка) ](https://www.w3.org/TR/CSS2/visudet.html#propdef-vertical-align).
Если я всё правильно понимаю, у нас всё ломается из-за overflow: hidden в Button-caption.
Даже не знаю, что предложить. :(

**Comment by mortifer** [comment]
как ни странно я тоже именно на этой неделе столкнулся с этой проблемой :)
в понедельник опишу как зарешал.
ну, как мне кажется.

**Comment by nanot1m** [comment]
Fixed in #59
