### ISSUE TITLE
[Dropdown] При длинных значениях вылазил за пределы экрана

### ISSUE THREAD

**Issue by aagordienko** [skbkontur/retail-ui#590]
Retail-UI, хром, винда.
Если имеем длинное значение в пункте меню в выпадашке, часть выпадашки не влазит в экран, имеем горизонтальный скролл.

Прилагаю скрин из tech и скрин из нашего проекта.

Кажется, в качестве решения, выпадашка должна вести себя как хинт - понимая, что справа места недостаточно, рисоваться от правого края дропдауна и расти влево :)

![photo_2018-07-10_15-02-48](https://user-images.githubusercontent.com/30799122/42503793-10d7a8c6-8453-11e8-9c43-6dd218180f49.jpg)
![photo_2018-07-10_15-03-15](https://user-images.githubusercontent.com/30799122/42503794-110076ca-8453-11e8-9b80-2e32a91e7824.jpg)

**Comment by zhzz** [comment]
@wKich Это будет breaking-change. 

Даже в наших stories ComboBox'а мы сами, опираясь на этот `white-space: nowrap`, делаем элементам `text-overflow: ellipsis`.

Тут, видимо, остается только самому стилизовать содержимое элементов.

**Comment by dzekh** [comment]
Ну тут есть кстати еще одно предложение — «понимая, что справа места недостаточно, рисоваться от правого края дропдауна и расти влево»

**Comment by zhzz** [comment]
Например, такой вариант. Ширину и текст не трогаем, но заставляем панель никогда не выходить за пределы экрана.

![!](https://i.imgur.com/BxB80Qe.gif)

**Comment by zhzz** [comment]
Начиная с **@0.34.0**, второй кейс можно будет обойти так: 
```
<Dropdown disablePortal={true} menuAlign={'right'} />
```
