### ISSUE TITLE
[i18n] Необходима возможность менять захакрдкоженные строки с помощью пропс

### ISSUE THREAD

**Issue by slogger** [skbkontur/retail-ui#594]

**Comment by wKich** [comment]
Можно все текстовки вынести в отдельные словари и с помощью пропса `locale` задавать свои переводы.

**Comment by dzekh** [comment]
В целом сейчас есть возможность [локализации](https://tech.skbkontur.ru/react-ui/#/LocaleProvider) почти всех компонентов. Скоро подъедет и дэйтпикер. по крайней мере есть возможность менять «захардкоженные строки». Закрываю.
