### ISSUE TITLE
[DropDownMenu > InternalMenu] Падает при child равным null

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#607]
Привет!

библиотека retail-ui
версия 0.18.14

Если в DropdownMenu сделать, что то типа такого:

```
<DropdownMenu ...>
   {this.renderSearchMenu()}
   {this.renderMenuItems()}
   !this.searchedItems.length && (
            <MenuItem disabled>
                <span className="not-found">{this.props.notFoundText}</span>
            </MenuItem>
        );
</DropdownMenu>
```

то он упадет с ошибкой

> Cannot read property 'type' of null

строка: 
https://github.com/skbkontur/retail-ui/blob/1eff09c1611c2dbc3d2c3577450259299295eda7/packages/retail-ui/components/internal/InternalMenu/InternalMenu.tsx#L88

Возможно мне нужно избегать null элементов в массиве детей ? 
Хотя вроде для реакта `void | null | boolean` валидные элементы.

Или можно вам выше добавить проверки на null и boolean, к проверкам на string и number. Могу сделать PR.

**Comment by nanot1m** [comment]
@slaeme Будет здорово если поправишь)
