### ISSUE TITLE
[ComboBox] placeholder, принудительная фокусировка, неожиданный ввод 

### ISSUE THREAD

**Issue by StarLordJ** [skbkontur/retail-ui#608]
1) Не отображается placeholder, если props.value === null и props.error === true
2) Принудительная фокусировка на combobox. После изменения value и props.error === true - фокусируется на контрол. В формах пользователь может принять неверные данные, при открытии формы происходит фокусировка на ошибочный combobox.
3) Не удаляется значение при неожиданном вводе. Старый Combobox умел при вводе значения не справочника и потере фокуса удалять его, сейчас такого поведения нет. Даже если в handleUnexpectedInput засеттить value: null.

**Comment by wKich** [comment]
Fixed by #705
