### ISSUE TITLE
[TopBar] Наведение на стрелку виджета выбора сервисов

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#623]
Cерая плашка при нажатии на стрелку должна доходить до края панели сверху и снизу: https://guides.kontur.ru/components/header/#07
Сейчас она не доходит:
<img width="881" alt="screen shot 2018-07-19 at 17 11 10" src="https://user-images.githubusercontent.com/26383080/42941939-c67f598c-8b77-11e8-950c-f0a093eb2a9b.png">

- библиотека Retail-ui
- версия — та что http://tech.skbkontur.ru/react-ui/#/TopBar ;
- браузер Safari, Mac ОС;

**Comment by Shururup** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Пофиксить кнопку виджета у логотипа в сафари](https://trello.com/c/Mba1ZE9E/46-%D0%BF%D0%BE%D1%84%D0%B8%D0%BA%D1%81%D0%B8%D1%82%D1%8C-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D1%83-%D0%B2%D0%B8%D0%B4%D0%B6%D0%B5%D1%82%D0%B0-%D1%83-%D0%BB%D0%BE%D0%B3%D0%BE%D1%82%D0%B8%D0%BF%D0%B0-%D0%B2-%D1%81%D0%B0%D1%84%D0%B0%D1%80%D0%B8)
