### ISSUE TITLE
[FxInput] Добавить prop refInput

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#629]
Добавить возможность указывать prop `refInput` для `FxInput`. Которое позволяет получить ссылку на элемент `input`.

**Comment by nanot1m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FxInput нельзя зафокусить программно](https://trello.com/c/ee7le1NM/47-fxinput-%D0%BD%D0%B5%D0%BB%D1%8C%D0%B7%D1%8F-%D0%B7%D0%B0%D1%84%D0%BE%D0%BA%D1%83%D1%81%D0%B8%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%BE)
