### ISSUE TITLE
Некорректно отображается dropdown с иконкой

### ISSUE THREAD

**Issue by ando771** [skbkontur/retail-ui#63]
После коммита https://github.com/skbkontur/retail-ui/commit/d44942e0a319d7bd47bde9127d4624b26d4383eb#diff-1f6edd48633732db8cf62aaa79c3b8ebL34 стал некорректно отображаться dropdown, если было указано свойство icon, пример на скриншоте.
![dropdown_bug](https://cloud.githubusercontent.com/assets/19431369/21954510/d50d3ac4-da74-11e6-8382-cda4dd4189f4.png)

**Comment by nanot1m** [comment]
Буду рад, если просмотришь #64
