### ISSUE TITLE
[Logotype] Виджет не отображается при изменении пропса withWidget

### ISSUE THREAD

**Issue by denexapp** [skbkontur/retail-ui#631]
### Окружение:
Retail-ui, версия 0.19.1 (Последняя на 20.07.2018)
Windows 10, Firefox/Edge/YandexBrowser

### Шаги воспроизведения:
1. Смонтировать компонент Logotype
2. Установить значение пропса withWidget равным true
3. Установить значение пропса withWidget равным false
4. Установить значение пропса withWidget равным true
5. Кликнуть по стрелочке открытия виджета

### Ожидаемый результат:
Откроется виджет со списком продуктов контура

### Фактический результат:
Ничего не произойдёт

### Предложения:
Стоит протестировать сценарии с динамическим изменением пропса withWidget, например, открыть виджет и установить withWidget в false и подобным.

**Comment by nanot1m** [comment]
@denexapp А для чего вам нужно включать отключать виджет?

**Comment by denexapp** [comment]
@nanot1m для адаптивной вёрстки. Хочу в мобилках использовать TopBar с Logotype, но виджет не приспособлен к мобилкам
