### ISSUE TITLE
[Tooltip] При render={ () => null } тело тултипа не рисуется, а стрелочка рисуется

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#641]
Привет! Опиши, пожалуйста, подробней проблему, которая возникла:

- библиотека retail-ui
- версия 0.20.0;
- браузер последний Chrome, ОС Win 10;

В сторибуке тултипа написано:
![image](https://user-images.githubusercontent.com/22623111/43261350-cd523f80-90f5-11e8-8913-55752b424c9b.png)

В реальности тултип не показывается, но стрелочка показывается:
![image](https://user-images.githubusercontent.com/22623111/43261387-f1c8bb3c-90f5-11e8-97fd-5cf093504e28.png)

**Comment by Shururup** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Tooltip] При render={ () => null } тело тултипа не рисуется, а стрелочка рисуется](https://trello.com/c/ieudS8xs/48-tooltip-%D0%BF%D1%80%D0%B8-render-null-%D1%82%D0%B5%D0%BB%D0%BE-%D1%82%D1%83%D0%BB%D1%82%D0%B8%D0%BF%D0%B0-%D0%BD%D0%B5-%D1%80%D0%B8%D1%81%D1%83%D0%B5%D1%82%D1%81%D1%8F-%D0%B0-%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%BE%D1%87%D0%BA%D0%B0-%D1%80%D0%B8%D1%81%D1%83%D0%B5%D1%82%D1%81%D1%8F)
