### ISSUE TITLE
[PopupMenu] Среди детей может быть false, его надо игнорировать

### ISSUE THREAD

**Issue by andgein** [skbkontur/retail-ui#642]
В `PopupMenu` или `DropdownMenu` может быть какая-нибудь такая логика:

```
<DropdownMenu caption={...}>
   <MenuItem></MenuItem>
   <MenuSeparator />
    { showSomeMenuItems && <MenuItem>...</MenuItem>}
</DropdownMenu>   
```

Если `showSomeMenuItems = false`, то всё выражение заменяется на `false`. `InternalMenu` обрабатывает эту ситуацию неправильно и падает. Проблема где-то здесь:
https://github.com/skbkontur/retail-ui/blob/master/packages/retail-ui/components/internal/InternalMenu/InternalMenu.tsx#L86

Там ожидается строка, число, или что-то, что имеет `child.type` (например, `MenuItem` или `MenuHeader`).

Обход проблемы — явно возвращать строку:
`{ showSomeMenuItems ? <MenuItem>...</MenuItem> : ''}`

Но хочется заполучить и поддержку первого синтаксиса.

**Comment by andgein** [comment]
Кажется, это копия #607, а я просто не заметил, что была новая версия, потому что не было release notes :)

Пока закрываю, проверю на последней версии.

**Comment by nanot1m** [comment]
@andgein кейс c false тоже должен упасть 🙁

**Comment by andgein** [comment]
Проверил, на новой версии всё хорошо, да.
