### ISSUE TITLE
[Hint] Не закрывается, когда используется на выпадающем списке, например Select

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#646]
Привет! Опиши, пожалуйста, подробней проблему, которая возникла:

- библиотека retail-ui;
- версия 0.20;
- браузер, ОС: Chrome, Win10;

Использую Hint вместе с Select, как то так:
```
<Hint ...>
    <Select/>
</Hint>
```
Чтобы было вот так:
![image](https://user-images.githubusercontent.com/22623111/43392714-f1f56504-940d-11e8-82e7-386b036e9aa5.png)

Но при использовании, когда ты выбираешь часовой пояс, Hint остается открытым:
![image](http://g.recordit.co/NSEQKqGB2b.gif)

**Comment by 21alexander21** [comment]
При закрытии Select'а (или дропдауна, или комбобокса, не важно), не происходит событие ```mouseleave```. Пока не починили, можно использовать ```onMouseLeave``` и ```onMouseEnter``` селекта вместе с ```manual``` хинта
