### ISSUE TITLE
[TokenInput] Реализовать "Поле с токенами"

### ISSUE THREAD

**Issue by dmitrymurzin-skb** [skbkontur/retail-ui#650]
Реализовать компонент "Поле с токенами" https://guides.kontur.ru/controls/tokens

**Comment by mshatikhin** [comment]
@dzekh.

Реализовали основную часть функциональности из гайдов https://guides.kontur.ru/controls/tokens/

Осталось не реализовано:

- Токены с маской
- Цветные токены
- Валидация с тултипом
- Каждый токен может валидироваться отдельно

Кому нужна данная функциональность пишите комментарии.

пул реквест в библиотеку, https://github.com/skbkontur/retail-ui/pull/667

Предлагаю выкатить под флагом next, чтобы поиграться на боевой. 
@wKich @21alexander21 Что думаете?

**Comment by dzekh** [comment]
Кажется, что без этих фич уже можно более-менее полноценно использовать контрол. 
Думаю что маску в токенах и цвет можно отложить на долго или отказаться совсем. 
Все остальное тоже терпит.
В дальнейшем, нужно будет сделать, по приоритетам: 
1) валидацию по отдельности 
2) с тултипом

**Comment by EvgenyPlotnikov45** [comment]
Отмечу несколько багов, с которыми столкнулся при первом использовании:
1) Нереализован лимит отображения айтемов, а если точнее, то при передачи дополнительного `MenuItem` компонента в свойство `selectedItems`, который содержит в себе запись "отображено 5 из 100", этот айтем воспринимается как токен, который можно выбрать и добавить. Я интуитивно предполагал, что должно работать как в `ComboBox` компоненте)
![image](https://user-images.githubusercontent.com/15770443/47715801-ab153680-dc62-11e8-8964-d83b225204af.png)
2) Если для меню нехватает места снизу, то оно должно открыться сверху
![image](https://user-images.githubusercontent.com/15770443/47716291-127fb600-dc64-11e8-8e45-d9fc87eb5850.png)
3) Когда мы удаляем айтемы из списка кликом мыши, список не обновляется и удаленные айтемы в нем неотображаются.
Допустим у нас есть токен инпут с выбранными элементами:
![image](https://user-images.githubusercontent.com/15770443/47716658-3e4f6b80-dc65-11e8-962a-a32297bd820f.png)
Мы кликаем по по крестикам и удаляем элементы:
![image](https://user-images.githubusercontent.com/15770443/47716716-6343de80-dc65-11e8-9299-fa00dcd59447.png)
Кажется, что после удаления элемента он должен появиться в списке, но нет.

**Comment by wKich** [comment]
@EvgenyPlotnikov45, мы на днях с @mshatikhin немного пообщались и возникла мысль использовать внутри `TokenInput` существующий `ComboBox`. Сейчас там какая-то своя реализация местами очень похожая на ту, которая есть в комбобоксе. И как ты верно заметил интуитивно `TokenInput` воспринимается, как `ComboBox`, а на деле многих вещей не реализовано в нем.
