### ISSUE TITLE
[Input] нет возможности указать тип `number`

### ISSUE THREAD

**Issue by IrinaSkb** [skbkontur/retail-ui#653]
Привет! Опиши, пожалуйста, подробней проблему, которая возникла:

- библиотека (retail-ui, react-ui-validations или еще что-то)
- версия;
- браузер, ОС;
- при каком сценарии;
- по возможности прикрепи скриншот или гифку с примером;
- возможно у тебя есть предложения по её решению;

**Comment by 21alexander21** [comment]
для числовых значений есть компонент ```CurrencyInput```

**Comment by 21alexander21** [comment]
Никак. Можно, либо использовать ```CurrencyInput``` для ввода денежных значений, либо использовать ```Input``` и валидировать значения самостоятельно
