### ISSUE TITLE
[DatePicker] добавить возможность  скролить до maxDate

### ISSUE THREAD

**Issue by IrinaSkb** [skbkontur/retail-ui#658]
Привет! Опиши, пожалуйста, подробней проблему, которая возникла:

- retail-ui
Когда указываем `maxDate` дату в прошлом, календарь открывается всегда на текущем дне, хочется прокручивать до `maxDate`
![screenshot 8](https://user-images.githubusercontent.com/41990507/43697795-fc488764-995f-11e8-854e-02d168c490a2.png)

**Comment by dzekh** [comment]
А откуда такое желание — скроллить к максимально или минимально возможной дате? 
Кажется что эти даты никак не связаны с теми, что может хотеть выбирать пользователь. 
Если проектировщик может предположить какие-то даты, можно поставить ссылки на них рядом с полем: https://guides.kontur.ru/controls/calendar/#05

**Comment by dzekh** [comment]
А, до меня дошло. 
Условие такое — если диапазон возможных дат не совпадает с текущей датой — нужно открывать на ближайшем возможном для выбора месяце. Если он в прошлом — то на самом позднем, если в будущем, то на раннем. 

Все логично. Нужно добавить в Гайды оговорку.
