### ISSUE TITLE
[Modal] Реакция на уменьшение высоты контента.

### ISSUE THREAD

**Issue by Frumcheg** [skbkontur/retail-ui#66]
Лайтбокс замечательно реагирует на увеличение высоты контента, однако обратное действие остаётся для него незамеченным: [GIF с демонстрацией](https://cloud.githubusercontent.com/assets/2862206/22250955/d8d24dcc-e26a-11e6-938d-6830ee77e1bd.gif)

UPD:, при увеличении высоты контента, футер сначала уезжает за пределы экрана и появляется прилипшим только при скролле

**Comment by molokovev** [comment]
@nanot1m, ты ещё не занимался этим?
Если помнишь, у нас ещё была хотелка насчёт отключения функции с изменением контента. Пока не буду заводить отдельную задачу под это.

**Comment by mshatikhin** [comment]
+1 пофиксите плиз
![modal](https://user-images.githubusercontent.com/1788385/27320677-bcd2f180-55b0-11e7-97b2-dd44e97d24f9.gif)

**Comment by nanot1m** [comment]
У нас нет возможности перерисовывать модалку при изменении высоты контента, так как модалку ничего не знает об изменениях дочерних элементов.

Можно зафорсить модалку пересчитать позицию вызвав `LayoutEvents.emit()`
```js
import LayoutEvents from "@skbkontur/react-ui/lib/LayoutEvents";
LayoutEvents.emit();
```
