### ISSUE TITLE
[Combobox] При disabled=true отображает меню по клику

### ISSUE THREAD

**Issue by vkochev** [skbkontur/retail-ui#660]
- react-ui
- 0.20.0
- плоские контролы
disabled=true, но при клике все равно вываливается меню:
![image](https://user-images.githubusercontent.com/22343087/43784895-a36db64e-9a7e-11e8-962b-af313aa5fd8d.png)

**Comment by nanot1m** [comment]
@vkochev Добавлю, что воспроизводится только в плоском дизайне

**Comment by nanot1m** [comment]
Тут скорее опечатка, на скрине видео, что disabled=true

**Comment by 21alexander21** [comment]
У меня в сторибуке не воспроизводится ни в 0.20.0, ни в 0.20.2. Что я делаю не так?

**Comment by mshatikhin** [comment]
@21alexander21 это в flat дизайне кажется

**Comment by vkochev** [comment]
@21alexander21 плоские контролы?

**Comment by 21alexander21** [comment]
Площе некуда
