### ISSUE TITLE
[ComboboxOld] findDOMNode on onmounted component в ie11

### ISSUE THREAD

**Issue by JasonZIglar** [skbkontur/retail-ui#664]
- retail-ui
- 0.20.1;
- IE11;

![script](https://user-images.githubusercontent.com/23415836/43894779-91e93e1a-9bec-11e8-859b-1f8529d4c651.gif)

![renderlayer](https://user-images.githubusercontent.com/23415836/43894807-aeffefb2-9bec-11e8-80f3-1538c243a06b.gif)

**Comment by wKich** [comment]
Надо переходить на новый ComboBox
