### ISSUE TITLE
[Input] Возможность передачи type="number"

### ISSUE THREAD

**Issue by denexapp** [skbkontur/retail-ui#675]
### Сценарий:
Мобилка, ввод в поле, в котором разрешено вводить только цифры.

### Хотелка:
Хотелось бы показывать циферную клавиатуру при редактировании текста в поле на мобилках, передавая type="number" в input.

### Пути решения:
Принимать и обрабатывать значение "number" для пропса "type".
--- или ---
Создать отдельный компонент NumberInput

### Вещи, над которыми стоит подумать:
Наличие стрелочек в поле справа на десктопных браузерах
Изменение значения по колёсику мыши
Изменение значения стрелками вверх/вниз на клавиатуре
Тип пропса value
Ввод нецелых чисел
Работа(возможные конфликты) с другими пропсами, например mask

**Comment by dzekh** [comment]
Принимать только числа — ок, поможет пользователю не ошибиться, вызовет нужную клавиатуру.
Но вот это, сильно лишнее:
1) Наличие стрелочек в поле справа на десктопных браузерах
2) Изменение значения по колёсику мыши
3) Изменение значения стрелками вверх/вниз на клавиатуре

Особенно глупо все это выглядит при запросе номера телефона или кода ИФНС.

**Comment by denexapp** [comment]
@dzekh В случае номера телефона и других заранее известных больших величин (в моём кейсе тоже) -- да, эти стрелочки/колёсико будет совершенно не к месту. 

Но могут быть ситуации, когда такой ввод полезен. Например, удобно прокрутить от нуля до небольшого значения.
Выдуманный кейс: ввод количества человек в номере отеля.

Также можно покрутить колёсиком, чтобы изменить значение и мгновенно видеть результат какого-нибудь расчёта, основанного на этом значении.
Выдуманный кейс: расчёт цены на продукт в калькуляторе цен в зависимости от лицензии.

Мне кажется, эти штуки должны быть опциональными

**Comment by dzekh** [comment]
Могут быть ситуации, но они ужасно редкие, и решаются простым вводом с клавиатуры. 
И да, это не должно быть частью поля "number", это должны быть отдельные опции, для ввода небольших количеств. 
Если вот прям без них никак — команда продукта может сама реализовать такое поведение, если решит что это нужно. 
В любом случае, нужно дождаться реального запроса на это как минимум от двух команд.

**Comment by 21alexander21** [comment]
Замечу, что на iOS `type="number"` не включает цифровую клавиатуру без атрибута `pattern`

**Comment by 21alexander21** [comment]
Предлагаю убрать ограничения на `type` в инпуте и добавить проп `disableApperance` (по дефолту `true`), чтобы убрать стрелочки. Обо всем остальном должен позаботиться разработчик, использующий библиотеку.

**Comment by denexapp** [comment]
@21alexander21 Мне кажется, не стоит убирать ограничение совсем. Сейчас есть гарантия, что контрол будет работать правильно и по гайдам. Если убрать ограничение, придётся где-то отдельно писать, что разработчик дальше отвечает сам за себя. Кроме того, появятся проблемы:
Что делать с input type range, date, color и прочими радостями?
Какой тип передавать в props value?
И разные конфликты с уже существующими пропсами

**Comment by slawwan** [comment]
поделюсь своим видением.
У нас уже есть CurrencyInput - этот контрол позволяет вводить суммы (они же числа дробные и целые) с форматированием на лету и правильным позиционированием курсора.

Правильное позиционирование курсора с форматированием на лету - не совсем простая задача, эту логику можно вынести в FormatedInput, который будет сделан на основе Input

Затем можно отделить логику ввода чисел в DecimalInput. Сделать его на основе FormattedInput и предоставить возможность задавать разделители между тысячами, количество знаков после запятой, знаковость/беззнаковость и все что еще понадобится.

Затем поле ввода сумм CurrencyInput реализовать на основе DecimalInput, нужно просто задать правила форматирования.

Можно сделать и IntInput на основе DecimalInput, нужно просто задать размер дробной части равный нулю

итого получаем такое:
```
Input <- FormattedInput <- DecimalInput <- CurrencyInput
                                        <- IntInput
```

либо можно такую иерархию попробовать
```
Input <- FormattedInput <- XxxInput <- CurrencyInput
                                    <- DecimalInput
                                    <- IntInput
```
FormatedInput может пригодиться например когда мы захотим в поле ввода номера банковской карты на лету расставить пробелы между четверками цифр, ну можно и другие примеры придумать. В любом случае это достаточно большая и переиспользуемая функциональность, кажется она достойна жить самостоятельно.

**Comment by slawwan** [comment]
Это я вот к чему.  Этими контролами мы обеспечим разработчику возможность работы с числами как с числами, чтобы в `onChange` прилетал `number` не зависимо от пользовательского усройства и клавиатуры. А затем можно решать задачу показа специализированной клавы для каких-то отдельных устройств. причем по-хорошему бы это решать не выставлением атрибута type через пропсы. Я бы сформулировал эту задачу по-другому:

Нужен пропс с помощью которого можно было бы задать тип клавиатуры, а вот как это будет сделано - дело десятое. причем для DecimalInput по умолчанию можно выставить цифровую клаву.

**Comment by denexapp** [comment]
@slawwan Мне нравится предложение выделить FormattedInput. Как я понимаю, FormattedInput будет принимать только цифры? Тогда я бы предложил более простую иерархию:
Input <- NumberInput <- FormattedInput <- CurrencyInput

Ну либо так, если не выделять FormattedInput:
Input <- NumberInput <- CurrencyInput

NumberInput(ну либо назвать DecimalInput) будет иметь пропс, позволяющие ограничить точность в знаках после запятой, принимать пропс value типа number и возвращать тип number в onChange. NumberInput также не будет принимать пропс type

Насчёт последнего предложения. Есть проблема - тип клавиатуры зависит от атрибута type тега input, лежащего внутри компонента Input. Существует атрибут [inputMode](https://caniuse.com/#feat=input-inputmode), но он не поддерживается нигде, кроме последних версий хрома. Поэтому вряд ли получится изменять тип вызываемой клавиатуры независимо от тега input.

**Comment by denexapp** [comment]
В CurrencyInput используется type="text" и value передаётся типом number. Это нужно, чтобы отделять разряды пробелами. В таком случае, не получится вызвать нужную клавиатуру, разве что на Chrome с атрибутом inputMode.

Получается, нет смысла наследовать CurrencyInput от NumberInput, т.к. у них будет разный type(text у CurrencyInput и number у NumberInput) и соответственно разная логика.

@slawwan Если есть потребность в FormattedInput, то я бы создал отдельный issue – похоже, что он никак не будет пересекаться с NumberInput.

Учитывая вышеизложенное, я предлагаю в качестве решения остановится на создании нового контрола NumberInput без изменения уже существующих.

**Comment by dzekh** [comment]
Предлагаю в этой ситуации ограничится тем, что добавить возможность показывать нужную клавиатуру на мобилках, и граничить ввод символов. Ведь основная хотелка бага «показывать циферную клавиатуру при редактировании текста в поле на мобилках». 

Пока наша библиотека официально не поддерживает мобильные устройства, поэтому ставлю задачке минорный лэйбл и не считаем это багом. Как будет возможность — поправим.

**Comment by Ant-VAV** [comment]
Хочу присоединиться к этому багу.
Было бы круто не только number передавать, а вообще все валидные type добавленные в html5.

Было бы круто лежать в направлении семантичности вёрски и удобства для мобильных.

**Comment by Aminopyridin** [comment]
Давно не пользовалась контролами (года два уже).
Пилила только что сайт на чистом html, потом думаю «мне пригодятся модалки, подключу-ка я контуровские контролы, классно будет: контруровские контролы на сайте международного контеста». подключила, стала все переводить на них и с ужасом узнала, что за два года в контролах не появилось возможности указать `type=number` и `type=email` для инпутов — это классная клавиатура для первого случая и встроенная валидация для второго из коробки. 
Пришлось material-ui использовать.

**Comment by dzekh** [comment]
Открывать на мобилках нужные клавиатуры уже можно.
