### ISSUE TITLE
[ComboBox] при потере фокуса в выпадающем списке с одним элементом, не срабатывает onChange со значением данного элемента

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#680]
Привет! Опиши, пожалуйста, подробней проблему, которая возникла:

- retail-ui 0.22.0
- Chrome, Win 10

В сторибуке ComboBox есть такое описание:
![image](https://user-images.githubusercontent.com/22623111/44506648-d149b380-a6c0-11e8-81b8-6ccbaa43a94c.png)

Сейчас все в том же сторибуке такой функционал не работает:
![image](https://user-images.githubusercontent.com/22623111/44506686-f4746300-a6c0-11e8-986e-f46bf034a5d6.png)
![image](https://user-images.githubusercontent.com/22623111/44506696-f9d1ad80-a6c0-11e8-8607-e8b6df87ec5a.png)

Либо не актуальное описание, либо сломался этот функционал.

**Comment by 21alexander21** [comment]
Сломался этот функционал, будем чинить
