### ISSUE TITLE
[CurrencyInput] maxLength ведёт себя неочевидно

### ISSUE THREAD

**Issue by nulladdict** [skbkontur/retail-ui#685]
Привет! Опиши, пожалуйста, подробней проблему, которая возникла:

- библиотека (retail-ui)
- версия 0.22.0;
- maxLength учитывает пробельные символы, используемые для форматирования ввода  
(например, при maxLength={5} можно ввести только 9999 или -9999);

**Comment by 21alexander21** [comment]
@slawwan что-то можешь сказать по этому поводу?
