### ISSUE TITLE
[Tooltip] Отдельно стрелочка отдельно тело

### ISSUE THREAD

**Issue by mshatikhin** [skbkontur/retail-ui#698]
![joxi_screenshot_1535543239915](https://user-images.githubusercontent.com/1788385/44785890-df5d6f80-abab-11e8-8ace-3f5a36e1dfe0.png)

Привет! Опиши, пожалуйста, подробней проблему, которая возникла:

- "react-ui-validations": "0.3.0"
- "@skbkontur/react-ui": "0.22.0"
- Windows,Chrome

Сценарий: рандомно появляется при скроле.

**Comment by 21alexander21** [comment]
Опиши как воспроизвести
