### ISSUE TITLE
[Dropdown] Вид отображения ссылкой

### ISSUE THREAD

**Issue by mshatikhin** [skbkontur/retail-ui#70]
Хочется чтобы дропдаун меню открывалось не кнопкой, а ссылкой.

Вообще было бы замечательно вынести (реализовать) компонент popup, который не будет привязан к кнопке.

Типа такого:

![popup](https://cloud.githubusercontent.com/assets/1788385/22321474/08eb02b8-e3b7-11e6-8d72-981f87fbbb58.jpg)

**Comment by nanot1m** [comment]
@mshatikhin `DropdownMenu` решает эту проблему?

**Comment by mshatikhin** [comment]
@nanot1m да 👍
