### ISSUE TITLE
[Combobox] Фокусируется при изменении props.error с false на true

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#704]
Привет! Опиши, пожалуйста, подробней проблему, которая возникла:

- retail-ui 
- версия 0.22
- браузер, ОС Win10, Chrome
- при каком сценарии;

Заполняются поля в форме массовой операцией, и одно из полей становится с ошибкой и ComboBox сам фокусируется выпадает DropDown. Наверное так быть не должно.

гифка:
![image](http://g.recordit.co/NbFcLyuvQD.gif)

**Comment by wKich** [comment]
Я думаю это дубль #608
