### ISSUE TITLE
[Tooltip] - Тултип заезжает на границы TextArea

### ISSUE THREAD

**Issue by StarLordJ** [skbkontur/retail-ui#721]
![tooltiptop](https://user-images.githubusercontent.com/14982003/45665820-3b247400-bb2c-11e8-8a40-65eddbaab487.png)
![tooltipbottom](https://user-images.githubusercontent.com/14982003/45665821-3bbd0a80-bb2c-11e8-9da1-2554814a4552.png)

Привет! В retail-ui версии 0.20.1 (возможно и раньше, но в версии 0.16.3 всё ещё работало правильно) Tooltip стал заезжать на границы TextArea во всех позициях "top ..." и "bottom ...".
Поглядел в браузерах: Chrome, Edge, IE11 - везде воспроизводится.

**Comment by wKich** [comment]
Есть такое. Кажется можно полечить, если для `span`, в который оборачивается контент тултипа, проставить стиль `display: inline-block`

**Comment by 21alexander21** [comment]
Ситуация такова: `display: inline-block` лечит баг с позиционированием, но ломает относительную ширину у переданного потомка. А т.к. у очень многих пользователей контролы обернуты в `ValidationWrapperV1` (который оборачивает потомка в тултип), это сломало много форм.

Пока фикс откатим, чтобы поискать лучшее решение

**Comment by wKich** [comment]
Пофиксится в #901 при использовании пропса `useWrapper={false}` для тултипа
