### ISSUE TITLE
Не работает в IE11

### ISSUE THREAD

**Issue by MaxGorshkov** [skbkontur/retail-ui#722]
библиотека retail-ui 0.22.0
плоская тема
не открывается в браузере IE 11

Ошибка:
**TypeError: Объект не поддерживает свойство или метод "includes"**
./node_modules/retail-ui/components/ensureOldIEClassName.js
./node_modules/retail-ui/components/ensureOldIEClassName.js:18

Стек:
```
  15 |     classes += ' rt-ie' + ieVerison;
  16 | }
  17 | var ua = window.navigator.userAgent;
> 18 | exports.isIE = isIE = !!ieVerison || ua.includes('MSIE ') || ua.includes('Trident/');
  19 | if (isIE) {
  20 |     classes += ' rt-ie-any';
  21 | }
```

**Comment by wKich** [comment]
Подключи `babel-polyfill`

**Comment by MaxGorshkov** [comment]
спасибо за совет!
помогло
