### ISSUE TITLE
[Textarea] неправильно работает ширина

### ISSUE THREAD

**Issue by 21alexander21** [skbkontur/retail-ui#724]
Проп `width` передается элементу `textarea`, а не обертке (у которой захардкожена ширина в 250px)

**Comment by mifopen** [comment]
Ну фак. Ну сломалось же всё.
http://tech.skbkontur.ru/react-ui/#/Textarea
```let initialState = { value: "" };
<Textarea
  width="100%"
  value={state.value}
  onChange={(_, value) => setState({ value })}
  autoResize
  placeholder="Through faith we can reign in every area of life"
/>;```
например

С Input та же хрень

Плоская схема, если что у нас

**Comment by 21alexander21** [comment]
что именно сломалось?

**Comment by mifopen** [comment]
у тебя работает код выше? если вставить его в 
http://tech.skbkontur.ru/react-ui/#/Textarea

**Comment by mifopen** [comment]
я про 100%

**Comment by 21alexander21** [comment]
да,  `%` не работают уже давно, поправим

**Comment by 21alexander21** [comment]
@mifopen по поводу `Input` заведи пожалуйста отдельное issue

**Comment by mifopen** [comment]
Готово) https://github.com/skbkontur/retail-ui/issues/741

**Comment by 21alexander21** [comment]
По поводу `Textarea` и ширины в `%` - это явно неправильное поведение. Надо подумать как передать ширину в обертку и чтобы при этом компонент правильно вел себя во время ресайза.

**Comment by wKich** [comment]
Забыли для flat темы исправить стили
