### ISSUE TITLE
[Input] Добавить возможность передать в Input перфикс или постфикс.

### ISSUE THREAD

**Issue by vandal-x** [skbkontur/retail-ui#727]
Привет! 
Возникла потребность в том, чтобы в поле ввода была возможность показать, что можно изменять только часть его значения. Поэтому предлагаю добавить, по аналогии со свойствами `leftIcon` и `rightIcon`, свойство которое бы позволяло бы добавить в поле ввода какой-нибудь компонент слева или справа.
![feature](https://user-images.githubusercontent.com/22432062/45747649-ee21ca00-bc1f-11e8-895d-a7cafd48168e.gif)

**Comment by wKich** [comment]
Можно попробовать решить проблему с помощью маски, но к сожалению в библиотеке реализующей работу с масками [https://github.com/sanniassin/react-input-mask/issues/44](нельзя задавать маски с неопределенным кол-вом символов)

В качестве обходного пути можно использовать вот такую маску `ex\ample.com/store/*******************` с нужным кол-вом `*` в конце

**Comment by vandal-x** [comment]
А как быть со стилизацией? Как это выглядит в моих макетах
![example](https://user-images.githubusercontent.com/22432062/45751771-c71dc500-bc2c-11e8-99de-251113bc2324.png)
Маска выглядит немного странно в моем случае: оставляет множество символов "_" если она заполнена не до конца.
![mask_example](https://user-images.githubusercontent.com/22432062/45751832-00eecb80-bc2d-11e8-83bb-6a3cb4377dff.png)

**Comment by wKich** [comment]
Используй `maskChar={null}`, тогда у тебя не будет подчеркиваний

**Comment by dzekh** [comment]
Да, маска выглядит странно. правильней дизэйблить - делой серой ту часть которая не может редактироваться. А в новой маске которую мы делаем возможно все это учесть?

**Comment by wKich** [comment]
Надо учесть этот момент в #579

**Comment by vandal-x** [comment]
В конечном итоге мне не подошел input с маской, из ограничения на использование символов.
В моем случае пользователь может ввести часть url используя такие символы как "_" или "-". Возможно даже путь на кириллице, но это не точно.

**Comment by wKich** [comment]
Кажется что это частный случай маски и наверно стоит действительно сделать возможность передавать префикс
