### ISSUE TITLE
[Button] Баг в кнопке: белая полоса справа

### ISSUE THREAD

**Issue by tsypilov** [skbkontur/retail-ui#728]
Привет!
В версии 0.22.0+, компонент Button, с пропсами use="primary" size="medium" появляется вот такая полоса справа, как на скриншоте. При этом, воспроизводится только в Chrome последней версии (Версия 69.0.3497.100) и не всегда. 
Было бы здорово, если исправите :)

![image](https://user-images.githubusercontent.com/31158839/45753115-2d0c4b80-bc31-11e8-9a3d-cba605ebbc60.png)

**Comment by wKich** [comment]
Похоже на баг хрома. Белая полоска зависит от ширины `viewport` и ширины кнопки.

**Comment by mortifer** [comment]
это бага не только хрома к сожалению

такая же фигня есть в эксплрорере, а хром видимо поменял чуточку рендер, который стал похож на эксплореровский и вот эта хрень вылезла.

**Comment by mortifer** [comment]
и от версии библиотеки это не зваисит - отродясь такое помедение было :)

**Comment by dzekh** [comment]
Может как-то пофиксим все-таки?

**Comment by mortifer** [comment]
> Может как-то пофиксим все-таки?

я нашел способ в принципе

**Comment by mortifer** [comment]
Диме рассказал

**Comment by mortifer** [comment]
после https://github.com/skbkontur/retail-ui/pull/811
проблема не решена в ie и ff

IE
![image](https://user-images.githubusercontent.com/2478874/49136836-a64cac80-f30c-11e8-9576-7ab2bbac99ed.png)

FF
![image](https://user-images.githubusercontent.com/2478874/49136844-b1074180-f30c-11e8-959d-1e4630f4441c.png)

**Comment by dzekh** [comment]
Кажется это уже другая проблема

**Comment by mortifer** [comment]
Корень проблемы тот же на самом деле. Хоть визуально и по-разному пороявляется несколько

**Comment by qwerty2323** [comment]
Проверено в Chrome 78, FF 69, IE 11:
1. Отсутствие полосы белой полосы справа, слева, сверху или снизу.
