### ISSUE TITLE
[Button] Стиль ховера по дефолтной кнопке 

### ISSUE THREAD

**Issue by mshatikhin** [skbkontur/retail-ui#73]
При наведении мыши на серую кнопку она промигивает по центру - выглядит очень странно  (у меня два моника на маке, с одним моником такой фигни нет), все остальные ховеры кнопок работают нормально. 

попробовал поменять градиент (брал последовательно из html color shades) без дерганья начинает работать с цвета #E0E0E0

сейчас у кнопки градиент 
background-image: linear-gradient(-180deg, #FFFFFF, #EBEBEB);

я поменял на (стало норм): 
background-image: linear-gradient(-180deg, #FFFFFF, #E0E0E0);

Раздражает дерганье очень сильно, так как стиль ховера используется не только на кнопке и баг повторяется везде где серый градиент.

Снял это всё на телефон, можете глянуть =) 

https://yadi.sk/i/Wz8JQquh3AxVxv

Если снимать через захват экрана, баг на видео не проявляется.

**Comment by nanot1m** [comment]
Актуальна ли данная проблема?

**Comment by nanot1m** [comment]
@mshatikhin не отвечает

**Comment by mshatikhin** [comment]
@nanot1m это исчезло :)
