### ISSUE TITLE
[TopBar] Съехала стрелка у виджета сервисов

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#734]
После обновления на 0.23.0 заметили, что стрелочка у виджета сервисов съехала вниз на пару пикселей.
Слева — http://tech.skbkontur.ru/react-ui/#/TopBar, справа наложен скриншот из макета с гайдов https://drive.google.com/file/d/0B4LHy-uwPCJxLTdZSk1aeVBybWM/view
![topbarservicestickalignment](https://user-images.githubusercontent.com/9248122/45805543-63e96c80-bcd8-11e8-9726-8777cd13b54a.jpg)
Похоже, это поменялось в https://github.com/skbkontur/retail-ui/commit/2f9495b325d7008bd821d4d9ddaf3fbc128384c5#diff-1605ad4ea57f774bd490720203bcad89

**Comment by molokovev** [comment]
Блин, тут на скриншоте плохо видно, могу скинуть файл, если нужно будет

**Comment by dzekh** [comment]
да, видимо когда отступ убирали #623 съехала стрелка. нужно поправить

**Comment by 21alexander21** [comment]
![image](https://user-images.githubusercontent.com/12668989/45940601-7246c980-bff3-11e8-81f1-e0f39ce2bf9f.png)

в гайдах отступ стрелочки примерно 1.6-1.7 px, в контролах 1px. Стоит ли сделать 2px?

**Comment by wKich** [comment]
Сделаем 2px

**Comment by 21alexander21** [comment]
Пофиксилось в 0690828

**Comment by dzekh** [comment]
А точно пофиксилось?

**Comment by dzekh** [comment]
Эта стрелка бралась из шрифта? как и где проверить?

**Comment by wKich** [comment]
Ну похоже что сейчас корректно рисуется стрелка. Да, бралась из шрифта, можно установить 0.23-ю версию и там посмотреть

На скорую руку сфоткал. Первый с витрины контролов, второй из гайдов
<img width="413" alt="screenshot 2018-10-27 at 13 20 14" src="https://user-images.githubusercontent.com/6397708/47601546-f96cd000-d9eb-11e8-9ff8-7592aa545485.png">
<img width="357" alt="screenshot 2018-10-27 at 13 22 54" src="https://user-images.githubusercontent.com/6397708/47601547-fc67c080-d9eb-11e8-8402-38c0fdaa7fc6.png">

**Comment by dzekh** [comment]
да, вроде ок
