### ISSUE TITLE
[Link]  children wrap

### ISSUE THREAD

**Issue by slawwan** [skbkontur/retail-ui#737]
библиотека retail-ui
сейчас верстка ссылки выглядит так:
```
<a>
    <span>icon-symbol</span>
    child-text
    <child-tag/>
    child-text
    <child-tag/>
</a>
```
чтобы в тесте ну или не в тесте получить текст ссылки нужно каким-то образом исключить символ иконки, если он есть, для этого еще нужно понять, есть ли иконка в ссылке, подробнее о проблеме и решении тут https://github.com/skbkontur/react-ui-testing/pull/26

то что передается в Link в props.children предлагаю обернуть в какой-нибудь тег, чтобы упростить доступ к контенту, к innerText в частности.

```
<a>
    <span>icon-symbol</span>
    <link-internal-wrapper-tag>
        child-text
        <child-tag/>
        child-text
        <child-tag/>
    </link-internal-wrapper-tag>
</a>
```

**Comment by wKich** [comment]
Переезд на svg иконки решит skbkontur/react-ui-testing#26 и никакого врапера делать не нужно будет

**Comment by wKich** [comment]
#718
