### ISSUE TITLE
[Input] Просьба реализовать возможность задавать размеры как у [Button]

### ISSUE THREAD

**Issue by mshatikhin** [skbkontur/retail-ui#74]
Хочется чтобы размер инпута можно было задавать так же как кнопкам.

**Comment by nanot1m** [comment]
Такая возможность есть, надо добавить в документацию

**Comment by nanot1m** [comment]
Она даже задокументирована (:

**Comment by mshatikhin** [comment]
Свойство 

size:enum ('small', 'default', 'large')
DEPRECATED

Не работает

**Comment by nanot1m** [comment]
@mshatikhin сорян, неправильно тебя понял изначально 😊 подумал про свойство width

**Comment by nanot1m** [comment]
https://guides.kontur.ru/controls/input/#25
Начало положено!

**Comment by nanot1m** [comment]
Добавлено в #77

**Comment by mshatikhin** [comment]
@nanot1m спасибо за оперативность! =)
