### ISSUE TITLE
[Input] Не работает width="100%"

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#741]

**Comment by 21alexander21** [comment]
![image](https://user-images.githubusercontent.com/12668989/45955645-e43a0580-c029-11e8-84f5-196a737e26e3.png)

`<Input width="100%" leftIcon={<Icon name="Search" />} />`
Такой код приводит к другому результату? http://tech.skbkontur.ru/react-ui/#/Input

**Comment by halfee** [comment]
В ComboBox тоже не работает.
И есть нюанс. В оба примера добавил width="100%"
http://tech.skbkontur.ru/react-ui/#/ComboBox
![image](https://user-images.githubusercontent.com/1036441/46123003-6d715800-c235-11e8-87d4-3c8aeed53b45.png)

**Comment by wKich** [comment]
Проблема не с Input'ом или ComboBox'ом, а в Tooltip'е, в который оборачивается компонент.

**Comment by halfee** [comment]
Скорее всего проблема именно в компоненте.
Использую react-ui-validations, и сломалась такая конструкция. Раньше работало.
```
<ValidationWrapperV1>
    <ComboBox width={"100%"} />
</ValidationWrapperV1>
```

**Comment by 21alexander21** [comment]
Проблема в тултипе: `ValidationWrapperV1` оборачивает детей в тултип, которой с недавних пор инлайн-блочный (лечили другой баг с позиционированием тултипа). Баг критичный, поправим в самое ближайшее время

**Comment by 21alexander21** [comment]
Починил откатом #721
