### ISSUE TITLE
Новые тайпинги ломают компиляцию в typescript < 3.0 

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#744]
После добавления `defaultProps` в некоторых компонентах разваливается компиляция.
Как я понял, typescript < 3.0 не умеет парсить `defaultProps`, поэтому не понимает, что пропы, указанные в интерфейсе как обязательные, на самом деле не обязательные.
Поэтому после обновления приходится класть локально тайпинги, в которых проп будет помечен как опциональный.
Может, я что-то делаю не так?

**Comment by molokovev** [comment]
Я не уточнил, у нас версия ts 2.9.2.
@wKich, как думаешь, нормально это — требовать обновить ts в проекте, чтобы мочь обновить библиотеку?

**Comment by mshatikhin** [comment]
@molokovev какой смысл не обновляться до ts 3+?

**Comment by molokovev** [comment]
@mshatikhin, да в общем-то смысла никакого нет. Вопрос скорее в том, нормально ли то, что я, захотев обновить библиотеку, должен обновить ts.

**Comment by wKich** [comment]
@molokovev, я не вижу ничего плохого в том что ts был обновлен. Тут скорее всего проблема, что такое обновление произошло неожиданно и без какого-либо анонса для других команд, использующих библиотеку.

В будущем мы будем более внимательно относится к таким правкам и дорабатывать процессы, чтобы не случалось подобных неожиданностей.
