### ISSUE TITLE
[Logotype] Некрасивый :(

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#75]
![7b3ecf837c](https://cloud.githubusercontent.com/assets/9248122/22416151/65f575a8-e6ee-11e6-8cc5-d0a6897ea94a.jpg)
Фиолетовый вариант взят из [гайдов](http://guides.kontur/components/header/), синий — из реальной жизни..))

**Comment by nanot1m** [comment]
относится к #65
