### ISSUE TITLE
Вставка телефона, если юзер пытается вставить больше 10 цифр 

### ISSUE THREAD

**Issue by VeraGlushenkova** [skbkontur/retail-ui#751]
Проблема: пользователи часто копируют откуда-то номера телефонов и вставляют их в поле для телефона.
При этом вставляются только первые 10 символов.
Чаще всего люди копируют полный номер телефона с 8 или +7 и при копировании получают неправильный номер телефона, в котором нужно стереть первую цифру и добавить последнюю. Это очень сильно раздражает.

Можно ли обработать такую ситуацию?
1) пользователь вставляет в поле с телефоном больше чем 10 цифр 
И
2) первые цифры это 7 или 8
то обрезать первую цифру и вставлять со второго символа

**Comment by byTimo** [comment]
Вы можете написать свой `PhoneInput` и там реализовать такую логику. Внутри `PhoneInput`-а будет простой `Input` с маской, а вы сами будете обрезать номер телефона так, как вы хотите и вставлять его в инпут.

**Comment by 21alexander21** [comment]
Будет круто, если вы сделаете свой компонент `PhoneInput` и сделаете pr.
