### ISSUE TITLE
[DatePicker] Обрезается правая часть выпадашки календаря

### ISSUE THREAD

**Issue by aagordienko** [skbkontur/retail-ui#752]
- "@skbkontur/react-ui": "^0.15.0";
- FF и Хром свежие.

Выпадашка всегда рисуется одной ширины, независимо от ширины инпута или оберток над инпутом. Тестировал без лишних стилевых оберток, только 1-2 родительских дива.

Могу продемонстрировать баг на тестовой тачке.

![default](https://user-images.githubusercontent.com/30799122/46220289-54aa9480-c352-11e8-8ca7-e822b8b00c78.png)

**Comment by 21alexander21** [comment]
@aagordienko в актуальной версии библиотеки тоже воспроизводится?

**Comment by aagordienko** [comment]
> 
> 
> @aagordienko в актуальной версии библиотеки тоже воспроизводится?

Да, проверил на ^0.23.3

**Comment by 21alexander21** [comment]
Тогда можно пример кода или инструкцию как повторить?

**Comment by 21alexander21** [comment]
#762
