### ISSUE TITLE
[retail-ui] Структурировать variables.less

### ISSUE THREAD

**Issue by bdskrur** [skbkontur/retail-ui#758]
Существует проблема дублирования переменных css стилей в variables.less, по причине отсутствия строгой структуры использования цветов в компонентах. Решение это проблемы значительно облегчит возможность кастомизации компонентов.

**Comment by dzekh** [comment]
Сейчас, после добавления кастомизации как-то лучше стало? Если есть конкретные предложения что улучшить — опиши.

**Comment by bdskrur** [comment]
кажется сейчас все как надо
