### ISSUE TITLE
[retail-ui] Возможность горячей замены переменных variables.less

### ISSUE THREAD

**Issue by bdskrur** [skbkontur/retail-ui#759]
Хочется иметь возможность предоставлять пользователям как минимум 2 варианта цветовой схемы (темную и светлую). Для этого необходимо реализовать эту возможность в retail-ui.

**Comment by wKich** [comment]
Переключение цветовой схемы на лету появится только после полного перехода на css-in-js.

В данный момент можно настроить в webpack сборку css бандлов для каждой цветовой схемы. Минусы такого решения, увеличение времени сборки кратное кол-ву цветовых схем (можно немного оптимизировать) и переключение только с перезагрузкой страницы. Если такой вариант в качестве временного решения тебя устроит, я могу помочь.

**Comment by wKich** [comment]
@bdskrur Тебя устроит вариант переключения с перезагрузкой страницы?

**Comment by bdskrur** [comment]
Да, учитывая что сейчас этой возможности вообще нет, то конечно

**Comment by wKich** [comment]
Решили на очной встрече
