### ISSUE TITLE
[DatePicker] Указать box-sizing

### ISSUE THREAD

**Issue by 21alexander21** [skbkontur/retail-ui#762]

**Comment by ArkadiyVoronov** [comment]
@21alexander21 Привет!
Можно я попробую решить эту проблему?

**Comment by 21alexander21** [comment]
Конечно)

**Comment by wKich** [comment]
#525

**Comment by ArkadiyVoronov** [comment]
@wKich > #525 Спасибо.
Нам нужно вот этот код обернуть`<DatePickerOld
  value={state.date}
  onChange={(_, date) => setState({ date })}
  onUnexpectedInput={x => (x.length ? x : null)}
/>`
https://github.com/skbkontur/retail-ui/issues/525#issuecomment-387356725
вот этим:
`.react-ui-portal {
  box-sizing: initial;
}`

**Comment by ArkadiyVoronov** [comment]
В https://github.com/skbkontur/retail-ui/issues/525#issuecomment-387356725
Говорится о 

> порталах

, на которые нужно применить `.react-ui-portal {
  box-sizing: initial;
}`
Я не нашёл в документации о них.

**Comment by wKich** [comment]
Есть обращения с этой проблемой, передвинул в `To do`
