### ISSUE TITLE
[Group] Добавить пример в сторибук и тесты

### ISSUE THREAD

**Issue by 21alexander21** [skbkontur/retail-ui#766]
- У компонента `Group` нет ни одной сториз и ни одного теста, надо исправить
- Нужно верунуть повышенный `zIndex` компоненту `Input` при фокусе, чтобы он адекватно выглядел в группе 

![image](https://user-images.githubusercontent.com/12668989/46343988-0e5a7b80-c659-11e8-8272-000fabac2008.png)

**Comment by minajevs** [comment]
In progress
