### ISSUE TITLE
[ComboBox] Упросить работу с totalCount

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#789]
Сейчас функция `getItems` может возвращать только промис резолвящийся в массив значений для отображения. `totalCount` приходится передавать отдельным пропсом, что выглядит не очень удобно. Будет лучше есть функция `getItems` сможет принимать промис резолвящийся в объект вида:
```ts
{
  items: Array<T>,
  totalCount: number,
}
```

**Comment by dzekh** [comment]
Нужно разобраться насколько важно и сложно

**Comment by wKich** [comment]
Точно не сильно важно, но заметно улучшает DX
