### ISSUE TITLE
[Radio] [Checkbox] [Toggle] во флет версии в фокусе нет белого отступа у обводки фокуса

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#790]
Нужно сделать отступ в 1px между заливкой и обводкой фокуса. 
Скорее всего его нет и у валидации и у ворнинга. Нужно сделать [как на картинке](https://www.figma.com/file/HK4BZYgmQAkR8NbOr3cAMoNK/Focus-on-highlited-components?node-id=2%3A30)
<img width="440" alt="Frame@2x" src="https://user-images.githubusercontent.com/26383080/54826576-e11a8c00-4cd1-11e9-8072-00edd2bb594d.png">

2x
![Frame](https://user-images.githubusercontent.com/26383080/54826577-e11a8c00-4cd1-11e9-9bf8-2b9a26fdeaec.png)

**Comment by zhzz** [comment]
Стоит подождать скриншотов для плоской темы из #985.

**Comment by lenoraart** [comment]
Широкая обводка вокруг checked button.
http://localhost:6060/iframe.html?selectedKind=Button&selectedStory=table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
![image](https://user-images.githubusercontent.com/37067213/54817455-d1427e00-4cb8-11e9-903c-345ff0fd9a4b.png)

**Comment by lenoraart** [comment]
"Съехал" белый бордер в IE.
![image](https://user-images.githubusercontent.com/37067213/54818821-f8e71580-4cbb-11e9-99e4-3ae961e754db.png)

**Comment by dzekh** [comment]
Я обновил примеры вверху — на всех контролах белая обводка должна торчать внутрь компонента, а синяя - 2px наружу. Сейчас это так и есть.

Кажется, что можно даже не делать исключения а применять это ко всем компонентам, в том числе и белым или без заливки.  

Еще обнаружил что нет внутренней белой обводки у тогла в фокусе, ни в плоской ни в дефолтной теме. Нужно добавить.

**Comment by lenoraart** [comment]
Толщина обводки вокруг checked button исправлена:
![image](https://user-images.githubusercontent.com/37067213/54905593-3ab5cd00-4f03-11e9-9a88-0a03c65705cb.png)
