### ISSUE TITLE
[Logotype] разное положение иконки облачка в разных браузерах

### ISSUE THREAD

**Issue by nanot1m** [skbkontur/retail-ui#8]
Есть проблема, что логотип по разному отображается в разных браузерах.
Может кто-нибудь помочь выровнять облачко?
http://tech.skbkontur.ru/react-ui/#/components/Logotype

Так выглядит логотип в IE11
<img width="361" alt="2016-10-24 22 05 27" src="https://cloud.githubusercontent.com/assets/9278185/19655742/8f6b3a9e-9a36-11e6-865a-d74f9afb1f66.png">

А так в Chrome
<img width="361" alt="2016-10-24 22 05 42" src="https://cloud.githubusercontent.com/assets/9278185/19655759/a24d1718-9a36-11e6-8045-69fee01b5f34.png">

**Comment by mortifer** [comment]
я тут задумался - а никого не напрягает, что шрифты по разному рендерятся? :)

**Comment by mortifer** [comment]
за что бороться то на самом деле?
облачко на 99% в компании со шрифтом идёт - это раз. и выглядеть будет по разному.
для разных размеров шрифта оно разное - это два... 
это как у иконок шрифтовых пытаться попасть в пиксели и в 14 и в 15 размере шрифта.
я просто вспомнил как в прошлый раз там подгонял всякие магические цифири - ужаснулся

**Comment by mortifer** [comment]
мож обсудим?

**Comment by mortifer** [comment]
если проблема только в том, что облачно рендерится на пиксель ниже, а не в размытии разном, то решается это через vertical-align: -1px вместо -2px - для ie 

и в FF подозреваю что так же надо сделать
т.к. они одинаково рендерят такие штуки
