### ISSUE TITLE
[Toast] Тост не всегда поверх всех элементов

### ISSUE THREAD

**Issue by michaeluskov** [skbkontur/retail-ui#80]
Retail-UI v.0.6.6. 
Попытка вставить тост на главную Экстерна.

![2017-02-03 16_50_32-](https://cloud.githubusercontent.com/assets/4506837/22590456/1d08642c-ea31-11e6-8c0d-356d9277400d.png)

**Comment by nanot1m** [comment]
Поправлено в 0c95b99
