### ISSUE TITLE
[button] Полоса с правой стороны

### ISSUE THREAD

**Issue by halfee** [skbkontur/retail-ui#805]
Привет! 
- retail-ui@0.25.0

У зеленой кнопки в хроме полоса с правой стороны.
Воспроизводится на [tech.skbkontur](http://tech.skbkontur.ru/react-ui/#/Button).

Chrome 69
![image](https://user-images.githubusercontent.com/1036441/46999726-f0544700-d13f-11e8-945b-b4c53ec2b256.png)

Firefox 63
![image](https://user-images.githubusercontent.com/1036441/46999819-2b567a80-d140-11e8-84c0-c3f0c42c9342.png)

**Comment by 21alexander21** [comment]
Duplicate #728
