### ISSUE TITLE
[Button] Разная толщина шрифта в Firefox и Chrome (macOS) 

### ISSUE THREAD

**Issue by mshatikhin** [skbkontur/retail-ui#81]
У меня в системе установлен шрифт SegoeUI,

В хроме кнопки выглядят нормально

![2017-02-06_11-06-38 2](https://cloud.githubusercontent.com/assets/1788385/22636450/0f528a00-ec5d-11e6-9d93-80688dbd8956.png)

а firefox жирные (и некоторые заголовки тоже отличаются)

![2017-02-06_11-07-34 2](https://cloud.githubusercontent.com/assets/1788385/22636451/0f54e1d8-ec5d-11e6-8e1b-3d17d03f13c0.png)

может быть дописать font-weight в стили кнопок?

**Comment by nanot1m** [comment]
Тут скорее сам сервис должен задать дефолтный шрифт

**Comment by nanot1m** [comment]
@mshatikhin актуальна проблема?

**Comment by mshatikhin** [comment]
@nanot1m починено)
