### ISSUE TITLE
[Autocomplete] Выделить инпут при фокусе

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#814]
Есть сценарий когда нужно выделить текст в инпуте автокомплита при получении фокуса, чтобы его удалить одним нажатием на клавиатуре или заменить новым значением просто начав вводить новое значение.

Было бы здорово написать метод в автокомплите setSelectionRange, который бы вызывал одноименный метод в инпуте. Или добавить props "какое-то имя", чтобы включать или выключать автовыделение при фокусе.

PS у ComboBox такое поведение из коробки, но он нам не подходит так как нам нужна маска ввода, ну и в целом идейно он там не нужен.

**Comment by wKich** [comment]
Недавно буквально добавили пропс `selectAllOnFocus` #783. В доку забыли добавить описание

**Comment by slaeme** [comment]
Отлично, спасибо!
