### ISSUE TITLE
[Tooltip] Сделать возможность закрытия тултипа даже при mouse over на нем

### ISSUE THREAD

**Issue by paatrofimov** [skbkontur/retail-ui#818]
В версии либы 0.7.4 тултип с настройкой hover мог закрываться даже, когда курсор мыши наводился на него. Это поведение в какой-то версии ушло. Сейчас, чтоб он закрылся, мышь надо навести на любую другую зону, кроме тултипа и рендерящихся в нем children.

Проблема в том, что тултип перекрывает другие инпуты. Раньше, можно было с любого инпута вести мышь в любом направлении и даже если курсор проходил через тултип, он тут же закрывался.

Есть пример инпута, окруженного другими инпутами. Пользователь может отредактировать центральный и захотеть отредактировать следующий в любом направлении. Но открытый тултип лишит его этой возможности и заставит описать дугу мышью, чтоб добраться, например, до верхнего инпута на скрине. Это очень неудобно для пользователя.

Можно ли добавить возможность кастомизации, когда тултип закрывать? Такая функциональность когда-то была дефолтом. В гайдах ничего противоречащего такой функциональности не увидел. Очевидно, там не описан такой случай - когда тултип в любой позиции перекроет что-то важное.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/17619635/47176146-48e93700-d32e-11e8-81ce-c53a961f8a51.gif)

**Comment by wKich** [comment]
Если не ошибаюсь, такое поведение необходимо было для тех случаев, когда в тултипе могли находится интерактивные элементы, например ссылки на норматив. По поводу кастомизации, вроде ничего не должно мешать её сделать, но я бы узнал мнение @dzekh

**Comment by dzekh** [comment]
Согласен, можно сделать кастомизацию, добавить параметр который бы отключал такое поведение, но по умолчанию оставить то поведение что сейчас — если курсор проходит через тултип, он не закрывается. У такого тултипа не должно быть крестика закрытия. Если в тултип добавлен крестик — переопределять  поведение по умолчанию нельзя.

При этом хорошо было бы добиться того, чтоб не срабатывало наведение на элементы находящиеся под  тултипом. В примере, когда открываться еще один тултип а потом исчезает — довольно глючно выглядит.
