### ISSUE TITLE
[Icon] Размытые иконки

### ISSUE THREAD

**Issue by molokovev** [skbkontur/retail-ui#83]
Иконки размываются в IE10 или если в любом браузере открыть инструменты разработчика.
Вот, например, скриншоты с одной и той же страницы в хроме на винде:
![image](https://cloud.githubusercontent.com/assets/9248122/22644002/a5f93092-ec82-11e6-9c43-e5ef26a227f5.png) ![image](https://cloud.githubusercontent.com/assets/9248122/22644013/b22b5e58-ec82-11e6-8f6c-3b9aba5974e3.png)

**Comment by pikhnova** [comment]
То же самое происходит если уменьшить размер окна (во всех браузерах).
![default](https://cloud.githubusercontent.com/assets/25151439/25484756/b2c6274a-2b74-11e7-8fa3-26fa0c395a88.gif)

**Comment by dzekh** [comment]
В коде на гайдах есть такие строчки, может они помогут:
        //Note всегда четкие иконки
        $(window).resize(function () {
            $iconsBlock.width('100%');
            $iconsBlock.width((Math.round($iconsBlock.width() / 4)) * 4);
        });
А то что они будут плыть при зуме и если им поставить размер не 14px — неизбежно.

**Comment by mortifer** [comment]
Это никак не полечить кроме как избавлением от субпиксельных координат контейнеров в которых располагаются иконки. Т.е. по факту проблема не в иконках.
