### ISSUE TITLE
При управлении с клавиатуры в выпадающем списке не видно последний комментарий

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#860]
В выпадающем списке может быть в самом низу коммент типа "показано 10 элементов из 100, уточните поиск, чтобы увидеть остальные"
Но если эти 10 элементов уже со скроллом в выпадающем списке, то коммент внизу виден только при прокрутке скролла колёсиком мыши.
Если пользователь использует клавиатуру, то подсветка пунктов меню доходит до последнего пункта и останавливается, не доскроллив до текста коммента — его просто не видно
Нужно придумать и сделать, так чтобы последний тык стрелкой показывал и последний пункт меню и коммент. 

Вот видео наглядное, в нём сначала скроллят мышью, а потом - стрелками: https://yadi.sk/i/-SepEFUHWbsljg

**Comment by dzekh** [comment]
> Можно попробовать в конец добавить элемент с нулевой высотой

Это команды сами должны сделать? 
А мы можем сделаем так, чтоб им не пришлось об этом думать? Если есть в конце какой-то текст, то мы мотаем до него с клавиатуры?

**Comment by dzekh** [comment]
И что значит, как мы это решим?

**Comment by wKich** [comment]
![screen recording 2018-11-01 at 11 23 24_24](https://user-images.githubusercontent.com/6397708/47836140-ddd93f00-ddc8-11e8-82d5-5bd310fcaaa9.gif)

Сделал очень по тупому, вставил в конец пустой `<MenuItem />`. Если делать правильно, то надо чуть-чуть поправить код, но кажется что это не сложная задача.

**Comment by dzekh** [comment]
когда выкатим?
