### ISSUE TITLE
[Popup] не используется флаг disableAnimations

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#863]
Флаг `disableAnimations` должен давать возможность отключать/включать анимацию появления/исчезновения `Popup`, но фактически сейчас флаг ни на что не влияет.

**Comment by paatrofimov** [comment]
В тултипе в handleMouseLeave есть таймаут в 100 мсек перед закрытием. Судя по истории, когда флаг disableAnimations  работал, этот таймаут не убирался. Считается, что этот таймаут не имеет отношения к анимации? Когда-то, видимо, этого таймаута не было и при onhover off с тултипа он сразу исчезал. И это было (для нас) хорошо. Сейчас он ждет 100 мсек перед исчезанием. Можно сделать, чтоб disableAnimations выключал этот таймаут в том числе?

**Comment by 21alexander21** [comment]
Если убрать таймаут и вести курсорам по нескольким элементам, завернутым в тултип, эти тултипы будут моргать. Кажется правильнее дать возможность задавать этот таймаут, а по-дефолту оставить 100мс
