### ISSUE TITLE
[Modal] При открытии нескольких Modal-ов контент страницы движется влево

### ISSUE THREAD

**Issue by roman-g** [skbkontur/retail-ui#866]
retail-ui 0.26.3

Сценарий:
1. На странице есть вертикальный скролл
2. Открываем Modal - вертикальный скролл пропадает
3. Открываем ещё один Modal - контент страницы движется влево на 15 px

![2018-10-29_17-23-36](https://user-images.githubusercontent.com/13969526/47649763-0fbb8d00-dba0-11e8-85c8-198a3e7636b5.gif)

**Comment by roman-g** [comment]
Возможно, тут была похожая проблема: https://github.com/skbkontur/retail-ui/issues/571

**Comment by wKich** [comment]
Да, есть такое. В ИЕ11 воспроизводится. Будем чинить
