### ISSUE TITLE
[Tests] Распараллелить запуск тестов из react-ui-testing

### ISSUE THREAD

**Issue by vkochev** [skbkontur/retail-ui#872]
- react-ui-testing@master

После принятия пулл-реквеста https://github.com/skbkontur/retail-ui/pull/858 тесты из react-ui-testing будут запускаться на 2 версиях реакта и текущей (локальной) версии контролов (https://github.com/skbkontur/retail-ui/blob/install-current-retail/packages/react-ui-testing/TestPages/versions.js#L5-L22).

Сейчас тесты идут ~40 минут. Это уже долго.

1. При добавлении еще одной версии реакта в тесты, они будут проходить в 1.5 раза дольше. Это превысит ограничение тревиса на 50 минут за билд (https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts). Сборка будет фейлиться.
2. Тесты должны осуществлять и свою изначальную функцию - тестирование библиотеки react-ui-testing на разнообразных парах версий реакта и контролов. Проблема упирается в п.1.

Предлагаю на каждую пару версий тесты запускать параллельно.

- Про туннель:  
Для каждого билда нужно поднимать один экземпляр туннеля:
https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Best+Practices#SauceConnectBestPractices-UseaSingleSauceConnectTunnelorPoolforEachTestSuiteorBuild
Саус предлагает использовать пулл туннелей, если мы запускаем 200 или более параллельных задач в туннеле. https://wiki.saucelabs.com/display/DOCS/High+Availability+Sauce+Connect+Proxy+Setup#HighAvailabilitySauceConnectProxySetup-TheSituation
Мы такой границы не достигли, поэтому можно не делать пулл туннелей.

- Про браузеры:
Сейчас в саусе ограничение - 5 браузеров одновременно. Это существенная проблема, так как браузеры используются и для скриншотных тестов в retail-ui.

**Comment by wKich** [comment]
Закрываю из-за неактуальности. После переезда на TeamCity и инфраструктуру КЭвеба #985 тесты стали проходить, без распараллеливания всего за ~13 минут.
