### ISSUE TITLE
[Tooltip]  "Съезжает" тултип при клике в поле "Промокод"

### ISSUE THREAD

**Issue by lenoraart** [skbkontur/retail-ui#882]
- retail-ui;
- Chrome ver. 70.0.3538.77, Win 10 Pro;

1.Перейти по ссылке https://auth4.dev.kontur/registration?customize=testPromo;
2.Заполнить поля "Почта" и "Пароль";
3.В поле "Промокод" ввести "ewqeqew";
4.Нажать "Зарегистрироваться";
5.Кликнуть в поле "Промокод", а потом снова по "Зарегистрироваться".
![image](https://user-images.githubusercontent.com/37067213/48050806-e1076d00-e1c4-11e8-8b4b-485d701e4a5c.png)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37067213/48050886-32176100-e1c5-11e8-86e1-9174343dbef9.gif)

**Comment by zhzz** [comment]
@lenoraart можешь показать код формы? Не получается воспроизвести.

**Comment by zhzz** [comment]
Исправлено начиная с версии **0.19.0**.
