### ISSUE TITLE
[Tooltip] Закрывается при клике на его содержимом

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#883]
По гайдам так нельзя. Например, там могут быть ссылки внутри

**Comment by mifopen** [comment]
https://guides.kontur.ru/controls/tooltip/#06

**Comment by wKich** [comment]
Можешь привести пример? На [витрине](http://tech.skbkontur.ru/react-ui/#/Tooltip) кликаю в содержимое тултипа, ничего не происходит, в том числе если в тултипе есть ссылка

**Comment by mifopen** [comment]
Хм. Действительно не могу повторить. Вроде стабильно закрывался. ещё понаблюдаю, спасибо
