### ISSUE TITLE
[ComboBox] Нужен onKeyUp на инпуте, который внутри

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#885]

**Comment by wKich** [comment]
Можно узнать для чего?

**Comment by mifopen** [comment]
Ну потенциально для чего угодно. Конкретно сейчас чтобы навешать на него горячую клавишу

**Comment by mifopen** [comment]
Это правда фича, которая не должна быть доступна клиентам библиотеки и её нужно обсуждать? Вроде если я из-за неё сломаю какой-то сценарий гайдов это либо моя проблема, либо проблема гайдов.

**Comment by 21alexander21** [comment]
> Это правда фича, которая не должна быть доступна клиентам библиотеки и её нужно обсуждать? Вроде если я из-за неё сломаю какой-то сценарий гайдов это либо моя проблема, либо проблема гайдов.

Обсуждать надо список пропсов, которые будут попадать во внутренний инпут. Прокидывать только один `onKeyUp` - слишком специфичная штука

**Comment by mifopen** [comment]
ну да, я к этому и вёл. Может стоит рассмотреть comboBox как инпут, и сделать для него соответствующие пропсы? Ведь он почти инпут)

**Comment by wKich** [comment]
Можно подумать над этим, чтобы прокидывать часть пропсов в инпут, но для этого надо сделать, чтобы инпут всегда рисовался. И меня смущает что в таком случае, onChange на комбобокс, это будет не onChange инпута, и как результат запутанная документация. Сейчас ради одного `onKeyUp` делать этого не хочется.

Оберни `ComboBox` в div или span и навесь туда `onKeyUp`
