### ISSUE TITLE
[Tooltip] Много раз ренедрится при показе и скрытии

### ISSUE THREAD

**Issue by Mmvas** [skbkontur/retail-ui#899]
При показе tooltip функция, которая передается в props.render вызывается 2 раза при показе tooltip и при закрытии tooltip 
Такое поведение заметили в версии 0.20.1, точно нет в версии 0.16.3
Воспроизводится и на витрине https://tech.skbkontur.ru/react-ui/#/Tooltip

**Comment by 21alexander21** [comment]
Это большая проблема? при `trigger === 'hover'`, рендер вызывается на каждый `mousemove`.
