### ISSUE TITLE
[Fias] Доработки

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#905]
Продолжаем работу над контролом **Fias**. Черновик гайда на [google docs](https://docs.google.com/document/d/1HFXspT239SSyPOKqbvW66Gh2Gi32gPbZrJTcPPElBVk).
Как делают другие можно посмотреть [здесь](https://dadata.ru/suggestions/#address) и [здесь](https://fias.nalog.ru/SearchPage.aspx). Плюс, еще один полезный [сервис](https://xn--80ap2aj.xn--80asehdb/) для изучения базы адресов.

Доработки по гайду:
- [ ] Настроить подсказки в выпадашках (не предлагать поиск, если он не включен; сделать их отключаемыми;)
- [ ] Опциональные, редактируемые, валидируемые доп. поля (_Индекс_, ОКАТО, ОКТМО, код ФИАС)
- [ ] Значки вопросов и Tooltip'ы с подсказками на них 
- [ ] [?] Обработка городов фед. значения в обоих полях (_Регион_ и _Город_)
- [x] Выбор страны и Textarea для иностранных адресов
- [ ] [?] Сортировка подсказок по гайду [backend]
- [ ] Обработка устаревших адресов
- [ ] Поиск по типу региона

Доработки по ревью:
- [ ] Тесты
- [ ] [FiasComboBox] pluralize в renderTotalCount
- [x] Сделать функцию renderRow(label, field)
- [ ] Подумать над сокращением кода в обработчиках ответов FiasAPI.

Доработки на основе обратной связи:
- [x] Выбор полей для отображения
- [x] Верификация домов
- [ ] Улучшить взаимодействие с полем поиска #1026 
- [ ] Увеличить лимит результатов поиска домов (https://github.com/skbkontur/retail-ui/issues/905#issuecomment-528545562)

Известные баги и улучшения:
- [x] [FiasComboBox] Подсветка искомой строки не обновляется после выбора элемента
- [x] [FiasComboBox] После фокуса на поле с ошибкой нужно открывать список, если есть варианты 

Вопросы к backend'у:
- **Критично**! Поиск по всем родителям работает только на уровне Street. (Нельзя найти город в выбранном регионе не выбрав район). [`GET /v1/addresses?directParent=false`](https://wiki.skbkontur.ru/pages/viewpage.action?pageId=192906330) [[issue](https://yt.skbkontur.ru/issue/PS-1401)]
- Верификация Settlement и PlanningStructure проходит для некоторых одно-буквенных имен (включается поиск и подстановка вариантов)[[issue](https://yt.skbkontur.ru/issue/PS-1658)] 
- Не возвращается кол-во найденных результатов.
- Сортировка результатов не полностью соответствует гайдам.
- Верификация Stead и Room не работает (намеренно, из-за неполноты данных ФИАС). Отключено на клиенте.
- Валидация домов не распознает поле "estateStatus", соответственно не различает дома и владения (Екатеринбург, ул. Абрикосовая дом/владение 10).

Возможные улучшения:
- Возможно, стоит объединить _Город_ и _Населенный пункт_? 
- Обработка неверной раскладки при вводе: "Vjcrdf" -> "Москва".
- [ComboBox] Сохранять фокус после выбора значения
- Возможность вместо ссылки отрендерить любой контрол через `props.children`

**Comment by zhzz** [comment]
Коллекция тестовых адресов:

- Екатеринбург, улица Абрикосовая, дом 10. 
(невозможно ввести "владение 10" из-за валидации)

- Кемеровская область, город Мыски, квартал 4-ый, дом 10.
(дом без улицы, но с планировочной структурой)

- Севастополь, село Поворотное, 10.
(земельный участок, без улицы)

- Севастополь, село Поворотное, дом 32.
(дом без улицы)

**Comment by denexapp** [comment]
В Fias не можем ввести адрес: город Санкт-Петербург, ул. Бухарестская, литера К. Решается увеличением limit до {30}, но кажется это не ок.

**Comment by zhzz** [comment]
> В Fias не можем ввести адрес: город Санкт-Петербург, ул. Бухарестская, литера К. Решается увеличением limit до {30}, но кажется это не ок.

Видимо, есть смысл увеличить дефолтный лимит только для домов.

**Comment by denexapp** [comment]
У нас часто путаются пользователи при вводе адресов с городами федерального значения -- они вводят их в поле "город", и город не находится.

Вижу, подзадача с обработкой таких случаев есть в списке, но под вопросом. Нашим пользователям её решение точно принесёт пользу, нам бы хотелось, чтобы вы взяли эту задачу 🙂

**Comment by zhzz** [comment]
@denexapp посмотрим, что можно сделать

**Comment by rustho** [comment]
Перенесли в react-ui-addons
https://git.skbkontur.ru/ui/ui-parking/-/issues/25
