### ISSUE TITLE
[ComboBox] В режиме автокомплита при фокусе сбрасывается введенное значение

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#908]
Если в `ComboBox` с `autocomplete={true}` ввести значение не из справочника, убрать и снова сделать фокус, введенное значение будет сброшено на значение из пропа `value`.

Необходимо чтобы при фокусе значение не сбрасывалось.

**Comment by zhzz** [comment]
Видимо я сломал в #875. Исправлю.
