### ISSUE TITLE
[Tooltip] Добавить возможность программного открытия/закрытия

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#914]
- [ ] Добавить для `props.trigger` состояние `manual`
- [ ] Добавить публичные методы для открытия/закрытия тултипа
- [ ] Публичные методы должны кидать ошибку, будучи вызванными если `props.trigger` не `manual` или не `click`
- [ ] Вместо использования `popupProps.opened` устанавливать `state.opened` при изменении `props.trigger`

**Comment by YakOFF19** [comment]
Стоит или нет в таком случае на тултипе показывать closeButton?

**Comment by wKich** [comment]
Думаю лишним не будет.

**Comment by zhzz** [comment]
@wKich а можешь припомнить для какого сценария это понадобилось? И почему в режиме `click` тоже нужно дать управлять вручную?

**Comment by wKich** [comment]
Хорошие вопросы. Почти 2 года прошло, я не помню :)

**Comment by zhzz** [comment]
Тогда, видимо, не стоило пока брать в работу. Четкого понимания нет, зачем это нужно.

Может прикрыть до выяснения? Если вдруг всплывет, то PR уже есть)

**Comment by YakOFF19** [comment]
В принципе, при желании можно управлять через триггеры opened и closed.

**Comment by lossir** [comment]
Да, давайте закроем) Странно, что мы этого не сделали весной, когда перебирали все ишью

**Comment by dzekh** [comment]
@wKich может это кто-то в чатике или лично просил? Может в чатике спросить?

**Comment by wKich** [comment]
![image](https://user-images.githubusercontent.com/6397708/92351431-26649080-f0f5-11ea-9bca-dcc597252c73.png)

https://t.me/c/1105868284/14288 Нашел во фронтовом чатике, изначально в нем не смотрел

**Comment by zhzz** [comment]
Окей, вопрос больше был про режим `click`, чем он такой особенный. Режим `manual`, сам по себе, действительно не помешал бы. 

А вот публичный метод закрытия не стоит ли включить и в остальных режимах тоже (кроме `opened` и `closed`)? Это может пригодиться, например, для закрытия тултипа по клику внутри него или при скролле страницы.

Может, пусть открытие работает только в `manual`, а закрытие во всех, кроме `opened` и `closed`?

**Comment by zhzz** [comment]
Или открытие тоже разрешить во всех режимах, кроме opened/closed. Есть ли смысл ограничивать?

**Comment by wKich** [comment]
Я за все режимы кроме opened/closed.
