### ISSUE TITLE
[retail-ui] warnings в компонентах

### ISSUE THREAD

**Issue by 21alexander21** [skbkontur/retail-ui#915]
Компоненты генерят много сообщений в консоль - это не круто и, например, затрудняет просмотр логов jest'а. Надо пройтись и почистить.

**Comment by wKich** [comment]
`Link` - Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:".
