### ISSUE TITLE
[Menu] Исправить наименование приватных полей

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#926]
Нужно переименовать приватные поля у компонента `Menu` убрав подчеркивание в начале имени.

**Comment by zhzz** [comment]
Все не устаревшие компоненты с подчеркиваниями:

Button, Checkbox, DatePicker, DateSelect, Dropdown, Gapped, IgnoreLayerClick, Kebab, Link, Logotype, Menu, PasswordInput, Popup, Radio, RadioGroup, RenderContainer, ScrollContainer, Select, Spinner, Sticky, Switcher, Tabs, Toast, TopBar.

Как с остальными?

**Comment by 21alexander21** [comment]
> Все не устаревшие компоненты с подчеркиваниями:
> 
> Button, Checkbox, DatePicker, DateSelect, Dropdown, Gapped, IgnoreLayerClick, Kebab, Link, Logotype, Menu, PasswordInput, Popup, Radio, RadioGroup, RenderContainer, ScrollContainer, Select, Spinner, Sticky, Switcher, Tabs, Toast, TopBar.
> 
> Как с остальными?

Надо все переименовывать потихоньку. Можно это приурочить к задаче, связанной с компонентом.  Только делать надо отдельным коммитом.
