### ISSUE TITLE
[Tooltip] Приподнять над инпутом

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#928]
По гайдам
https://guides.kontur.ru/principles/validation/#22
он чуть выше инпута, чем реализован

**Comment by 21alexander21** [comment]
На сколько выше?

**Comment by dzekh** [comment]
В гайдах четко не определено на каком расстоянии от элементов должен появляться тултип. В разных гайдах по разному, и я бы не назвал ни одно решение осознанным. Пока ошибки в библиотеке нет, возможно ошибка в гайдах. Я когда договорюсь с дизайнерами — уточню задачу, пока ставлю лэйбл «wait design».

**Comment by dzekh** [comment]
Добавил в гайды инфу по тултипу и его отступам: https://guides.kontur.ru/controls/tooltip/#Razmer_i_raspolozhenie

В библиотеке есть проблема с тем, что тултип не меняет своего положения с изменением размера поля или кнопки: 
![img](https://user-images.githubusercontent.com/26383080/51375474-c720c980-1b27-11e9-87f2-136e9a606bea.png)

Чем больше высота поля или кнопки, тем глубже тултип заезжает внутрь. 
Нужно сделать так чтоб указатель тултипа был всегда на расстоянии 2px от границ объекта.
Если смотреть на странице с примерами тултипа, от дива он на расстоянии 7px. Это тоже нужно исправить на 2. Если он открывается справа или слева от контролов или кнопок — отступ тоже 7px, который нужно исправить на 2.

**Comment by wKich** [comment]
Почему так происходит описано тут #721. Тултип оборачивает компонент в `span`, высота которого зависит от `line-height`. У инпутов разных размеров значение `line-height` меняется не сильно, поэтому возникает "наезд" тултипа на содержимое инпута. Можно скорректировать отступы `Popup`, который используется в тултипе и переключить значение по умолчанию для флага `useWrapper` на `false`, но перед этим необходимо тщательно протестировать, что у потребителей ничего не сломается.

**Comment by wKich** [comment]
Как ещё один вариант. Можно выкатить правки в `next` версии и попросить команды посмотреть, что всё хорошо или не хорошо.

**Comment by dzekh** [comment]
Насколько я понимаю `useWrapper=false` убирает из верстки этот `span`?
А зачем этот `span` нужен?

Если он не так важен и это какое-то устаревшее решение — давай попробуем, как ты предлагаешь — в ветке `next` поставить `useWrapper=false`, и рассказать всем — попросить чтоб потестили.

**Comment by wKich** [comment]
`span` нужен чтобы навесить на него события мыши (Enter/Leave) и не зависеть от компонента вокруг которых оборачивается `Tooltip`, потому что у нас нет знания о том какая внутри верстка и как она может изменяться. Если не использовать `span` это может привести к тому что в определенный момент мы перестанем получать события от дочернего элемента, потому что компонент, который был обернут в `Tooltip` перерисовал себя, об этом сейчас мы никак не узнаем.

Ещё одним решением могло бы стать использование стиля для `span` [`display: contents`](https://caniuse.com/#feat=css-display-contents), но поддержка его в браузера оставляет желать лучшего.

Для лучше поддержки вышеописанной ситуации я бы ещё добавил в `Tooltip/Hint/etc` публичный метод, дернув который можно уведомить `Popup` об изменении в верстке, либо что скорее всего будет более правильным, прокидывать из `Popup` контекст с функцией, которую могут дернуть дочерние компоненты, чтобы уведомить о том что они перерисовались

**Comment by dzekh** [comment]
А что если у инпутов поменять `line-height`? Они же все равно в одну строку.

**Comment by dzekh** [comment]
Попробовал менять `line-height` - не работает. может что-то не то делаю?

**Comment by wKich** [comment]
А оно не будет работать. Ведь надо задавать `line-height` обертке которую использует `Tooltip`, а потом ресетить его. Более того пока дочерний компонент не будет отрисован нам неизвестно значение, которое необходимо в `line-height` просетить. А ещё возникнут проблемы с `baseline` и для правильного позиционирования, придется сдвигать этот `span`.

В общем оно не стоит того чтобы так костылять. `findDOMNode` и навешивание хендлеров на HTML элемент кажется норм решением. Можно было бы поступить, как это сделано в библиотеке валидаций, через `cloneElement`, но тогда бы для правильной работы тултипа требовалось реализовывать API в каждом компоненте, который ты хочешь обернуть в тултип. В принципе такое решение тоже имеет право на жизнь, но увеличивает порог входа.

Кажется, что `useWrapper={false}` норм решение, которое требует от пользователя всего лишь дергать метод обновления подписок и позиции тултипа при изменении обернутого компонента.

**Comment by rustho** [comment]
#2005
