### ISSUE TITLE
[Modal.Header, Modal.Footer] Loader в Modal.Body накрывает залипающие Header и Footer

### ISSUE THREAD

**Issue by slaeme** [skbkontur/retail-ui#934]
Привет! 
- Библиотека retail-ui: 0.30.0
- Браузер Chrome, Win10

При залипании Modal.Header или Modal.Footer, Loader в Modal.Body перекрывает: Modal.Header или Modal.Footer:
![image](https://user-images.githubusercontent.com/22623111/48824900-86a30a80-ed87-11e8-86c4-de28d8bbb4cb.png)

Минимальный пример: 
```
<Modal>
    <Modal.Header>Title</Modal.Header>
    <Modal.Body>
        <Loader active type="big">
             body
        </Loader>   
    </Modal.Body>
    <Modal.Footer panel={state.panel}>
        Footer
    </Modal.Footer>
</Modal>
```

**Comment by wKich** [comment]
Есть такая проблема #776. Мы попробуем придумать системное решение.

**Comment by wKich** [comment]
Утащил пример в связаную задачу, закрываю чтобы не дублировались
