### ISSUE TITLE
[Input] Маска работает в режиме замены символов

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#941]
Если начать вводить что-то в маске до введённых символов, то ввод начнёт заменять символы, а не сдвигать их

**Comment by wKich** [comment]
Я думаю, что такое поведение предотвращает возможность появления невалидного по маске ввода. Но скорее всего ты прав, что инпут с маской должен вести себя как инпут без маски, то есть в режиме вставки, а не замены. Давай узнаем мнение @dzekh, гайды сейчас не регламентируют в каком режиме должен находится инпут с маской.

**Comment by dzekh** [comment]
В гайдах нет. Согласен, на первый взгляд кажется, что инпут с маской должен вести себя как инпут без маски — не заменять символы а сдвигать. 
Отсюда еще две странности поведения:
1) Можно поставить курсор и начать вводить значение не с начала а с середины. 
2) Если стираешь символы маски с середины введенного — не стертые символы стоят на месте, и не сдвигаются влево за курсором. 

Это все оправдано тем, что маска может быть сложной, и если сделать поведение «как в обычном инпуте» то, как сказал Дима появится невалидное по маске значение. 

Возможно есть смысл сделать дополнительно к такой маске «простую маску» которая будет вести себя как обычный инпут и сдвигать. Но кажется сейчас есть более важные дела, и в принципе такое поведение оправдано. 

Будем обсуждать с дизайнерами.

**Comment by mifopen** [comment]
В версии 0.32.1 работает без замены. Нам так и надо. Что делать с багой? =)

**Comment by dzekh** [comment]
Тогда закрываем
