### ISSUE TITLE
[Input] Видно курсор в зафокусенном инпуте под тултипом

### ISSUE THREAD

**Issue by mifopen** [skbkontur/retail-ui#942]
https://i.imgur.com/CmlGYOC.gifv

**Comment by wKich** [comment]
Это только в ИЕ или в других браузерах такое же поведение?

**Comment by mifopen** [comment]
Только в IE

**Comment by zhzz** [comment]
Bug IE [https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7657766/](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7657766/).

Делать `document.activeElement.blur()` для IE?

**Comment by wKich** [comment]
> Делать `document.activeElement.blur()` для IE?

Я думаю что не стоит. Можно конечно рисовать кастомный курсор для всех полей, но только ради починки этого бага делать это я не вижу смысла.
