### ISSUE TITLE
[DropdownMenu] Невозможно позиционировать caption относительно родителя

### ISSUE THREAD

**Issue by original001** [skbkontur/retail-ui#944]
библиотека: retail-ui последняя

сейчас caption рисуется внутри inline-block,  поэтому нет возможности его положить например во flex.

<img width="629" alt="screenshot 2018-11-26 at 18 57 38" src="https://user-images.githubusercontent.com/8949234/49152603-2f77d980-f335-11e8-9238-cc3c322e1664.png">

**Comment by wKich** [comment]
Если уберем `inline-block`, то вероятнее всего сломается верстка в других командах. Можно добавить свойство `width` в `DropdownMenu`

**Comment by dzekh** [comment]
а в чем проблема, зачем caption класть во флекс? что не так на скриншоте?

**Comment by wKich** [comment]
Хочется чтобы `caption` можно было растягивать по ширине родителя. Но сейчас нет такой возможности. Указание `<Button width="100%" />` ни к чему не приведет, так как `caption` оборачивается в `inline-block`

**Comment by dzekh** [comment]
Дежурному — посмотреть какие есть варианты решения

**Comment by zhzz** [comment]
Да, проп `width` для `DropdownMenu` поможет. Нужно добавить.

**Comment by zhzz** [comment]
Про `width` добавлен в #2354 и релизнут в `2.17.0`
