### ISSUE TITLE
[DropdownMenu] Добавить возможность закреплять элементы на верху списка

### ISSUE THREAD

**Issue by original001** [skbkontur/retail-ui#945]
Привет! Опиши, пожалуйста, проблему, которая возникла:
- Библиотека и её версия (retail-ui, react-ui-validations или другие);
retail-ui
- Сценарий или произведенные действия;
Нужно добавить возможность закреплять элементы на верху списка
- Прикрепи скриншот или гифку с примером;
<img width="476" alt="screenshot 2018-11-27 at 05 37 15" src="https://user-images.githubusercontent.com/8949234/49152698-7534a200-f335-11e8-91eb-1e3d2fdfb13e.png">

**Comment by dzekh** [comment]
@original001, для залипающих панелей внутри выпадающих списков мы будем использовать однопиксельную тень, как в компоненте дэйтпикера. 

box-shadow: 0px -1px 0px rgba(0, 0, 0, 0.1); 

![frame](https://user-images.githubusercontent.com/26383080/53479914-e7836280-3a9b-11e9-87c6-769442772b51.png)

Это бщеконтуровский стандарт. В гайдах нет примера, ну кроме дейтпикера, но в библиотеках для фигмы и скетча тень такая.
