### ISSUE TITLE
[Radio] Вынести переменные стилей в variables.less

### ISSUE THREAD

**Issue by bdskrur** [skbkontur/retail-ui#964]
Привет!
- retail-ui;

Хочется иметь возможность переопределять стили у компонента Radio

**Comment by dzekh** [comment]
Привет! Сейчас, с помощью [кастомизации](https://tech.skbkontur.ru/react-ui/#/Customization) это возможно сделать?

**Comment by wKich** [comment]
Закрываю, так как кастомизация выпущена в версии 1.0.0, многие стили для Radio теперь кастомизируются. Если чего-то не хватает в кастомизации, предлагаю открыть новое ишью и описать более подробно чего именно не хватает.
