### ISSUE TITLE
[SidePage] Очень длинное название в хедере

### ISSUE THREAD

**Issue by ArtManyak** [skbkontur/retail-ui#971]
Если в хедере много текста, то при скроллинге он схлапывается и остается белый кусок.
Приложил картинки, там на заднем фоне даже код видно
![image](https://user-images.githubusercontent.com/10251724/49576757-bcd7b100-f967-11e8-9a77-6dd9272d3a15.png)
![image](https://user-images.githubusercontent.com/10251724/49576765-c3662880-f967-11e8-883a-3b1503b043f0.png)

**Comment by wKich** [comment]
@dzekh, а как должно быть?

**Comment by wKich** [comment]
Вот PR #414 в котором сделали такое поведение

**Comment by dzekh** [comment]
Белый фон, что остался от заголовка должен исчезать, контент сдвигаться вверх.

**Comment by wKich** [comment]
Тогда скролл пропадет и контент будет скакать

**Comment by dzekh** [comment]
Это норм. Когда бадет гайд по анимации — добавим плавности. Пока так.

**Comment by wKich** [comment]
Я не про плавность. Я про то что скролла не станет и шапка в таком случае должна перестать быть залипающей

**Comment by dzekh** [comment]
Давай тогда сделаем так, чтоб залипшая обрезанная шапка появлялась только в тот момент, когда заголовок проскроллился вверх и по высоте его осталось столько, сколько нужно для залипшего заголовка. При этом крестик внутри заголовка должен быть залипший до этого момента.

Когда скроллим обратно (вниз) — залипший заголовок исчезает, как только должен начать появляться незалипший из под него. Появляется незалипший, крестик снова становится залипшим внутри заголовка с этого момента.

Похожее поведение нужно перенести на заголовок лайтбокса, если получится.
