### ISSUE TITLE
[Modal] Скачет ширина окна при скролле

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#972]
Лайтбокс растягивается по ширине по заголовку, когда заголовок не залипший, а когда залипший — по ширине контента. 

Чтобы повторить — вставить в Modal.Header длинный текст, а в Modal.Body высокий див с маленьким контентом:

`<Modal.Header>Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title </Modal.Header>
<Modal.Body>
        <div style={{height: 600}}>
        <p>Use rxjs operators with react hooks</p> 
        </div>
</Modal.Body>`

Лечится если указать ширину лайтбокса, но тем не менее, ширина лайтбокса не должна меняться при скролее.

**Comment by dzekh** [comment]
Кажется больше не воспроизводится

**Comment by JackUait** [comment]
> Кажется больше не воспроизводится

Похоже, что баг не был закрыт, так как пулл-реквест #1399 в котором была попытка закрыть этот баг, был закрыт сам (имеется ввиду пулл-реквест) по итогам [голосования](https://github.com/skbkontur/retail-ui/pull/1399#issuecomment-495484418)

Также Максим (@lossir) на основе этого ишью и #1399 создал связанное ишью #1417
Максим, если помнишь в чём была суть, можешь подсказать какой статус у этого ишью и #1417?

**Comment by lossir** [comment]
Вроде пользователи не приходили с такой проблемой. Значит можно закрыть и эту и https://github.com/skbkontur/retail-ui/issues/1417.
