### ISSUE TITLE
[Tooltip] Закрывать без задержки при значении триггера hoverAnchor

### ISSUE THREAD

**Issue by paatrofimov** [skbkontur/retail-ui#973]
Проблема такая. В форме на одной странице есть много контролов с валидацией. Если быстро водить по ним мышкой, создается впечатление, что форма подлагивает. Потому что каждый тултип задерживается при исчезновении.

Видео такое плохо захватывает, т.к. мало фпс. Проблему больше видно глазом. Если нужно, могу сделать тестовый стенд с формой.

Сейчас захардкожен таймаут в 100 мс. С @21alexander21 обсудили, что кастомизацию этого значения сделать можно.

![image](https://user-images.githubusercontent.com/17619635/49601302-4a86c100-f9a7-11e8-9bb6-5c9dce7c4fd6.png)

**Comment by wKich** [comment]
Ты хочешь чтобы они сразу закрывались? У тебя библиотека валидаций используется?

Я не думаю что давать кастомизировать таймаут хорошая идея. Если хочется сразу закрывать тултип на `MouseLeave`, можно сделать это следующими вариантами:

- Переехать на библиотеку валидаций. Там при `MouseLeave` триггер тултипа переключается на `closed` и тултип закрывается сразу.
- При использовании `disableAnimations` отключать таймаут.
- При использовании `trigger={'hoverAnchor'}` отключать таймаут.

Первый вариант не требует никаких правок в библиотеке и будет работать сразу, но минус его в том что быстро втащить в проект и переехать не получится.

Второй вариант добавляет какую-то неявную логику и может выйти нам боком.

Мне больше нравится 3-й вариант. Суть его в том, что тултип всё равно закроется при попытке навести на содержимое тултипа. А изначальная цель таймаута как раз в том, чтобы с `trigger={'hover'}` иметь возможность взаимодействовать с содержимым тултипа

**Comment by paatrofimov** [comment]
Либу валидаций не втаскивали.
Варианты 2 и 3 подходят к нашему сценарию оба. Мы используем оба флага для тултипов валидаций.

**Comment by dzekh** [comment]
Как вариант можно не убирать таймаут а повесить таймаут не только на закрытие, но и на открытие. 

Если мы уберем таймаут с закрытия тултипы будут моргать, если водить мышью быстро по контролам и все равно будет не круто.  

Если мы добавим небольшой таймаут на открытие — при проведении по контролам будет меньше моргания, а задержка на открытие будет не такая большая чтоб заставить ждать. 

Это нормальная практика для хинтов, но там таймаут довольно большой, потому что инфа справочно/вспомагательная.
