### ISSUE TITLE
Обновить readme при использовании css-loader@2

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#981]
Во 2-й версии `css-loader` изменили значение по умолчанию для опции `modules` https://github.com/webpack-contrib/css-loader/releases/tag/v2.0.0. Теперь для работы библиотеки необходимо указывать опции:
```js
{
  loader: 'css-loader',
  options: { modules: 'global' }
}
```

**Comment by sashasushko** [comment]
А ещё не пора ли под 7-й бабель и 4 вебпак переписать инструкцию по слоу-старту?
