### ISSUE TITLE
[Input][Button] размер шрифта medium

### ISSUE THREAD

**Issue by 21alexander21** [skbkontur/retail-ui#988]
По-дефолту, размер **medium** равен `14px` и переключается на `16px` флагом `Upgrade.enableSizeMedium16px`. Но во flat-версии он по-дефолту `16px`. Нужно привести обе версии к одному поведениею

**Comment by 21alexander21** [comment]
Разбил на #1094 и #1095

**Comment by dzekh** [comment]
Судя по опросу в чатике скорее всего никто не использует переключатель Upgrade.enableSizeMedium16px — по этому есть смысл просто отказаться от этого переключателя. В плоской теме будут свои значения, в дефолтной свои.
