### ISSUE TITLE
[RadioGroup] Курсор не меняется на палец

### ISSUE THREAD

**Issue by vkochev** [skbkontur/retail-ui#990]
- retail-ui@0.32.1
- Chrome

Если запустить сторибук с флагом STORYBOOK_FLAT_UI, то здесь можно увидеть, что при наведении курсор не меняется:
http://localhost:6060/?selectedKind=RadioGroup&selectedStory=inline&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Хотелось бы, чтобы курсор менялся так же, как и не в плоском дизайне.

**Comment by wKich** [comment]
Для класса `root` не указано свойство `cursor: pointer;` в less файле плоской темы

**Comment by 21alexander21** [comment]
@dzekh , а радиокнопки вообще должны менять курсор на поинтер?

**Comment by dzekh** [comment]
Вообще в интернетах нет такой практики, но в Контуре — да, надо всеми интерактивными элементами меняем курсор. Над радиокнопками и чекбоксами тоже. Нигде вроде это не зафиксировано, но мы проговаривали на дизайнерских встречах что придерживаемся этого правила.

**Comment by 21alexander21** [comment]
> Вообще в интернетах нет такой практики, но в Контуре — да, надо всеми интерактивными элементами меняем курсор. Над радиокнопками и чекбоксами тоже. Нигде вроде это не зафиксировано, но мы проговаривали на дизайнерских встречах что придерживаемся этого правила.

Нужно в гайдах зафиксировать, и упомянуть что это правило не распространяется на лэйблы инпутов
