### ISSUE TITLE
[InternalMenu] Из-за скрола окна обновляются другие компоненты.

### ISSUE THREAD

**Issue by step-off** [skbkontur/retail-ui#996]
Возникают проблемы с производительностью при использовании Kebab, который внутри использует InternalMenu.

InternalMenu на componentDidMount зовет метод _focusWithScrollRestore, где происходит скролл окна.

Рабочий пример. На странице используется компонент из react-virtualized для отображения больших списков. Он слушает скролл window, и обновляется по этому событию. Получается, что список полностью ре-рендерится на каждое открытие/закрытие кебаба:

![j8lzscldmy](https://user-images.githubusercontent.com/20541685/49931445-b063d300-fee8-11e8-9cf9-6280e5fe70a9.gif)

**Comment by step-off** [comment]
Когда пользователь скроллит лист сам, и список обновляется - это нормальное поведение. Если же список обновляется при открытии и закрытии кебаба, то это кажется довольно странным.

**Comment by wKich** [comment]
Я согласен с тем что вызов scrollTo кажется лишним и отдельное спасибо за PR. На следующей неделе мы посмотрим и постараемся влить.

Просто хотел сказать, что если открытие кебаба происходит с задержкой/фризами из-за полной перерисовки, которая триггерится с помощью `scrollTo`, то скорее всего пользователю не очень удобно с такими тормозами скроллить список. Возможно стоит посмотреть в сторону того чтобы использовать `PureComponent` или добавить в элементы списка `shouldComponentUpdate`. Это не только уменьшит проблему с открытием кебаба, но и улучшит производительность в целом при прокрутке.

**Comment by step-off** [comment]
Спасибо!
